### ISSUE TITLE
clang power tool doesn't works..

### ISSUE THREAD

**Issue by SungJJinKang** [Caphyon/clang-power-tools#1004]
clang power tool doesn't works..
When start to compile, export compilation database...., it never respond. It just show START ~~~ log..
I don't even know how to see log.

**Comment by hero101111** [comment]
Hello @SungJJinKang ,

Please provide more information about the project you're trying Clang Power Tools on. 
To see more information please enabled Verbose Logging from the Clang Power Tools Visual Studio extension settings.

Regards,
Gabriel

**Comment by SungJJinKang** [comment]
@hero101111 Verbose Loggin didn't show anything
