### ISSUE TITLE
"The string is missing the terminator: '." when trying to export compilation database and a "'" is in the filepath

### ISSUE THREAD

**Issue by Treeniks** [Caphyon/clang-power-tools#1021]
I am currently trying to run the "Export Compilation Database" command on a Solution and it kept giving me the following error:
```
The string is missing the terminator: '.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
```
After trying around a little, I found out the problem was a "'" in my project's filepath. After renaming the folder my project was in, the problem went away.
It's an easy thing to fix, simply remove the apostrophe from the project's path. I assume this is caused by some missing quotations in some powershell script.

**Comment by mariru27** [comment]
Hi @Treeniks,

Thank you for reporting this problem, and for helping us identify the solution. The fix for this issue will be available in the next release of Clang Power Tools (`v7.8`). 

Regards,
Marina
