### ISSUE TITLE
Property Sheet changes are not used if unsaved

### ISSUE THREAD

**Issue by rgraebert** [Caphyon/clang-power-tools#103]
Hi,

it seems you are reading from the property sheets files when loading the include paths for Clang. The problem is that if I make a change in the property sheet, the property sheet is not automatically saved. I need to manually save the property sheet before I can rerun clang. It would be nice if you could either trigger a save of the project (and property sheet) before running the tool or read the options from the propert sheets objects in memory.

Thanks,

Robert

**Comment by mariusz102102** [comment]
From my point of view this is not issue of "clang-power-tools" but property of Visual Studio.

**Comment by cpp-red-lion** [comment]
This is standard Visual Studio behavior, I'm afraid.
After editing a property-sheet from within VS, you need to `Save All` and then run Tidy again.

**Comment by rgraebert** [comment]
Fair enough. It is just a little unintuitive. VS for example automatically saves all open source files when you trigger a build.
