### ISSUE TITLE
Display command lines in Verbose mode - feature request

### ISSUE THREAD

**Issue by mariusz102102** [Caphyon/clang-power-tools#104]
Hi,

Currently it is not clear from Visual Studio output window which command were called

It would be nice to display all command lines in Verbose mode to output window. I would like to see:
1. PowerShell script command line - "c:/../clang-build.ps1 ...options ....."
2. clang command line - "c:/.../clang.exe ...."
3. clang-tidy command line - "c:/.../clang-tidy.exe ...options..."

In that way it will be easiest i.e. start debugging PowerShell. 

Regards,
Mariusz

**Comment by hero101111** [comment]
Hello Mariusz,

An excellent suggestion. 
We'll implement this verbose mode improvement as soon as possible.

Thank you for your feedback,
Gabriel.

**Comment by hero101111** [comment]
Hi Mariusz,

I'm glad to inform you that we've implemented this improvement.

[Clang argument verbose logging.](https://github.com/Caphyon/clang-power-tools/commit/06cbfa02a74dd490a2f877cb48f33286af798b83)
[clang-build.ps1 invocation argument verbose logging ](https://github.com/Caphyon/clang-power-tools/commit/ac4af7003be0d34482d2c89a90103e527a16a7d6)

Regards,
Gabriel
-------------------------------
Please note that this fix is currently live only for the github repository.
The latest Visual Studio extension (1.6.0) does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. Don't forget to restart Visual Studio after replacing the script file.

To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

**Comment by mariusz102102** [comment]
Gabriel,

Thank you!

Regards,
Mariusz
