### ISSUE TITLE
Clang Power Tools appears at the end of the context menu

### ISSUE THREAD

**Issue by LegalizeAdulthood** [Caphyon/clang-power-tools#105]
Muscle memory has me assuming that Project Properties is always the last item on the context menu in solution explorer for a project.

Clang Power Tools installs itself at the end (other tools install themselves just before the end) and now my muscle memory is broken and I can't rely on Properties being the last entry on the context menu.

**Comment by Enache-Ionut** [comment]
Hi,
In the next release(this `Friday`) the `Clang Power Tools` item will be just above the `Properties` in `Context Menu`. It will remain on the last position only for `Tab File Context Menu` where the `Properties` item does not exist. 

Thank you for your feedback!
