### ISSUE TITLE
Clang-power-tools offline

### ISSUE THREAD

**Issue by vegovs** [Caphyon/clang-power-tools#1056]
I am trying to use clang-power-tools on an offline client, but I get a powershell error when using it. CPT outputs that an exception occurs when a ps script invokes a webrequest, I guess for a ps script used. It tries to download a ps script from github. Is it possible to do a complete offline installation of cpt?

**Comment by hero101111** [comment]
Hello @vegovs ,

The mechanism for self-update should not be triggered unless changes are made to `clang-build.ps1`. Only then it would trigger a re-download of helper scripts. We will investigate to see if there's a bug in this mechanism that causes it to trigger unnecessarily. 

Until we find what's going on, you can manually disable this mechanism by setting the `HKEY_CURRENT_USER\Software\Caphyon\Clang Power Tools\ScriptTimestamp`  registry string value (REG_SZ) to `42`.

Let us know if this workaround is getting Clang Power Tools up and running on your offline machine.

Regards,
Gabriel.

**Comment by vegovs** [comment]
I am unable to find this registry string. This is the output from VS2019, VS2020 outputs nothing.


--- CLANG COMPILE STARTED ---

VERBOSE: Loaded assembly C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Professional\MSBuild\Current\Bin\Microsoft.Build.Utilities.Core.dll
VERBOSE: Download required script... $scriptName
VERBOSE: GET 
https://raw.githubusercontent.com/Caphyon/clang-power-tools/master/ClangPowerTools/ClangPowerToolsShared/Tooling/v1//ps
Clang/msbuild-project-cache-repository.ps1 with 0-byte payload
Invoke-WebRequest : The remote name could not be resolved: 'raw.githubusercontent.com'
At C:\users\xxx\appdata\local\microsoft\visualstudio\16.0_8f45c164\extensions\dugv4glt.1u5\Tooling\v1\clang-build.p
s1:274 char:5
+     Invoke-WebRequest -Uri $request -OutFile $scriptFilePath
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
cpt:ensureScriptExists : Could not download required script file (msbuild-project-cache-repository.ps1). Aborting...
At C:\users\xxx\appdata\local\microsoft\visualstudio\16.0_8f45c164\extensions\dugv4glt.1u5\Tooling\v1\clang-build.p
s1:324 char:18
+ ForEach-Object { cpt:ensureScriptExists $_ $shouldRedownload } |
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,cpt:ensureScriptExists
 

--- CLANG COMPILE FINISHED ---

**Comment by hero101111** [comment]
If it's not present in the registry then create it by hand, using regedit.

**Comment by vegovs** [comment]
Got it! Love that its 42-> the answer to the universe and everything

**Comment by hero101111** [comment]
That is unexpected. Did you try to restart the Visual Studio instance?

**Comment by vegovs** [comment]
Did a full restart of the computer. Nothing happens in 2022, and same issue I 2019. :S

**Comment by hero101111** [comment]
I'm thinking maybe something got corrupted in the PowerShell scripts...
Can you try manually downloading the PowerShell scripts (both _clang-build.ps1_ and the the _psClang_ folder) from https://github.com/Caphyon/clang-power-tools/tree/master/ClangPowerTools/ClangPowerToolsShared/Tooling/v1 and placing them in your Clang Power Tools VS extension folder?

You will be able to locate the VS extension folder by looking for `clang.build.ps1` in [%LOCALAPPDATA%](url)

**Comment by mariru27** [comment]
Hi @vegovs,

Do you still have the same problem?

Kind regards,
Marina

**Comment by mariru27** [comment]
I will close this issue as we need more information
