### ISSUE TITLE
Release v8.0 VSIX is missing

### ISSUE THREAD

**Issue by kkm000** [Caphyon/clang-power-tools#1058]
Since 3 days ago, as v8.0 was released, apparently, VS 2020 wants to update from v7.9, but when I attempt to update, the VSIX installer reports that the extension is at the latest version. I have no idea how did it hear about the update, but VSIX is neither on the Marketplace nor on GitHub. The manifest shows v7.9 in the VSIX on the Marketplace.

Could you please upload the new build in addition to sources? Either Marketplace or GitHub should be fine. Thanks!

**Comment by hero101111** [comment]
Hello @kkm000 

There've some days-long delay issues regarding the Extension Gallery validation process of our VSIX package. Luckily, we've just been informed via email that the validation is now complete and everything is back to normal.

You should be able to update using the usual channels, currently. As a workaround, if you still encounter update issues, we've published the 8.0 VSIX package on our Github releases page, for manual installation.


Apologies for the inconvenience and thanks for reaching out to us.

Best regards, 
Gabriel
