### ISSUE TITLE
is it possible to use Clang Power Tool to Format non cpp files?

### ISSUE THREAD

**Issue by aik6980** [Caphyon/clang-power-tools#1065]
Hi,

I have a HLSL shader file project and I wonder,
is it possible to use Clang Power Tool to Format non cpp files?

In my custom build project (CMake generated) the "Format" is grey out on my non cpp files 

Thanks

**Comment by hero101111** [comment]
Hello @aik6980 

At the moment (CPT v8.1) it is not possible to manually run, using the context menu, Clang Format on custom file extensions.
We've added this improvement to our to-do list and will add support for it in a coming-soon release.

We'll update this thread when the required updates have been made.

Thanks for your feedback.
Regards,
Gabriel.

**Comment by aik6980** [comment]
thank you!
