### ISSUE TITLE
Visibility in Visual 2015 "Extensions & updates"

### ISSUE THREAD

**Issue by ptaahfr** [Caphyon/clang-power-tools#1069]
Is it possible to have the last supported version for Visual Studio 2015 still visible in the marketplace ?

It's a bit unsettling not being able to install it from one month to another.

Best Regards

**Comment by hero101111** [comment]
Hi @ptaahfr 

The last version of Clang Power Tools that supports Visual Studio 2015 is 7.5.0 and the VSIX can be downloaded [here](https://github.com/Caphyon/clang-power-tools/releases/download/v7.5/ClangPowerTools-v7.5.0-VisualStudio2015-2017-2019.vsix). We will update our marketplace page description to include this link. 

Might I ask what you meant by it being unsettling not being able to install it from one mount to another?

Thank you for reaching out to us.
Regards,
Gabriel

**Comment by ptaahfr** [comment]
>Might I ask what you meant by it being unsettling not being able to install it from one >month to another?
It was just a way to express my surprise since I suddently couldn't install it with no change on my side, but i found the right package here.

Thank you for the answer. I'm sure the link in the description would be very useful.

**Comment by hero101111** [comment]
So you were referring to installing on VS2015 machines that didn't have Clang Power Tools installed.
After seeing the "one month to another" I was fearing that perhaps we are falsely giving update notifications to VS2015 users and them not being able to actually update. From what I understand, this is not the case.

**Comment by ptaahfr** [comment]
> 

No, sorry for the misunderstainding, right now in a fresh VS2015, the package is not findable at all.
