### ISSUE TITLE
Grayed out buttons on Offline Machine

### ISSUE THREAD

**Issue by Aderinom** [Caphyon/clang-power-tools#1074]
Hello Team!

I've tried installing the Extension on two different versions of VS in an offline environment.
Both of them have the Extensions buttons grayed out. 

After some searching I found this, which I tried :
https://clangpowertools.com/offline-activation.html

But sadly it has not helped either. Nor Rebooting or Reinstalling the Extension.

Is this a Bug? Or are Offline systems not supported?

**Comment by mariru27** [comment]
Hi Aaron Kelbsch,


Clang Power Tools have a bug about running in offline mode and we working
on that, but the scenario described by you seems different, so I hope you
can help us if you want, by responding to these questions:

Just to make sure, setting button are disabled too?
Did you try after in online mode, to see if the buttons are enabled?


With regards,
Marina

**Comment by Aderinom** [comment]
Hi Marina! 

1. Correct, the Setting button is disables as Well. 
2. Sadly because of company policy I can't put the machine online. I tried it on another system which was online, which seemed to work fine (Same version used). 

infos about the Machine on wich the bug occurs: 

> OS : Microsoft Windows [Version 10.0.19042.868]
> VS : Visual Studio 2022 and Visual studio 2017 Pro
> Extension version : 8.1.0
> Steps to reproduce:
>  - Download CPT from "https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools"
>  - Copy it over to the target System which has limited access to the internet ()
>  - Install as usual


Are there any Log files I could share with you? Or would I have to set up debugging for the Extension to get more info?

Best Regards,
Aaron

**Comment by mariru27** [comment]
Hi Aron,

We made in the past month's releases related to your problem, did you
install the latest version?
Do you have the same problem?

Let us know

Best regards,
Marina

**Comment by Aderinom** [comment]
Hi Marina,

Just installed the new version. (8.5.0.161 on VS2022)
No change however.

**Comment by mariru27** [comment]
Hi @Aderinom,

What version of Visual Studio are you using?
Try to update your Visual Studio to the latest version

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @Aderinom,

Do you have the same problem?
Did you try to update Visual Studio to v17.3.5, and Clang Power Tools to v9.3?

Best regards,
Marina

**Comment by mariru27** [comment]
I will close this issue as we need more information
