### ISSUE TITLE
Error when Visual Studio extension updater runs after closing the IDE.

### ISSUE THREAD

**Issue by ThiagoAlexsander** [Caphyon/clang-power-tools#1080]
![image](https://user-images.githubusercontent.com/40046468/151424847-f8f06361-c331-4034-8794-cf4fdc63b4bc.png)

**Comment by mariru27** [comment]
Hi Alexander,

The extension is uploaded on marketplace but is going through a verifying process, we just need to wait.
Sorry for inconvenience.
