### ISSUE TITLE
Ability to abort clang-tidy is missing

### ISSUE THREAD

**Issue by rgraebert** [Caphyon/clang-power-tools#109]
Hi,

thanks for your work on the clang-power-tools. I am having a lot of fun checking our projects with Clang and Clang-tidy directly in VS.

I made the mistake of calling clang-tidy on a bigger project (200+ source files). I could not find a way to cancel the execution of the script. Ideally I would be abort the current tidy call or at least before the next clang-tidy run. I also cannot kill VS with the task manager, as I will loose all my settings that I have made.

Thanks

**Comment by cpp-red-lion** [comment]
That's a very good suggestion.
We'll definitely have to add an option to abort a long running operation.
Thanks.

**Comment by cpp-red-lion** [comment]
Work in progress...

**Comment by cpp-red-lion** [comment]
Implemented in version 2.1
Give it a try.

**Comment by Enache-Ionut** [comment]
This issue was fixed in the new version 2.1.0 just released : www.clangpowertools.com
