### ISSUE TITLE
No C++20 modules support

### ISSUE THREAD

**Issue by checkraisefold** [Caphyon/clang-power-tools#1094]
I'm honestly not sure how there's no issue on this, but there's currently no support for formatting module files for any compiler. This includes .ixx files, the only module file type supported in Visual Studio.

**Comment by mariru27** [comment]
Hi,

Thank you for submitting this issue. We will provide a fix for it as soon as possible.

**Comment by checkraisefold** [comment]
Any estimate on when this will be completed? It should only be adding .ixx to the list of extensions that are formatted.

**Comment by Kyiro** [comment]
Any updates on modules?

**Comment by mariru27** [comment]
Hi,

Sorry for the delayed answer @checkraisefold @Kyiro
We are working on it, the functionality will be available in the next release.

Best regards,
Marina

**Comment by Kyiro** [comment]
Thank you for the quick answer. I appreciate it

**Comment by mariru27** [comment]
Hi @Kyiro, @checkraisefold

We enabled format on .ixx file extensions and it is available in release [v2023.1](https://clangpowertools.com/CHANGELOG.html)
Let us know if It works for you

Have a nice day,
Marina
