### ISSUE TITLE
Cross Translation Unit (CTU) Possible? 

### ISSUE THREAD

**Issue by SevHub** [Caphyon/clang-power-tools#1120]
Hello, 

is it possible to use CTU with the Clang Power Tools? 

Assume the Two files One.c and Two.c: 

One.c
```
int myMethodOne()
{
	return 42 / myMethodTwo();
}
```
Two.c
```
int myMethodTwo()
{
	return 0; 
}
```

There is an obvious division by zero bug, but Clang Power Tools can not find it, because it does not look into methods that come from other translation Units. Is there an option to enable CTU?

**Comment by hero101111** [comment]
Hi,

Sorry about the delayed answer, as I'm sure you have already gathered, at the moment we don't have support for CTU in Clang Power Tools. Have you managed to get a workflow up and running using CTU on Visual Studio projects?

**Comment by mariru27** [comment]
I will close this issue as no user feedback is provided
