### ISSUE TITLE
Missing tidy-fix from menu

### ISSUE THREAD

**Issue by Philippe91** [Caphyon/clang-power-tools#1127]
I haven't use clang-power-tools for about a year. Today, when updating to the latest version (8.6.0) in MSVC 2022, I see that the **Tidy-fix** function (the only function I ever used), is missing. Why?
![image](https://user-images.githubusercontent.com/8200618/166713189-0c6d7e13-8911-4a53-be29-63d4ec429bb0.png)

**Comment by Philippe91** [comment]
Ok, but pity. This slows down my workflow which used my favorite compare tool (outside Visual Studio).
I wish your "improvement" was rather an option.

**Comment by hero101111** [comment]
@Philippe91 your workflow should continue to be accommodated with the updated UI. We offer a checkbox (the top left one) for quickly selecting & fixing all files. You can then bypass our custom diffing tool and use your preferred one.

**Comment by mariru27** [comment]
Hi @N-Dekker and @Philippe91,

In new [Clang Power Tools](https://clangpowertools.com/CHANGELOG.html) **release v8.7.0** We introduced the option to run Tidy-Fix directly
 `` To activate Tidy-Fix: (Settings → Tidy → 1-step Tidy-Fix) ``

<img width="507" alt="image" src="https://user-images.githubusercontent.com/46792157/168231302-bc92d445-2387-4453-89ee-bf1026aafadd.png">

**Comment by Philippe91** [comment]
Thanks for listening 👍
