### ISSUE TITLE
/std:c++latest should imply -std=c++2b

### ISSUE THREAD

**Issue by matbech** [Caphyon/clang-power-tools#1132]
When the language standard is set to /std:c++latest, then -std=c++2b should be added to the clang compiler options.
The reason is that Visual Studio 17.3 already supports certain features (e.g. contains in string) from the up-coming C++ standard.

Manually adding -std=c++2b to the settings does not work as this will also add the switch when C files are being compiled.

**Comment by hero101111** [comment]
Hi @matbech 

Just pushed a fix for this on on main branch, they'll be integrated into our next release. 
You can grab these changes directly, without waiting for the next release, by using the `PowerShell scripts [Update]` option from the Clang Power Tools VS extension settings dialog.

Thanks for taking the time to provide us this feedback.

Regards,
Gabriel.

**Comment by matbech** [comment]
Thank you.
