### ISSUE TITLE
I cannot find clang++.exe,  where clang-power-tool install clang on Windows?

### ISSUE THREAD

**Issue by aik6980** [Caphyon/clang-power-tools#1141]
I cannot find clang++.exe,  where clang-power-tool install clang on Windows?

I'm trying to setup clang compiler for my Visual studio project, anyone please help?

**Comment by mariru27** [comment]
Hi,

You can find clang++.exe in `%appdata%\ClangPowerTools\LLVM_Lite\Bin` or `%appdata%\ClangPowerTools\LLVM\LLVM14.0.3\bin` (if you have LLVM downloaded from Clang Power Tools settings)

**Comment by aik6980** [comment]
thank you :)
