### ISSUE TITLE
Can't find powershell.exe

### ISSUE THREAD

**Issue by dacmot** [Caphyon/clang-power-tools#1144]
Hi,

I just installed clang power tools. Clang format works great, but when I run compile or tidy, I get the same error :

```
--- CLANG TIDY STARTED ---

PowerShell.exe : The term 'PowerShell.exe' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try
again.
At line:1 char:1
+ PowerShell.exe -ExecutionPolicy Unrestricted -NoProfile -Noninteracti ...

--- CLANG TIDY FINISHED ---
```

I don't think it's a power tool problem, but I'm running out of things to try to resolve this.

I'm running :
* Windows 10, 21H2
* Visual Studio 2017, 15.9.45
* Powershell 5.1.19041.1682
* CPT 9.0.0.958
`PSModulePath=C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules`

I tried opening Visual Studio as administrator, as well as a regular user. I am able to start powershell from a VS2017 developer command prompt, as well as with a regular command prompt. `C:\Windows\System32\WindowsPowershell\v1.0\` is in my PATH. I tried installing Powershell 7 but it didn't seem to help either.

Any tips and steps to try and fix this would be greatly appreciated. Thank you.

**Comment by hero101111** [comment]
Hello @dacmot 

Did you make sure that `C:\Windows\System32\WindowsPowershell\v1.0\` is added to you _System PATH_ variable, and not the _user-specific PATH_?

**Comment by dacmot** [comment]
Hi @hero101111. Thanks for the quick reply.

Yes, `C:\Windows\System32\WindowsPowershell\v1.0\` is in my system path. So is PSModulePath. Both of these are set again in the user variables, but with the value %path%;... And %psmodulepath%;...

**Comment by hero101111** [comment]
That's interesting... 
Can you try opening up a `CMD.exe` console window and try running `PowerShell.exe` into the console window? Does CMD manage to find PowerShell?

**Comment by dacmot** [comment]
I know, right? :-)

As mentioned in the original post, I can launch powershell from either a command prompt (user and admin) as well as from a developer command prompt for VS 2017 (user and admin too)

**Comment by hero101111** [comment]
Let's investigate this a bit further...

Please grab [Sysinternals Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) and inspect the VS2017 process. Right click on it > Properties > Environment. You should see PATH listed there, copy and paste it somewhere where you can examine it. Does it look OK?

**Comment by dacmot** [comment]
Ah! Great thinking. I forgot procexp could do that.

Indeed, it isn't there. And I have an idea why. Something about my weird work setup.

Thanks!
