### ISSUE TITLE
export compiled database.props

### ISSUE THREAD

**Issue by rgzntrade** [Caphyon/clang-power-tools#1145]
Version 9.0
Cannot include third-party header paths in the compiled database.props

**Comment by hero101111** [comment]
Hi @rgzntrade ,

Can you go into more specific detail regarding this database.props mechanism you're referring? 
I'm afraid I don't understand this scenario and can't offer help until I understand more.

Regards,
Gabriel.

**Comment by rgzntrade** [comment]
> 

Correct a mistake, it is complied database.json not compiled database.props.
1. third-party libraries used in development, such as curl. curl headers and libraries are added to the project via curl.props. clang-power-tools exports complied database.json without the contents of curl.props.
2. qt vs tools generated props and h, cpp files do not appear in the complied database.json

**Comment by rgzntrade** [comment]
> 



> > 
> 
> Correct a mistake, it is complied database.json not compiled database.props.
> 
> 1. third-party libraries used in development, such as curl. curl headers and libraries are added to the project via curl.props. clang-power-tools exports complied database.json without the contents of curl.props.
> 2. qt vs tools generated props and h, cpp files do not appear in the complied database.json

The first problem does not exist and the second problem can be solved with the first method. Add the .props automatically generated by qt to the project to generate the correct compiled database.json

**Comment by rgzntrade** [comment]
> Hi @rgzntrade ,
> 
> Can you go into more specific detail regarding this database.props mechanism you're referring? I'm afraid I don't understand this scenario and can't offer help until I understand more.
> 
> Regards, Gabriel.

There is still an imperfection that does not include the moc_xxx.cpp generated by qt in the compiled database.json。

**Comment by hero101111** [comment]
I'm still unable to fully understand the issue described here.
Please attach a small reproducer project we can use to investigate the reported issue.

**Comment by mariru27** [comment]
Hi @rgzntrade,

Do you still have the same problem on [Clang Power Tools v2023.6.0](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools)?

Kind regards,
Marina

**Comment by mariru27** [comment]
I will close this issue as we need more information
