### ISSUE TITLE
Bug Compile fails with Visual Studio extension

### ISSUE THREAD

**Issue by saumyajyoti** [Caphyon/clang-power-tools#1150]
Getting below error when compiling any fie/project.

--- CLANG COMPILE STARTED ---

Evaluate-MSBuildCondition : Cannot bind argument to parameter 'condition' because it is an empty string.
At C:\users\smukhe5\appdata\local\microsoft\visualstudio\17.0_8bbb323a\extensions\szec20uz.y2x\Tooling\v1\psClang\msbuild-project-load.ps1:608 char:58
+ ...     $validChild = ((Evaluate-MSBuildCondition($nodeCondition)) -eq $t ...
+                                                  ~~~~~~~~~~~~~~~~

--- CLANG COMPILE FINISHED ---

**Comment by hero101111** [comment]
Hi @saumyajyoti 

We are going to need more information regarding this. Please enable verbose mode and give us the detailed log.

**Comment by mariru27** [comment]
Hi @saumyajyoti,

New [Clang Power Tools v2023.3.0](https://clangpowertools.com/CHANGELOG.html) release may fix the problem. Can you try it and tell us if it works?


Best regards,
Marina

**Comment by saumyajyoti** [comment]
HI @mariru27 ,
The issue is resolved with latest version. 

Thanks,
Saumya.
