### ISSUE TITLE
clang-format fails if .clang-format does not exist despite fallback style being set

### ISSUE THREAD

**Issue by oold** [Caphyon/clang-power-tools#1156]
The output window shows the following error:
```
--- ERROR ---
Format config file not found.
Create the config file and place it in the solution folder or select one of the predefined format styles from Clang Power Tools settings -> Format -> Style.
```

Settings:
![image](https://user-images.githubusercontent.com/11773932/185114091-43cb885b-b7a2-43ad-8ee0-510e5a7b7f82.png)

**Comment by mariru27** [comment]
Hi @oold,

Thank you for reporting this issue.
We can reproduce this problem and we working on fix, in the meantime you can use Style instead of Fallback style.
`Set Style` to `Microsoft`

Best regards,
Marina
