### ISSUE TITLE
all options is disabled

### ISSUE THREAD

**Issue by Modify24x7** [Caphyon/clang-power-tools#1157]
Clang Power Tools: v9.1.0.1424
Visual Studio 2019 Enterprise: v16.9.3

Download from: https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools

Screenshot:
![Untitled](https://user-images.githubusercontent.com/19856038/187627731-d5dcb81d-25c8-420d-b424-9594d4340b4c.jpg)

Project Link: https://github.com/Modify24x7/DotNetCLR

**Comment by mariru27** [comment]
Hi @Modify24x7,

Thank you for reporting this issue
Try to update your visual studio to the latest version

Let us know if this answer helped you.

Best regards,
Marina

**Comment by Modify24x7** [comment]
New version visual studio too buggy, so i cannot update.

i restart my pc with using junk cleaning tool, then vs open everything
working fine,
but reopen all options is disabled.

**Comment by mariru27** [comment]
Try to install this version of Clang Power Tools
https://github.com/Caphyon/clang-power-tools/releases/tag/v8.0

**Comment by mariru27** [comment]
Hi @Modify24x7 , 

Are your clang commands enabled now?

If I didn't express myself well and you understand to update Visual Studio 2019 to 2022, there is no need to do that.
Just try to update Visual Studio 2019 to the `latest version 16.11.18. `

**Comment by Ruben-fp** [comment]
Hello @mariru27,

I have the same issue:
![image](https://user-images.githubusercontent.com/57401075/212036376-72157518-6a63-4aa0-8a90-bc70bdaa47f0.png)

Using Visual Studio Professional 2022 (64-bit) - LTSC 17.0
Version 17.0.17

Unfortunately, I cannot update VS2022.
Moreover, Clang Power Tools 2022 version 2023.1.1
![image](https://user-images.githubusercontent.com/57401075/212036813-68dbe845-c870-47ee-af82-e881841199cb.png)

**Comment by mariru27** [comment]
Hi @Modify24x7,

Do you have the same problem with [Clang Power Tools version 8.0](https://github.com/Caphyon/clang-power-tools/releases/tag/v8.0)

Best regards,
Marina

**Comment by Ruben-fp** [comment]
Hello Marina, 

Yes, I have the same problem with Clang Power Tools version 8.0?
Note that, after downloading the installer gives the following pop-up:
![image](https://user-images.githubusercontent.com/57401075/212039027-f7ebd85a-3301-4dc2-9d26-18deafb85b04.png)

**Comment by mariru27** [comment]
This happens to me very often

**Comment by Ruben-fp** [comment]
The version 'Clang Power Tools version 8.0' has the same issue.
Note that I use CPT recently successfully. However, I had to downgrade VS2022 in order to be compliant with other developers.
Now it is not working anymore.

**Comment by mariru27** [comment]
I am so glad that its working ^^

I will continue to look into this problem

Have a nice day @Ruben-fp,
Marina
