### ISSUE TITLE
Add support for "include-what-you-use"

### ISSUE THREAD

**Issue by cpp-red-lion** [Caphyon/clang-power-tools#116]
https://include-what-you-use.org/

https://github.com/include-what-you-use/include-what-you-use

**Comment by d0ru** [comment]
Quick howto for running **IWYU** on a single file:

0) Set **INCLUDE** environment variable with system include paths and your project code includes.

1) Run IWYU and capture the result:

`include-what-you-use -std=c++14 -fsyntax-only -fms-compatibility -fms-compatibility-version=19.10 -fdelayed-template-parsing -DUNICODE -D_UNICODE -DWIN32 -D_WINDOWS -D_DEBUG FILE.cpp 2>iwyu_out.txt`

2) Cleanup IWYU report file (_iwyu_out.txt_). For example I had to remove "stdafx.h" (precompiled header) from the list and replace <> with simple "" for all new #include paths.

3) Fix includes from IWYU report.

`python fix_includes.py --noblank_lines --nocomments --nosafe_headers --nokeep_iwyu_namespace_format <iwyu_out.txt`

4) Compile.

**Comment by pjwhams** [comment]
See also the IncludeToolbox AddIn which does this already: https://github.com/Wumpf/IncludeToolbox

**Comment by mariru27** [comment]
Hi @d0ru, @pjwhams,

You can use `Optimize includes` command  (include-what-you-use) available in [Clang Power Tools release v2023.6.0](https://clangpowertools.com/CHANGELOG.html)
