### ISSUE TITLE
Format on Save is not working

### ISSUE THREAD

**Issue by marovira** [Caphyon/clang-power-tools#1173]
Recently I noticed that having Format on Save turned on wasn't formatting files whenever I saved them. I can confirm that manual formatting works via selection or whole document (`Edit.FormatSelection` and `Edit.FormatDocument`) but having format on save seems to have no effect.

**VS Info:**
* Visual Studio Enterprise 17.3.4
* ClangPowerTools version: 9.2.0.1954
* Format settings; `style=file`, `Fallback style=none`, `Format on save=on`

Let me know if you need any additional information.

**Update**
Upon more research, it appears that this issue is not exclusive to this extension, and was caused by an update to Visual Studio itself. I'm going to leave what I've found here in case it helps someone come up with a solution (or put more pressure on VS devs to fix it).

Based on [this](https://github.com/Elders/VSE-FormatDocumentOnSave/issues/47) and reading through the tickets linked to this issue, it appears that the problem may have been introduced as early as 17.3.0. According to the logged issues, it seems that VS changed the order of execution on saving files. Specifically, it appears that VS is saving the file before sending the event that Format Document on Save (and I'm guessing Clang Power Tools) rely on to format the file. This issue appears to be inconsistent in prior versions of VS, which I can certainly attest to as it would randomly fail to format on occasion, but it is completely broken in 17.3.4. I don't know if there is a way to fix this, but I figured I'd link the issue here. For what it's worth, the author of Format Document On Save also linked [this](https://developercommunity.visualstudio.com/t/Visual-Studio-clears-dirty-flag-before-c/10124978#T-N10148841-N10155655) issue in the developer community for VS.

**Comment by mariru27** [comment]
Hi @marovira,

Thank you for reporting this issue, and for your feedback.
We working on a fix

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @marovira,

We found a fix, but it is in the testing phase, you can use this pre-release until then.
https://github.com/Caphyon/clang-power-tools/releases/tag/v9.2.1

Regards,
Marina

**Comment by marovira** [comment]
Hi @mariru27,

Thanks a lot for the quick fix! I just tested it and it works perfectly.

Cheers,
Mauricio
