### ISSUE TITLE
"format on save" doesn't seem to work

### ISSUE THREAD

**Issue by jokoon** [Caphyon/clang-power-tools#1175]
Using visual studio 2022 17.3.3 with a .clang-format file present inside the project, I can't manage to make this feature work.

As I understand it, this feature should automatically do a "format" (ALT+M) when saving the file with CTRL+S.

For some reason it doesn't work.

I've tried with and without specifying a clang-format.exe in the format option menu.

This issue seems present both on Clang powertools and Clang powertool 2022 (I'm not really sure what is the difference between those 2 extension on the extension store).

I have disabled similar extension like code beautifier, and I made sure I don't have both CPT and CPT 2022 enabled at the same time.

I am still content with ALT+M, but this feature worked for previous versions.

**Comment by mariru27** [comment]
Hi @jokoon,

Thank you for reporting this issue, and for your feedback.
We working on a fix #1173

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @jokoon,

We found a fix, but it is in the testing phase, you can use this pre-release until then.
https://github.com/Caphyon/clang-power-tools/releases/tag/v9.2.1

Marina

**Comment by jokoon** [comment]
> Hi @jokoon,
> 
> We found a fix, but it is in the testing phase, you can use this pre-release until then. https://github.com/Caphyon/clang-power-tools/releases/tag/v9.2.1
> 
> Regards, Marina

Thanks a bunch!

I tried it and it works.

When can we expect for it to be available on the extension store?

**Comment by mariru27** [comment]
It is in the testing phase, so next week

Marina
