### ISSUE TITLE
Format on Save unexpected behaviour

### ISSUE THREAD

**Issue by marovira** [Caphyon/clang-power-tools#1177]
This was introduced by the fix to #1173 and #1174. Whenever you save and formatting occurs on the file, Visual Studio displays the file as not saved, meaning you have to save twice in order to get the changes committed to the file: once to trigger formatting, and once again to actually save the file.

This can cause some issues where files that you saved aren't actually written to disk.

**Comment by mariru27** [comment]
Hi @marovira,

Thank you for reporting this issue, is helping us a lot
We can reproduce this problem and we are working on a fix.

Regards,
Marina

**Comment by mariru27** [comment]
Hi @marovira,

Did you try our last release [v9.2.2](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools#:~:text=Clang%20Power%20Tools%20is%20a,with%20its%20static%20analyzer%20and)?

Best regards,
Marina

**Comment by marovira** [comment]
Hi @mariru27 

Yes I tried it last night and it works perfectly. Thanks for the fast turnover on these bugs!

Cheers!
