### ISSUE TITLE
Disabling ALL Predefined Checks still results in some checks being performed

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#1180]
After disabling all predefined checks here: Settings->Tidy->Predefined Checks (Select)

and then running a Tidy, I still see various results for checks such as DeadStore being reported in the Output and Error List.

I believe the issue may be with the resulting .clang-tidy file that is being auto generated prior to the Tidy:

It only contains a single line as follows:
Checks: ''

But if I export a .clang-tidy file manually I see:
Checks:            '-*'

**Comment by mariru27** [comment]
Hi @netx123,

Can you help us with some more information and give us settings,json file that contains predefined checks? Usually you can find it in "C:\Users\Your_Username\AppData\Roaming\ClangPowerTools\settings.json"

Best regards
Marina

**Comment by netx123** [comment]
Hi @mariru27,
Please find attached the requested settings file.
[settings.zip](https://github.com/Caphyon/clang-power-tools/files/9663702/settings.zip)

**Comment by mariru27** [comment]
I think this is not a bug, you are using in a different way our functionality

If you set  `Detect .clang-tidy file` property Off, tidy will run based on selected predefined checks (not from .clan-tidy file), and will be stored in "C:\Users\Your_Username\AppData\Roaming\ClangPowerTools\settings.json"

If you want to make an .clang-tidy file and share with someone else, or just keep it, you can press `Export` button and save it,
of course if you want to make tidy based on predefined checks from .clang-tidy file, you can set  `Detect .clang-tidy file` On

Please tell me if it works for you
Investigating your problem I found some bugs that we will fix #1181, thank you for report

Best regards,
Marina

**Comment by netx123** [comment]
I beleive this is still a bug. As you say yourself, with Detect .clang-tidy file property Off, "tidy will run based on selected predefined checks", however this is not the case, the important thing here is that with ALL predefined checks being disabled, it can be observed that checks are still being reported, which is not the expected behaviour.

The issue is that the Checks value being written to .clang-tidy and settings.json should always start with Checks: '-*' (To ensure that all checks are first disabled) without this you still get some checks being performed, then concatenate the checks from predefined checks, for example Checks: '-*,abseil-duration-comparison'

**Comment by mariru27** [comment]
You are right, thank you for helping me to understand the problem 

I am working on a fix

Best regards,
Marina
