### ISSUE TITLE
Version 9.2.2.1998 skips all projects after Clang compile starts post MSVC Build

### ISSUE THREAD

**Issue by IrisPeter** [Caphyon/clang-power-tools#1183]
Hi,

I'm a new user and so as such I might just be getting the setup wrong.  I've had the power tools installed for a while but didn't really have time to use it, my first foray into it is to try clang-tidy today.

I have some code where it has

```cpp
if (map_container.size() == 0) doSomething()
```
which I was hoping after clang tidy was configured with readability-container-size-empty would after running the fix become
```cpp
if (!map_container.empty() == 0) doSomething()
```

when it didn't I looked for a reason and I noticed at the top of the output
```
Error while trying to load a compilation database:
Could not auto-detect compilation database for file "TestDA.cpp"
```
and so I thought well it must need the compilation database to be able to spot that one so I initiated a compile. I have seen the clang compile running quite a few times and you see some output from the code (i.e you see the odd line of code from one of the .cpp files), but I did notice at the top a syntax error for the powershell alias.

It turned out that for some reason when I installed the powershell script, it ended up with a 2nd backslash when setting the value for the cpt alias, once I fixed that the clang compile seemed to stop doing any compiling what so ever and instead for every project in the solution says:
```
--- CLANG COMPILE STARTED ---

PROJECT #124: C:\Dev\proj1.vcxproj [|]
Skipped. Configuration not present: |
```

it then carries on until its iterated through every project in the solution and then ends with
```
--- CLANG COMPILE FINISHED ---
```

How do I get round this?  I have the latest LLVM 15.0.0 installed within the power tools configuration

**Comment by mariru27** [comment]
Hi @IrisPeter,

To help you I need to investigate this problem first, I hope you can help me with some informations

Can you send us a screenshot with your `platform configurations`?
From Build -> Configuration Manager

And a full log with `Verbose Mode` On 
Settings from tool bar -> Compile -> Verbose Mode

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @IrisPeter 

New [Clang Power Tools v2023.2.1](https://clangpowertools.com/CHANGELOG.html) release may fix the problem. Can you try it and tell us if it works?

Best regards,
Marina

**Comment by Bluesman74** [comment]
Hi @mariru27 

Yes that seems to have solved that problem.  Is there any way they can add the functionality so that it will trigger a checkout of the affected files, as otherwise I have to checkout the entire directory I'm working on, run the Clang Tidy step, and then run the TFS command required for it to uncheckout all unchanged files.

**Comment by mariru27** [comment]
Hi @Bluesman74,

Thank you for your feedback
Could you provide more information about your suggestion, including examples?

Kind  regards,
Marina

**Comment by IrisPeter** [comment]
> Hi @mariru27
> 
> Yes that seems to have solved that problem. Is there any way they can add the functionality so that it will trigger a checkout of the affected files, as otherwise I have to checkout the entire directory I'm working on, run the Clang Tidy step, and then run the TFS command required for it to uncheckout all unchanged files.

@mariru27 if I am working on code that is stored in TFS, within Visual Studio, if I make an edit in the file within Visual Studio then TFS automatically checks out that file for me, however when I click on the Tidy Icon clang-tidy goes off and finds a whole load of files it wants to modify, these files are all stored in TFS when I chose to say yes to modify the files it has discovered, it doesn't realise that they are need to be checked out for it to be able to edit them.

**Comment by mariru27** [comment]
We will close this issue as no information was provided
