### ISSUE TITLE
automatic including order adjustment should ignore pch.h

### ISSUE THREAD

**Issue by 3roman** [Caphyon/clang-power-tools#1193]
automatic including order adjustment should ignore some special head files(tipically pch.h), otherwise, it will always cause compilation errors.

> Hi @3roman,
> 
> Unfortunately, we don't have support for that, and we don't have in plan to make some changes in the near future. But I recommend something that we are using too, [disable format on a piece of code](https://releases.llvm.org/3.6.0/tools/clang/docs/ClangFormatStyleOptions.html)
> 
> Clang-format understands also special comments that switch formatting in a delimited range. The code between a comment `// clang-format off` or `/* clang-format off */` up to a comment `// clang-format on` or `/* clang-format on */` will not be formatted.
> 
> Best regards, Marina

@mariru27 Thanks for your serious reply. 
I think this is a good compromise to deal with my issue immediately. Good Job!!!

**Comment by mariru27** [comment]
Hi @3roman,

Unfortunately, we don't have support for that, and we don't have in plan to make some changes in the near future.
But I recommend something that we are using too, [disable format on a piece of code](https://releases.llvm.org/3.6.0/tools/clang/docs/ClangFormatStyleOptions.html)

Clang-format understands also special comments that switch formatting in a delimited range. The code between a comment `// clang-format off` or `/* clang-format off */` up to a comment `// clang-format on` or `/* clang-format on */` will not be formatted.

Best regards,
Marina
