### ISSUE TITLE
Hyperlinks in Tidy Checks Not Found for clang-analyzer-* links

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#1211]
Steps to reproduce:

1) Open the Settings Screen
2) Click the Tidy tab, and Click the "Select" button for Predefined Checks
3) Scroll to any of the "clang-analyzer-*" checks, and click the "Description" hyperlink

Expected: The corresponding web page to open
Actual: The website shows "Not Found" error

The format of the URLs may have changed for these, as the links in CPT are like:
https://clang.llvm.org/extra/clang-tidy/checks/clang/analyzer-optin.osx.OSObjectCStyleCast.html

But the links on clang.llvm.org are:
https://clang.llvm.org/extra/clang-tidy/checks/clang-analyzer/optin.osx.OSObjectCStyleCast.html

**Comment by mariru27** [comment]
Hi @netx123,

Thank you for reporting this issue
I can reproduce the problem, a fix will be available in the next release.

Best regards,
Marina
