### ISSUE TITLE
Several Tidy Checks are missing from the list

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#1213]
I've compared the list of available checks from LLVM 15.0.4 with the list in CPT and found the following are missing from CPT.

abseil-cleanup-ctad
altera-id-dependent-backward-branch
altera-unroll-loops
bugprone-assignment-in-if-condition
bugprone-easily-swappable-parameters
bugprone-implicit-widening-of-multiplication-result
bugprone-shared-ptr-array-mismatch
bugprone-stringview-nullptr
bugprone-suspicious-memory-comparison
bugprone-unchecked-optional-access
bugprone-unhandled-exception-at-new
cert-err33-c
cert-exp42-c
cert-flp37-c
cert-pos47-c
clang-analyzer-apiModeling.Errno
clang-analyzer-apiModeling.TrustReturnsNonnull
clang-analyzer-cplusplus.StringChecker
concurrency-thread-canceltype-asynchronous
cppcoreguidelines-prefer-member-initializer
cppcoreguidelines-virtual-class-destructor
misc-confusable-identifiers
misc-const-correctness
misc-misleading-bidirectional
misc-misleading-identifier
modernize-macro-to-enum
objc-assert-equals
portability-std-allocator-const
readability-container-contains
readability-container-data-pointer
readability-duplicate-include
readability-identifier-length
readability-suspicious-call-argument

**Comment by mariru27** [comment]
Hi @netx123,

Thank you for this remark, it helps us a lot to make Clang Power Tools a better product
I will introduce these checks in the next release

Have a nice day,
Marina
