### ISSUE TITLE
CPT 9.5.0.14 seems to have triggered a regression for issue #1180

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#1216]
Installed update 9.5.0 today and performed a comparision of results from the previous 9.4.0 and have discovered that the issue #1180 seems to have returned.

For example even though the check clang-analyzer-deadcode.DeadStores is disabled, when running 9.5.0 on a project this is once again showing clang-analyzer-deadcode.DeadStores checks to appear in the results pane.

**Comment by mariru27** [comment]
Hi @netx123,

Thank you for reporting this issue
After investigating more, I found out that this bug was present in [v9.4.2](https://github.com/Caphyon/clang-power-tools/releases/tag/v9.4.2) too
I am working on a fix

Have a nice day,
Marina

**Comment by mariru27** [comment]
I tried your example, and for me works
Can you try with a predefined check on, and after with all predefined checks off? This problem is still reproducing?

If you disable all predefined checks, you will see this error:
```
Error: no checks enabled.
USAGE: clang-tidy.exe [options] <source0> [... <sourceN>]
OPTIONS:
Generic Options:
  --help                         - Display available options (--help-hidden for more)
  --version                      - Display the version of this program
clang-tidy options:
  --checks=<string>              - 
  . . .
  ```
  Make sure to Export Tidy file config (if Detect .clang-tidy file is active)
  Setting -> Tidy -> Export Tidy file config

**Comment by netx123** [comment]
Hi @mariru27 , I've tested again with all predefined checks off, and I still have the same issue.

I am testing this on an entire project (around 30 files)

Looking through the output window I do see several "Error: no checks enabled."
"USAGE: clang-tidy.exe" messages, which are probably from each running thread, however I suspect that some threads in the new parallel execution mode are having issues accessing the .clang-tidy config file due to a conflict, as I also see the folllowing in the output window:

The process cannot access the file 'F:\ourTestProject\.clang-tidy' because it is being 
used by another process.

Cannot create a file when that file already exists.
    + CategoryInfo          : WriteError: (F:\...\.clang-tidy:String) [Rename-Item], IOException
    + FullyQualifiedErrorId : RenameItemIOError,Microsoft.PowerShell.Commands.RenameItemCommand
    + PSComputerName        : localhost

Cannot find path 'F:\ourTestProject\.clang-tidy' because it does not exist.

After this point in the output I start seeing clang tidy reporting results for checks when it shouldn't be.

**Comment by mariru27** [comment]
You are right @netx123, parallel execution is causing this problem. 
Thank you for helping me to find out the problem

I am working on a fix

Have a nice day,
Marina

**Comment by mariru27** [comment]
Hi @netx123,

We are working on a fix, in the meantime, you can use our previous version of Clang Power Tools [v9.4.2](https://github.com/Caphyon/clang-power-tools/releases/tag/v9.4.2)

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @netx123,

We made a release with a fix for this bug
Try Clang Power Tools [v9.5.1](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools#:~:text=Clang%20Power%20Tools%20is%20a,with%20its%20static%20analyzer%20and) and tell us if the problem is still reproducing 

Thank you for your cooperation

Have a nice day,
Marina

**Comment by netx123** [comment]
Hi @mariru27,

Wow, thank you for fixing this so quickly,
I’ve tested and it’s working great now, really fast too!

Thanks again.
