### ISSUE TITLE
Option to limit the number of cores

### ISSUE THREAD

**Issue by Philippe91** [Caphyon/clang-power-tools#1218]
Your recent addition to run on multiple cores is great, but you should provide an option to limit the number of cores being used. My computer gets too warm after some minutes.

**Comment by Philippe91** [comment]
Great support, thanks!

**Comment by Philippe91** [comment]
I could only try the option "limit the number of cores" today on my large project. Unfortunately, it is not ok 🙁
Let me explain why.
You use the environment variable "NUMBER_OF_PROCESSORS" and let the user apply a coefficient between 50% and 100% to it... the problem is that "NUMBER_OF_PROCESSORS" gives the number of virtual cores. This means, if the machine has hyperthreading (typical case), this number is twice the number of physical cores. But what counts for the power consumption is the number of physical cores.

Let's take an example: on my machine, "NUMBER_OF_PROCESSORS" is 64 because the CPU has 32 physical cores and hyperthreading. If I select 50% in the Clang-Power-Tools options, the process will run on 32 cores... this will mean **32** processes, each one running in its own thread. This means full power consumption :)

**The solution is easy**: rather than a low limit of 50%, give a low limit of 20 or 25%.

**Comment by mariru27** [comment]
Hi @Philippe91,

I understand your problem, thank you for sharing this information with us
We will change the low limit to 20%
I will let you know when a release with this improvement is available

Have a nice day,
Marina

**Comment by mariru27** [comment]
Hi @Philippe91,

A release with bugfix for this issue is available in new [v2023.2.1 of Clang Power Tools](https://clangpowertools.com/CHANGELOG.html)

Thank you for your help

Have a nice day,
Marina
