### ISSUE TITLE
Allow export for clang make

### ISSUE THREAD

**Issue by g-glowacki** [Caphyon/clang-power-tools#122]
I will really appreciate if there will be a possibility to export or even print the whole command called when clang and clang-tidy is called. 
I know the command line could be really long, especially when there's a long -I list, but it really will help me (and I think many others) executing the clang-tools by hand or even build a simple cmake for it.

**Comment by cpp-red-lion** [comment]
You can see all the details behind the scenes, including the command line passed to `clang++` or `clang-tidy` by activating the **verbose mode**.

`Clang Power Tools > Settings > General > Verbose Mode` => **True**

Eg.  **[Output tab]**

**clang++**

`VERBOSE: Clang job args[0]: -include-pch "win\GuiProj.clang.pch" -x c++ "editor\ImageButtonControl.cpp" -Werror -std=c++14 -Wall 
-fms-compatibility-version=19.10 -fms-compatibility -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-variable -Wno-unused-value -fsyntax-only -DWIN32 -D_WINDOWS -D_DEBUG -DUNICODE -D_UNICODE`

**clang-tidy**

`VERBOSE: Clang job args[0]: "editor\ImageButtonControl.cpp" -checks=-*,modernize-use-equals-default,modernize-use-equals-delete 
-header-filter="comps\\win" -quiet -- -Werror -std=c++14 -Wall -fms-compatibility-version=19.10 -fms-compatibility -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas 
-Wno-unused-variable -Wno-unused-value -DWIN32 -D_WINDOWS -D_DEBUG -DUNICODE -D_UNICODE`
