### ISSUE TITLE
Format file extension not updating (.ixx)

### ISSUE THREAD

**Issue by xoorath** [Caphyon/clang-power-tools#1221]
Hey,

I have a c++20 module file and am trying to run clang format on it. It would appear that adding .ixx to the file extensions does not appear to provide any option to format the file.

![image](https://user-images.githubusercontent.com/769014/206886684-186e04ea-018a-4154-a9b5-28bede99e4db.png)

**Comment by xoorath** [comment]
I'm wondering if / assuming that this is related to module support itself and not the file extensions in particular #1094 

Really happy to see recent activity on that issue.

**Comment by xoorath** [comment]
Huh, I'm finding that the clang-format installed with the power tools (LLVM 15.0.5) handles module files just fine, so maybe there is another issue with file extensions not getting passed to clang-format?

**Comment by mariru27** [comment]
Hi @xoorath,

Thank you for reporting this problem
I tested format on .ixx file, you are right, it works with LLVM 15.0.5
From extension, format options are enable just on some specific file extensions (that not include .ixx right now)
But we will fix that problem, and a fix will be available in next release

I will notify you here when the release will be made

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @xoorath,

We enabled format on .ixx file extensions and it is available in release [v2023.1](https://clangpowertools.com/CHANGELOG.html)
Let us know if It works for you

Have a nice day,
Marina
