### ISSUE TITLE
Clang-Tidy ignores <ExternalIncludePath> dependencies

### ISSUE THREAD

**Issue by mikaelwallin-rw** [Caphyon/clang-power-tools#1224]
We use <ExternalIncludePath></ExternalIncludePath> in Visual Studio. This makes us able to configure Microsoft Static Analysis for External dependencies however this seems to be ignored by Clang-Tidy so it cannot perform its analysis because it breaks when it encounters a dependency that it cannot find.

**Comment by mariru27** [comment]
Hi @mikaelwallin-rw,

Sorry for delayed answer

Can you help us to reproduce this issue? 
Can you give as an text project and a full output (don't forget to activate verbose mode from Settings -> Compile)?

Best regards,
Marina

**Comment by mikaelwallin-rw** [comment]
[ExternalDependenciesExample.zip](https://github.com/Caphyon/clang-power-tools/files/10732211/ExternalDependenciesExample.zip)
[verbose_compile.txt](https://github.com/Caphyon/clang-power-tools/files/10732223/verbose_compile.txt)

Sure, I hope I can be of help.
Here you go. 

Best regards,
Mikael

**Comment by mariru27** [comment]
Hi @mikaelwallin-rw,

We have tested your project, and it works, after we made some changes
You need to change `Additional Include Directories` value to `$(ProjectDir)` 

Click right on your project -> Properties -> C/C++ -> General -> `Additional Include Directories` 
Don't forget to change Configuration and Platform value to All before modifying Additional Include Directories

![image](https://user-images.githubusercontent.com/46792157/220392787-6ea389b8-edd5-4329-8eec-6da287b96f74.png)

You can restart your Visual Studio before running again clang-tidy

Let me know if you need more information

Kind regards,
Marina

**Comment by mikaelwallin-rw** [comment]
Hello Marina,

The above project uses <ExternalIncludePath>.\include;$(ExternalIncludePath)</ExternalIncludePath> to include the dependencies.
This is to demonstrate an external dependency. We use this feature in Visual Studio to control Static Analysis Warnings on external dependencies. 
However, Clang-Power-Tools does not parse these dependencies when compiling. So it fails.
I do not want to use Additional Include Directories because then we cannot control Static Analysis warning levels on those external includes.

Kind regards,
Mikael

**Comment by mariru27** [comment]
Hi @mikaelwallin-rw,

Thank you for provided information
We are looking into it and working towards a fix.
I will keep you updated as progress is made.

Best regards,
Marina

**Comment by mikaelwallin-rw** [comment]
Hi @mariru27,
Fantastic. Thank you.

Have a nice day
Mikael
