### ISSUE TITLE
clang-tidy dont apply fixes 

### ISSUE THREAD

**Issue by usser0134** [Caphyon/clang-power-tools#1225]
I have an issue with clang-tidy auto replacement when modernize, it dont work..
I even tried run visual studio as administrator, but dont seem to work

**Comment by mariru27** [comment]
Hi @usser0134,

Thank you for reporting this issue

Can you give us a code example?
What tidy check are you using?

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @usser0134,

You can activate verbose mode, and give us from output so we can help you

Have a nice day,
Marina
