### ISSUE TITLE
New version popup keeps appearing on first build after opening Visual Studio

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#1228]
Previous versions of CPT would display the New Version pop only once.

However after upgrading to 2023.1 the new version pop keeps appearing on the first build after opening Visual Studio.

**Comment by mariru27** [comment]
Hi @netx123,

We are working on a fix right now, thank you for reporting this issue
I will notify you here when an release with this fix will be available

Best regards, 
Marina

**Comment by mariru27** [comment]
@netx123 

In Clang Power Tools [v2023.1.1](https://clangpowertools.com/CHANGELOG.html) we fixed the popup issue
Thank you again for reporting this problem

Have a nice day,
Marina
