### ISSUE TITLE
C++20 compatibility

### ISSUE THREAD

**Issue by Philippe91** [Caphyon/clang-power-tools#1231]
Tidy and Compile don't seem to understand C++20 code. A lot of errors are generated.
Can you give an example of Compile flags that works for you (for the latest MSVC and C++20 and Clang 15.04) ?

Also, the option "Continue on Error" seems to have no effect.

**Comment by mariru27** [comment]
Hi @Philippe9,

Thank you for reporting this issue
Make sure that in your .vcxproj project, Language Standard si set to stdcpp20
You need to have this line:  `<LanguageStandard>stdcpp20</LanguageStandard>`
Can you give us clang compile log with verbose mode on?

Best regards,
Marina

**Comment by Philippe91** [comment]
I am speaking about the clang compiler and clang-tidy as run by ClangPower Tools; see picture. My large solution is using c++20 with MSVC without any problem. My question is: what command line (on picture) are you using for a c++20 project with the latest MSVC IDE?

![image](https://user-images.githubusercontent.com/8200618/210800218-6e2106e3-be57-4c97-be41-633ffeeaab1b.png)

**Comment by mariru27** [comment]
Hi @Philippe91,

You can activate verbose mode from the same window. 
Run compile, and in output you can see the command line we are using

This is an example:
`
VERBOSE: INVOKE: C:\Users\M\AppData\Roaming\ClangPowerTools\LLVM_Lite\Bin\clang++.exe -x c++ "C:\Users\M\source\repos\RSA-BigInt\BigInt\Source.cpp" -std=c++14 -Wall -fms-compatibility-version=19.10 -Wmicrosoft 
-Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-value -m32 -fsyntax-only "-DUNICODE" "-D_UNICODE" "-D_MT" 
"-D_DLL" "-D_DEBUG" "-D_CONSOLE" "-D_DEBUG_FUNCTIONAL_MACHINERY" -isystem"C:\Program Files\Microsoft Visual 
Studio\2022\Community\VC\Tools\MSVC\14.33.31629\include"......
`

Best regards,
Marina

**Comment by Philippe91** [comment]
To answer my original question, it was in fact, necessary to specify: -std=c++20

My mistake was thinking -Wc++20-compat was enough.
