### ISSUE TITLE
After using clang Tidy, the animated building icon in the status bar never clears

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#1240]
I've seen this for a while now but have only today realized that the issue is triggered by using the clang tidy option.

Usually when you Build a project the animated building icon can be seen in the status bar, and once the build finishes the icon dissapears.

However when ever I perform CPT->Tidy the build animation appears, but remains there animating forever.
Even when future builds are performed the animation will now never dissapear.

![BuildingIcon](https://user-images.githubusercontent.com/8387938/213290302-d5b05277-6622-4459-8f5d-818b01f6174e.png)

**Comment by mariru27** [comment]
Hi @netx123,

You are right, I can reproduce this problem, we are working on a fix
Thank you for reporting issues, and for you contribution

Have a nice day,
Marina

**Comment by mariru27** [comment]
Hi @netx123,

The issue can be resolved by upgrading to release v2023 of Clang Power Tools and Clang-Format Editor. 

Thank you, we appreciate your assistance in improving our product.

Have a nice day,
Marina
