### ISSUE TITLE
Cannot run ClangFormatEditor.exe

### ISSUE THREAD

**Issue by irissam** [Caphyon/clang-power-tools#1242]
Hi. I'm very excited to try out this tool, but I have not been able to get it to run.

In Visual Studio, I'm able to open the Clang Power Tools settings window, but when I try to open "Clang-Format Editor" from the "Format" tab, I'm shown a small dialog box that reads: "To run this application, you must install .NET. Would you like to download it now?" I press "Yes", but nothing ever happens.

I'm using Visual Studio 2022 version 17.4.4. I've tried both extensions "Clang Power Tools" and "Clang Power Tools 2022" from the Visual Studio Marketplace, and both are presenting me with the same issue. I've also tried installing the standalone "Clang Format Editor" from https://www.clangpowertools.com/ClangFormatEditor.msi, which has the same issue.

![image](https://user-images.githubusercontent.com/62903761/215218244-e39ac755-a592-4eb0-97c9-37733cb9b018.png)

Thanks in advance for your help

**Comment by irissam** [comment]
Forgot to mention, I have already installed the .NET 5.0 Desktop Runtime (v5.0.2) from here: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-5.0.2-windows-x86-installer

**Comment by irissam** [comment]
My issue was I installed the x86 version of .NET framework, when I should have installed the x64 version. Funny how I figure this out immediately after reporting the issue 😅

**Comment by mariru27** [comment]
Hi @irissam,

No problem, I am glad that you found the solution

Have a nice day,
Marina
