### ISSUE TITLE
Closing CPT Settings screen causes the "Output" pane to get focus

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#1247]
For example I often have the focus on the "Error List" or "Task List" panes.

However if I go into CPT Settings and just close the screen, it causes the focus to be switched to the "Output" pane,.

Whilst it's OK for this to happen after a Tidy event has completed,  I don't beleive that this should be happening when simply closing the Settings screen.

**Comment by mariru27** [comment]
Hi @netx123,

You are right, I can reproduce this issue
Investigating this problem I found another one #1249 :smile:

Thank you for your help, I will let you know when a fix is available

Have a nice day,
Marina

**Comment by mariru27** [comment]
Hi @netx123,

A release with bugfix for this issue is available in new [v2023.2.1 of Clang Power Tools](https://clangpowertools.com/CHANGELOG.html)

Thank you for your help

Have a nice day,
Marina
