### ISSUE TITLE
How to ignore clang-tidy warnigns from thirdparty directory

### ISSUE THREAD

**Issue by FlorianReimold** [Caphyon/clang-power-tools#1250]
Hi,

I analyzed a rather small project of mine, which however uses the header-only asio library. This causes clang-tidy to overload me with thousands of warnings from the included headers:

![image](https://user-images.githubusercontent.com/11774314/216270700-0bee2e19-6f98-4040-9eae-747731cac270.png)

As you can imagine, regularly going through thousands of warnings is not really an option, just to pick out  the few warnings that come from my actual code. Is there a setting to turn those warnings off? 

Kind regards
Florian

**Comment by mariru27** [comment]
Hi @FlorianReimold,

Make sure to include third party library dependencies via the Include directories project option. 
Additional include directories should point only to code you can modernize.

You can find all details in [this blog](https://clangpowertools.com/QaA.html)

Best regards,
Marina

**Comment by FlorianReimold** [comment]
The Visual Studio project file is auto-generated with CMake, so I prefer a generic solution of excluding entire directories that doesn't.
But I think I figured it out, so sorry for bothering.

If anybody ever comes across the same issue: I used a header filter regex to remove the warnings. My regex is `^((?!/thirdparty/|/_deps/).)*$`, which removes warnings from header files inside the `thirdparty` and `_deps` directory.

You have to either:
- Add the regex to the Tidy / Header Filter Option in the GUI (I wouldn't recommend this option)

_or_

- Configure the Addin to use your `.clang-tidy` file and add the following line to it:
    `HeaderFilterRegex: '^((?!/thirdparty/|/_deps/).)*$'`
  **Also make sure** to clear the Tidy / Header Filter Option in the GUI, as it would otherwise override your precious setting.
