### ISSUE TITLE
UI enhancements for Tidy settings - make Custom Checks field more intuitive

### ISSUE THREAD

**Issue by Mike4Online** [Caphyon/clang-power-tools#1257]
In the Clang Power Tools settings tab named `Tidy`, I have found myself editing the `Custom Checks` field, then proceeding with a Clang Tidy run -- only to find that the `Custom Checks` I specified were ignored and instead checks were obtained from my `.clang-tidy` file.

### SUGGESTION No. 1
Enhance this tab so the `Custom Checks` field would be greyed out and read-only -- unless the `Use check from` field was set to `CustomChecks`.

On the same tab, under `Custom Checks`, I often type an explicit list of checks and forget that Clang Tidy enables its own default set of checks above-and-beyond what I specify explicitly.  Sometimes the checks I specify cannot perform their fixes because some default check can also fix the same line of code, and the two fixes are conflicting with each other.

### SUGGESTION No. 2
Add a checkbox to the `Tidy` settings tab named `[  ]  disable default checks` that when checked would implicitly add `-*;` in front of any specified Custom Checks text.  This checkbox -- whether enabled or disabled -- would be remembered on subsequent runs.  As with the first suggestion, this new checkbox would be greyed out and read-only unless `Use checks from` was set to `CustomChecks`.

**Comment by mariru27** [comment]
Hi @Mike4Online,


Thank you so much for your suggestion! I really appreciate it and will definitely give it some thought
What version of Clang Power Tools are you using?

Regards,
Marina

**Comment by Mike4Online** [comment]
I am running Clang Power Tools 2022 version 2023.2.0
LLVM = 15.0.7
Visual Studio 2022 build 17.4.2

**Comment by mariru27** [comment]
Interesting, because we thought that we don't have a problem with checks that cannot be performed because of conflicts.
Thank you for letting us know

 Would you be able to provide me with a test project so I can replicate the issue? Any help would be greatly appreciated.

I need to discuss with my colleagues about your suggestions before moving forward, I will let you updated

Best regards,
Marina

**Comment by Mike4Online** [comment]
I am still attempting to replicate the issue.  I am now able to run `clang-tidy.exe` from a Command Prompt, using commands based on the INVOKE commands shown in Clang Power Tools verbose mode.  There seems to be an issue with conflicts in the check named `cppcoreguidelines-prefer-member-initializer` that is independent of Clang Power Tools.  But I was able to get this check to apply fixes when run directly via `clang-tidy.exe`, despite these conflicts.  I intend to post another comment when I have more to report and a simplified example.

I am also attempting to write a procedure or guideline for myself in running Clang-Tidy checks to perform fixes.  Specifically, I am trying to understand:

- Which Clang-Tidy checks may overlap each other in some ways, and which of these are best and in what order to run them.  For example, `cppcoreguidelines-init-variables`, `cppcoreguidelines-pro-type-member-init`, and `modernize-use-default-member-init`.  
- What order to run other fixes.  For example, running the `member init` fixes before running `modernize-use-equals-default`.
- Which fixes may need to be run more than once, e.g.  `misc-const-correctness` along with `readability-make-member-function-const`
- Which fixes have bugs which can corrupt my source files.  For example, `readability-isolate-declaration` can add newlines (LF) as end-of-line markers wherever it adds new lines, even if the source file uses CR+LF (Windows-style) line endings.

As Clang-Tidy experts, do you or your team have any Clang-Tidy notes or guidelines that you could post?

**Comment by mariru27** [comment]
Hi @Mike4Online 

Unfortunately, we don't have any Clang-Tidy notes or guidelines that we can share. However, we're happy to help answer any questions you might have as you work on your procedure or guideline.

Best regards,
Marina

**Comment by mariru27** [comment]
Also thanks for the suggestion! My colleague and I have discussed it, and we agree that it would be a good idea to enhance the tab as you suggest. We plan on implementing your suggestion in the near future

**Comment by mariru27** [comment]
Hi @Mike4Online =,


is issue is available in new [v2023.2.1 of Clang Power Tools](https://clangpowertools.com/CHANGELOG.html)

Thank you for your help

Have a nice day,
Marina

**Comment by Mike4Online** [comment]
I am glad that the `Custom Checks` field is now read-only unless `Use check from` is set to `CustomChecks`.  But even when this field is read-only, it is not shown disabled (i.e. with gray shading).  So it is not _visually obvious_ that the the `Custom Checks` do not apply.   If you could gray the field when disabled, (and un-gray it when enabled), that would finish this feature request.

As for the `Disable default checks` checkbox to implicitly add `-*;` to whatever the user specifies in `Custom Checks`, I'd still like to see that. What do you think of this second suggestion?

**Comment by mariru27** [comment]
You are right @Mike4Online, I forgot to disable the default checks (I think your suggestions are good)

I appreciate you bringing up this topic and offering assistance

Have a nice day,
Marina

**Comment by mariru27** [comment]
Hi @Mike4Online,

Implementation for this issue is available in new [v2023.3.0 of Clang Power Tools](https://clangpowertools.com/CHANGELOG.html)

Thank you for your help

Have a nice day,
Marina

**Comment by Mike4Online** [comment]
The `Custom Checks` field is now read-only and visually greyed-out, unless `Use check from` is set to `CustomChecks`. I still do not see a new checkbox to disable default checks.  But I'm glad for the changes and will close this feature request as resolved.
