### ISSUE TITLE
Feature: Specify .clang-tidy location or discover.

### ISSUE THREAD

**Issue by mikaelwallin-rw** [Caphyon/clang-power-tools#1267]
We want to use one .clang-tidy file for the whole repository. However, clang-tidy does not detect the file in the root folder.
The .clang-tidy file must be located in the same place as the  .cpp file. From what I have discovered. clang-tidy has `--config-file=<string>`  could you expose this in UI? Another suggestion would be for the application to discover .clang-tidy files by traversing the path up to the root location and discover .clang-tidy files. Same behavior as clang-format.

We use the root folder behavior of .clang-format but .clang-tidy weirdly does not work the same.

**Comment by mariru27** [comment]
We already detect .clang-tidy file in the root folder
Make sure to have `Detect .clang-tidy file` active and `Use check from Tidy File` selected
![image](https://user-images.githubusercontent.com/46792157/223653532-77451e97-0fa4-4714-8654-d1a4ef46e66f.png)

You can also test with our tool to `Export` Tidy file config, and make sure that you don't have a typo in your .clang-tidy file

If you still have problems, please send us a test project with `.clang-tidy` file in it, to reproduce your issue

Best regards,
Marina

**Comment by mikaelwallin-rw** [comment]
Yes, this is correct. The repository-wide .clang-tidy was blocked by a misplaced .clang-tidy in a folder further down. Closing this issue.
