### ISSUE TITLE
Display full command line for commands called in Visual Studio output in verbose mode

### ISSUE THREAD

**Issue by mariusz102102** [Caphyon/clang-power-tools#127]
It was partially implemented in https://github.com/Caphyon/clang-power-tools/issues/104

1. All command lines should be self contained.  We should be able to copy/paste (to cmd, power-shell terminal without additional settings). It will simplify debugging and testing. 
Currently it is impossible seeing only visual studio output to guess: what is path to clang.exe, how to pass include paths to clang.exe.
1.1. add full path to clang.exe
Instead of adding clang.exe 
`$env:Path += ";$locationLLVM"`
and than calling clang.exe. it is better to just use full path clang.exe
1.2. add include paths to clang.exe call 
 instead of setting environment variables
 $ENV:INCLUDE = $includePathsString;
it is better explicit specify include path when calling clang.exe

2. Display clang_builds.ps1 command line from Visual Studio plugin before calling clang_builds.ps1
3. Display clang (see point1 ) command line before building pch
4. Display clang (see point1 ) command line before building cpp

**Comment by chri7325** [comment]
I can't seem to see verbose output either when running the clang_builds.ps1 script from cmd.exe.  Is it possible to add a switch for this?

**Comment by cpp-red-lion** [comment]
@chri7325 There is a standard PowerShell switch to put the script in VERBOSE mode: `-verbose`
Just append it to your command-line.

In fact, this is what our VS extension does when you enable Verbose mode from the Settings GUI.

**Comment by chri7325** [comment]
@cpp-red-lion Ah, I see.  I didn't find it in the script so I thought it was missing.  I thought it was set using environment variables.  My apologies.

**Comment by cpp-red-lion** [comment]
Suggested enhancements were addressed in `v2.6`
