### ISSUE TITLE
Tidy: Option "Use checks from" is reset to default

### ISSUE THREAD

**Issue by magnesj** [Caphyon/clang-power-tools#1271]
Version: `2023.3.0`

- In Settings, set Tidy->"Use checks from" to `TidyFile`
- on a project, from the context menu, select "Clang Power Tools"->Tidy
- opening Settings displays "Use checks from" is changed to `PredefinedChecks`

It looks like the execution of clang-tidy on a project reset settings to `PredefinedChecks` . The setting is not changed if clang-tidy is applied on a single file.

**Comment by mariru27** [comment]
Hi @magnesj,

Thank you so much for bringing this issue to our attention
We are committed to resolving the problem and will keep you updated as we make progress

Have a nice day,
Marina

**Comment by mariru27** [comment]
Hi @magnesj,

A fix for this issue is available in Clang Power Tools [release v2023.4.0](https://clangpowertools.com/CHANGELOG.html)

Have a nice day,
Marina
