### ISSUE TITLE
Enable download and installation of LLVM 16.0.0

### ISSUE THREAD

**Issue by bersbersbers** [Caphyon/clang-power-tools#1272]
LLVM 16.0.0 has been released, would be great to be able to use it from the Power Tools:
https://github.com/llvm/llvm-project/releases

**Comment by mariru27** [comment]
Hi @bersbersbers,

Thank you for letting us know about the release of LLVM 16.0.0! 
We appreciate your suggestion and we'll definitely consider including it in the next release of our Clang Power Tools

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @MarcelNehring,

LLVM 16.0.0 is available in Clang Power Tools [release v2023.4.0](https://clangpowertools.com/CHANGELOG.html)

Have a nice day,
Marina
