### ISSUE TITLE
Regression of Issue: After using clang Tidy, the animated building icon in the status bar never clears

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#1276]
After upgrading to 2023.4.0 I noticed that issue #1240 has returned.

**Comment by mariru27** [comment]
Hi @netx123,

Thank you for reporting this issue
You are right, I can reproduce this problem, we are working on a fix

Have a nice day,
Marina

**Comment by mariru27** [comment]
Hi @netx123,

The fix for this problem is available in [release v2023.5.0 for Clang Power Tools](https://clangpowertools.com/CHANGELOG.html)

Have a nice day,
Marina
