### ISSUE TITLE
Forced includes via propertysheets not found

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#128]
Hi,

In our projects we use propertysheets in which we sometimes also refer to other propertysheets. Hence, you should parse propertysheets recursively. In one of these propertysheets we used a force include which is not included resulting in a compilation failure due to missing symbols. This already goes wrong in the precompiled header generation step, it seems to me that it doesn't pass forced includes into that step?

I tried to work around it by supplying the following in the clang compile options setting:

`-FI "d:\\src\\myforcedinclude.h" `

That doesn't seem to be getting the file either, any way to workaround this for now? 

Kind regards,

Jacob

**Comment by cpp-red-lion** [comment]
Hi,
Are you using the latest version of Clang Power Tools (`v2.0`) ?

**Comment by jcageman** [comment]
Hi,

Yes, just to be sure i downloaded the latest marketplace release just now.

Some more information, a properysheet could look like this:
```
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets">
      <Import Project="a.props" />
      <Import Project="b.props" />
      <Import Project="c.props" />
  </ImportGroup>
</Project>
```

Then a.props could contain:
```
<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
	  <ForcedIncludeFiles>$(ProjectName)_macros.h;$(FRAMEWORKDIR)\includes\coredefines.h;%(ForcedIncludeFiles)</ForcedIncludeFiles>
    </ClCompile>
  </ItemDefinitionGroup>
</Project>
```

**Comment by hero101111** [comment]
Hi @jcageman ,

Property sheets are parsed recursively already.
During the v2.0 refactoring we accidentally introduced a [typo ](https://github.com/Caphyon/clang-power-tools/commit/f5661c9b44ee85361f5a9c3f5bd7cbaeff3e276d)in the xpath selector for the `ForcedIncludeFiles` project setting. Just pushed a fix for it.

We apologize for the inconvenience.

Regards,
Gabriel

---

Please note that this fix is currently live only for the github repository.
The latest Visual Studio extension (2.0) does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Don't forget to restart Visual Studio after replacing the script file.
