### ISSUE TITLE
awareness of `/external:I`

### ISSUE THREAD

**Issue by X1aomu** [Caphyon/clang-power-tools#1280]
While #1270 added support for `ExternalIncludePath`, `/external:I` should have been treat in the same way.

Some tools, like CMake, currently make use of `/external:I` instead of `ExternalIncludePath`. When working with a CMake generated Visual Studio project, the compilation database generated by Clang Power Tool miss some header include directories.

Those include directories is in introduced by such CMake keywords:

```cmake
target_include_directories(<target> SYSTEM ...)
```

which then become `/external:I ...` in the .vcxproj project file.

FYI, there is a issue tracks that [why CMake use `/external:I`](https://gitlab.kitware.com/cmake/cmake/-/issues/23834) .

**Comment by mariru27** [comment]
Hi @X1aomu,

Thank you for reporting this issue
Could you provide us with a sample project to help us better understand and reproduce the issue at hand? We're not familiar with the CMake technology, and this would also enable us to utilize the "/external:I" feature

Best regards,
Marina

**Comment by X1aomu** [comment]
No quite related to CMake, `/external:I ...` is such an extra compiler option that have similar (or same?) effects with `ExternalIncludePath`.

This is a short example Visual Studio Solution.

Files structure:

```
.
├── compile_commands.json (generated by Clang Power Tools)
├── ConsoleApplication1
│   ├── ConsoleApplication1.cpp
│   ├── ConsoleApplication1.vcxproj
│   ├── ConsoleApplication1.vcxproj.filters
├── ConsoleApplication1.sln
├── libabc
│   ├── libabc.cpp
│   ├── libabc.h
│   ├── libabc.vcxproj
│   ├── libabc.vcxproj.filters
```

![image](https://user-images.githubusercontent.com/18374537/232726079-c8f601b7-d4d6-48d0-af91-bfb60c524d7e.png)

The generated compile_commands.json:

```json
[
  {
    "directory": "D:/src/ConsoleApplication1/",
    "command": "\"C:/Program Files/LLVM/bin/clang++.exe\" -x c++ \"D:/src/ConsoleApplication1/ConsoleApplication1/ConsoleApplication1.cpp\" -std=c++14 -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-value -m32 -fsyntax-only \"-DUNICODE\" \"-D_UNICODE\" \"-D_MT\" \"-D_DLL\" \"-DWIN32\" \"-D_DEBUG\" \"-D_CONSOLE\" \"-D_DEBUG_FUNCTIONAL_MACHINERY\" -isystem\"C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/include\" -isystem\"C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.35.32215/atlmfc/include\" -isystem\"C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Auxiliary/VS/include\" -isystem\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/ucrt\" -isystem\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/um\" -isystem\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/shared\" -isystem\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/winrt\" -isystem\"C:/Program Files (x86)/Windows Kits/10/Include/10.0.22621.0/cppwinrt\"",
    "file": "D:/src/ConsoleApplication1/ConsoleApplication1/ConsoleApplication1.cpp"
  }
]
```

The problem: the directory of `libabc.h` doesn't appear in `compile_commands.json`. It could be something like this:

```
-isystem"D:/src/ConsoleApplication1/ConsoleApplication1/libabc"
```

**Comment by mariru27** [comment]
@X1aomu, thank you so much for taking the time to give such a thorough and detailed explanation

I am working on this issue, I will let you know as the progress are made

Kind regards,
Marina

**Comment by mariru27** [comment]
Hi @X1aomu,

A solution for this issue is available in [release v2023.5.0 for Clang Power Tools](https://clangpowertools.com/CHANGELOG.html)

Thank you for your help, means a lot for our product

Have a nice day,
Marina

**Comment by X1aomu** [comment]
thanks for quick action.

I've tried the v2023.5.0, and it worked with my simple example post above.

But my CMake workload still have problems yet. I'll dig some more to find the more presice problemetic case.

**Comment by mariru27** [comment]
Hi @X1aomu,

Any updates about problematic case?

Kind regards,
Marina

**Comment by mariru27** [comment]
I will close this issue as we need more information

**Comment by X1aomu** [comment]
@mariru27 

Sry for late response. I just noticed your reply yesterday, and planned to reply now. But still late for about 1h, lol.

I actually have some discoveries, but couldn't dig deeper because of my busy.

Seems it was a new problem with CMake generated projects, not quite related to `/external:I`.

I have found some error message print from `.ps1` scripts. 

```
--- JSON COMPILATION DATABASE STARTED ---

Evaluate-MSBuildCondition : Cannot bind argument to parameter 'condition' because it is an empty string.
At C:\users\kid\appdata\local\microsoft\visualstudio\16.0_f8cf492b\extensions\scbjrkad.rmj\Tooling\v1\psClang\msbuild-p
roject-load.ps1:620 char:58
+ ...     $validChild = ((Evaluate-MSBuildCondition($nodeCondition)) -eq $t ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Evaluate-MSBuildCondition], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Evaluate-MSBuildCondition
Evaluate-MSBuildCondition : Cannot bind argument to parameter 'condition' because it is an empty string.
At C:\users\kid\appdata\local\microsoft\visualstudio\16.0_f8cf492b\extensions\scbjrkad.rmj\Tooling\v1\psClang\msbuild-p
roject-load.ps1:620 char:58
+ ...     $validChild = ((Evaluate-MSBuildCondition($nodeCondition)) -eq $t ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Evaluate-MSBuildCondition], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Evaluate-MSBuildCondition
Evaluate-MSBuildCondition : Cannot bind argument to parameter 'condition' because it is an empty string.
At C:\users\kid\appdata\local\microsoft\visualstudio\16.0_f8cf492b\extensions\scbjrkad.rmj\Tooling\v1\psClang\msbuild-p
roject-load.ps1:620 char:58
+ ...     $validChild = ((Evaluate-MSBuildCondition($nodeCondition)) -eq $t ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Evaluate-MSBuildCondition], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Evaluate-MSBuildCondition
Evaluate-MSBuildCondition : Cannot bind argument to parameter 'condition' because it is an empty string.
At C:\users\kid\appdata\local\microsoft\visualstudio\16.0_f8cf492b\extensions\scbjrkad.rmj\Tooling\v1\psClang\msbuild-p
roject-load.ps1:620 char:58
+ ...     $validChild = ((Evaluate-MSBuildCondition($nodeCondition)) -eq $t ...
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Evaluate-MSBuildCondition], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Evaluate-MSBuildCondition
Exception calling "IsPathRooted" with "1" argument(s): "Illegal characters in path."
At C:\users\kid\appdata\local\microsoft\visualstudio\16.0_f8cf492b\extensions\scbjrkad.rmj\Tooling\v1\psClang\io.ps1:35
8 char:13
+         if ([System.IO.Path]::IsPathRooted($childPath))
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException
Exception calling "IsPathRooted" with "1" argument(s): "Illegal characters in path."
At C:\users\kid\appdata\local\microsoft\visualstudio\16.0_f8cf492b\extensions\scbjrkad.rmj\Tooling\v1\psClang\io.ps1:35
8 char:13
+         if ([System.IO.Path]::IsPathRooted($childPath))
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentException

Exported JSON Compilation Database to . . . . .
 ```

Found that there was some `Write-Debug` `Write-Verbose` in the `.ps1`s,. How can i enabled the message when generating the compilation database?

**Comment by mariru27** [comment]
Hi @X1aomu,

You are just in time, we trying to close issues that are not more active

We are not proficient in cmake build system, can you help us by providing a test project, it will help us a lot

Regarding to enable Write-Debug message, we don't support this feature at this moment, but we planning to implement. I have opened already an issue #1299..  Thank you for reminding us

Kind regards,
Marina

**Comment by X1aomu** [comment]
Here is the sample project: https://github.com/X1aomu/demo-cmake

Assuming that you have VS2019/VS2022 installed, clone, then `cd` to the project root, then run `cmake --preset vs2019`.

After that, you should find the `.sln` file under dir `build/vs2019`. Open it with VS, then run `Clang Power Tools` against `main.cpp` or the project `the_executable`.

Those should reproduce the problem.

I found, shortly, the `/external:I` may still be relevant...

The first thing is the [`SYSTEM` cmake keyword](https://cmake.org/cmake/help/latest/command/target_include_directories.html), used [here](https://github.com/X1aomu/demo-cmake/blob/41bcf8e646e0cded5fb7ab163ddb1f0a30420ffd/src/libabc/CMakeLists.txt?#L5). With `SYSTEM` keyword, cmake will generate `external:I ...` things instead of using `AdditionalIncludeDirectories`

The second one is that it has something to do with `/` and `\`. I just give a try at changing the generated path, from `/` to `\`, the it works. For example, `/external:I "D:/src/demo-cmake/src/libabc"` to `/external:I "D:\src\demo-cmake\src\libabc"`.

**Comment by mariru27** [comment]
Hi @X1aomu,

Thank you for detailed example, I can reproduce the problem
We are working towards a fix, I will let you know when a release with this bugfix will be available

Kind regards,
Marina

**Comment by mariru27** [comment]
Hi @X1aomu,

We have a bugfix for this issue in Clang Power Tools release v2023.7.0

Kind regards,
Marina

**Comment by X1aomu** [comment]
Now it works.
Thanks.
