### ISSUE TITLE
`Compile` and `Tidy` options are not available for modules (*.ixx)

### ISSUE THREAD

**Issue by jovibor** [Caphyon/clang-power-tools#1282]
They are greyed out.

![image](https://user-images.githubusercontent.com/5625787/233811798-f5b4deb9-5311-484f-9fc9-8a6f85f2c17c.png)

If I rename the file to have `.cpp` extension it all works fine.

**Comment by mariru27** [comment]
Hi @jovibor,

Upon further investigation, it appears that the Clang Compile and Tidy options for modules with the `.ixx` extension are not currently implemented. However, I appreciate you bringing this to our attention and suggesting this functionality

We will look into this and explore the possibility of implementing these options for modules with the `.ixx` extension. We will keep you updated on any progress or developments related to this issue

Thank you for your feedback and for helping us improve our system

Kind regards,
Marina

**Comment by mariru27** [comment]
Hi @jovibor,

Can you help us by testing the [Clang Power Tools VSIX](https://drive.google.com/file/d/1_S5ttfgJOgfw4UTzVF8P0_Spk4xxPWyh/view?usp=sharing) and letting us know if it behaves as intended? If it doesn't meet your expectations, could you provide us with a sample project to test on? 
I'm not very familiar with modules, so this would be very helpful for me

Kind regards,
Marina

**Comment by mariru27** [comment]
I am glad to hear that

Great to know! I appreciate your assistance and the sample provided @jovibor
I'll keep you informed about any updates or progress on this issue

Have a nice day,
Marina
