### ISSUE TITLE
No clang-format after clang-tidy

### ISSUE THREAD

**Issue by Holo-Duke** [Caphyon/clang-power-tools#1287]
Hello,

I'm using CPT 2023.5.0 with LLVM 16.0.0 and after clang-tidy did it's work the code is not formatted by clang-format. I've set `FormatStyle: 'file'` in the `.clang-tidy` file and also Style 'file' and _Format after Tidy: On_ as well as _1-step-tidy-fix: On_ in the UI settings. 
It seems as if the fixes are exported via `--export-fixes` but when they are applied via `clang-apply-replacements.exe` there is no `--format` switch on the command line.
Found out that even if the `--help` of `clang-apply-replacements.exe` says different, I had to specify `--style=file` along with `--format` on the command line as well to get the code properly formatted.

**Comment by mariru27** [comment]
Hi @Holo-Duke,

Thank you for reporting this issue and for detailed description

We are working on a fix, I will let you know when a release with this issue is available

Best regards,
Marina

**Comment by mariru27** [comment]
Hi @Holo-Duke,

A fix for this issue is available in [Clang Power Tools release v2023.6.0](https://clangpowertools.com/CHANGELOG.html)

Kind regards,
Marina
