### ISSUE TITLE
How to choose platform when generating compile command?

### ISSUE THREAD

**Issue by sykuang** [Caphyon/clang-power-tools#1292]
Thank you for contributing an amazing tool for VS, it's really helpful to me when using clangd as the LSP.
I would like to know if it's possible to choose platform to generate the compile_command.json since there exist several platforms in the project solution I am using.

**Comment by mariru27** [comment]
Hi @sykuangm,

Thank you for your positive feedback! I'm glad to hear that you find the tool helpful when using clangd as the Language Server Protocol (LSP) in Visual Studio

Regarding your question, Clang Power Tools does have the capability to generate the compilation database (compile_commands.json) automatically based on the selected toolset from Visual Studio. The compilation database contains the necessary build commands and compiler flags for each source file in your project.

To change your `Platform Toolset` go to project `Properties`

![image](https://github.com/Caphyon/clang-power-tools/assets/46792157/8b17112f-5ba1-42b0-88da-498ca146405a)

Once again, thank you for your feedback, and I'm glad that the tool is assisting you in your development workflow. If you have any further questions or need additional assistance, please feel free to ask!

Have a nice day,
Marina

**Comment by sykuang** [comment]
Hi @mariru27,
Thank you for your quick reply. The issue I met is there are several platforms (win32, x64 and arm); when generating the compile commands, I would like to choose the platform and Debug/Release. However, it always generates commands based on  win32 release. I found a workaround that I can manually modify the order of platforms and versions in visual studio project files to generate the correct version I want.

**Comment by mariru27** [comment]
Hi @sykuang,

Thank you for clarifying the issue. I apologize for any confusion in my previous response. It seems that you were referring to choosing the platform configuration and Debug/Release settings, rather than the platform toolset.

I'm glad to hear that you found a workaround

Have a nice day,
Marina

**Comment by dapetcu21** [comment]
Hi! Can this be re-opened? Manually adjusting the order of platforms or configurations in the project files is not an reasonable option for everyone, especially when there's a large amount of projects in the solution or when the .sln-s are generated by an external tool.
