### ISSUE TITLE
On 2023.6 _MSC_VER recognized incorrectly

### ISSUE THREAD

**Issue by SlavaC1** [Caphyon/clang-power-tools#1296]
I'm trying to compile a project on Power Tools 2023.6 and I see that _MSC_VER recognized incorrectly. It is recognized as 1910 when in fact it's 1936, which causing to take incorrect header files from libraries.

**Comment by mariru27** [comment]
Hi @SlavaC1,

Thank you for reporting this issue

To continue investigate this problem, please provide us full log from output
 - First activate `Verbose mode`
 
Kind regards,
Marina

**Comment by SlavaC1** [comment]
Attaching the log file.
[log.txt](https://github.com/Caphyon/clang-power-tools/files/11891574/log.txt)

Also the header with decisions looks like this:

```
#if _MSC_VER < 1900
	#include "xlocnum_hack_vs2010-2013.h"
#elif _MSC_VER == 1900
	#include "xlocnum_hack_vs2015.h"
#elif _MSC_VER >= 1910 && _MSC_VER < 1914
	#include "xlocnum_hack_vs2017.h"
#elif _MSC_VER == 1914 // VS 2017 version 15.7
	#include "xlocnum_hack_vs2017_15_7.h"
#elif _MSC_VER >= 1915 && _MSC_VER < 1920 // VS 2017 version 15.8 and higher
	#include "xlocnum_hack_vs2017_15_8.h"
#elif _MSC_VER >= 1920 && _MSC_VER < 1926 // VS 2019 version 16.0 to 16.6
	#include "xlocnum_hack_vs2019.h"
#elif _MSC_VER >= 1927 && _MSC_VER < 1929 // VS 2019 version 16.7 to 16.9
	#include "xlocnum_hack_vs2019_16_7.h"
#elif _MSC_VER >= 1929 && _MSC_VER < 1931 // VS 2019 version 16.10 to 16.11, 1930 is VS 2022
	#include "xlocnum_hack_vs2019_16_10.h"
#elif _MSC_VER >= 1931 && _MSC_VER < 1938 // VS 2022 version 17.1
	#include "xlocnum_hack_vs2022_17_1.h"
```

**Comment by mariru27** [comment]
Do you have the same problem on [Clang Power Tools v2023.5.0](https://github.com/Caphyon/clang-power-tools/releases/tag/v2023.5.0) (don't forget to disable auto update after reinstalling this version)?

What version of Visual Studio you using?

**Comment by SlavaC1** [comment]
Same issue with 2023.5.0

**Comment by mariru27** [comment]
Thank you for quick reply

**Comment by mariru27** [comment]
@SlavaC1, you can bypass this problem by changing `-fms-compatibility-version` value (for example in 19.36)

![image](https://github.com/Caphyon/clang-power-tools/assets/46792157/1254c30e-d870-4586-a3e0-b08f41001208)

**Comment by SlavaC1** [comment]
Thanks a lot! Now it's working. Not very intuitive though...
