### ISSUE TITLE
Provide option to use -fix-errors with Clang-Tidy

### ISSUE THREAD

**Issue by s-martin** [Caphyon/clang-power-tools#13]
I'm running the extension on a rather large codebase, which fails to compile with Clang, because of includes like `WinSock2.h`. Therefor `-fix` does not work, because the project fails to compile with Clang.

It would be useful to add the option `-fix-errors` in the extension settings.

**Comment by cpp-red-lion** [comment]
A reasonable suggestion; thanks.
I think `-fix-errors` is a better default for our PowerShell `-tidy-fix` switch.
Applied this change in commit: `da2ab87`
