### ISSUE TITLE
Fails with Powershell 7

### ISSUE THREAD

**Issue by SlavaC1** [Caphyon/clang-power-tools#1300]
Fails with Powershell 7 enabled. Logs attached
[log.txt](https://github.com/Caphyon/clang-power-tools/files/12014291/log.txt)

**Comment by mariru27** [comment]
Hi @SlavaC1,

Thank you for reporting this issue
We are working towards a fix

Kind regards,
Marina

**Comment by mariru27** [comment]
What version of Clang Power Tool and Visual Studio you using?

**Comment by SlavaC1** [comment]
VS 17.6.4 and CPT 2023.6.0. I think you can see it in the logs

**Comment by mariru27** [comment]
It this log I can find a single problem, but it doesn't affect the build:

```
SetValueInvocationException: 
Line |
   3 |  $RawUI.CursorPosition = @{X=0;Y=0}
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception setting "CursorPosition": "The handle is invalid."
```

Did you find anything suspicious between cpt log generated by Powershell 7 vs Windows Powershell?

**Comment by mariru27** [comment]
I have this error too, but it doesn't affect my build 
However, we will try not to show the error that can confuse our users

Thank you for reporting this problem, if you find any issues, don't hesitate to contact us

Kind regards
Marina

**Comment by SlavaC1** [comment]
Thanks a lot @mariru27
