### ISSUE TITLE
"Add LLVM" doesn't work

### ISSUE THREAD

**Issue by VioletGiraffe** [Caphyon/clang-power-tools#1301]
I manually downloaded and installed the latest LLVM from the official website. I installed it into a non-default location. I click "Add LLVM" and select that LLVM folder, but nothing happens. I tried selecting the LLVM\bin folder, nothing happens still.

I would like a clear error message instead of a silent failure.

**Comment by mariru27** [comment]
Hi @VioletGiraffe,

Thank you for reporting the issue. We are investigating the problem and will provide a solution along with a clear error message.

Regards,
Marina

**Comment by mariru27** [comment]
Hi @VioletGiraffe,

What version of LLVM you trying to add?

**Comment by VioletGiraffe** [comment]
16.0.0

**Comment by mariru27** [comment]
Hi @VioletGiraffe,

Do you use the last version of Clang Power Tools?

I found out that our extension accepts adding just predefined versions of LLVM, but we will disable this check. If you are using a lower version of Clang Power Tools, it may be the reason why it fails.

Kind regards,
Marina

**Comment by VioletGiraffe** [comment]
Hi Marina, it was the latest one on the day I submitted this issue. i. e. 5 days ago.

**Comment by mariru27** [comment]
Hi @VioletGiraffe,

We cannot reproduce your issue, and we don't find something suspicious in our source code

Can you provide the full log output after compile run? (activate verbose from Settings -> Verbose mode)
Please send us the `settings.json` file from `%appdata%\ClangPowerTools\settings.json`

Kind regards,
Marina

**Comment by VioletGiraffe** [comment]
I can see that it does work, so maybe there's no problem. It found LLVM because I added it to PATH. I'm just put off by the fact that I can't specify the LLVM installation manually, and if it wasn't on the PATH, it would likely not work. Would a log still be helpful when analysis is working?

**Comment by mariru27** [comment]
Glad to hear that it's working

We definitely will output a message when operation will be completed successfully

Kind regards,
Marina

**Comment by mariru27** [comment]
Hi @VioletGiraffe,

We have a bugfix for this issue in Clang Power Tools release v2023.7.0

Kind regards,
Marina
