### ISSUE TITLE
Error on each file

### ISSUE THREAD

**Issue by menuet** [Caphyon/clang-power-tools#131]
Hi,

The tool sound promising. Thanks for developing it.

However, when I use clang-tidy, even when I disable every check, I get this error on each analyzed file:

```
error: unknown key 'misc-assign-operator-signature,
                 modernize-make-unique,
                 modernize-replace-auto-ptr,
                 modernize-use-auto,
                 modernize-use-nullptr,
                 modernize-use-override,
                 performance-for-range-copy,
                 readability-identifier-naming,
                 performance-implicit-cast-in-loop,
                 readability-implicit-bool-cast,
                 readability-inconsistent-declaration-parameter-name,
                 readability-redundant-smartptr-get,
                 readability-redundant-string-cstr,

```
Do you have an idea about the cause ?

**Comment by mariusz102102** [comment]
Please share your test case: simplified Visual Studio solution/project.

**Comment by cpp-red-lion** [comment]
What LLVM version are you using ?

**Comment by menuet** [comment]
@mariusz102102 , I will try to reproduce my issue with a vs project with a single file and I will attach it here.

@cpp-red-lion , at first try, I used LLVM 4.0.1 (which was the version that I had installed a long time ago).
Then I saw, that the doc recommends LLVM 5.0, so I tried it.
I got the same error.

**Comment by menuet** [comment]
While trying to reduce the project to a small one, I figured out what was wrong:
My code base contains some old files .clang-tidy in the folders hierarchy that contain obsolete checks that provoked the error that I got.

Sorry for making you lose your time !

**Comment by cpp-red-lion** [comment]
No problem.
Glad you figured it out :)

**Comment by menuet** [comment]
One more stupid question and then I promiss to stop:

When I run clang-tidy, I get this report:

> Start Clang Tidy
> [ INFO ] WILL PROCESS PROJECTS: 
> 	core.vcxproj
> [ INFO ] 1. PROCESSING PROJECT BLABLAH\core.vcxproj
> 43: BLABLAH\core-precompiled.cpp
> 31 warnings generated.
> 42: BLABLAH\DatabaseConnectionService.cpp
> 37 warnings generated.
> 41: BLABLAH\RxJukeSchedulers.cpp
> 110 warnings generated.
> ....
> 

And so on for each file.

Where should I look to acually see the warnings ?

**Comment by menuet** [comment]
I close this issue because by new pb is not related at all with it.
I will open a new issue if I cannot find a solution.

**Comment by cpp-red-lion** [comment]
Hi,

> BLABLAH\core-precompiled.cpp
> 31 warnings generated.

`clang-tidy` output such as this one indicates warnings from PCH or system headers (STL, SDK, CRT) that are automatically ignored by tidy, because you cannot address them anyway.
Warnings and errors from **your** code should be visible right there in the Output and Error tabs.
