### ISSUE TITLE
forced includes not taken into account with tidy

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#133]
Hi,

The forced includes are now correctly taken into account when compiling using the plugin, but when using the tidy option it still complains about missing symbols from those forced include files.

If you need more information let me know.

Kind regards,

Jacob

**Comment by cpp-red-lion** [comment]
That's just weird ?!
The same VS property-sheet parsing engine is used both for clang compile and clang-tidy.

**Comment by jcageman** [comment]
To be clear, i noticed that in the logging it finds the forced includes. I suspect those are just not passed to the tidy command. Could that be the case?

**Comment by hero101111** [comment]
Indeed, it seems we only passed force includes to clang compilation, not when in tidy mode.
Sorry about that. [Fixed it.](https://github.com/Caphyon/clang-power-tools/commit/008f113f89df9a57f32f7383bbf6cf0a3c696a87)

Regards,
Gabriel
---

Please note that this fix is currently live only for the github repository.
The latest Visual Studio extension (2.0) does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Don't forget to restart Visual Studio after replacing the script file.

**Comment by jcageman** [comment]
Works like a charm so far! Thanks for all the fixes up till now!
