### ISSUE TITLE
c++ and cuda c++ program，using clang-power-tool-src\ClangPowerTools\ClangPowerToolsShared\Tooling\v1\clang-build.ps1 generate compile_commands.json， not find cu file‘s compile commands

### ISSUE THREAD

**Issue by HEUBITLYJ** [Caphyon/clang-power-tools#1332]
c++ and cuda c++ program，using clang-power-tool-src\ClangPowerTools\ClangPowerToolsShared\Tooling\v1\clang-build.ps1 generate compile_commands.json， not find cu file‘s compile commands

**Comment by mariru27** [comment]
Hi @HEUBITLYJ,

Unfortunately, as of now, Clang Power Tools doesn't support CUDA
You might want to explore alternative tools or approaches for compiling CUDA files

Kind regards,
Marina
