### ISSUE TITLE
modernize-use-override IgnoreDestructors

### ISSUE THREAD

**Issue by marauder2k7** [Caphyon/clang-power-tools#1343]
Didnt know where else to ask this, in clang-tidy theres an option for mordernize-use-override which tells it to ignore destructors, how do i set this with clang power tools?

**Comment by mariru27** [comment]
Hi @marauder2k7,

You can add options from Clang Power Tools settings. [We have many tutorials here](https://clangpowertools.com/blog.html)
![image](https://github.com/Caphyon/clang-power-tools/assets/46792157/c45da8ca-11c6-404d-ab31-be2fb929d744)

let me know if there is anything else I can help you with

Have a nice day,
Marina

**Comment by marauder2k7** [comment]
Hey Marina, thanks for getting back to me. 

I can set it through the options to use modernize-use-override just fine and everything works as expected, its just theres no way to modify how modernize-use-override works, in clang-tidy there are different options for that. IgnoreDestructors being one of them. 

Its okay though we exported as many of the settings that we needed as we could through the options gui and then added the missing ones in with vscode.

Thanks,
Tommy.
