### ISSUE TITLE
could you please update the https://github.com/Caphyon/clang-format-editor

### ISSUE THREAD

**Issue by heartacker** [Caphyon/clang-power-tools#1348]
thanks

**Comment by mariru27** [comment]
Hi @heartacker,

I apologize for a late reply

Thank you for your contribution, we will update Clang Format Editor

Have a nice day,
Marina

**Comment by mariru27** [comment]
Hi @heartacker,

Check [Clang Format Editor](https://clangpowertools.com/clang-format-editor.html) v2024.3.0

Thank you for your contribution

Kind regards,
Marina
