### ISSUE TITLE
Since CPT 2024.4 Clang Tidy Checks are no longer sorted alphabetically

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#1353]
When viewing the list of Predefined Checks->Select

The list of Tidy Checks is no longer sorted in alphabetical order, in the latest version 2024.4

Reverting to version 2024.3 resolves the issue.

**Comment by mariru27** [comment]
@netx123,

Thank you so much for letting us know, [Clang Power Tools release](https://clangpowertools.com/CHANGELOG.html) v2024.4.1 is available.

Have a nice day,
Marina
