### ISSUE TITLE
Files to ignore - File picker

### ISSUE THREAD

**Issue by johanneskopf** [Caphyon/clang-power-tools#1355]
Hi,

It would be great if there is a file picker (e.g. using [this](https://learn.microsoft.com/en-us/dotnet/desktop/wpf/windows/how-to-open-common-system-dialog-box?view=netdesktop-8.0)) for the _Settings - Compiler - Files to ignore_ setting.

And as a small sidenote (did not know where else to put that): the release version of the latest release on the [changelog page](https://clangpowertools.com/CHANGELOG.html) is wrong. It should be _Version 2024.4.1_ but is _Version 2024.4.0_.

Best regards,
Johannes

**Comment by mariru27** [comment]
Thank you @johanneskopf, I changed the version. File picker is a good idea, I will talk with my team if we can prioritize it right now, and I will let you know when a release is available

Have a nice day,
Marina

**Comment by johanneskopf** [comment]
Thanks for the quick fix @mariru27 . Would be great if the file picker can be implemented. Otherwise just let me know if you would appreciate any help here. I can take a look myself on the weekend and make a PR.

Have a great day,
Johannes

**Comment by johanneskopf** [comment]
I went ahead and created the PR. See the PR for more details.

**Comment by mariru27** [comment]
Hi @johanneskopf,

Clang Power Tools release v2024.8.0 is now available and addresses your issue. As this issue is now resolved, I will close it. Thank you for contributing to Clang Power Tools!

Best regards,
Marina
