### ISSUE TITLE
Clang Format Editor missing Publisher

### ISSUE THREAD

**Issue by IrisPeter** [Caphyon/clang-power-tools#1361]
I cannot install the Clang Format Editor as it is missing a publisher which means it is blocked from installing

**Comment by mariru27** [comment]
Hi @IrisPeter,

The app is not sign, but you can install it anyway. Just press `More info`, and `Run anyway`.

Kind regards,
Marina

**Comment by IrisPeter** [comment]
Hi @mariru27 

Unfortunately I can't do that as the antivirus installed at work won't allow installation if it doesn't have a publisher

**Comment by mariru27** [comment]
Thank you @IrisPeter, for letting us know about this issue

I will address this problem to my team, maybe we can help you

Have a nice day,
Marina
