### ISSUE TITLE
Issue: Visual Studio 2022 encounters the error "The filename or extension is too long.

### ISSUE THREAD

**Issue by harrisonGPU** [Caphyon/clang-power-tools#1374]
### Enviroment
* Windows 11 system
* Visual Studio 2022

### Problem
When I use the `Export Compilation Database` feature, I encounter this issue. Even after `shortening the path` or setting the `LongPathsEnabled` value to 1 in the Windows Registry Editor, the problem still persists.

![image](https://github.com/user-attachments/assets/923fc8a1-35a2-4005-8621-89b790c843c0)

**Comment by TSWorld1314** [comment]
> Hi @TSWorld1314,
> 
> Could you let us know which version of Clang Power Tools you are currently using? Additionally, please provide the complete output log. Make sure to set the `verbosity level` to `2`
> 
> Kind regards, Marina

Hi @mariru27 
Here is my version:
![image](https://github.com/user-attachments/assets/fa833e47-4aa1-47a6-b1d7-a4b223685950)
But I don't know how to set verbosity level to 2 and dump it.

**Comment by mariru27** [comment]
You can find `verbosity level` in Clang Power Tools settings (from toolbar/context menu):
![image](https://github.com/user-attachments/assets/cb39b120-3420-4a91-8cdd-02cca7c0ca55)

**Comment by TSWorld1314** [comment]
Hi @mariru27 
I still not find this selection.
![image](https://github.com/user-attachments/assets/6a095953-9392-44c4-b864-258d2d66211f)

**Comment by mariru27** [comment]
In your case is set to 0
![image](https://github.com/user-attachments/assets/3038fd7c-9944-4bae-81e5-0ae9c6be1835)

**Comment by TSWorld1314** [comment]
Okay, I have already set it to 2, but when I use the Export Compilation Database feature, I don't find any log.
1. 
![image](https://github.com/user-attachments/assets/fae1ecf4-b414-4c5b-b3a5-065c7b634fa3)

2. 
![image](https://github.com/user-attachments/assets/48dd4a47-f20c-4930-abba-1a29eb7fdec2)
3. 
![image](https://github.com/user-attachments/assets/03b4245c-bb9d-463d-8961-2bc6d3c7e6cc)

**Comment by mariru27** [comment]
If you don't find any details in output, you can download the previous Clang Power Tools version from [here](https://github.com/Caphyon/clang-power-tools/releases/tag/v2024.4.1), please let me know if you have the same issue

**Comment by TSWorld1314** [comment]
I still have this problem, but I think it might be a system problem, not this extension issue.

**Comment by sakgoyal** [comment]
I am also having the same issue. Seems like its an issue with the list of files in "Files to ignore" being too large. removing that fixed the issue. idk how that value got set because I dont remember doing it myself
