### ISSUE TITLE
Context menu in Visual Studio 17.8 is disabled

### ISSUE THREAD

**Issue by CodeCraftsmanMI** [Caphyon/clang-power-tools#1375]
The context menu in Visual Studio is disabled:

![image](https://github.com/user-attachments/assets/81d76b67-44ed-43db-b30e-186ce6925651)

**Visual Studio**         Version    17.8.12
**Clang Power Tools** Version  2024.8.0

**Comment by mariru27** [comment]
Hi @CodeCraftsmanMI,

We know about this issue, try to update Visual Studio

Kind regards,
Marina

**Comment by CodeCraftsmanMI** [comment]
Good morning Marina,

Thank you for you e-mail.
Unfortunately, Visual Studio is up-to-date (17.8.12)
Perhaps there are other version of VS but because of company restriction I cannot change the version.

I am a huge fan of CPT!

Kind regards,

    Ruben


Ruben van Diggelen
Software Engineer
Hexagon Manufacturing Intelligence
E: ***@***.******@***.***>

**Comment by mariru27** [comment]
The last Visual Studio version is `17.10.5`. If you can't make an update, try to install the previous [Clang Power Tools version](https://github.com/Caphyon/clang-power-tools/releases/tag/v2024.4.1) (make sure it doesn't update automatically to v2024.8.0)

Let me know if it works for you

**Comment by CodeCraftsmanMI** [comment]
That works!
Thanks.

Ruben van Diggelen
Software Engineer
Hexagon Manufacturing Intelligence
E: ***@***.******@***.***>
