### ISSUE TITLE
visual studio clang power tools can not use

### ISSUE THREAD

**Issue by edidada** [Caphyon/clang-power-tools#1376]
![image](https://github.com/user-attachments/assets/5fb69100-90bd-4138-b508-81601fa38a93)
os;win 10,ide:vs 2022,build tool:cmake

**Comment by austin9109** [comment]
I have same problem. My environement is win11. After I upgrade from win10 to win11 the tools can no more be used, even after trying reinstall the extension.

**Comment by austin9109** [comment]
Dear @mariru27

After update to latest Visual Studio version, it works!
It is very helpful, thanks.
