### ISSUE TITLE
Add ability to Format All

### ISSUE THREAD

**Issue by ClaudiuHBann** [Caphyon/clang-power-tools#1384]
Add the ability to Format All automatically or through an action.

## Background
If you make an operation that changes multiple files and you `Save All`, `clang-format` will format only the focused file.
For example, rename an `enum` that is used in multiple files and use `Save All`, this can bring a bunch of conflicts in git.

## Describe the solution you'd like
Like the "Format On Save" toggle button, add another toggle button "Format All On Save All" or something similar.

**Comment by mariru27** [comment]
Hi @ClaudiuHBann,

Thank you for your feedback! You can already execute the format operation on an entire solution, project, or specific files from a filter. The format command is available in the context menu:
![image](https://github.com/user-attachments/assets/ce4b7c3b-1283-4c53-a803-261db1e6c029)

Kind regards,
Marina

**Comment by ClaudiuHBann** [comment]
I didn't know you can apply the Format operation on the entire solution.
Thank you
