### ISSUE TITLE
Clang power tools sub menu greyed out

### ISSUE THREAD

**Issue by TheSlugInTub** [Caphyon/clang-power-tools#1385]
I'm trying to generate a compile_commands.json for my visual studio project but all the options are just greyed out for some reason.
I have clang installed and my project runs fine. I'm on the latest version of clang power tools.

**Comment by mariru27** [comment]
Hi,

Thank you for reporting this issue, please try to update visual studio.

Kind regards,
Marina

**Comment by TheSlugInTub** [comment]
I updated visual studio and it worked now, thanks!

Sincerely,
Slug.
