### ISSUE TITLE
Properly use include paths with spaces and x86 (e.g. C:\Program Files(x86))

### ISSUE THREAD

**Issue by s-martin** [Caphyon/clang-power-tools#14]
If I try to add Windows SDK include paths to the setting `Include Directories` the compilation fails, because the PowerShell script chokes on spaces or x86. 

```
Start Clang Tidy

Die Benennung "x86" wurde nicht als Name eines Cmdlet, einer Funktion, einer 
Skriptdatei oder eines ausfuehrbaren Programms erkannt. Ueberpruefen Sie die 
Schreibweise des Namens, oder ob der Pfad korrekt ist (sofern enthalten), und 
wiederholen Sie den Vorgang.In Zeile:1 Zeichen:445
+ ... '%PROGRAMFILES(x86)%\\Windows Kits\\10\\Include\\10.0.15063.0\\um\\' 
-tidy-fix ' ...
+                    ~~~
    + CategoryInfo          : ObjectNotFound: (x86:String) [], CommandNotFound 
   Exception
    + FullyQualifiedErrorId : CommandNotFoundException

Done Clang Tidy
```

Non of the following attempts worked:
- `'%PROGRAMFILES(x86)%\\Windows Kits\\10\\Include\\10.0.15063.0\\um\\'`
- `"%PROGRAMFILES(x86)%\\Windows Kits\\10\\Include\\10.0.15063.0\\um\\"`
- `"C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.15063.0\\um\\"`
- `"C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\"`

**Comment by Enache-Ionut** [comment]
Now Include Directories option should work. Thank you for reporting this.
