### ISSUE TITLE
Compile successfully applies pch and works but clang-tidy doesn't

### ISSUE THREAD

**Issue by Predelnik** [Caphyon/clang-power-tools#147]
Is something wrong with my project configuration? It's actually generated from cmake so it can be a bit messed up.

Verbose outpus (errors from clang-tidy come from missing pch):
https://gist.github.com/Predelnik/54fde815bb7d209d7e3647d695deae38#file-clang-compile-txt
https://gist.github.com/Predelnik/54fde815bb7d209d7e3647d695deae38#file-clang-tidy-txt

**Comment by cpp-red-lion** [comment]
Hi,

What do you mean by "Compile ... works, but clang-tidy doesn't".
Do you mean that it doesn't apply the auto fixes on your source files ?

Have you enabled the "Fix" option from:
`VS Settings > Clang Power Tools > Tidy > Options > Fix [True]`

**Comment by Predelnik** [comment]
I mean that applying clang-tidy writes compilation errors clearly related to missing precompiled header like missing stuff from std, as you can clearly see from my log. While simple compile writes that everything is ok.

**Comment by cpp-red-lion** [comment]
I see...
Can you attach or send us via email your `vcxproj` file and (if the case) any required VS property-sheets, so that we can debug your problem ?

**Comment by Predelnik** [comment]
https://drive.google.com/uc?authuser=0&id=1hQZUngk9AFv4BLh2Ec_97cPcs0TotAdb&export=download
Sure but actually looking at it, looks like vcxproj quite nasty, considering that it connects precompiled header invidually for each file. Maybe it's not that easy to support. If only CMake had a better support for precompiled headers 😞

**Comment by cpp-red-lion** [comment]
Indeed, the generated `.vcxproj` file looks **horrible**, coming from CMake :(
We'll see if we can make something out of it... no promises.

**Comment by cpp-red-lion** [comment]
Hi,

We investigated this issue and we have the following findings:
 - There were a couple of bugs in our C++ standard detection, your project specifies _C++17_ but our detection found _C++14_. We've pushed a fix for this.
 - Your CMake-generated VS project specifies forced includes for each CPP file. 
Currently we support only forced includes specified _per project_. 

To make your project work you have to:
- Grab the latest clang-build.ps1 from github, using the instructions below
- Add this line in all `ItemDefinitionGroup > ClCompile` elements from your vcxproj:
`<ForcedIncludeFiles>PrecompiledHeader.h</ForcedIncludeFiles>` 

Please let us know if this solves your problem.

---

This fix is currently live only for the github repository.
The latest Visual Studio extension (`2.2`) does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Don't forget to restart Visual Studio after replacing the script file.

**Comment by Predelnik** [comment]
Thank you very much!
I will look if CMake generation of precompiled header could be done better (there are like 3 ways and each one is bad in some way)
You can close this issue then I guess.

**Comment by cpp-red-lion** [comment]
OK, then.
If you encounter further issues/bugs, let us know.
