### ISSUE TITLE
object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mrexodia** [Caphyon/clang-power-tools#148]
Got the latest version from the store with Visual Studio 2017 (15.5.0 Preview 5.0), with https://github.com/x64dbg/x64dbg (cloned with submodules), then try compiling the solution with clang power tools will crash with this message:

![](https://i.imgur.com/oUwPL55.png)

The output log appears to be doing fine until the crash happens:

http://codepad.org/TM2PcdIg

Heard about this on CppCast and love the idea!

**Comment by cpp-red-lion** [comment]
Hi,

> File C:\Users\Admin\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1 cannot be loaded because running scripts is disabled on this system. For more information, see about_Execution_Policies at http://go.microsoft.com/fwlink/?LinkID=135170.
At line:1 char:3
 'C:\Users\Admin\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1'
 CategoryInfo          : SecurityError: (:) [], PSSecurityException
 FullyQualifiedErrorId : UnauthorizedAccess

It appears that the problem could be related to a `PowerShell` **profile** on your system, interfering with our VS extension. *Clang Power Tools* uses a PowerShell script to drive the build and tidy workflows.

`C:\Users\Admin\Documents\WindowsPowerShell\Microsoft.PowerShell_profile.ps1`

What does this profile do ?

**Comment by mrexodia** [comment]
Well, it does nothing because it's not executed 😄 but the contents are:

```
# Chocolatey profile
$ChocolateyProfile = "$env:ChocolateyInstall\helpers\chocolateyProfile.psm1"
if (Test-Path($ChocolateyProfile)) {
  Import-Module "$ChocolateyProfile"
}
```

**Comment by mrexodia** [comment]
I removed the profile and the error still happens, I tried running every project individually and that works, it's just running it on the whole solution that causes the crash...

**Comment by cpp-red-lion** [comment]
I see...
Can you attach or send us via email your `vcxproj` file and (if the case) any required VS property-sheets, so that we can debug your problem ?

**Comment by mrexodia** [comment]
I started debugging the extension and after 30 minutes it finally got me a call stack:

![](https://i.imgur.com/JYzPuYe.png)

Sadly I cannot inspect the `aProjectItem` because it is a native object so I'll dig some more.

**Comment by mrexodia** [comment]
@cpp-red-lion The project is open source, the solution is https://github.com/x64dbg/x64dbg/blob/development/x64dbg.sln

**Comment by hero101111** [comment]
Hi,

I've tested the project you provided using Clang Power Tools 2.1 and Visual Studio 2017 (15.5).
However, I've been unable to reproduce the issue. Everything works fine.

I've noticed you are running a Preview version of Visual Studio. 
Maybe that's what's causing some issues.

Can you test on a non-preview instance of VS?

**Comment by mrexodia** [comment]
It also happens on the latest release version, I added some checks in the `GetConfiguration` function and `aProjectItem.ConfigurationManager` appears to return `null`. I found a SO answer related to it, but I don't know anything about your code so it's hard to tell what's going on. https://stackoverflow.com/questions/43279895/c-sharp-get-configuration-from-dte

**Comment by mrexodia** [comment]
Okay I added some more debug logging and my solution has 6 projects but if I run clang power tools on the solution it has a magical 7th project that has all empty information:

http://codepad.org/ZjmFe4ir

My debug log diff:

![](https://i.imgur.com/OIeoyWy.png)

**Comment by mrexodia** [comment]
Okay I added some more debug [logs](http://codepad.org/hxU0Sl9f) and there appears to to be a project with `Kind` "66A2671D-8FB5-11D2-AA7E-00C04F688DDE" (VsProjectKindMisc). This project is not part of the solution file. A [SO answer](https://stackoverflow.com/questions/7160425/what-is-miscellaneous-files-inside-dte-vs2010-solution) suggests that this happens with "Miscellaneous Files", which indeed appear to be present (after turning on the suggested option)...

**Comment by mrexodia** [comment]
#151 fixes this issue
