### ISSUE TITLE
Not working for files with cc extension

### ISSUE THREAD

**Issue by coertmetz** [Caphyon/clang-power-tools#149]
Clang power tools does not seem to process files with a cc extension. Can this be added?

**Comment by cpp-red-lion** [comment]
Hi,

This is a current limitation of our VS extension.
We'll address this in the next release, due by the end of this day.

Thanks for the feedback.

**Comment by cpp-red-lion** [comment]
This issue was fixed in version `2.2` (just published)
Thank you for your feedback !
