### ISSUE TITLE
Power tools looking for not existing Tools directory

### ISSUE THREAD

**Issue by coertmetz** [Caphyon/clang-power-tools#150]
I created an empty Console application. When I run the compile or tidy option I get the following output:

====================================
Start Clang Compile

[ INFO ] WILL PROCESS PROJECTS: 
C:\Temp\test\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.vcxproj
[ INFO ] 1. PROCESSING PROJECT C:\Temp\test\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.vcxproj
Get-Item : Cannot find path 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Tools\MSVC\' because it does not 
exist.
At C:\Users\Coert Metz\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\00wc1ql5.hmd\clang-build.ps1:519 char:11
+ return (Get-Item "$(Get-VisualStudio-Path)\VC\Tools\MSVC\" | Get-Ch ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo : ObjectNotFound: (C:\Program File...\VC\Tools\MSVC\:String) [Get-Item], ItemNotFoundExcep 
tion
+ FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

1: C:\Temp\test\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp

Done Clang Compile
====================================

The directory it mentions indeed does not exist. Visual Studio 2015 update 3 is installed and functioning properly. 

I tried updating my installation to include:
* Common Tools for Visual C++ 2015
* Visual Studio Extensibility Tools Update 3
but that did not help.

Am I missing some requirement that is not listed on the site?

**Comment by hero101111** [comment]
It appears we recently introduced a bug, while fixing an issue with Visual Studio 2017 Update 5 precompiled headers.

An updated version of Clang Power Tools will be released today which will fix this bug.

Sorry for the inconvenience.

**Comment by cpp-red-lion** [comment]
This issue was fixed in version `2.2`
Thank you for your feedback !
