### ISSUE TITLE
Custom checks field cannot be changed

### ISSUE THREAD

**Issue by chri7325** [Caphyon/clang-power-tools#155]
Hi, I just wanted to say thank you guys so much for this plugin and associated power shell script!  We have a custom clang tidy binary which is going to check if there is any implementation in header files as we are moving all implementation to source.  In order to run the check, we need to change the custom checks field in the plugin in order to run it.  However, no matter what I do, the custom field text box will not respect my changes.  I'm using Windows 10 with Visual Studio 15.3.4.  I have also reproed the issue on another Windows 10 machine running VS 15.5.0.  I've attached an image showing the case.  I can't seem to find where VS reads the field from.  
![power_tools](https://user-images.githubusercontent.com/12401649/33850892-2d1d5218-de6a-11e7-9d33-cee3250cd6a1.gif)

**Comment by cpp-red-lion** [comment]
Hi Christian,

We just fixed this bug in `v2.2` (published about 2 hours ago).
https://github.com/Caphyon/clang-power-tools/blob/master/CHANGELOG.md
(first item on the list)

Please update and try again. Sorry for the inconvenience.

Thanks for your feedback.

**Comment by chri7325** [comment]
Verified fix with v2.2.  I think that was the fastest turn around time I've ever seen :D

**Comment by cpp-red-lion** [comment]
💯
