### ISSUE TITLE
Cannot change default options

### ISSUE THREAD

**Issue by semawah** [Caphyon/clang-power-tools#157]
Thank you for this tool. Great idea. I have an issue though.

On my system I can only make Clang Tidy check for the custom checks: modernize-use-equals-default,modernize-use-equals-delete. 

![custom](https://user-images.githubusercontent.com/34470692/33872070-a05aa82e-df15-11e7-8c91-35eb9e4f61f5.png)

Adding/removing the "Custom Checks" in the options dialog does not alter the behaviour.

![changed](https://user-images.githubusercontent.com/34470692/33872170-06d38562-df16-11e7-905d-abe2a9e90c30.png)

When opening the dialog after modifying it the default options are back.

![custom](https://user-images.githubusercontent.com/34470692/33872181-10bd74d4-df16-11e7-8b19-f37444403553.png)

Am I missing something?

I'm on Visual Studio 15.4.4.

Thanks.

**Comment by cpp-red-lion** [comment]
Hi,

We just fixed this bug in `v2.2` (published yesterday).
https://github.com/Caphyon/clang-power-tools/blob/master/CHANGELOG.md
(first item on the list)

Please update (from VS) and try again. Sorry for the inconvenience.

Thanks for your feedback.

**Comment by cpp-red-lion** [comment]
Related issue: #155
