### ISSUE TITLE
Tidy fails with: 'Error while processing X.Cpp'

### ISSUE THREAD

**Issue by sdwe** [Caphyon/clang-power-tools#159]
Compiling X.Cpp succeeds.
Tidying fails with 'Error while processing X.Cpp'.

Workaround:
- Rename 'X.Cpp' to 'X.cpp'; **or**

Fix:
- Pass all options to clang-tidy that are passed to clang++ (here: '-x c++')

**Comment by cpp-red-lion** [comment]
This issue was fixed.
It will be available in the next version to be published on the VS Marketplace.

Thanks for your feedback.

**Comment by sdwe** [comment]
Thank you for sharing your tools and fixing the issue!
