### ISSUE TITLE
Allow .clang-tidy overrides

### ISSUE THREAD

**Issue by chri7325** [Caphyon/clang-power-tools#163]
As of version 2.3.0, clang-power-tools allows the use of using a .clang-tidy file by specifying -tidy .clang-tidy.  This allows clang-tidy to default to using the nearest .clang-tidy file found which is great for global setups.  However, there doesn't appear to be a way to override settings or specify additional settings that may be missing from this file.  For example, in our .clang-tidy file, we list the global checks that we'd like checked.  If we want to isolate a check and apply the fix for that one check so we can commit them individually, we can do so by adding `-checks=-*,some-check -fix" to clang-tidy and it will only run single-check with the rest of the options read from the .clang-tidy file (errors, format, header regex, etc).  I have tried to do this with the script with this
```
PowerShell.exe ... -tidy .clang-tidy -tidy-fix "-checks=-*,single-check -fix"
```
But -tidy-fix completely overrides -tidy.  Instead of -tidy-fix, could there be -tidy-additional or some other parameter that would allow me to do this?

Keep up the great work!

**Comment by cpp-red-lion** [comment]
Hi,

Sadly, this is an issue of non-intuitive UX. We designed a UI for this new option, that was not so intuitive to use :(

You **can** actually achieve what you want with the _current_ released version.

---

Here's the **UI changes** we decided to implement, to eliminate any _ambiguity_ regarding this workflow:

- Changing the "Operation mode" _label_:

  - New label text:  **Use checks from** {  predefined checks, custom checks, .clang-tidy config file }   
(same options)

- Changing the _tooltip_:
  - >Tidy checks: switch between explicitly specified checks (predefined or custom) and using checks from .clang-tidy configuration files.
Other options are always loaded from .clang-tidy files.

---

So, for the workflow you described, you should select the:  `custom checks` operation mode. 
Specify _individual_ checks you want and all other settings will be picked-up from your `.clang-tidy` config file(s).

The same applies for using the `PowerShell` script directly.  
Just specify `-tidy my_check` or `-tidyfix my_check` and the other tidy options will be picked-up from your `.clang-tidy` config file(s).

**Comment by chri7325** [comment]
@cpp-red-lion I'm actually having trouble verifying this.  When I run this command
```
PowerShell.exe -ExecutionPolicy Bypass -File ~/clang-build.ps1 -dir my_solution.sln -continue -vs-ver 2017 -vs-sku Professional -clang-flags '-Wall -fms-compatibility-version=19.11 -fms-compatibility -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-variable -Wno-unused-value' -active-config 'Debug|x64' -proj my_project -file my_file.cpp -tidy-fix --checks=-*,esri*
```
It runs fixes on all checks in the .clang-tidy file instead of the one's I've isolated.

**Comment by chri7325** [comment]
In the gui, it also looks like when I use the the custom checks option, it is injecting `-header-filter=.*` even though we have them defined in the clang-tidy file.  We only want a certain subset of headers to be analyzed so we are not analyzing 3rdparty.

**Comment by cpp-red-lion** [comment]
Hi,

There's a mistake in your command; maybe I wasn't explicit enough (above).

`~/clang-build.ps1 -dir my_solution.sln -continue -vs-ver 2017 -vs-sku Professional -clang-flags '-Wall -fms-compatibility-version=19.11 -fms-compatibility -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-variable -Wno-unused-value' -active-config 'Debug|x64' -proj my_project -file my_file.cpp -tidy-fix --checks=-*,esri*`

It should be:

`~/clang-build.ps1 ...  -proj my_project -file my_file.cpp -tidy-fix '-*,esri*'`

**Comment by chri7325** [comment]
Ahh I see.  My mistake again.  I have verified that this work.  Thanks again!

**Comment by cpp-red-lion** [comment]
> In the gui, it also looks like when I use the the custom checks option, it is injecting -header-filter=.* even though we have them defined in the clang-tidy file. We only want a certain subset of headers to be analyzed so we are not analyzing 3rdparty.

You're right about that. We'll try to find a solution.

Thanks for pointing that out.

**Comment by cpp-red-lion** [comment]
We're going to continue the work on this issue: #168
