### ISSUE TITLE
Set-Variable error when running the script on MINGWN

### ISSUE THREAD

**Issue by chri7325** [Caphyon/clang-power-tools#164]
For our windows environment, we use the "Git for Windows" mingwn bash.  This not only gives us the ability to easily use git on windows through a unix like interface, but it also allows us to write cross platform bash scripts so we can make our toolchain scripts work for Linux, MacOS and Windows.  When running the clang powershell script, I get these errors
```
Set-Variable : Cannot overwrite variable HOME because it is read-only or constant.
At C:\applications\3rdparty\architecture\llvm\bin\clang-build.ps1:353 char:3
+   Set-Variable -name $name -Value $value -Scope Global
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (HOME:String) [Set-Variable], SessionStateUnauthorizedAccessException
    + FullyQualifiedErrorId : VariableNotWritable,Microsoft.PowerShell.Commands.SetVariableCommand
```
For some of our projects, it doesn't appear to affect the tidy run and things look similar.  However, for others, I can't seem to reproduce the behavior that the plugin has vs running the script with the same parameters.  I'm not sure if this is due to this error logging.

**Comment by cpp-red-lion** [comment]
This is not an issue with our `PowerShell` script or *Clang Power Tools* VS extension.
It appears it is related to that console/bash you are using.

Please use the standard `PowerShell` console from Windows, or standard console `cmd`.

Also, our PowerShell script can be invoked non-interactively from **CI/automation** services like:   **Jenkins**, **TFS**, **Bamboo**, **Team City**, etc. 
They all have the ability to run PowerShell scripts (natively or through a plugin).

**Comment by chri7325** [comment]
@cpp-red-lion that's fair.  For us, we use everything through the git bash for windows and I could see others needing the same but it is understandable that it is a bit different.  I just thought I'd report it for testing.
