### ISSUE TITLE
Configurable "Header Filter" for tidy workflow

### ISSUE THREAD

**Issue by cpp-red-lion** [Caphyon/clang-power-tools#168]
At the moment, we use a hard-coded value for tidy header filter: `-header-filter=.*`

**Comment by jcageman** [comment]
A small addition that you might not have considered, would it be possible to create an option to only fix your own header. Currently when you have a large project you get spammed by warnings if you only try to fix one file. This of course assumes you have pairs of same name header and cpp but that is a very common pattern.

**Comment by cpp-red-lion** [comment]
Hi,

Very good suggestion, @jcageman !
We like it so much, that I think you'll just surprise you with it in the next version to be released this week :)

We'll let you know.

**Comment by cpp-red-lion** [comment]
This enhancement was implemented in `version 2.4` released today.
Thanks for you feedback 👍
