### ISSUE TITLE
evaluation order of imports

### ISSUE THREAD

**Issue by jmue** [Caphyon/clang-power-tools#169]
Hi,

```<Import\>```directives have to be evaluated inplace, but it looks like you are doing so after current file. I attached a sample project. It writes its output to ```cpt-test\Build\[Platform]\[Configuration]\```. Watch the verbose output of your script for ```OutDir``` and ```CommonBuildHome```.

[cpt-test.zip](https://github.com/Caphyon/clang-power-tools/files/1561964/cpt-test.zip)

**Comment by hero101111** [comment]
Can you please provide more info on consequences of this evaluation order issue are?
What should happen and doesn't?

The project you attached compiles OK (after changing file encodings to UTF8).

**Comment by jmue** [comment]
I'm having for example trouble with additional include directories. I've update the sample, so you check that a Clang Power Tools 'Compile (syntax)' failed.

[cpt-test.zip](https://github.com/Caphyon/clang-power-tools/files/1562620/cpt-test.zip)

**Comment by cpp-red-lion** [comment]
Hi,

Gabi (@hero101111) fixed this issue and we're test-driving it...
Should be published in the next version, to come out this week.
We'll let you know.

Thanks for the feedback 👍

**Comment by jmue** [comment]
Looks good now ... 
Thanks a lot!

**Comment by cpp-red-lion** [comment]
This issue was fixed in `version 2.4` released today.
Thanks for you feedback 👍
