### ISSUE TITLE
Suppress MS-style inline assembly clang-tidy error

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#177]
Hi,

I am getting the following error from clang pretty often:
`MS-style inline assembly is not available: Unable to find target for this triple (no targets are registered) [clang-diagnostic-error]`

I know this is a problem from clang, see https://reviews.llvm.org/D17981. They don't seem to want to fix this anytime soon..
It would be pretty annoying for people to compile LLVM + Clang from scratch and apply the above patch locally just to remove this error.
Would it be possible to just filter this one out?

Kind regards,

Jacob

**Comment by cpp-red-lion** [comment]
Hi,

Unfortunately, I'm not able to reproduce this issue. We do have a lot of 32-bit _inline assembly_ in our source code, but I don't see this diagnostic message you refer to.

Can you share a simple code example/project reproducing this issue ?

**Comment by jcageman** [comment]
The error more specifically:

```
:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\um\winnt.h(949): error: MS-style inline assembly is not available: Unable to find target for this triple (no targets are registered) [clang-diagnostic-error]
    __asm    {
    ^
```

This is on visual studio 2017 by the way, but i also had this on my own tooling on earlier versions

**Comment by cpp-red-lion** [comment]
We do include `<windows.h>` and I don't get that error...
What *clang* compile flags are you using ?

**Comment by jcageman** [comment]
The full list just to be sure:

`-m32 -fms-extensions,-fdelayed-template-parsing,-fms-compatibility,-fms-compatibility-version=19.11,-Wno-microsoft,-Wno-invalid-token-paste,-Wno-unknown-pragmas,-Wno-unused-variable,-Wno-unused-value,-Wno-implicit-exception-spec-mismatch,-Wno-typename-missing,-Wno-non-pod-varargs,-Wno-nonportable-include-path,-Wno-extra-tokens,-Wno-undefined-var-template,-DBOOST_USE_WINDOWS_H,-D_CRT_SECURE_NO_WARNINGS`

**Comment by cpp-red-lion** [comment]
Yep. Found it: it's the `-m32` flag.
That's what's causing your `__asm` diagnostic: _"MS-style inline assembly is not available"_

Why do you need that flag ?

**Comment by cpp-red-lion** [comment]
FYI, _Clang Power Tools_ compiles code with `-fsyntax-only` (no object file is generated).

**Comment by jcageman** [comment]
How can i resolve this warning? It seems from your response this is possible. Or else, why the won't fix?

**Comment by cpp-red-lion** [comment]
As I said above: the cause is the `-m32` flag.
That's what's causing your `__asm` diagnostic: _"MS-style inline assembly is not available"_

**Remove** that compilation flag and you should be fine.

**Comment by jcageman** [comment]
Fair enough, but i can't remove it since our code only compiles with 32 bit (specific memory allocator designed for 32 bit only). I will resolve it myself, since i think i am the only one who has this issue.

**Comment by Arminius** [comment]
I'm also using clang-tidy on a 32-bit-only application that uses _USE_32_BIT_TIME_T and have the same problem. If I remove the flag -m32 from clang, I get the error "You cannot use 32-bit time_t (_USE_32BIT_TIME_T) with _WIN64". Is there really no other way to resolve the inline assembly error, or to at least silence it?

**Comment by jcageman** [comment]
The only way to resolve it is building llvm from source and applying the patch described at https://reviews.llvm.org/D17981. The side effect is that your binaries are a bit large (/care)

**Comment by El-EmF** [comment]
> The only way to resolve it is building llvm and clang-tidy from source and applying the patch described at https://reviews.llvm.org/D17981. The side effect is that your binaries are a bit larger (/care)

hello, im trying for some days solving this specific error that you also had, and I am not able to correct it, you can be more specific in how I build llvm and Clang-tidy from source? thanks
