### ISSUE TITLE
vcxproj parsing error

### ISSUE THREAD

**Issue by jmue** [Caphyon/clang-power-tools#178]
Hi,

I have multiple nodes of the same type within a ```<ClCompile>``` node.  Clang Power-Tools compile throws ```"Did not expect that"```. I attached a sample.

[cpt-test.zip](https://github.com/Caphyon/clang-power-tools/files/1578243/cpt-test.zip)

**Comment by hero101111** [comment]
Hello,

Thank you for the sample project.
We have isolated this issue and a fix has been pushed for it.

An updated Clang Power Tools release will be coming later today.

Regards,
Gabriel

**Comment by jmue** [comment]
Works now ... 

Thank you!

**Comment by cpp-red-lion** [comment]
This issue was fixed in `version 2.4` released today.
Thanks for you feedback 👍
