### ISSUE TITLE
"Could not find property sheet" warning in VERBOSE mode 

### ISSUE THREAD

**Issue by jmue** [Caphyon/clang-power-tools#179]
I dont know if this is an error or not, but verbose mode prints out **```Could not find property sheet \Microsoft.Cpp.Default.props```** in a newly created vs2017 solution.

```
AUSFšHRLICH: Could not find property sheet \Microsoft.Cpp.Default.props
AUSFšHRLICH: SET_VAR ConfigurationType: Application
AUSFšHRLICH: SET_VAR UseDebugLibraries: true
AUSFšHRLICH: SET_VAR PlatformToolset: v141
AUSFšHRLICH: SET_VAR CharacterSet: Unicode
AUSFšHRLICH: Could not find property sheet \Microsoft.Cpp.props
AUSFšHRLICH: SET_VAR LinkIncremental: true
AUSFšHRLICH: Could not find property sheet \Microsoft.Cpp.targets
```

**Comment by hero101111** [comment]
Hello,

You must be testing the latest Github version of `clang-build.ps1`, right?

Until recently, Clang Power Tools  was not able to load platform toolset property sheets.
To work around this, we manually injected required include paths and preprocessor definitions, as needed.

However, we've recently worked on enabling full loading of projects, including platform property sheets. We think this will help resolve issues that we currently have with Nuget packages, among other benefits.
At this point it is experimental and disabled by default. 

If your project compiles OK, there is no need to enable it. 
_Ignore the prop sheet error messages._

However, if encountering problems with the default behavior, you can enable full project loading by setting the `CPT_LOAD_ALL` environment variable to `1`
