### ISSUE TITLE
Compile/Tidy is performed for all files that has same file name.

### ISSUE THREAD

**Issue by taeguk** [Caphyon/clang-power-tools#184]
When I right-click on only one file and click 'compile' or 'tidy' command, it is performed for all files that has same file name.

![image](https://user-images.githubusercontent.com/9107889/34325118-c0b7ea22-e8cb-11e7-905f-78a23e0a85ee.png)

**Comment by Enache-Ionut** [comment]
Hi,
Can you attach your project or a sample project reproducing the issue, so we can investigate ?
Thanks for your feedback.

**Comment by cpp-red-lion** [comment]
Thanks for bringing this to our attention.
A fix is in progress. Stay tuned.

**Comment by Enache-Ionut** [comment]
This issue was fixed and it will be available in the next version.

Thanks for your feedback.

**Comment by Enache-Ionut** [comment]
You can install the new version 2.5.1 just released today : https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools
