### ISSUE TITLE
Add option for clang driver to enable use for C projects

### ISSUE THREAD

**Issue by milancpp** [Caphyon/clang-power-tools#187]
I would like to use Clang Power Tools for a C based project (I really only want to use the test compile with fsyntax-only, no tidy or format)

For this to work, I need to change the clang driver to use clang.exe. Adding -std=C99 will not work with clang++.exe.

A simple combobox with options for clang.exe, clang++.exe and clang-cl.exe (see #1) would suffice I think

Thanks for this great extension!

**Comment by cpp-red-lion** [comment]
Hi,

Thank you for your suggestion.
We'll update this issue once we have something in progress.

**Comment by mrexodia** [comment]
Today I did a small test for my pull request and it looks like `clang++` can be used without issues to compile with `-std=c99`, you just have to specify `-x c`:

```
clang++ -x c -std=c99 -o blub.exe blub.c
```

**Comment by cpp-red-lion** [comment]
See also #321

**Comment by cpp-red-lion** [comment]
Fixed by PR #343
