### ISSUE TITLE
Some errors shown in the Output Window are not shown in the Error List Window

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#188]
When running Clang Power Tools->Compile against a project, the Output Windows shows multiple errors but these do not appear in the Error List, other errors do show.

I am unable to establish why some errors will show and others do not, perhaps there is a parsing issue?

I have included below a snippet from a projects output window, (The two "messages" correctly appear in the Error Window, but neither of the actual "errors" can be seen)

```
C:\Projects\ProjectName\TheProject\TEST.CPP
:68:39: error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
      if(ret = function_ret(&value, A_B, C)){

                                    ^

C:\Projects\ProjectName\TheProject/includes/CAD.h(18): message: expanded from macro 'A_B'
#define A_B         "ABC"             /* -1 if unknown ( )*/
                    ^
C:\Projects\ProjectName\TheProject\TEST.CPP
:119:39: error: ISO C++11 does not allow conversion from string literal to 'char *' [-Werror,-Wwritable-strings]
      if(ret = function_ret(&value, A_B, C)){
                                    ^

C:\Projects\ProjectName\TheProject/includes/CAD.h(18): message: expanded from macro 'A_B'
#define A_B         "ABC"             /* -1 if unknown ( )*/
                    ^
3
 errors generated.
```

**Comment by Enache-Ionut** [comment]
This issue was fixed and it will be available in the next version.

Thanks for your feedback.

**Comment by Enache-Ionut** [comment]
You can install the new version 2.5.1 just released today : https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools
