### ISSUE TITLE
Is it possible to create a similar extension for VS Code?

### ISSUE THREAD

**Issue by mmahimtura** [Caphyon/clang-power-tools#189]

**Comment by cpp-red-lion** [comment]
Hi,

Thank you for your suggestion.

We consider that the greatest asset of our VS extension is the ability to parse and adapt Visual Studio **project settings** to the Clang format. For VS Code, extracting "project" settings from the configured Json files should be much easier.

In terms of IDE integration, the extensibility framework for **VS Code** is completely different from the one in **Visual Studio** and unfortunately we don't have the experience to do it at the moment. 

_We welcome external help_ if someone has experience developing C++ extensions for **VS Code**.

**Comment by Bu11etmagnet** [comment]
Implementing VS Code support is left as an exercise :)
