### ISSUE TITLE
Get-VisualStudio-Path() fails when two versions of VS2017 installed.

### ISSUE THREAD

**Issue by kpiekara** [Caphyon/clang-power-tools#190]
Error:
```
Get-Item : Cannot find path 'C:\Program Files (x86)\Microsoft Visual 
Studio\2017\Enterprise C:\Program Files (x86)\Microsoft Visual 
Studio\2017\Professional\VC\Tools\MSVC\' because it does not exist.
```

because of:

```
vswhere.exe  -nologo -property installationPath
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional
```

In:
master/ClangPowerTools/ClangPowerTools/clang-build.ps1

at
```
if (Test-Path $kVsWhereLocation)
    {
      return (& "$kVsWhereLocation" -nologo -property installationPath)
    }
```

My temporary workaround:
```
-nologo -property installationPath -products Microsoft.VisualStudio.Poduct.Enterprise
```

Not sure if it should be configurable or split by newline and take first, so I create only issue report.

**Comment by hero101111** [comment]
Hello,

We just pushed a fix for this scenario, derived from your workaround solution.
Thank you for your feedback.

Regards,
Gabriel

---

Please note that this fix is currently live only for the github repository.
The latest Visual Studio extension (`2.4.1`) does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Don't forget to restart Visual Studio after replacing the script file.
