### ISSUE TITLE
Unable to ignore header files or directories

### ISSUE THREAD

**Issue by brendan-driscoll** [Caphyon/clang-power-tools#191]
I am having difficulty using the "Header filter" option for Clang Tidy. Every header included in a source file in my project is being tidied, no matter what I enter in the "Header filter" field. Even leaving this field empty results in all headers being tidied. I am using version 2.4.1.

I also cannot find a way to ignore a directory. I am including several third party packages in my project, and I do not want to receive errors / warnings from any files in these packages when I tidy my project, even if I have included files from these packages in my project. Is there any way to do this currently?

**Comment by hero101111** [comment]
Hello,

Have you tried to use the `Corresponding File` header-filter option?

**Comment by brendan-driscoll** [comment]
Unfortunately, the "Corresponding Header" option doesn't appear to ignore third party headers either, at least for third party headers that I have included in my source files.

The third party library that I'm trying to ignore is called "rapidJson" - is anyone able to replicate this behavior with this specific library?

**Comment by cpp-red-lion** [comment]
Now I'm confused.
Can you please attach a small test project reproducing the issue ?

Thanks.

**Comment by cpp-red-lion** [comment]
Hi @brendan-driscoll ,

Any updates ? 
Can you please attach a small test project reproducing the issue ?
