### ISSUE TITLE
nuget packages support

### ISSUE THREAD

**Issue by droppy** [Caphyon/clang-power-tools#192]
Clang power tools version 2.4.1

Issue:
No includes are resolved if header files are located in Nuget packages.

An empty console project with a Nuget package of Microsoft.googletest is attached to the issue.
I receive errors for both "Clang Tidy" and "Compile (syntax only)" IDE options indicating that the include file from Nuget can't be found:

_D:\ClangPowerTools_NugetCompatibility\ClangPowerTools_NugetCompatibility.cpp(1): error: 'gtest\gtest.h' file not found [clang-diagnostic-error]
#include <gtest\gtest.h>_

or
Start Clang Compile

_[ INFO ] WILL PROCESS PROJECTS: 
	D:\ClangPowerTools_NugetCompatibility\ClangPowerTools_NugetCompatibility.vcxproj
[ INFO ] 1. PROCESSING PROJECT D:\ClangPowerTools_NugetCompatibility\ClangPowerTools_NugetCompatibility.vcxproj
1: D:\ClangPowerTools_NugetCompatibility\ClangPowerTools_NugetCompatibility.cpp
D:\ClangPowerTools_NugetCompatibility\ClangPowerTools_NugetCompatibility.cpp:1:10: fatal error: 'gtest\gtest.h' file not found
#include <gtest\gtest.h>
         ^~~~~~~~~~~~~~~
1
 error generated._

[ClangPowerTools_NugetCompatibility.zip](https://github.com/Caphyon/clang-power-tools/files/1606732/ClangPowerTools_NugetCompatibility.zip)

**Comment by hero101111** [comment]
Hello,

We've reproduced the issue using the test project you submitted and we pushed a Github fix for it. 
Please take a few minutes to test our fix using the instructions below and let us know if everything runs OK.

Thanks for your feedback.

Regards,
Gabriel

---

Please note that this fix is currently live only for the github repository.
The latest Visual Studio extension (2.4.1) does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Don't forget to restart Visual Studio after replacing the script file.

**Comment by droppy** [comment]
I've tried clang-build.ps1 from f8fe1f6fe909a702f61ee3416f0ce36ef17e2db4 commit as was instructed and it worked fine after I first manually build the project (thus forcing MSVC to run nuget restore).

However, for some of my big projects it sill produces a similar error, I will create a separate issue report once I find out what causes the error and will be able to make a sample project reproducing the issue. Maybe some Nuget packages are malformed...
