### ISSUE TITLE
error encoding utf-16 when using vs2017

### ISSUE THREAD

**Issue by mazalet** [Caphyon/clang-power-tools#198]
Start Clang Compile

PROJECT: C:\Users\aemed\Documents\Visual Studio 2017\Projects\test\test\test.vcxproj
Set-Variable : 无法覆盖变量 HOME，因为该变量为只读变量或常量。
所在位置 C:\Users\aemed\AppData\Local\Microsoft\VisualStudio\15.0_b3aae91c\Extensions\mjvgbjmq.1tk\clang-build.ps1:393 
字符: 3
+   Set-Variable -name $name -Value $value -Scope Global
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (HOME:String) [Set-Variable], SessionStateUnauthorizedAccessException
    + FullyQualifiedErrorId : VariableNotWritable,Microsoft.PowerShell.Commands.SetVariableCommand
1: C:\Users\aemed\Documents\Visual Studio 2017\Projects\test\test\test.c
fatal error: UTF-16 (LE) byte order mark detected in 'C:\Users\aemed\Documents\Visual Studio 2017\Projects\test\test\test.c', but encoding is not supported
1 error generated.

Got errors.

Done Clang Compile

can any options to encoding  utf-8?

**Comment by cpp-red-lion** [comment]
Hi,

This is a known issue.

https://developercommunity.visualstudio.com/content/problem/140257/c-cannot-compile-the-standard-template-project-wit.html

Visual Studio **2017** generates for *new projects* template files encoded as **UTF-16 LE**.
Unfortunately, there is nothing we can do about the fact that Clang doesn't like UTF-16 source files that VS generates for new projects.

As a **workaround** you can _convert_ those VS generated files to **UTF-8** and everything will work fine, both with Clang and VS.

Hope MSFT will fix this soon.

**Comment by realcome** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		UTF-16 (LE) byte order mark detected in 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.14.26428\ATLMFC\include\afxres.rc', but encoding is not supported	test_png	D:\test_png\src\out\debug\obj\<stdin>	255	



How to resolev it?
