### ISSUE TITLE
Support for Open Folder projects

### ISSUE THREAD

**Issue by eel76** [Caphyon/clang-power-tools#200]
Are there any plans to support [Open Folder](https://docs.microsoft.com/en-us/cpp/ide/non-msbuild-projects) projects in the future?

**Comment by cpp-red-lion** [comment]
Hi,

Thanks for your suggestion.
We have thought about it, indeed, but we didn't prioritized it yet.

We didn't test to see what support the **Visual Studio Extensibility SDK** has for _Open Folder_ workflow.
At the moment, we depend on VS _property sheets_ and `vcxproj` files, as well as the Extensibility SDK.

It's definitely worth it. 
If somebody already has experience with this, we welcome external help :)

**Comment by Enache-Ionut** [comment]
Hi,

We are happy to announce the release of [Clang Power Tools version 5.1](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools). The CMake support for open file is ready 🎉

Thank you for your feedback 😃
