### ISSUE TITLE
Issues with paths containing "`"

### ISSUE THREAD

**Issue by DVMirchev** [Caphyon/clang-power-tools#211]
I tried to use the plug-in but my projects are in folders like this:

D:\`Branches\

And I get the error:

Exception calling "IsPathRooted" with "1" argument(s): "Illegal characters in path."

My guess is that those paths may have to be escaped in the power shell script. 

Edit: Full error message:

> At C:\Users\dimitar.mirchev\AppData\Local\Microsoft\VisualStudio\15.0_cbe75925\Extensions\dajnp3z0.dl3\clang-build.ps1:
> 582 char:12
> +   return ((Get-Item "$(Get-VisualStudio-Path)\VC\Tools\MSVC\" | Get-C ...
> +            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (D:\VC\Tools\MSVC\:String) [Get-Item], ItemNotFoundException
>     + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand
> Exception calling "IsPathRooted" with "1" argument(s): "Illegal characters in path."

**Comment by cpp-red-lion** [comment]
Thanks for your feedback 👍 

We'll try to find a workaround for this, in _PowerShell_.

**Comment by hero101111** [comment]
Unfortunately, this issue is more complex than it would appear; the ` character is a very special one in PowerShell. We cannot fix it lest be incur some serious refactoring around this issue.

It would be easier to just avoid this kind of paths.
