### ISSUE TITLE
`-DFOO="bar"` in original project breaks command line handling

### ISSUE THREAD

**Issue by hkaiser** [Caphyon/clang-power-tools#212]
The extension generates an invalid command line for clang if the project clang-tidy is to be used for has a preprocessor constant defining a string literal on the command line (`-DFOO="bar"`).

**Comment by hero101111** [comment]
Hi @hkaiser 

We're aware of this bug. A fix has already been pushed on github for it as part of #201 
An updated ClangPowerTools VS Extension will be released tomorrow.

Thanks for your feedback.

Regards,
Gabriel

**Comment by cpp-red-lion** [comment]
Hi,

This issue has been fixed in version `2.6` just released.

Thank you for your feedback 👍

**Comment by hkaiser** [comment]
Thanks!
