### ISSUE TITLE
No longer using kVcxprojXpathPropSheets to search for property sheets?

### ISSUE THREAD

**Issue by erikrenberg** [Caphyon/clang-power-tools#217]
I've been trying Clang Power Tools from time to time lately on my company's code but still with 2.6 I am not able to get it to compile. Previous showstoppers were VS macro expansion which you just added (great!) which prompted me to try again.

It appears not to find the props-file for the project, and I looked a bit at the source code and it appears to define a constant, `kVcxprojXpathPropSheets`, which I believe would point to the props-file that defines the necessary folders used.

However, `kVcxprojXpathPropSheets `appears not to be used? Is this a bug? Or doesn't it matter (is it obsolete?).

(If `kVcxprojXpathPropSheets  `doesn't matter I might post additional details about the our project structure, perhaps in a different issue). Thanks!

**Comment by hero101111** [comment]
Hi,

We've recently implemented a new way of parsing project data and we no longer rely on XPath selectors for loading property sheets. The `kVcxprojXpathPropSheets` constant is no longer used, we simply forgot to remove it.

Please attach a project file / prop sheet we can investigate this issue on.

**Comment by erikrenberg** [comment]
Thanks!

I have created a separate issue #224 which describes the exact problem I am having plus includes a test project. So I guess you can close this issue.

**Comment by cpp-red-lion** [comment]
Thanks for the test project.
We'll look into it.
