### ISSUE TITLE
How can I set the path of .clang-tidy config file?

### ISSUE THREAD

**Issue by taeguk** [Caphyon/clang-power-tools#218]
![image](https://user-images.githubusercontent.com/9107889/35543048-5a393f92-05a6-11e8-8dd3-ea53f1816aa1.png)

1. When I select '.clang-tidy config file' as 'Use checks from', what is the path where the .clang-tidy config file is loaded?

2. How can I set the path where the .clang-tidy config file is loaded?

**Comment by cpp-red-lion** [comment]
Hi @taeguk ,

http://clang.llvm.org/extra/clang-tidy/

> _Configuration files:_
  _clang-tidy_ attempts to read configuration for each source file from a `.clang-tidy` file located in the closest parent directory of the source file. 

Basically, _clang-tidy_ will start searching for your config file in the current source file directory, going up, up ../../.. until it finds one, or stops at the drive root.

As far as I know, the filename is not configurable (`.clang-tidy`), as it is the case with clang-format.

**Comment by cpp-red-lion** [comment]
BTW, you can use a custom `.clang-tidy` file in a directory you want to **exclude** when tidying and specify no checks to perform there.

**Comment by kr0ner** [comment]
Maybe ```clang-tidy -format-style= "$(< .clang-tidy.json)"``` ? Although this would require to convert the .clang-format to JSON :-/
