### ISSUE TITLE
Wrongly computed PCH header dir when using VS property-sheets

### ISSUE THREAD

**Issue by cpp-red-lion** [Caphyon/clang-power-tools#219]
Extended case related to issue: #209 
Reported by @Goraf

**Comment by hero101111** [comment]
We've just pushed a fix for this issue.
It will become available in the next release.

---

Please note that this fix is currently live only for the github repository.
The latest Visual Studio extension (`2.6`) does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. To locate the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

Don't forget to restart Visual Studio after replacing the script file.

**Comment by Goraf** [comment]
Works like a charm. Thank you for your great work on this really helpful tool.
