### ISSUE TITLE
Can't find property sheet used by VS

### ISSUE THREAD

**Issue by evsedykh** [Caphyon/clang-power-tools#225]
VS2015 Update 3 on Windows 10 Pro 64 bit with Russian language.

The problem is Clang Power Tools can't find boost include dir which is in property sheet Microsoft.Cpp.Win32.user.

All lines mentioning props from verbose log:

	ЏЋ„ђЋЃЌЋ: Could not find property sheet \Microsoft.Cpp.Default.props
	ЏЋ„ђЋЃЌЋ: Could not find property sheet \Microsoft.Cpp.props
	ЏЋ„ђЋЃЌЋ: Could not find property sheet \Microsoft.Cpp.targets

Also some internationalization problem in prefix of each line.

Could you please look at this issue. Can provide you some help if need with my settings. If you need project file I can provide it.

**Comment by cpp-red-lion** [comment]
Hi,

Please attach a test project reproducing the issue (including all referenced _custom_ VS property sheets).

Thanks.

**Comment by evsedykh** [comment]
Tried to create minimal example reproducing the issue. Try Debug x86 config.

[BoostInclude.zip](https://github.com/Caphyon/clang-power-tools/files/1689568/BoostInclude.zip)

**Comment by cpp-red-lion** [comment]
Thanks 👍

**Comment by hero101111** [comment]
Hi,

Currently we offer experimental support for loading platform property sheets.
By default we circumvent these property sheets as they are quite large and incur a delay in the project parsing. We manually detect platform include paths and other relevant settings.

You can enable it by setting the `CPT_LOAD_ALL` environment variable to `1`. 
This should make platform property sheets load.

Please let us know if this fixes your issue.

**Comment by evsedykh** [comment]
Yes, it fixes. Thank you.
