### ISSUE TITLE
Disable Clang compile & tidy commands for a file that is not in any loaded project.

### ISSUE THREAD

**Issue by dzolee** [Caphyon/clang-power-tools#226]
I got this tool running without problems with LLVM 5.0.1 and VS2017 prof (15.5.6) under Win7/64.
I can compile or tidy and file in the project/solution. However if I start VS without loading a project, and I drag-drop a .cpp file with Windows Explorer into VS, then try to compile the file with the power tools, I get the message box:
![grafik](https://user-images.githubusercontent.com/10893838/35735661-dc902aec-0825-11e8-83ee-ba7360925815.png)

If the file is part of a solution/project, however, clang is called and it will be compiled. Seems to happen only if the file is not part of any project.

**Comment by cpp-red-lion** [comment]
Hi @dzolee ,

This functionality is not supported in Clang Power Tools.
You can Clang compile or tidy a single file, but only when loaded into the context of a VS project.

**Comment by dzolee** [comment]
Thanks for the quick response, nevertheless I think it would be nice to have a sensible error message in such a case.

**Comment by cpp-red-lion** [comment]
Fair enough.
We'll disable clang compile and tidy commands when a file is not loaded in a VS project context, to avoid further confusion for users.

Thanks for your feedback 👍

**Comment by Enache-Ionut** [comment]
Hi,

The clang compile and tidy commands are now disabled for a file that is not in any loaded project. This fix will be available in the next release.
