### ISSUE TITLE
A single error found in a header can be displayed multiple times

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#227]
If an error is found in a header file, but that header is included in 10 different .cpp files, then that error is currently displayed 10 times in the Error list even though it is clearly the same error from the .h.

I think it would be better to only show unique errors, so for example if the error description, file name and line number are the same then treat the error as the same and only display the unique error once.

**Comment by cpp-red-lion** [comment]
Good suggestion 👍

**Comment by Enache-Ionut** [comment]
This issue was fixed and it will be available in the next version.

Thank you for your feedback !
