### ISSUE TITLE
"Stop Clang" command crashes all running Powershell processes

### ISSUE THREAD

**Issue by Arminius** [Caphyon/clang-power-tools#235]
You can reproduce this issue by opening a Powershell window, starting clang-tidy via Clang Power Tools -> Tidy Code and subsequently selecting Clang Power Tools -> Stop Clang. The Powershell window will be gone.

**Comment by cpp-red-lion** [comment]
Hi,

Thank you for bringing this issue to our attention.
We'll investigate/fix it and get back to you, on this thread.

**Comment by Enache-Ionut** [comment]
This issue was fixed and it will be available in the next version.

Thank you for your feedback !
