### ISSUE TITLE
Questions/Issues about/in sample-clang-build.ps1

### ISSUE THREAD

**Issue by kpiekara** [Caphyon/clang-power-tools#237]
1. .PARAMETER aVcxprojToIgnore, comment
is misspelled
`e.g. "msicomp" compiles all msicomp projects.`
should be 
`e.g. "msicomp" ignore all msicomp projects.`
?

2. .PARAMETER aClangCompileFlags
is not used, as '-aClangCompileFlags' parameter is set with kClangCompileFlags
`$scriptParams += ("-aClangCompileFlags", (Merge-Array $kClangCompileFlags))`
?

3.  .PARAMETER aClangCompileFlags
is
`Alias 'clang-flags'`
there is no alias set in file?

4. Examples of usage: 
` PS .\sample-clang-build.ps1 -dir `
There is no parameter dir? Hyphen is misleading.

5. Even with `-continue` whole scripts breaks when `#error some error text` is met in code. Looking for other issues it seems that there is problem in case when compilation is failed by preprocesor.

**Comment by cpp-red-lion** [comment]
Hi,

Thank you for bringing these issues to our attention.
We'll investigate/fix it and get back to you, on this thread.

**Comment by hero101111** [comment]
Hello,

We've updated the documentation. 
Thank you for pointing out the inaccuracies.

Regarding the behavior of `-continue`, we've addressed it as part of #234
Any errors during PCH creation stopped the compilation process, regardless of the `-continue` switch.

We'll release an updated version today.
