### ISSUE TITLE
clearcase checkout on any run

### ISSUE THREAD

**Issue by tuxStarElan** [Caphyon/clang-power-tools#238]
if i want to run tidy on a single file or a project all project of the solution will be checked out.
most likely caused be the new behavior to save all projects before running compile/tidy

**Comment by tuxStarElan** [comment]
Hi,

I think you close the issue a little bit to fast. I agree that saving the latest changes done by the user is necessary, but obviously only changes need to be saved. That seems to be the case prior to Visual Studio Compile action. There is no problem with the clearcase  source control provider plugin regarding save before compile, because all modified files/projects are checked out.

best regards
tuxStarElan

**Comment by cpp-red-lion** [comment]
Oops!
My bad. I’m sorry I didn’t get the nuance on the issue here.

I guess the problem is that we save all projects (even the ones unmodified).

This is definitely undesirable and we should fix that.

Thanks for the clarification.

**Comment by Enache-Ionut** [comment]
This issue was fixed and it will be available in the next version. 

Thank you for your feedback !
