### ISSUE TITLE
Seems to be trying to include #includes that are actually comments

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#240]
For example with the following comment included at the top of StdAfx.cpp

//This is just a comment #include "IGNORE.h" but yet it gets included

Results in the following error when using Tidy Code option:

```
Start Clang Tidy

PROJECT: F:\Projects\Test\DemoApp\DemoApp.vcxproj
Join-Path : Cannot find path 'F:\Projects\Test\DemoApp\DemoApp\IGNORE.h' because it does not exist.
At C:\Users\XXXXX\AppData\Local\Microsoft\VisualStudio\15.0_814f0842\Extensions\ux53zt2n.1tl\clang-build.ps1:530 
char:25
+ ... ]] $paths = Join-Path -Path "$base" -ChildPath "$child" -Resolve -Err ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (F:\Projec...emoApp\IGNORE.h:String) [Join-Path], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.JoinPathCommand
 

Done Clang Tidy
```

**Comment by cpp-red-lion** [comment]
Hi,

Can you attach a sample project (with all required dependencies), so that we can reproduce this issue ?

Thanks.

**Comment by netx123** [comment]
Please find attached a sample project:
[Test.zip](https://github.com/Caphyon/clang-power-tools/files/1724078/Test.zip)
I believe the issue may be caused by the regular expression in clang-build.ps1:
`return [regex]::match($fileContent,'#include "(\S+)"').Groups[1].Value `

**Comment by cpp-red-lion** [comment]
Thanks for the test project.
We'll investigate and get back to you (here) when we have a fix.

**Comment by hero101111** [comment]
Hi,

We've just pushed a fix for this. An updated version will be released today.
Thanks again for the feedback.
