### ISSUE TITLE
/MD and /MT project settings not propagated to clang

### ISSUE THREAD

**Issue by ravenAtSafe** [Caphyon/clang-power-tools#245]
I had to manually add `-D_MT` in order to quiet down Boost and TBB complaints about needing to be built in a multi-threaded way.

**Comment by cpp-red-lion** [comment]
Hi,

Thanks for bringing this issue to our attention 👍 
We'll address it soon and update this thread when it's done.

**Comment by ravenAtSafe** [comment]
I should disclose that I don't know if -D_MT is the *right* way of solving this, or sufficient.

Tangentially related, I had to set -DBOOST_USE_WINDOWS_H as well; I haven't figured out how it is auto defined when built by VC yet.

It's an ongoing process...

**Comment by vahtis** [comment]
I created a pull request for this.
It add -D_MT when runtime library is set to multi threaded in visual studio project. 
This solved our problems with boost.

**Comment by cpp-red-lion** [comment]
FYI, 

There are multiple configurations for `RuntimeLibrary` setting in VS:

- /MTd  `<RuntimeLibrary>MultiThreadedDebug</RuntimeLibrary>`
- /MT    `<RuntimeLibrary>MultiThreaded</RuntimeLibrary>`

- /MD   `<RuntimeLibrary>MultiThreadedDLL</RuntimeLibrary>`
- /MDd  `<RuntimeLibrary>MultiThreadedDebugDLL</RuntimeLibrary>`

**Comment by cpp-red-lion** [comment]
Thanks, @vahtis for your contribution 👍 

The fix will be available in the next release.
