### ISSUE TITLE
JSON Compilation Database

### ISSUE THREAD

**Issue by JVApen** [Caphyon/clang-power-tools#248]
This tool looks really useful, however, I find myself in a situation where the makefile forwards the commands to another build system.
Would it be possible to have an option to use the [JSONCompilationDatabase](https://clang.llvm.org/docs/JSONCompilationDatabase.html) instead?

**Comment by cpp-red-lion** [comment]
Hi,

Thank you for your suggestion.

We consider that the greatest asset of our Visual Studio extension is the ability to parse and adapt  **VS project settings** to the Clang format. Extracting "project" settings from a _JSON Compilation Database_ files should be much easier.

If you're interested and have the time, we welcome external contributors in this area.

Related issue: #189
