### ISSUE TITLE
processing of <AdditionalIncludeDirectories> in props files

### ISSUE THREAD

**Issue by tpzworks** [Caphyon/clang-power-tools#254]
Include folders are not properly parsed if we use multi line includes in the props file. For example

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemDefinitionGroup>
    <ClCompile>
      <AdditionalIncludeDirectories>
        %(AdditionalIncludeDirectories);
        
        $(ProjectDir);
        $(ProjectDir)Include;
        $(ProjectDir)Include\A;

        $(ProjectDir)Include\B;
        $(ProjectDir)Include\C;
      </AdditionalIncludeDirectories>
  </ItemDefinitionGroup>
</Project>

```

**Comment by tpzworks** [comment]
I know the solution, but that would mean putting all the includes in single line - not very readable.

**Comment by cpp-red-lion** [comment]
Hi,

Thanks for bringing this issue to our attention 👍 
We'll update this thread as soon as we have a fix.

**Comment by cpp-red-lion** [comment]
This issue was fixed and will be available in the next version we release.

Thanks to @InfiniteStateMachine for the patch and to @hero101111 for reviewing.
