### ISSUE TITLE
White space in project name and path

### ISSUE THREAD

**Issue by vahtis** [Caphyon/clang-power-tools#259]
I had to change regular expression matching from
Project\([{}\"A-Z0-9\-\\]+\) = \S+,\s(\S+),
to 
Project\([{}\"A-Z0-9\-\\]+\) = \".*?\",\s\"(.*?)\"
because \S+ stops at white space.

**Comment by cpp-red-lion** [comment]
Hi @vahtis ,

Thanks for your feedback 👍 

If you fork the project, you can submit a _Pull Request_ with the above change and become a contributor to _Clang Power Tools_.

**Comment by vahtis** [comment]
Done
https://github.com/Caphyon/clang-power-tools/pull/260

**Comment by cpp-red-lion** [comment]
Excellent 🎉 

Thanks for contributing 👏 
To be reviewed shortly.

**Comment by cpp-red-lion** [comment]
PR was merged into `master`.
It will be available in the next version.
