### ISSUE TITLE
Add support for NMake project files

### ISSUE THREAD

**Issue by trixnz** [Caphyon/clang-power-tools#278]
Our project currently defines the following nodes under the `PropertyGroup` nodes:
`NMakeBuildCommandLine`, `NMakeReBuildCommandLine`, `NMakeCleanCommandLine`, `NMakeIncludeSearchPath`, `NMakePreprocessorDefinitions`.

It seems like none of these are read (realistically, only the include path and preprocessor definitions are relevant) and passed on to `clang-tidy`.

**Comment by cpp-red-lion** [comment]
Hi,

Thank your for your suggestion 👍 
We'll look into it.

**Comment by hero101111** [comment]
Can you provide an explanation of what these properties do?
It's not clear to me how Visual Studio processes them.

**Comment by trixnz** [comment]
They act just like the regular Includes and Preprocessor keys, but aren't tied to ClCompile. They live under PropertyGroup.

You can find an example of their usage on this project: https://github.com/GameTechDev/ClusteredShadingAndroid/blob/master/ClusteredShadingAndroid.vcxproj#L39-L40

**Comment by hero101111** [comment]
Hello,

We're still having trouble understanding this feature request.
Under a test project, based on your _GameTechDev_ github sample, the NMAKE properties are fully loaded by clangpowertools.
>VERBOSE: SET_VAR NMakeBuildCommandLine: "\VisualGDB.exe" /build "" "/solution:" "/config:Debug" "/platform:Win32"
VERBOSE: SET_VAR NMakeCleanCommandLine: "\VisualGDB.exe" /clean "" "/solution:" "/config:Debug" "/platform:Win32"
VERBOSE: SET_VAR NMakeReBuildCommandLine: "\VisualGDB.exe" /rebuild "" "/solution:" "/config:Debug" "/platform:Win32"
VERBOSE: SET_VAR NMakePreprocessorDefinitions: __VisualGDB_CFG_Debug;
VERBOSE: SET_VAR NMakeIncludeSearchPath:
C:\Android\ndk\platforms\android-18\arch-arm\usr\include;C:\Android\ndk\toolchains\arm-linux-androideabi-4.6\prebuilt\windows\lib\gcc\arm-linux-androideabi\4.6\include;C:\Android\ndk\toolchains\arm-linux-androideabi-4.6\prebuilt\windows\lib\gcc\arm-linux-androideabi\4.6\include-f
ixed;
VERBOSE: SET_VAR NMakeForcedIncludes: C:\test\win\\gcc_Debug.h;\gcc_compat.h;

Should there be more to it than just loading them as regular project properties?

**Comment by trixnz** [comment]
Hi,

I am on vacation from work where the projects live, but based on your output, it looks like these are being read now (possibly due to changes since the construction of the issue?). I think it is fine to close this issue for now and I'll re-open it if the problem is still present when I can check in a few weeks.
