### ISSUE TITLE
clang-build.ps1 "Cannot find drive" Error 

### ISSUE THREAD

**Issue by GerdHH** [Caphyon/clang-power-tools#279]
I just started looking at Clang Power Tools on a relatively small vcxproj.  Clang Compile and Tidy run, but the VS Output window complains about a line in the clang-build.ps1 script:

Start Clang Tidy

PROJECT: R:\Server\Framework\UTxShared\UTxShared.vcxproj
Get-Item : Cannot find drive. A drive with the name 'Error 0x57' does not exist.
At C:\Users\hoereng\AppData\Local\Microsoft\VisualStudio\15.0_0d838d80\Extensions\140t5yjx.iwh\clang-build.ps1:597 char:12
+   return ((Get-Item "$(Get-VisualStudio-Path)\VC\Tools\MSVC\" | Get-ChildItem) | ...
+            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Error 0x57:String) [Get-Item],     DriveNotFoundException
    + FullyQualifiedErrorId : DriveNotFound,Microsoft.PowerShell.Commands.GetItemCommand

I'm using VS 2017 15.2.  Sorry, I don't speak power shell. Could this be caused by some cruft in my vcxproj file?

**Comment by cpp-red-lion** [comment]
Hi,

Can you attach the project file or something similar, reproducing the issue ?

Thanks.

**Comment by GerdHH** [comment]
Hello Victor,

Here is a zip that contains UTxShared.vcxproj (in UTxShared\Server\Framework\UTxShared) and its imported .props files in the Build and Server folder.  I'm using the Debug x64 configuration with VS2017 Update 2.

If the issue is not obvious, I'm happy to try and create a simpler example.

[UTxShared.zip](https://github.com/Caphyon/clang-power-tools/files/1817506/UTxShared.zip)

_____
Gerd

**Comment by cpp-red-lion** [comment]
Thanks for the test project.  
We'll look into it and post updates here.

**Comment by hero101111** [comment]
Hi,
 
Tried your sample project and everything appears to be running OK on my end.
Please enable `Verbose mode` and paste the log here.

**Comment by GerdHH** [comment]
Thanks for looking at this, Gabriel.  I don't speak PowerShell, but figured out that removing the "-prerelease" option in Function Get-VisualStudio-Path() fixes the error.

I'm on VS2017 Update 2 (Version 15.2).  It appears that vswhere.exe in 15.2 doesn't support -prerelease.

I'm attaching the contents of the output window with Verbose enabled.  If the error is just a 15.2 issue, I can work around it for now.  We will move to Update 6 soon.

_____
Gerd

[VerboseLog.txt](https://github.com/Caphyon/clang-power-tools/files/1835533/VerboseLog.txt)

**Comment by hero101111** [comment]
We've just pushed a fix for when `vswhere` doesn't support the `-prerelease` switch
An updated version of _Clang Power Tools_ will be released today.

**Comment by GerdHH** [comment]
Thank you very much for fixing this issue so promptly.  Version 3.2.0 works fine with VS2017 Update 2.
