### ISSUE TITLE
Improve responsiveness during lengthy operations

### ISSUE THREAD

**Issue by dzolee** [Caphyon/clang-power-tools#288]
If I start a Clang-Tidy on a rather big source file which also includes zillions of other sources, VS goes unresponsive and in the end I receive this notice:

![grafik](https://user-images.githubusercontent.com/10893838/37765127-bb821284-2dc3-11e8-8256-60454bb6ebaf.png)

Can you please research and add some periodic update, so that VS does not complain and the UI stays responsive?

Thanks

**Comment by Enache-Ionut** [comment]
Hi,

Thank you for bringing this issue to our attention.
We'll investigate it and we'll update this thread as soon as we have a fix.

**Comment by Enache-Ionut** [comment]
This issue was fixed and it will be available in the next release.
Thank you for your feedback!
