### ISSUE TITLE
Error: Cannot find given project 

### ISSUE THREAD

**Issue by Ali-Se** [Caphyon/clang-power-tools#29]
When I try to run (Compile or Tidy Code) on any project or file, I get an error message:

`
Start Clang Compile

Cannot find given project

Done Clang Compile
`
I'm using Visual C++ 2017, but with the standard solution file format, and Toolset: 14.0 (Visual Studio 2015) project format.

**Comment by reinsch82** [comment]
This happens to me too. 
It seems that the code is assuming the project file is called the same as the project in the UI which is not a requirement from VS. That's at least my problem I think

**Comment by cpp-red-lion** [comment]
We'll investigate this today, and hopefully we'll have a fix out by the end of the week.
It would help if you could attach a sample SLN + vcxproj file reproducing the issue (maybe a stripped-down version of your project config).
Thanks for reporting it.

**Comment by reinsch82** [comment]
sorry can't repro currently because of another issue #30

**Comment by cpp-red-lion** [comment]
We actually reproduced the project name issue; a fix is coming.

**Comment by reinsch82** [comment]
Just to be sure we are talking about the same issue, this is a repro I came up with.

[ConsoleApplication1.zip](https://github.com/Caphyon/clang-power-tools/files/1394425/ConsoleApplication1.zip)

**Comment by Ali-Se** [comment]
You are right @reinsch82 
When I tried the tool on a project with the same name as in VS, the error does not occur.
