### ISSUE TITLE
Use Pester for PowerShell unit tests

### ISSUE THREAD

**Issue by alexandear** [Caphyon/clang-power-tools#298]
[Pester](https://github.com/pester/Pester) is de-facto standard unit test framework for writing PowerShell unit tests.

[msbuild_translation_tests.ps1](../blob/master/ClangPowerTools/ClangPowerTools/msbuild_translation_tests.ps1) should be rewritten with the help of this framework.

**Comment by cpp-red-lion** [comment]
Interesting suggestion. Didn't know about that.  

Care to contribute 😉 such a test unit, to get us started ?

**Comment by alexandear** [comment]
I will rewrite few tests from `msbuild_translation_tests.ps1` with the help of Pester on the next few days.

**Comment by alexandear** [comment]
@cpp-red-lion added two tests that can be run using Pester. See referenced commit 7a8558072e2ff42f20369566b19e55906280a0c8.

To run tests:
* install latest Pester (4.3.1):
```
Install-Module -Name Pester -Force -SkipPublisherCheck
```
* execute tests:
```
Invoke-Pester .\msbuild_translation_tests.ps1
```
The output will be:
```
  Describing Evaluate-MSBuildCondition
    [+] When ImportDirectoryBuildProps is true and not exists DirectoryBuildPropsPath returns false 54ms
    [+] When Miscrosoft SDKs v7.1A installed returns true 18ms
Tests completed in 73ms
Tests Passed: 2, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0
```

E.g., when some test fails the output will be:
```
  Describing Evaluate-MSBuildCondition
    [+] When ImportDirectoryBuildProps is true and not exists DirectoryBuildPropsPath returns false 64ms
    [-] When Miscrosoft SDKs v7.1A installed returns true 67ms
      Expected $true, but got $false.
      265:         $result | Should -Be $true
      at <ScriptBlock>, C:\clang-power-tools\ClangPowerTools\ClangPowerTools\msbuild_translation_tests.ps1: line 265
Tests completed in 131ms
Tests Passed: 1, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0
```

**Comment by cpp-red-lion** [comment]
Thanks 👍 
Do you have a PR for this ?

**Comment by alexandear** [comment]
No, I have not created PR. I migrated only two tests from 35 overall.

I can't migrate the rest of the tests. They are failed on my machine. I think, it is because of the some missing projects that used in tests:
```
$UserRootDir   = "c:\test"
$WinDir        = "C:\Windows"
$ProjectDir    = "C:\Users\Default"
$TargetName    = "YOLOTest"
$varB          = 1
```

**Comment by hero101111** [comment]
@alexandear thanks for prototyping a couple of tests using Pester.
We're in the process of reorganizing the code and will refactor the other tests so that they no longer fail.

**Comment by hero101111** [comment]
Happy to inform you that we've finished migrating our test code to Pester.
Thank you for the helpful feedback.
