### ISSUE TITLE
clang-build.ps1 assumes VS is installed in c:\Program Files(x86)

### ISSUE THREAD

**Issue by reinsch82** [Caphyon/clang-power-tools#30]
I have it installed on E: so it doesn't work as expected

**Comment by cpp-red-lion** [comment]
Oops!
Your're right, the PS script assumes ${Env:ProgramFiles(x86)} install location for Visual Studio and Windows SDK. 
When we started, we didn't think this was going to be a major issue (few people actually change default install location for these tools).
We'll definitely need to support custom install locations. 
Thanks for bringing it up.

**Comment by hero101111** [comment]
Issue was fixed.
