### ISSUE TITLE
Empty string as file path

### ISSUE THREAD

**Issue by adevaykin** [Caphyon/clang-power-tools#302]
Hello. First of all, thanks for the great tool!
Unfortunately clang-tidy as well as clang compile (syntax only) doesn't work on a pretty big project I have. It's a solution with a number of C++ and C# projects and custom build commands defined in the "Build Events" section of the properties of the project of interest. I've added all the non-C++ projects to the ignore field.
The reported problem looks as follows:
```
IsFileMatchingName : Das Argument kann nicht an den Parameter "filePath" gebunden werden, da es sich um eine leere 
Zeichenfolge handelt.
In C:\Users\Alexander\AppData\Local\Microsoft\VisualStudio\15.0_a9f14941\Extensions\zubklc1t.fkt\clang-build.ps1:2155 
Zeichen:64
+                   Where-Object {  IsFileMatchingName -filePath $_ `
+                                                                ~~
    + CategoryInfo          : InvalidData: (:) [IsFileMatchingName], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,IsFileMatchingName
```
So it seems that clang tries to process a file, whereas file path is an empty string.

I've enabled verbose debug output as suggested in one of the issues here and saw additional warnings. These are obviously related to the custom build event. Not sure if it may be related to the main problem...
```
DEBUG: Intermediate PS expression: cd "$(${SolutionDir})..\Installer"
python GetVersionString.py  -gt  "$(${OutDir})version.txt"
DEBUG: In Zeile:1 Zeichen:12
+ ($s = "cd "$(${SolutionDir})..\Installer"
+            ~~
```

I will be happy to help tracking this issue down if you point me to how to debug the script.

**Comment by hero101111** [comment]
Hi,

We need more info regarding that expression, in particular its initial form. 
Have a look in the log (`Start evaluate MSBuild expression...`) and post here its value.

**Comment by hero101111** [comment]
We're currently unable to reproduce this issue using the pre-build event you have specified. 

Can you please try again using the latest ClangPowerTools release and let us know if anything is still broken?

**Comment by adevaykin** [comment]
@hero101111 thank you for the reply. Unfortanutely it still fails. Now without that many errors in verbose mode, but now also when I remove the pre- and post-build steps it fails with the output like in my first message here. I'll try to debug it myself a bit and will report results.

**Comment by adevaykin** [comment]
@hero101111 so I layed around with clang-build.ps1 and found out the following:
- in the `Process-Project` function `$stdafxCpp`, `$stdafxDir` and `$stdafxHeader` are empty
- in the `Get-Project-PchCpp` function `$pchCppRelativePath` is empty at the moment when it is returned and `$kVcxprojXpathPCH` contains the following:
```
ns:Project/ns:ItemGroup/ns:ClCompile/ns:PrecompiledHeader[text()='Create']
```

Let me know where to dig to find out the reason. I could not create a new simple project to reproduce the issue.

**Comment by hero101111** [comment]
By default a vcxproj file includes cpps and headers using relative paths.
Does your project include files using wildcards or properties? I think this could be the cause.

You can inspect the `Project > ItemGroup > ClCompile` XML elements in your vcxproj to find out.

**Comment by adevaykin** [comment]
File names are directly specified as relative paths. The error message is printed when I try to clang-compile a file. When I try to compile the whole project, it simply finishes in 3 seconds reporting "Done"

Here is a part of the vcxproj file with censored parts replaced with ...:
```
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" ToolsVersion="15.0">
  <PropertyGroup Label="Globals">
    <ProjectGuid>{...}</ProjectGuid>
    <Keyword>Win32Proj</Keyword>
    <RootNamespace>...</RootNamespace>
    <ProjectName>...</ProjectName>
    <ConfigurationType>DynamicLibrary</ConfigurationType>
    <CharacterSet>Unicode</CharacterSet>
  </PropertyGroup>
  <Import Project="$(SolutionDir)Project-Template.vcxproj" />
  <ItemDefinitionGroup>
    <ClCompile>
      <PrecompiledHeader>Use</PrecompiledHeader>
      <AdditionalIncludeDirectories>$(SolutionDir)ExternalLibraries/inc/...;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
      <PreprocessorDefinitions>..._EXPORTS;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <AdditionalOptions>/Zm750 /std:c++latest %(AdditionalOptions)</AdditionalOptions>
    </ClCompile>
    <PreBuildEvent>
      <Command>
      </Command>
    </PreBuildEvent>
    <PostBuildEvent>
      <Command>
      </Command>
    </PostBuildEvent>
    <Link>
      <AdditionalDependencies Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">%(AdditionalDependencies);...</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
  <ItemGroup>
    <ClCompile Include="AlphaPass.cpp" />
  </ItemGroup>
  <ItemGroup>
    <ClInclude Include="AlphaPass.h" />
<Image Include="..\..\Resources\....ico" />
    <ResourceCompile Include="....rc" />
  </ItemGroup>
  <ItemGroup>
    <None Include="....h" />
    ...
  </ItemGroup>
</Project>
```

**Comment by hero101111** [comment]
Sadly, I don't see anything suspicious in this snippet.

Something prevents the list of project CPPs from loading. 
Can you confirm this by inspecting the `$projCpps` variable as soon as it's instantiated using `Get-ProjectFilesToCompile`?

**Comment by hero101111** [comment]
Hello,

We've recently rewritten the part of Clang Power Tools that was the culprit for this problem.
Starting with `v5.0`, due to be released soon, your project should compile OK.

Meanwhile, you can try manually testing the new code by grabbing it from the CPT github `master` and placing in inside the VS Extension directory.

Regards,
Gabriel.
