### ISSUE TITLE
PCH usage is not configurable at file level

### ISSUE THREAD

**Issue by icze** [Caphyon/clang-power-tools#313]
Hallo,

thanks for your nice tool. I found a problem with pre-compiled headers.
In my project settings the usage of a pre-compiled header is enabled.
But if I now disable it for one file only, Clang Power Tools still uses it.

The following example demonstrates the bug with the fact that "WinSock2.h" has
 to be included before "Windows.h":
[PrecompiledHeaderBug.zip](https://github.com/Caphyon/clang-power-tools/files/1931225/PrecompiledHeaderBug.zip)

**Comment by hero101111** [comment]
Hi @icze,

Unfortunately, at the moment, we don't support PCH configuration at the file level. 
We unable to push a quick fix, sadly. Moving forward we'll definitely add support for it. 

This issue thread will be updated when progress is made.

Thank you for your feedback and sample project.

**Comment by icze** [comment]
Hi @hero101111,

Thanks for fixing the bug in future. As workaround I put the affected files to the 'Files to ignore' setting.

Regards
Ingo

**Comment by hero101111** [comment]
Hello,

Happy to inform you that we've just finished implemented this.
It'll be available in version `4.2` of ClangPowerTools, to be released soon.

Best regards,
Gabriel.
