### ISSUE TITLE
Update clang-format.exe to the latest version 6.0.0.0

### ISSUE THREAD

**Issue by pavelpokutnev** [Caphyon/clang-power-tools#318]
Current release 3.3.1 installs the outdated version of the clang-format.exe 5.0.0.0. Please update it to the latest version 6.0.0.0, since it adds some new styling options like IndentPPDirectives, ...

**Comment by cpp-red-lion** [comment]
Hi,

We'll update our "in the box" version of `clang-format` to **6.0** in our next release (due next week). 

In the meantime, you can use the following _workaround_ to manually update `clang-format` used by _Clang Power Tools_:  
- Search for `clang-format.exe` in your `%LOCALAPPDATA%` folder
- Replace it with version 6.0 from your LLVM installation 👇  (if you have any)
- Restart Visual Studio

👉  If you don't have an LLVM 6 installation handy, you can grab the latest `clang-format.exe` from here:   
[clang-format.exe v6.0](https://github.com/Caphyon/clang-power-tools/blob/master/ClangPowerTools/ClangPowerTools/llvm/bin/clang-format.exe)

**Comment by cpp-red-lion** [comment]
Updated in commit: 471a98bf

**Comment by pavelpokutnev** [comment]
OK, thanks for the quick action!
