### ISSUE TITLE
Allow other file endings than .cpp

### ISSUE THREAD

**Issue by GerrietReents** [Caphyon/clang-power-tools#32]
First: Thanks a lot for this project! I hoping for something like this for months! 

It looks like your extension is currently filtering source files by the file ending `.cpp`

Please broaden the filter in clang-build.ps1, for example like
`Set-Variable -name kExtensionCpp             -value ".cpp|.c|.cxx"       -Option Constant`
or even make it configurable.

Best regards,
Gerriet

**Comment by cpp-red-lion** [comment]
We're working on it.
We restricted the compilation to `.cpp` files because, initially, we ran into some issues with clang with custom extensions. 
Eg.
`clang++.exe: error: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Werror,-Wdeprecated]`

**Comment by GerrietReents** [comment]
Great! Thanks a lot!

I saw that problem, too. We compile everything as C++, so i can add -x c++ to the clang options.

**Comment by cpp-red-lion** [comment]
`clang++ -x c++ source.xyz` sounds like a good option.
We'll try this approach and open-up the script to all file types, registered in vcxproj with `<ClCompile />`

**Comment by cpp-red-lion** [comment]
Issue fixed.
