### ISSUE TITLE
Support mixed C and C++ projects

### ISSUE THREAD

**Issue by ben-craig** [Caphyon/clang-power-tools#321]
I have projects that are mostly C++, with a few .c files.  Compile (syntax only) fails on those files, usually because of void* -> T* conversions (thanks malloc).

clang++ supports the "-x c" flag to compile C code, even while using the clang++ driver executable.

[mixed_c_and_cpp.zip](https://github.com/Caphyon/clang-power-tools/files/1951589/mixed_c_and_cpp.zip)

This is closely related to issue #187 .

**Comment by cpp-red-lion** [comment]
Hi,

Thank you for your suggestion 👍 

We don't have support for compiling **C** files right now.

You can skip compiling those files by using a file filter:
eg.

`-file-ignore "[\.]c$"`   (when invoking from PowerShell / CLI)

or

ClangPowerTools > Settings > General > File to ignore:   `[\.]c$`

**Comment by cpp-red-lion** [comment]
See also #187
