### ISSUE TITLE
Compile - no matching function error

### ISSUE THREAD

**Issue by Rocinante8** [Caphyon/clang-power-tools#322]
Hello,
I get the error Clang : no matching function for call to 'GetProcessAffinityMask' when trying to compile. No problems compiling in Visual Studio C++. The function is declared in WinBase.h which is included in Windows.h which is included in my company's standard header which is included in StdAfx.h (precompiled header).

Using Visual Studio 15.6.7

Thanks
.

**Comment by Rocinante8** [comment]
I think the problem is that it thinks I'm compiling in 64 bit mode.
PDWORD_PTR is defined as a an unsigned long pointer in 32 bits; as a unsigned long long pointer in 64 bits. How do I tell clang that I'm compiling in 32 bits?

**Comment by hero101111** [comment]
Hello,

First of all we're sorry for the long response delay. 
We've tested this scenario using the `-m32` flag and we think it should work for you.

We don't have UI support for it right now so you'll have to manually enable it:
- locate `clang-build.ps1` in `%LOCALAPPDATA%`
- open script and locate function `Get-CompileCallArguments`
- add `"-m32"` to the clang argument list variable`$projectCompileArgs`
- restart _Visual Studio_ and try compiling again using _Clang Power Tools_

Note that the `-m32` flag is incompatible with x64 builds of LLVM so you'll need to make sure the **x86** LLVM is installed and added to the `PATH` environment variable. 

Please test this and let us know if your code compiles.

**Comment by hero101111** [comment]
We looked a bit further into this and it looks like `-m32` *can* be set from `General > Compile flags`
You can skip the manual instructions I mentioned above.

**Comment by cpp-red-lion** [comment]
This issue will be addressed as part of #380 

Thanks for the feedback 👍
