### ISSUE TITLE
Visual studio crashes in settings

### ISSUE THREAD

**Issue by torgeiws** [Caphyon/clang-power-tools#329]
After updating to Clang Power tools version 3.4.0, I get a crash when I go into the settings for Tidy, go to Predefined Checks, and try to expand one of the"cppcoreguidelines-pro-bounds-..." checks. Simply clicking these triggers the crash, and it seems to happen on multiple of them.
 
I tried the debug option, which gave me this information in a popup:
System.Windows.Markup.XamlParseException: 'The 'T' start tag on line 1 position 395 does not match the end tag of 'TextBlock'. Line 1, position 642.'
See full details [here](https://pastebin.com/rKWNdc3Y)

**Comment by cpp-red-lion** [comment]
Hi,

Thanks for bringing this issue to our attention.
We will address it immediately and release a fix soon.

**Comment by torgeiws** [comment]
You would probably find this yourself, but it looks like other checks have this problem as well. I encountered it on "google-runtime-member-string-references" as well.

**Comment by Enache-Ionut** [comment]
Hi,

This issue has been resolved and is available in the new version v3.4.2 just released.
Thank you for your feedback!
