### ISSUE TITLE
Make clang-power-tools work with CMake based projects

### ISSUE THREAD

**Issue by truschival** [Caphyon/clang-power-tools#330]
Visual Studio has progressed significantly with respect to CMake projects. But I can't get clang-power-tools to work with a CMake based project (Open Folder), even if I let cmake generate the compile-commands.json.
I am running VS 15.7.1 and CMake 3.11.x on Windows7 x64 Enterprise

* The buttons are greyed out for both clang-format and clang-tidy. 
* The Setup works if I have a Visual Studio Solution for C++ Console Application

**Comment by cpp-red-lion** [comment]
Hi,

Support for CMake projects is not yet available.
Thanks for your suggestion.

We'll update this thread once we have it working.

**Comment by AliAskari** [comment]
I have only recently found clang-power-tools, it's really amazing. It would be great if it was also available in the Open Folder projects. I currently have to manually generate the Visual Studio Solution file and use the extension, which is not a big deal, but not every one in our team is willing to do it. 

Thanks for the great work!

**Comment by Zingam** [comment]
+1 for CMake projects

**Comment by s-martin** [comment]
I'd really like this feature, too.

Could you give some info, if this feature is on your roadmap or if there are any impediments for an implementation?

**Comment by cpp-red-lion** [comment]
This feature is on our immediate roadmap.   
Stay tuned for updates on this.

**Comment by s-martin** [comment]
So according to #605 this is fixed?

**Comment by Enache-Ionut** [comment]
Hi,

Yes, this issue is fixed. I will close it now.
Thank you for all your feedback and support 😃

**Comment by dtromb** [comment]
"This issue is fixed", but how do you use it?  There is still no context menu item in cmake projects...
