### ISSUE TITLE
Invoke CompileCommand has no observable effect

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#34]
Hi, i just downloaded your awesome plugin! Got powershell 5.1 on windows 10, installed LLVM and the latest version of the plugin of the marketplace using VS2015.3

When i press Invoke CompileCommand it has no observable effect and doesn't show anything in the output window. How can i trace what is going wrong? I suspect its something in my setup, but without any logging its hard to figure it out.

**Comment by jcageman** [comment]
Oke, it seems the Invoke CompileCommand doesn't work. When right clicking on a while in the editor and using the compile command it does produce output. 

1. Visual studio default include paths are not recognized? For example i get compile errors due to c:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\;c:\Program Files (x86)\Windows Kits\8.1\Include\um\;c:\Program Files (x86)\Windows Kits\8.1\Include\shared\ not being searched? I already noticed the option to add include directories, but if you correctly parse visual studio projects and MSVC version you should be able to detect this? I did make an extension recently, so i am quite certain you are missing VS default include paths.
2. Forced includes are not considered it seems. Its a visual studio option under C/C++ -> Advanced -> Forced include file.

For both note that propertysheets need to be parsed recursively if you do this via PowerShell. At least in our case we have propertysheets within propertysheets! Yey!

**Comment by cpp-red-lion** [comment]
Hi,
Thanks for the feedback.
For [2] I created a new issue: #39

**Comment by cpp-red-lion** [comment]
For [1] we need some clarifications.
Can you send us a vcxproj file reproducing the issue described ?

**Comment by jcageman** [comment]
The error im getting: 

```
Start Clang Compile

[ INFO ] WILL PROCESS PROJECTS: 
	TidyRepro.vcxproj
[ INFO ] 1. PROCESSING PROJECT D:\src\TidyRepro\TidyRepro\TidyRepro.vcxproj
clang++.exe: warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]
clang++.exe: warning: argument unused during compilation: '-e mit-pch' [-Wunused-command-line-argument]
In file included from D:\src\TidyRepro\TidyRepro\stdafx.h:8:
D:\src\TidyRepro\TidyRepro/targetver.h:8:10: fatal error: 'SDKDDKVer.h' file not found
#include <SDKDDKVer.h>
         ^~~~~~~~~~~~~
1 error generated.
Errors encountered during PCH creation

Done Clang Compile

```

In the end i didn't even need to do anything, this is just the default visual studio template.

[TidyRepro.zip](https://github.com/Caphyon/clang-power-tools/files/1399212/TidyRepro.zip)

**Comment by cpp-red-lion** [comment]
Thanks for the attachment @jcageman. We'll look into it.

**Comment by hero101111** [comment]
[Fixed issue](https://github.com/Caphyon/clang-power-tools/commit/414f60d611e4e3fc53eb0e470e4e7a72e8b4010b)

**Comment by hero101111** [comment]
Issue .2 was also [fixed](https://github.com/Caphyon/clang-power-tools/commit/e70dce4b55f41a8fda90fc776f9eaa9d25868307)
