### ISSUE TITLE
How do I produce the same VSIX as the version from the store?

### ISSUE THREAD

**Issue by mrexodia** [Caphyon/clang-power-tools#341]
Hello,

Currently I'm trying to make some changes to the Powershell script, but if I build the Visual Studio solution it appears to produce a different version of `clang-build.ps1`. From what I can tell some scripts are merged. Is it documented somewhere how to produce the VSIX from the store?

Thanks,

Duncan

**Comment by cpp-red-lion** [comment]
Hi,

I'm afraid the steps for building the VSIX package are not documented on GitHub.
You will need VS2017 for that (with VS Extensibility SDK component) 

![vs ext dev](https://user-images.githubusercontent.com/32536589/40657612-2cc0e386-6351-11e8-8cb9-9b2add4b2305.PNG)

![vs ext sdk](https://user-images.githubusercontent.com/32536589/40657617-3288b456-6351-11e8-9822-b6ffd9e23461.PNG)

**Comment by mrexodia** [comment]
Yeah I use Visual Studio 2017 to compile and it works fine, but clang-format.ps1 is much smaller than the one in the store. I think the included powershell files are put directly in the file but it’s not happening automatically...

**Comment by cpp-red-lion** [comment]
Ah, I see what you mean, now...

We recently refactored the old `clang-build.ps1` file and split it into _several smaller files_.  

These are all located in the [psClang](https://github.com/Caphyon/clang-power-tools/tree/master/ClangPowerTools/ClangPowerTools/psClang) directory. They all have to be included in the VSIX package now.  

Our current version (3.4.2) from the Store still uses the old big standalone PowerShell script.  
The next version (3.5) will be the first to ship the refactored code (currently on `master` branch).

**Comment by mrexodia** [comment]
Ah okay! For now I’ll just manually copy the psClang directory in the vsix
file then :)

**Comment by mrexodia** [comment]
Fixed in #347
