### ISSUE TITLE
Output window keeps stealing focus

### ISSUE THREAD

**Issue by calumr** [Caphyon/clang-power-tools#35]
The `outputWindow.Show` call in OutputManager is forcing focus to the VS output window on every message. For long builds with lots of messages this makes it impossible to do any text editing while clang-power-tools is running.

**Comment by Enache-Ionut** [comment]
If the method is completely removed the user will not have any feedback from the extension if the Output window in closed.  I fixed this by calling the Show() method only when a command begins and ends.

**Comment by calumr** [comment]
Thanks, that's a much better solution. I really love how well this extension is working so far, you've done a great job!
