### ISSUE TITLE
Introduce extra option in menu: Tidy+fix

### ISSUE THREAD

**Issue by mrexodia** [Caphyon/clang-power-tools#352]
Currently you have to toggle the 'fix' option in the settings, however it would be nice to have a separate menu option that enables the fix.

**Comment by cpp-red-lion** [comment]
Hi,

Interesting suggestion. We'll think about it.  
We'll try to find a simple UX solution that improves this workflow.  

Thanks for your feedback 👍

**Comment by Enache-Ionut** [comment]
This issue was solved and it will be available in the next release.
Thank you for your feedback!

**Comment by mrexodia** [comment]
Very nice, I will try it today! Thanks a lot ❤️

**Comment by Enache-Ionut** [comment]
This issue is currently live only for the github repository.
The latest Visual Studio extension (3.6) does not contain the fix. It will be included in the next release.

**Comment by mrexodia** [comment]
I know, but I compiled the extension before 😉

**Comment by cpp-red-lion** [comment]
v3.7 release is imminent... (today)
