### ISSUE TITLE
C project files trigger 'C99 was disabled in PCH file but is currently enabled' error

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#358]
This started in recent weeks. I get error for each file in the project --only in the output, it is not going into the error list. I see no discrepancy in the command line used for pch.

[clang_pch.log](https://github.com/Caphyon/clang-power-tools/files/2102337/clang_pch.log)

other nuances related to pch:
 - in VS my pch is made using 2 forced includes, I suspect cpt only uses the first instead of both/combination (pch.cpp is an empty file)
 - the pch is compiled into the middle of my source tree, I would like to control the temp location (or use the space for intermediate files from the project or the temp folder)
 - it would be great to know how to eliminate the "warning: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated [-Wdeprecated]" 

an unrelated note, page https://caphyon.github.io/clang-power-tools//QaA that comes up for 'more info' in the VS extension manager refers to 5.01 binaries while the main page to 6.0

**Comment by pasa-** [comment]
The problem is actually deeper: the program now ignores the project setting <CompileAs>CompileAsCpp</CompileAs> and issues compilation based on the file extension. This worked fine a few weeks ago.

I worked around for myself by changing the .ps1 script portion
Set-Variable -name kExtensionC               -value ".c"                -option Constant

to .cnnnnnn as I'm never interested in C compile but it should really look at the project setting again.

**Comment by cpp-red-lion** [comment]
Updated Q&A page info to LLVM 6.0 ✔️

**Comment by pasa-** [comment]
Project demonstrating the problem.  The original PCH report is just effect of using the incorrect mode.

[cpt1.zip](https://github.com/Caphyon/clang-power-tools/files/2117094/cpt1.zip)

**Comment by hero101111** [comment]
We've reproduced the issue and are working on a fix for the next release of **ClangPowerTools**.

Regarding the `warning: treating 'c-header' input as 'c++-header` message, we've tried to get around it but haven't had any success. Seems to be an oddity of `clang++.exe`.
