### ISSUE TITLE
Clang Tidy does not behave as expected when Treat additional includes = include directories

### ISSUE THREAD

**Issue by matthew-dews** [Caphyon/clang-power-tools#364]
I am running Clang Power Tools 3.6 in VS 2015. With the option "Treat additional includes as" set to "include directories" running Clang Tidy does not behave how it is configured. I suspect Visual Studio is caching something in a weird way which I haven't figured out how to clear yet.

For example I have the following configuration:
- "Treat additional includes as" set to "include directories"
- "Continue on error" is checked (necessary for the tool to even work in the first place).
- "Fix" is checked in the Tidy - General config
-  "Use checks from" is set to "custom checks"
- The only custom check specified is "modernize-use-override"

When I run Clang Tidy in this configuration it runs as if it were doing "modernize-use-override" and no fixes are applied.
I noticed this after running Clang Tidy on an entire solution (approx 20 projects). I can't provide this project as an example but on a smaller test project I made for this I Have a similar issue.

On the smaller project:
- Fix checked
- Custom check of just "modernize-use-override"

When I run Clang Tidy on this smaller project it properly identifies a case where "modernize-use-override" should be triggered but does not fix it. Looking at the verbose output I can see the -fix flag is not present!

I've tried the following to clear the settings, with no success:
- Repair Visual Studio

and

- Uninstall Clang Power Tools
- Restart Visual Studio
- Install Clang Power Tools

and

- Uninstall Clang Power Tools
- Restart VS
- Reset all user settings
- Install Clang Power Tools

Is there a way to purge all settings related to Clang Power Tools? It feels like there's some setting being cached somewhere. It's possible I had two instances of VS open and I edited the settings in one instance which mucked things up.

EDIT:
Additional tidbit: Checking Fix in Tidy-General menu, after clicking OK in the settings dialog then restarting VS and reopening the same solution the Fix box is unchecked. Doing this a second time and the setting sticks.

**Comment by cpp-red-lion** [comment]
Hi,

I'm not exactly sure what is happening there...  

You can reset all _Clang Power Tools_ settings, by deleting all config files in this folder:  
`%AppData%\ClangPowerTools`  
(close Visual Studio first)  

If the problem persists after _reset_, please attach that simple test project, so we can reproduce the issue.

Thanks.

**Comment by matthew-dews** [comment]
I deleted all the files in the folder as you asked. When I started up the big project up again the Fix checkbox wouldn't set until after a few restarts. After that I had no issues. 

My test solution:
[ClangTidyTest.zip](https://github.com/Caphyon/clang-power-tools/files/2120695/ClangTidyTest.zip)

I can reproduce this issue as follows:
1. Delete the files in `%AppData%\ClangPowerTools`
2. Open test .sln file (I suspect this will work with any project)
- Open `Clang Power Tools - Tidy`  settings menu
  - Check the Fix checkbox
  - Set `Use checks from` to `custom checks`
  - In Custom Checks add `modernize-use-override`
  - Click OK to save changes
- Open Settings again and observe the changes remain in the UI
- Close Visual Studio
- Open `%AppData%\ClangPowerTools\TidyOptionsConfiguration.config`
  - Observe the tag `<Fix>false</Fix>`. This is not what I would expect
  - Close the file
3. Open the test solution again
- Open `Clang Power Tools - Tidy` settings menu
  - Observe that the Fix checkbox is not checked
  - Observe that `Custom Checks` is what we set
  - Click OK to save changes
- Close Visual Studio
- Open `%AppData%\ClangPowerTools\TidyOptionsConfiguration.config`
  - Observe the tag `<Fix>false</Fix>`. This is still not what I would expect
  - Close the file
4. Repeat the steps in 3 until the Fix box is checked when opening the settings. I had to open and close Visual Studio 3 times in total before the Fix box was checked on start.

More about my environment in case it's helpful:
- Windows 10 Enterprise 1703 64-bit
- Visual Studio 2015 Update 3
- Clang Power Tools v3.6.0

**Comment by cpp-red-lion** [comment]
Hi,

Thanks for the detailed info on reproducing this issue 👍 

We'll investigate it ASAP and update this thread when we have news.
Stay tuned.

**Comment by Enache-Ionut** [comment]
Hi,

This issue was fixed and it is available in the new [version v3.7](https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools) just released. From now the Clang Tidy-Fix action has a dedicated command in our toolbar and context menu.

Thank you for your feedback!

![toolbar](https://user-images.githubusercontent.com/10616921/42263003-819e2702-7f75-11e8-84fc-f4b56ddd05e9.PNG)

![contextmenu](https://user-images.githubusercontent.com/10616921/42263008-83e3a000-7f75-11e8-8ba9-819946b7ed7f.PNG)
