### ISSUE TITLE
Automatically detect target platform (set -m32 for 32 bit builds)

### ISSUE THREAD

**Issue by MarcelNehring** [Caphyon/clang-power-tools#380]
When the target platform in Visual Studio is set to `Win32` power tools do not automatically add parameter `-m32` to tell clang it should target a 32 bit system. I can manually add it in the options dialog and thus successfully run clang to target 32 bit. Could this be automated? I.e. could power tools add `-m32` automatically depending on the platform setting in visual studio?

Related: #322

**Comment by cpp-red-lion** [comment]
Hi,

Good suggestion 👍 
Thanks for your feedback.

We'll update this thread when progress is made...

**Comment by hero101111** [comment]
We've added this detection to the next release of Clang Power Tools, `4.0`; to be released soon.
