### ISSUE TITLE
Cannot find given project

### ISSUE THREAD

**Issue by abhatter** [Caphyon/clang-power-tools#381]
Getting an error:
Cannot find given project

when running clang tidy on file within a project.
Verbose build spits output:

Solution file paths:
    C:\myProject\myProject.sln
Source Directory: C:\myProject\
Found 0 projects

The projects contained within this solution are in C:\myProject\<subfolder>\<subfolder>\

Any suggestions?

Thanks

**Comment by Enache-Ionut** [comment]
Hi, 

This issue was fixed and it will be available in the next release v3.9.
Thank you for your feedback!
