### ISSUE TITLE
Clang TidyFix removed way to much code.

### ISSUE THREAD

**Issue by schultztom** [Caphyon/clang-power-tools#384]
I'm not sure if this belongs here or should be addressed directly to clang-tidy. But i got a surprise when i ran clang-tidy on a project i'm working on. It seems that Tidy removed a chunk of my business logic while performing a fixup "redundant boolean literal in conditional return statement", [readability-simplify-boolean-expr]

Here is the LOG:
10: C:\Repository\###\BaseInstance.cpp
2860 warnings and 1 error generated.
Error while processing C:\Repository\###\BaseInstance.cpp.
C:\Repository\###\..\..\source\code\include\###/lib/stdafx.h(26): error [clang-diagnostic-error]: '###/logging/facade/logger.h' file not found 
#include <###core/logging/facade/logger.h>
         ^
C:\Repository\###\BaseInstance.cpp(27): warning [modernize-use-equals-default]: use '= default' to define a trivial default constructor 
BaseInstance::BaseInstance()
              ^
C:\Repository\###\BaseInstance.cpp(39): warning [google-readability-todo]: missing username/bug in TODO 
        //TODO do stuff here.
        ^~~~~~~~~~~~~~~~~~~~~
        // TODO(###): do stuff here.
C:\Repository\###\BaseInstance.cpp(39): message: FIX-IT applied suggested code changes
C:\Repository\###\BaseInstance.cpp(40): warning [readability-simplify-boolean-expr]: redundant boolean literal in conditional return statement 
        return true;
               ^
C:\Repository\###\BaseInstance.cpp(84): warning [readability-simplify-boolean-expr]: redundant boolean literal in conditional return statement 
        return true;
~~~~~~~~~~~~~~~^~~~~
C:\Repository\###\BaseInstance.cpp(79): message: FIX-IT applied suggested code changes
    if (it != m_Storage.end())
    ^
clang-tidy applied 2 of 2 suggested fixes.

And this is the DIFF:
--- a/source/code/src/KcsAggregator-Lib/BaseInstance.cpp
+++ b/source/code/src/KcsAggregator-Lib/BaseInstance.cpp
@@ -36,7 +36,7 @@ bool BaseInstance::RegisterDataValueBinding(
     const auto it = m_Storage.find(elementId);
     if (it != m_Storage.end())
     {
-        //TODO do stuff here.
+        // TODO(###): do stuff here.
         return true;
     }
     return false;
@@ -76,14 +76,7 @@ bool BaseInstance::GetDataValue(
 {
     const ElementId subId (0, TupleNumeric(0, elementId.GetSubId()));
     const auto it = m_Storage.find(subId);
-    if (it != m_Storage.end())
-    {
-        value = DataValue(it->second,
-                            AttributeType::Value,
-                            SystemTime::GetSystemTime());
-        return true;
-    }
-    return false;
+    return ;
 }

**Comment by cpp-red-lion** [comment]
Hi,

Thank you for your interest in _Clang Power Tools_  

Unfortunately, we cannot help you with this issue, as it is related to `clang-tidy` itself.  
You should file a bug report here: https://bugs.llvm.org/
