### ISSUE TITLE
clang power tools does not include nuget packages 

### ISSUE THREAD

**Issue by schultztom** [Caphyon/clang-power-tools#386]
I'm trying Clang power tools version 3.7.1, and it seems to be unable to include the nuget packages that my project is dependent on. I get compilation errors that the files are not found.
.

**Comment by hero101111** [comment]
Hello,

We're gonna need additional information, what nuget package(s), VS version ,etc.
A sample project would help us as well.

**Comment by hero101111** [comment]
Cannot reproduce. Our test nuget packages work fine.
