### ISSUE TITLE
Add support for force includes

### ISSUE THREAD

**Issue by cpp-red-lion** [Caphyon/clang-power-tools#39]
-include <filename>
Adds an implicit #include into the predefines buffer which is read before the source file is pre-processed.
Translate MSVC flag /FI to clang++ -include

**Comment by cpp-red-lion** [comment]
Suggested by @jcageman

**Comment by hero101111** [comment]
[This issue was fixed](https://github.com/Caphyon/clang-power-tools/commit/e70dce4b55f41a8fda90fc776f9eaa9d25868307)
