### ISSUE TITLE
Invoking any of the clang tools from the Clang Power Tools menu/buttons do nothing

### ISSUE THREAD

**Issue by misuo** [Caphyon/clang-power-tools#412]
When invoking e.g. **Compile (syntax-only)** the Visual Studio output window only shows **Done Clang Compile** but no errors or anything other output, e.g. if having C++ syntax errors in the source file or if **Verbose mode** setting is checked.

Same with **Tidy** - and **Clang Format** does not output anything!

![image](https://user-images.githubusercontent.com/21021375/44552547-f115c180-a72a-11e8-8995-4c20c7b92f7c.png)

Source file is a very simple test `.cpp`:

```
int main()
{
      int * p = 0; // clang-tidy should convert to nullptr, clang-format should indent

  p = 0.0  // ; missing! error

  return p == 0 ? 1 : 0;
}
```

Any idea what could be wrong of what I'm missing?

I'm using/installed:

- Visual Studio 2017 15.7.3
- Clang Power Tools 3.9.1 
- LLVM 6.0.1 (64-bit)
- PATH environment variable do include path to the executables `C:\Program Files\LLVM\bin`. When running in command prompt, these run just fine.

**Comment by netx123** [comment]
I can replicate this same behaviour only when Visual Studio is editing a single .cpp source file.
If you have a solution open in VS which contains the test .cpp file then Clang Power Tools works as expected.

**Comment by Enache-Ionut** [comment]
Hi,

As @netx123  said if you will include your .cpp file inside of a project then Clang Power Tools will work perfectly. Visual Studio has the same behavior for this kind of files. You need to create a new project every time when you want to try a piece of code as above or you need to include your file inside of an existing Visual Studio project.

Regards,
Ionut
