### ISSUE TITLE
clang-tidy is not using Include directories correctly

### ISSUE THREAD

**Issue by monamimani** [Caphyon/clang-power-tools#419]
I am using the c++ version of vulkan.h, vulkan.hpp
In there the class vk::device has an implicit conversion operator from vk::Device to VkDevice.

My code compiles fine without error or warning with visual studio, but it seems clang is not seeing the include directory of Vulkan.

Maybe it is an environment issue? I am including the path to the Vulkan SDK like this $(VULKAN_SDK)\Include in the Include Directories of the VC++ Directories of the project properties.

> Start Clang Tidy
> 
> PROJECTS:
>   D:\_Dev\Playground\VulkanTriangleApp\VkHal\VkHal.vcxproj
> PROJECT: D:\_Dev\Playground\VulkanTriangleApp\VkHal\VkHal.vcxproj
> 1: D:\_Dev\Playground\VulkanTriangleApp\VkHal\srcs\VkHal\VkRenderer.cpp
> 6 warnings and 12 errors generated.
> Error while processing D:\_Dev\Playground\VulkanTriangleApp\VkHal\srcs\VkHal\VkRenderer.cpp.
> D:\_Dev\Playground\VulkanTriangleApp\VkHal\srcs\VkHal/VkDebugReport.h(73): error: no viable conversion from 'const vk::Device' to 'VkDevice' (aka 'VkDevice_T *') [clang-diagnostic-error]
>   vkCheck(m_setObjectNameFct(device, reinterpret_cast<VkDebugUtilsObjectNameInfoEXT*>(&nameInfo)));

I also have other includes in the Include Directories and they are fine. the env var is the only thing i can see that would be different.

**Comment by hero101111** [comment]
Environment variables should be taken into account. Not sure what happening here...
Please activate `Verbose mode` and look in the verbose log for detected _Include Directories_.

**Comment by monamimani** [comment]
Thanks, I had actually multiple issues. First I had 2 version of LLVM and the wrong one was being used. 
Then, clang was complaining about ambiguous overload. It was a situation where probably clang is right but still, the code worked.
Anyway thanks!
