### ISSUE TITLE
Provide an option to disable opening of changed files

### ISSUE THREAD

**Issue by PeterFeicht** [Caphyon/clang-power-tools#420]
Clang Power Tools registers a listener for file changes in a project when `clang-tidy` is run to open changed files, which stays active even after it's finished.

Please provide an option to disable this listener completely (I really don't want random changes popping up VS when I'm working somewhere else), and maybe also fix it so the listener gets unregistered after `clang-tidy` has finished running.

**Comment by Enache-Ionut** [comment]
We have fixed this issues. The fix will be available in Clang Power Tools v4.0.

Thank you for your feedback!
