### ISSUE TITLE
"\..\" in paths incorrectly escaped

### ISSUE THREAD

**Issue by gerboengels** [Caphyon/clang-power-tools#426]
I have an include path `"foo\..\bar"`. In `Run-ClangJobs`, the backslashes are escaped, so it yields `"foo\\..\\bar"`. However, commit 273473b7f96301a4289e64aecea435e2de276f6c broke this: now it is escaped to `"foo\..\\bar"`. Now my include directory's are not found.

A fix which works for me, is changing
```
# make sure escaped double quotes are not messed up
$clangConfigContent = $clangConfigContent -replace '\\([a-zA-Z0-9_/\-\\])', '\\$1'
```
to
```
# make sure escaped double quotes are not messed up
$clangConfigContent = $clangConfigContent -replace '\\([^"])', '\\$1'
```
So to actually do what the comment says.
Alternatively, changing the regex to `'\\([a-zA-Z0-9_/\-\\\.])'` would also work, but might miss other cornercases.

**Comment by hero101111** [comment]
Thank you for your feedback. We'll include your fix in the next release (`v4.1`).
