### ISSUE TITLE
Angle brackets in preprocessor defines don't work properly

### ISSUE THREAD

**Issue by Keshi** [Caphyon/clang-power-tools#428]
If you have a project level preprocessor define such as `ABC=<XYZ>`, clang power tools doesn't appear to pass that to the preprocessor properly.  The output of the compile error resulting from that will say `-lt XYZ -gt` which is obviously incorrect

**Comment by hero101111** [comment]
Indeed, this is an bug of the latest release (`v4.0`); thank you for reporting it. 
We'll fix the issue and release an updated ClangPowerTools version as soon as possible.

**Comment by Keshi** [comment]
It seems that `ABC="XYZ"` is also bugged, as it results in `""XYZ""`

**Comment by hero101111** [comment]
We've looked into it and indeed it is. The next release (`v4.1`) will address both these issues.
