### ISSUE TITLE
Cannot locate Visual Studio 2015

### ISSUE THREAD

**Issue by ChristofferLindmark** [Caphyon/clang-power-tools#437]
I've had this bug in a couple of versions now, which makes me unable to use this tool.

It cannot find VS2015. I have VS2013 installed too, so maybe that is causing some trouble.

Cannot locate Visual Studio location
At C:\Users\Choffe\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\mwqoovi4.psr\psClang\visualstudio-detection.ps1
:100 char:9
+         throw "Cannot locate Visual Studio location"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot locate Visual Studio location:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot locate Visual Studio location
 

Done Clang Tidy

**Comment by hero101111** [comment]
Please attach a full verbose log. It will help us in investigating the issue.

**Comment by ChristofferLindmark** [comment]
Start Clang Tidy

VERBOSE: clang-build.ps1 invocation args: 
  aVcxprojToCompile = F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj 
  aCppToCompile = F:\SubversionC\source\Sound Installer\InstallerApp.cpp 
  aVcxprojConfigPlatform = Debug|Win32 
  aClangCompileFlags = -Werror -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste 
-Wno-unknown-pragmas -Wno-unused-value 
  aContinueOnError = True 
  Verbose = True 
  aTidyFlags = 
-*,google-readability-casting,google-readability-function-size,google-readability-namespace-comments,google-readability
-redundant-smartptr-get,modernize-avoid-bind,modernize-deprecated-headers,modernize-loop-convert,modernize-make-shared,
modernize-make-unique,modernize-raw-string-literal,modernize-redundant-void-arg,modernize-replace-auto-ptr,modernize-re
place-random-shuffle,modernize-shrink-to-fit,modernize-unary-static-assert,modernize-use-bool-literals,modernize-use-de
fault-member-init,modernize-use-emplace,modernize-use-equals-delete,modernize-use-noexcept,modernize-use-nullptr,modern
ize-use-transparent-functors,modernize-use-using,readability-avoid-const-params-in-decls,readability-container-size-emp
ty,readability-deleted-default,readability-delete-null-pointer,readability-else-after-return,readability-function-size,
readability-identifier-naming,readability-implicit-bool-cast,readability-inconsistent-declaration-parameter-name,readab
ility-misleading-indentation,readability-misplaced-array-index,readability-named-parameter,readability-non-const-parame
ter,readability-redundant-control-flow,readability-redundant-declaration,readability-redundant-function-ptr-dereference
,readability-redundant-member-init,readability-redundant-smartptr-get,readability-redundant-string-cstr,readability-red
undant-string-init,readability-simplify-boolean-expr,readability-static-definition-in-anonymous-namespace,readability-u
niqueptr-delete-release 
  aTidyHeaderFilter = .* 
  aVisualStudioVersion = 2015 
  aVisualStudioSku = Professional 
  aSolutionsPath = F:\SubversionC\Projects\Sound Installer\Win\Installer.sln 
VERBOSE: CPU logical core count: 8
VERBOSE: Scanning for solution files
VERBOSE: Solution file paths:
VERBOSE:   F:\SubversionC\Projects\Sound Installer\Win\Installer.sln
VERBOSE: 
VERBOSE: Source directory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: Scanning for project files
VERBOSE: Found 1 projects
VERBOSE: PROCESSING ALL PROJECTS
PROJECT: F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: Deleting variables initialized by previous project:
VERBOSE: 
VERBOSE: Importing environment variables into current scope
VERBOSE: SET_VAR ALLUSERSPROFILE: C:\ProgramData
VERBOSE: SET_VAR APPDATA: C:\Users\Choffe\AppData\Roaming
VERBOSE: SET_VAR CommonProgramFiles: C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramW6432: C:\Program Files\Common Files
VERBOSE: SET_VAR COMPUTERNAME: CHOFFBAR
VERBOSE: SET_VAR ComSpec: C:\WINDOWS\system32\cmd.exe
VERBOSE: SET_VAR DriverData: C:\Windows\System32\Drivers\DriverData
VERBOSE: SET_VAR FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
VERBOSE: SET_VAR FPS_BROWSER_USER_PROFILE_STRING: Default
VERBOSE: SET_VAR HOMEDRIVE: C:
VERBOSE: SET_VAR HOMEPATH: \Users\Choffe
VERBOSE: SET_VAR LOCALAPPDATA: C:\Users\Choffe\AppData\Local
VERBOSE: SET_VAR LOGONSERVER: \\CHOFFBAR
VERBOSE: SET_VAR MSBuildLoadMicrosoftTargetsReadOnly: true
VERBOSE: SET_VAR NUMBER_OF_PROCESSORS: 8
VERBOSE: SET_VAR OneDrive: C:\Users\Choffe\OneDrive
VERBOSE: SET_VAR OS: Windows_NT
VERBOSE: SET_VAR Path: 
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Choffe\.dn
x\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance 
Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\nodejs\;C:\Program 
Files\Git\cmd;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft 
SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\NVIDIA 
Corporation\PhysX\Common;C:\Program Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak 
Detector\bin\Win64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files\TortoiseSVN\bin;C:\Program Files\LLVM\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files 
(x86)\VisualSVN\bin;C:\Users\Choffe\AppData\Local\Microsoft\WindowsApps;C:\Users\Choffe\AppData\Roaming\npm;
VERBOSE: SET_VAR PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
VERBOSE: SET_VAR PkgDefApplicationConfigFile: C:\Users\Choffe\AppData\Local\Temp\devFD33.tmp
VERBOSE: SET_VAR PROCESSOR_ARCHITECTURE: x86
VERBOSE: SET_VAR PROCESSOR_ARCHITEW6432: AMD64
VERBOSE: SET_VAR PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
VERBOSE: SET_VAR PROCESSOR_LEVEL: 6
VERBOSE: SET_VAR PROCESSOR_REVISION: 5e03
VERBOSE: SET_VAR ProgramData: C:\ProgramData
VERBOSE: SET_VAR ProgramFiles: C:\Program Files (x86)
VERBOSE: SET_VAR ProgramFiles(x86): C:\Program Files (x86)
VERBOSE: SET_VAR ProgramW6432: C:\Program Files
VERBOSE: SET_VAR PSExecutionPolicyPreference: Bypass
VERBOSE: SET_VAR PSModulePath: C:\Program 
Files\WindowsPowerShell\Modules;C:\Users\Choffe\Documents\WindowsPowerShell\Modules;C:\Program Files 
(x86)\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
VERBOSE: SET_VAR PUBLIC: C:\Users\Public
VERBOSE: SET_VAR SESSIONNAME: Console
VERBOSE: SET_VAR SystemDrive: C:
VERBOSE: SET_VAR SystemRoot: C:\WINDOWS
VERBOSE: SET_VAR TEMP: C:\Users\Choffe\AppData\Local\Temp
VERBOSE: SET_VAR TMP: C:\Users\Choffe\AppData\Local\Temp
VERBOSE: SET_VAR USERDOMAIN: CHOFFBAR
VERBOSE: SET_VAR USERDOMAIN_ROAMINGPROFILE: CHOFFBAR
VERBOSE: SET_VAR USERNAME: Choffe
VERBOSE: SET_VAR USERPROFILE: C:\Users\Choffe
VERBOSE: SET_VAR windir: C:\WINDOWS
VERBOSE: SET_VAR VisualStudioDir: C:\Users\Choffe\Documents\Visual Studio 2015
VERBOSE: SET_VAR VisualStudioEdition: Microsoft Visual Studio Professional 2015
VERBOSE: SET_VAR VisualStudioVersion: 14.0
VERBOSE: SET_VAR VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VERBOSE: SET_VAR VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VERBOSE: SET_VAR VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VERBOSE: SET_VAR VSLANG: 1033
VERBOSE: SET_VAR VSSDK140Install: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
VERBOSE: SET_VAR XTC_IDE: 1698a6a6c25a4bb0a2c93f1aeea430eb
VERBOSE: SET_VAR MSBuildProjectFullPath: F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR ProjectDir: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR MSBuildProjectExtension: .vcxproj
VERBOSE: SET_VAR MSBuildProjectFile: InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildProjectName: InstallerApp
VERBOSE: SET_VAR MSBuildProjectDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR MSBuildProgramFiles32: C:\Program Files (x86)
VERBOSE: SET_VAR ProjectName: InstallerApp
VERBOSE: SET_VAR TargetName: InstallerApp
VERBOSE: SET_VAR VisualStudioVersion: 14.0
VERBOSE: SET_VAR MSBuildToolsVersion: 14.0
VERBOSE: SET_VAR SolutionDir: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR SolutionName: Installer
VERBOSE: 
Sanitizing F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: InstallerApp
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR Configuration: Debug
VERBOSE: SET_VAR Platform: Win32
VERBOSE: SET_VAR ProjectGuid: {AE7BA814-C099-4ACF-A817-C2CE2B8F7097}
VERBOSE: SET_VAR RootNamespace: InstallerApp
VERBOSE: SET_VAR WindowsTargetPlatformVersion: 8.1
VERBOSE: Could not find property sheet \Microsoft.Cpp.Default.props
VERBOSE: SET_VAR ConfigurationType: Application
VERBOSE: SET_VAR PlatformToolset: v120_xp
VERBOSE: SET_VAR UseOfMfc: false
VERBOSE: Could not find property sheet \Microsoft.Cpp.props
VERBOSE: Property sheet: F:\SubversionC\Projects\Sound Installer\Win\SoundInstaller.props
VERBOSE: 
Sanitizing F:\SubversionC\Projects\Sound Installer\Win\SoundInstaller.props
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\SoundInstaller.props
VERBOSE: SET_VAR MSBuildThisFileExtension: .props
VERBOSE: SET_VAR MSBuildThisFile: SoundInstaller.props
VERBOSE: SET_VAR MSBuildThisFileName: SoundInstaller
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR _ProjectFileVersion: 14.0.25431.1
VERBOSE: SET_VAR OutDir: \DebugOutput\
VERBOSE: SET_VAR IntDir: \Debug\
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: InstallerApp
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: Property sheet: F:\SubversionC\Projects\Sound Installer\Win\TTSI_Version.props
VERBOSE: 
Sanitizing F:\SubversionC\Projects\Sound Installer\Win\TTSI_Version.props
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\TTSI_Version.props
VERBOSE: SET_VAR MSBuildThisFileExtension: .props
VERBOSE: SET_VAR MSBuildThisFile: TTSI_Version.props
VERBOSE: SET_VAR MSBuildThisFileName: TTSI_Version
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: InstallerApp
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR _ProjectFileVersion: 14.0.25431.1
VERBOSE: SET_VAR LinkIncremental: true
VERBOSE: SET_VAR TargetName: Installer
VERBOSE: Could not find property sheet \Microsoft.Cpp.targets
VERBOSE: Platform toolset: v120_xp
VERBOSE: Switching to default VsVer because of toolset. Reloading project...
VERBOSE: Deleting variables initialized by previous project:
VERBOSE:   ALLUSERSPROFILE
VERBOSE:   APPDATA
VERBOSE:   CommonProgramFiles
VERBOSE:   CommonProgramFiles(x86)
VERBOSE:   CommonProgramW6432
VERBOSE:   COMPUTERNAME
VERBOSE:   ComSpec
VERBOSE:   DriverData
VERBOSE:   FPS_BROWSER_APP_PROFILE_STRING
VERBOSE:   FPS_BROWSER_USER_PROFILE_STRING
VERBOSE:   HOMEDRIVE
VERBOSE:   HOMEPATH
VERBOSE:   LOCALAPPDATA
VERBOSE:   LOGONSERVER
VERBOSE:   MSBuildLoadMicrosoftTargetsReadOnly
VERBOSE:   NUMBER_OF_PROCESSORS
VERBOSE:   OneDrive
VERBOSE:   OS
VERBOSE:   Path
VERBOSE:   PATHEXT
VERBOSE:   PkgDefApplicationConfigFile
VERBOSE:   PROCESSOR_ARCHITECTURE
VERBOSE:   PROCESSOR_ARCHITEW6432
VERBOSE:   PROCESSOR_IDENTIFIER
VERBOSE:   PROCESSOR_LEVEL
VERBOSE:   PROCESSOR_REVISION
VERBOSE:   ProgramData
VERBOSE:   ProgramFiles
VERBOSE:   ProgramFiles(x86)
VERBOSE:   ProgramW6432
VERBOSE:   PSExecutionPolicyPreference
VERBOSE:   PSModulePath
VERBOSE:   PUBLIC
VERBOSE:   SESSIONNAME
VERBOSE:   SystemDrive
VERBOSE:   SystemRoot
VERBOSE:   TEMP
VERBOSE:   TMP
VERBOSE:   USERDOMAIN
VERBOSE:   USERDOMAIN_ROAMINGPROFILE
VERBOSE:   USERNAME
VERBOSE:   USERPROFILE
VERBOSE:   windir
VERBOSE:   VisualStudioDir
VERBOSE:   VisualStudioEdition
VERBOSE:   VisualStudioVersion
VERBOSE:   VS110COMNTOOLS
VERBOSE:   VS120COMNTOOLS
VERBOSE:   VS140COMNTOOLS
VERBOSE:   VSLANG
VERBOSE:   VSSDK140Install
VERBOSE:   XTC_IDE
VERBOSE:   MSBuildProjectFullPath
VERBOSE:   ProjectDir
VERBOSE:   MSBuildProjectExtension
VERBOSE:   MSBuildProjectFile
VERBOSE:   MSBuildProjectName
VERBOSE:   MSBuildProjectDirectory
VERBOSE:   MSBuildProgramFiles32
VERBOSE:   ProjectName
VERBOSE:   TargetName
VERBOSE:   MSBuildToolsVersion
VERBOSE:   SolutionDir
VERBOSE:   SolutionName
VERBOSE:   MSBuildThisFileFullPath
VERBOSE:   MSBuildThisFileExtension
VERBOSE:   MSBuildThisFile
VERBOSE:   MSBuildThisFileName
VERBOSE:   MSBuildThisFileDirectory
VERBOSE:   Configuration
VERBOSE:   Platform
VERBOSE:   ProjectGuid
VERBOSE:   RootNamespace
VERBOSE:   WindowsTargetPlatformVersion
VERBOSE:   ConfigurationType
VERBOSE:   PlatformToolset
VERBOSE:   UseOfMfc
VERBOSE:   _ProjectFileVersion
VERBOSE:   OutDir
VERBOSE:   IntDir
VERBOSE:   LinkIncremental
VERBOSE: 
VERBOSE: Importing environment variables into current scope
VERBOSE: SET_VAR ALLUSERSPROFILE: C:\ProgramData
VERBOSE: SET_VAR APPDATA: C:\Users\Choffe\AppData\Roaming
VERBOSE: SET_VAR CommonProgramFiles: C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramW6432: C:\Program Files\Common Files
VERBOSE: SET_VAR COMPUTERNAME: CHOFFBAR
VERBOSE: SET_VAR ComSpec: C:\WINDOWS\system32\cmd.exe
VERBOSE: SET_VAR DriverData: C:\Windows\System32\Drivers\DriverData
VERBOSE: SET_VAR FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
VERBOSE: SET_VAR FPS_BROWSER_USER_PROFILE_STRING: Default
VERBOSE: SET_VAR HOMEDRIVE: C:
VERBOSE: SET_VAR HOMEPATH: \Users\Choffe
VERBOSE: SET_VAR LOCALAPPDATA: C:\Users\Choffe\AppData\Local
VERBOSE: SET_VAR LOGONSERVER: \\CHOFFBAR
VERBOSE: SET_VAR MSBuildLoadMicrosoftTargetsReadOnly: true
VERBOSE: SET_VAR NUMBER_OF_PROCESSORS: 8
VERBOSE: SET_VAR OneDrive: C:\Users\Choffe\OneDrive
VERBOSE: SET_VAR OS: Windows_NT
VERBOSE: SET_VAR Path: 
C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Users\Choffe\.dn
x\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance 
Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\nodejs\;C:\Program 
Files\Git\cmd;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft 
SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\NVIDIA 
Corporation\PhysX\Common;C:\Program Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak 
Detector\bin\Win64;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;
C:\Program Files\TortoiseSVN\bin;C:\Program Files\LLVM\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files 
(x86)\VisualSVN\bin;C:\Users\Choffe\AppData\Local\Microsoft\WindowsApps;C:\Users\Choffe\AppData\Roaming\npm;
VERBOSE: SET_VAR PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
VERBOSE: SET_VAR PkgDefApplicationConfigFile: C:\Users\Choffe\AppData\Local\Temp\devFD33.tmp
VERBOSE: SET_VAR PROCESSOR_ARCHITECTURE: x86
VERBOSE: SET_VAR PROCESSOR_ARCHITEW6432: AMD64
VERBOSE: SET_VAR PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
VERBOSE: SET_VAR PROCESSOR_LEVEL: 6
VERBOSE: SET_VAR PROCESSOR_REVISION: 5e03
VERBOSE: SET_VAR ProgramData: C:\ProgramData
VERBOSE: SET_VAR ProgramFiles: C:\Program Files (x86)
VERBOSE: SET_VAR ProgramFiles(x86): C:\Program Files (x86)
VERBOSE: SET_VAR ProgramW6432: C:\Program Files
VERBOSE: SET_VAR PSExecutionPolicyPreference: Bypass
VERBOSE: SET_VAR PSModulePath: C:\Program 
Files\WindowsPowerShell\Modules;C:\Users\Choffe\Documents\WindowsPowerShell\Modules;C:\Program Files 
(x86)\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
VERBOSE: SET_VAR PUBLIC: C:\Users\Public
VERBOSE: SET_VAR SESSIONNAME: Console
VERBOSE: SET_VAR SystemDrive: C:
VERBOSE: SET_VAR SystemRoot: C:\WINDOWS
VERBOSE: SET_VAR TEMP: C:\Users\Choffe\AppData\Local\Temp
VERBOSE: SET_VAR TMP: C:\Users\Choffe\AppData\Local\Temp
VERBOSE: SET_VAR USERDOMAIN: CHOFFBAR
VERBOSE: SET_VAR USERDOMAIN_ROAMINGPROFILE: CHOFFBAR
VERBOSE: SET_VAR USERNAME: Choffe
VERBOSE: SET_VAR USERPROFILE: C:\Users\Choffe
VERBOSE: SET_VAR windir: C:\WINDOWS
VERBOSE: SET_VAR VisualStudioDir: C:\Users\Choffe\Documents\Visual Studio 2015
VERBOSE: SET_VAR VisualStudioEdition: Microsoft Visual Studio Professional 2015
VERBOSE: SET_VAR VisualStudioVersion: 14.0
VERBOSE: SET_VAR VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VERBOSE: SET_VAR VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VERBOSE: SET_VAR VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VERBOSE: SET_VAR VSLANG: 1033
VERBOSE: SET_VAR VSSDK140Install: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VSSDK\
VERBOSE: SET_VAR XTC_IDE: 1698a6a6c25a4bb0a2c93f1aeea430eb
VERBOSE: SET_VAR MSBuildProjectFullPath: F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR ProjectDir: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR MSBuildProjectExtension: .vcxproj
VERBOSE: SET_VAR MSBuildProjectFile: InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildProjectName: InstallerApp
VERBOSE: SET_VAR MSBuildProjectDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR MSBuildProgramFiles32: C:\Program Files (x86)
VERBOSE: SET_VAR ProjectName: InstallerApp
VERBOSE: SET_VAR TargetName: InstallerApp
VERBOSE: SET_VAR VisualStudioVersion: 15.0
VERBOSE: SET_VAR MSBuildToolsVersion: 15.0
VERBOSE: SET_VAR SolutionDir: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR SolutionName: Installer
VERBOSE: 
Sanitizing F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: InstallerApp
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR Configuration: Debug
VERBOSE: SET_VAR Platform: Win32
VERBOSE: SET_VAR ProjectGuid: {AE7BA814-C099-4ACF-A817-C2CE2B8F7097}
VERBOSE: SET_VAR RootNamespace: InstallerApp
VERBOSE: SET_VAR WindowsTargetPlatformVersion: 8.1
VERBOSE: Could not find property sheet \Microsoft.Cpp.Default.props
VERBOSE: SET_VAR ConfigurationType: Application
VERBOSE: SET_VAR PlatformToolset: v120_xp
VERBOSE: SET_VAR UseOfMfc: false
VERBOSE: Could not find property sheet \Microsoft.Cpp.props
VERBOSE: Property sheet: F:\SubversionC\Projects\Sound Installer\Win\SoundInstaller.props
VERBOSE: 
Sanitizing F:\SubversionC\Projects\Sound Installer\Win\SoundInstaller.props
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\SoundInstaller.props
VERBOSE: SET_VAR MSBuildThisFileExtension: .props
VERBOSE: SET_VAR MSBuildThisFile: SoundInstaller.props
VERBOSE: SET_VAR MSBuildThisFileName: SoundInstaller
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR _ProjectFileVersion: 14.0.25431.1
VERBOSE: SET_VAR OutDir: \DebugOutput\
VERBOSE: SET_VAR IntDir: \Debug\
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: InstallerApp
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: Property sheet: F:\SubversionC\Projects\Sound Installer\Win\TTSI_Version.props
VERBOSE: 
Sanitizing F:\SubversionC\Projects\Sound Installer\Win\TTSI_Version.props
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\TTSI_Version.props
VERBOSE: SET_VAR MSBuildThisFileExtension: .props
VERBOSE: SET_VAR MSBuildThisFile: TTSI_Version.props
VERBOSE: SET_VAR MSBuildThisFileName: TTSI_Version
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\SubversionC\Projects\Sound Installer\Win\InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: InstallerApp.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: InstallerApp
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\SubversionC\Projects\Sound Installer\Win\
VERBOSE: SET_VAR _ProjectFileVersion: 14.0.25431.1
VERBOSE: SET_VAR LinkIncremental: true
VERBOSE: SET_VAR TargetName: Installer
VERBOSE: Could not find property sheet \Microsoft.Cpp.targets
VERBOSE: Force includes: 
VERBOSE: Preprocessor definitions:
VERBOSE:   "-D_DEBUG"
VERBOSE:   "-D__WXDEBUG__"
VERBOSE:   "-DWIN32"
VERBOSE:   "-D__WXMSW__"
VERBOSE:   "-D_WINDOWS"
VERBOSE:   "-DNOPCH"
VERBOSE:   "-DwxUSE_UNICODE=1"
VERBOSE:   "-D_UNICODE"
VERBOSE:   "-DUNICODE"
VERBOSE:   "-DPROJECT_VERSION=1.4.0"
VERBOSE:   "-DBUILD_NUMBER=20484"
VERBOSE:   -D_MT
VERBOSE:   -D_USING_V110_SDK71_
VERBOSE:   -D_DEBUG_FUNCTIONAL_MACHINERY
VERBOSE: 
VERBOSE: Additional include directories:
VERBOSE:   F:\SubversionC\Source\Common
VERBOSE:   F:\SubversionC\Source\Common\wxWidgets
VERBOSE:   F:\SubversionC\Source\Sound Installer
VERBOSE:   F:\SubversionC\3rdParty\wxWidgets-3.0.1\include
VERBOSE:   F:\SubversionC\3rdParty\wxWidgets-3.0.1\include\msvc
VERBOSE: 
Cannot locate Visual Studio location
At C:\USERS\CHOFFE\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\14.0\EXTENSIONS\mwqoovi4.psr\psClang\visualstudio-detection.ps1
:100 char:9
+         throw "Cannot locate Visual Studio location"
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Cannot locate Visual Studio location:String) [], RuntimeException
    + FullyQualifiedErrorId : Cannot locate Visual Studio location
 

Done Clang Tidy

**Comment by hero101111** [comment]
Indeed, the problem is related to the `VS Version - Platform Toolset` relationship.

We're pushing a fix for the issue. It will be available in the next release of Clang Power Tools (`v4.2`).

Thank you for reporting the issue,
Gabriel.
