### ISSUE TITLE
Wrong file processed when clicking on open files tab.

### ISSUE THREAD

**Issue by g-glowacki** [Caphyon/clang-power-tools#44]
When a file is selected in Solution Explorer, then this file is always processed even if the execution of clang-tidy is done through clicking on tab bar with opened files.

**Comment by cpp-red-lion** [comment]
I can confirm this bug.
It manifests itself only when `Track Active Item in Solution Explorer` is OFF.
We actually have this option ON, so we missed this issue... oops!
As a workaround, until we fix this bug, please enable `Track Active Item in Solution Explorer` from:
[VS] > [Options] > [Projects and Solutions] > [General]

**Comment by Enache-Ionut** [comment]
This issue was fixed [here](https://github.com/Caphyon/clang-power-tools/commit/a62508a184de264075cdaa0ced315d911fb75898).
