### ISSUE TITLE
VS 2017: Option "Use checks from .clang-tidy config file" is not working

### ISSUE THREAD

**Issue by enterid** [Caphyon/clang-power-tools#444]
MS Visual Studio 2017 ver. 15.8.7
Clang Power Tools 4.2.0

Predefined and Custom checks are empty, "Use checks from" is set to ".clang-tidy config file".
.clang-tidy file is present in the parent folder of the tested source file and is working fine executing clang-tidy with the same file from the command line, but execution from VS has no effect.

P.S. tested with modernize-use-nullptr check.

**Comment by Enache-Ionut** [comment]
Hello,

We reproduced the issue. We'll update this thread once the problem will be fixed.
Thank you for your feedback!

**Comment by Enache-Ionut** [comment]
This issue was fixed and will be available in the next Clang Power Tools version (v4.4) 😃
