### ISSUE TITLE
Ignore thirtparty libraries from checks

### ISSUE THREAD

**Issue by philong6297** [Caphyon/clang-power-tools#446]
I have tried to do like this but it didn't work but it still checks on Qt files:
![capture](https://user-images.githubusercontent.com/29605147/47155230-7920dd80-d30e-11e8-8314-01da80cecaba.PNG)

**Comment by FadiBitar** [comment]
According to these instructions, third party dependencies should be added via Include Directories, not Additional Include Directories.
This is however a problem for people who use a dependency manager like Conan, which inserts the conan-managed dependencies into the Additional Include Directories, so now Clang Power Tools and Conan, two tools that developers are likely to love, don't play nice with each other.

Furthermore, according to this post: https://github.com/Caphyon/clang-power-tools/issues/281#issuecomment-428911550 mentioning the folder to exclude by name should take care of excluding a third party library. Having tried this, it seems that it only works for a single directory. As soon as I add a second directory the whole thing seems to stop working even though the field seems to be explicitly made for multi-line input.

Just off the top of my head it seems to me like this is a bug in the file-ignore functionality introduced in version 4.

**Comment by hero101111** [comment]
Hello,

First, let me begin with apologies for the late reply. Second, allow me to offer some light into how `-file` `-file-ignore` `-proj` and `-proj-ignore` parameter matching works:

1.  If the `-literal` switch is present, files and projects are matched exactly by their short names (with or without extension) e.g. `foo` matches `foo.vcxproj` and `foo.cpp`.
2.  If `-literal` is not present, files and projects are matched by their _full_ name (full path on disk), using regex. E.g. `proj\\source\\ui` matches all projects and files in `proj\source\ui` directory tree.
3.  Regardless of `-literal`, if a rooted path is given as parameter (e.g. `c:\app\myapp.vcxproj`) then the project or file path is matched by its full name, letter by letter, for the entire string. No regex is applied. 

**(3)** is basically your scenario, with the _catch-22_ that there has to be a *full match* (no substring matching is performed as of `v4.9`).

-----------

We've decided to extend **(3)** to perform substring matching, which will enable you to perform the file matching by-directory you describe in this issue. This change will take effect starting with the `v5.0` release, which will be out soon.

Regards,
Gabriel.

**Comment by hero101111** [comment]
Hello again,

A quick update: We've had a bit of rescheduling of the release schedule and version `v4.10` was released a few days ago, instead of `v5.0`. Nonetheless, the drectory-match change described above _is_ included in `v4.10`.

------

Please take a minute to go over the [release notes](https://clangpowertools.com/CHANGELOG.html). There are some breaking changes (`-literal` was removed and we provide a new mechanism for regex matching).

Regards,
Gabriel.
