### ISSUE TITLE
X warnings generated printed out when there are no warnings

### ISSUE THREAD

**Issue by gajop** [Caphyon/clang-power-tools#448]
As the title says, once I have cleaned up the code and got to 0 warnings, I still get an odd message upon invoking clang-tidy:

```

Start Clang Tidy

PROJECTS:
  $PathToMyProject.vcxproj
PROJECT: $PathToMyProject.vcxproj
1: $PathToMyCppFile.cpp
18069 warnings generated.



Done Clang Tidy
```

Any reason what's causing this message and if it can be removed?

**Comment by Enache-Ionut** [comment]
Hi, 

Those warnings (e.g. "58 warnings generated") are generated by `system headers` (Windows SDK, CRT, etc.) and are `by default suppressed by Clang`. You cannot access/fix them.

If clang-tidy finds issues in your code, they should be visible in the VS Output pane and Error pane.
