### ISSUE TITLE
Cannot run clang-build.ps1 with toolset v120 (VS2013) if VS15 is installed

### ISSUE THREAD

**Issue by hugolm84** [Caphyon/clang-power-tools#450]
Running 
```
clang-build.ps1 -dir SomeSolution.sln - proj SomeSubProj.vxproj -vs-ver 2013 -vs-sku 2013
```
I expected that toolset vs120 would be choosen. However, if VS15 is detected, it will take precedence. 

I'd like to lint using VS13 if possible.

```
VERBOSE: Platform toolset: v120
VERBOSE: Switching to VS2015 because of v140 toolset. Reloading project...
```
Possibly connected to
https://github.com/Caphyon/clang-power-tools/pull/438
https://github.com/Caphyon/clang-power-tools/issues/437

**Comment by netx123** [comment]
I was just about to raise this exact same issue.
I only have VS2017 and VS2013 installed, but see the same message in verbose output regarding switching to VS2015.
I have tested this with Clang Power Tools 3.9.0 and it works correctly in that release.
The issue is present in 4.2 and 4.2.1

**Comment by hugolm84** [comment]
Yes, Clang-Tidy will be run using system includes based on the Toolset used in VS17

**Comment by hero101111** [comment]
Support for this was added with #525, pending release with `CPT 4.8.1`
