### ISSUE TITLE
Regex for parsing errors and warnings does not allow '-' in path

### ISSUE THREAD

**Issue by GerrietReents** [Caphyon/clang-power-tools#46]
Currently the regex for wanings and errors looks like this:
`(.\:\\[ \w+\\\/.]*[h|cpp])(\r\n|\r|\n| |:)*(\d+)(\r\n|\r|\n| |:)*(\d+)(\r\n|\r|\n| |:)*(error|note|warning)[^s](\r\n|\r|\n| |:)*(.*)`
The `\w` only allows names for files/direcrories consisting of words (`[a-zA-Z0-9_]`)
In my projects I also have `-`.  
Can we relax the regex to
`(.\:\\[ \S+\\\/.]*[h|cpp])(\r\n|\r|\n| |:)*(\d+)(\r\n|\r|\n| |:)*(\d+)(\r\n|\r|\n| |:)*(error|note|warning)[^s](\r\n|\r|\n| |:)*(.*)`
allowing any non whitespace in file names? Or how does a correct regex for file names look like?

**Comment by Enache-Ionut** [comment]
Yes, you are right. I updated the regex as you showed it the example replacing \w+ with \s+.
