### ISSUE TITLE
clang-tidy error in Boost header

### ISSUE THREAD

**Issue by PeterFeicht** [Caphyon/clang-power-tools#468]
I've been getting this error lately when running clang-tidy on some of our files:

```
[...]/boost/type_traits/has_trivial_move_assign.hpp(49): error: no template named 'is_assignable'; did you mean 'std::is_assignable'? [clang-diagnostic-error]
   BOOST_HAS_TRIVIAL_MOVE_ASSIGN(T)
   ^
[...]/boost/type_traits/intrinsics.hpp(233): message: expanded from macro 'BOOST_HAS_TRIVIAL_MOVE_ASSIGN'
#     define BOOST_HAS_TRIVIAL_MOVE_ASSIGN(T) (__is_trivially_assignable(T&, T&&) && is_assignable<T&, T&&>::value && !::boost::is_volatile<T>::value)
                                                                                     ^
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\type_traits:523:9: note: 'std::is_assignable' declared here
        struct is_assignable
```

Is this likely to be caused by my project configuration, or should this be fixed in Clang Power Tools? This is with Boost 1.68 and VS 2017 (using VS2015 toolset).

**Comment by cpp-red-lion** [comment]
Hi,   

Could you create a simple project + dependencies reproducing this issue ?
(attach it here) 

Thanks.

**Comment by PeterFeicht** [comment]
I will try next week, my first attempt wasn't all too successful since Visual Studio decided to freeze when importing all of Boost...

**Comment by icze** [comment]
Hi together,

seems to be a boost issue:
https://stackoverflow.com/questions/52412203/is-assignableerror-when-using-boost-1-68-llvm-vs2017
The fix worked for me.

Regards!
Ingo

**Comment by PeterFeicht** [comment]
That's good to hear. I couldn't recall where the error was exactly so I was waiting for our internal Boost dependency to be updated so it would show again.
