### ISSUE TITLE
VS2017: Few predefined checks missing

### ISSUE THREAD

**Issue by IrinSamuel** [Caphyon/clang-power-tools#471]
Hello, 

VS2017 version 15.8.3
Clang Power tool version 4.3.2
LLVM 7.0.0

for Clang Tidy, checks mentioned in (https://clang.llvm.org/extra/clang-tidy/index.html#using-clang-tidy) are missing in (Clang Power tools ->tidy -> Predefined Checks) , eg: abseil-, google-, fuchsia-, portability-

Thanks for looking into, 
Best regards, 
Irin

**Comment by Enache-Ionut** [comment]
Hi, 

We have updated the `Tidy` -> `Predefined checks` option page. All the new checks will be available in the next version (v4.4).

Thank you for you feedback!
