### ISSUE TITLE
clang-format formats CMakeLists.txt

### ISSUE THREAD

**Issue by s-martin** [Caphyon/clang-power-tools#477]
I use a CMake project with VS.

If I apply clang-format to the whole project, it formats also my CMakeLists.txt file in the source tree and breaks it.

Please exclude CMakeLists.txt from clang-format.

In addition it would be good to get some visual feedback that clang-format is currently running over the project. So far I thought it works not on project level, because I get no feedback after clicking.

**Comment by Enache-Ionut** [comment]
Hi, 

We excluded `CMakeLists.txt` from clang-format. The fix will be available in the next Clang Power Tools version. 
Regarding the visual feedback of clang-format we think it will be a good idea to create a new issue for this improvement. We have been thinking about this before, it is a good suggestion.

Thank you for your feedback 😃
