### ISSUE TITLE
Feature request: Export config to .clang-tidy

### ISSUE THREAD

**Issue by s-martin** [Caphyon/clang-power-tools#478]
It would be a helpful improvement, if the currently selected clang-tidy configuration could be exported to a .clang-tidy file.

**Comment by hprica** [comment]
@s-martin, the feature to export .clang-tidy was included in v5.0. Go to Extensions > Clang Power Tools > Export Clang Tidy Config.

Let us know if you have any issues.

**Comment by s-martin** [comment]
Can confirm, works for me! Thanks!
