### ISSUE TITLE
Can't compile on dual CPU PC

### ISSUE THREAD

**Issue by corppeon** [Caphyon/clang-power-tools#48]
I have a dual CPU PC (2 x 4 physical cores -> 2 x 8 logical cores). Calling compile gives an error;

+   [System.IO.DirectoryInfo] $child = ($directory | Get-ChildItem)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : ConvertToFinalInvalidCastException
Could not compare "0" to "8 8". Error: "Cannot convert the "System.Object[]" 
value of type "System.Object[]" to type "System.Int32"."
At C:\Users\xxx\AppData\Local\Microsoft\VisualStudio\15.0_e15d5032\Extension
s\d0kad1w4.pp0\clang-build.ps1:926 char:7

Looks like it is failing to parse "8 8" coming back from Get-WmiObject -class Win32_processor | Select-Object -property NumberOfLogicalProcessors -ExpandProperty NumberOfLogicalProcessors

**Comment by cpp-red-lion** [comment]
Thanks for bringing this to our attention.
Will fix this ASAP.

**Comment by hero101111** [comment]
[Fixed issue](https://github.com/Caphyon/clang-power-tools/commit/91ecfbfeed9a8b0054e33f10f2a780801d903dab)
