### ISSUE TITLE
Feature Request: Get visual feedback, when invoking clang-format on project level

### ISSUE THREAD

**Issue by s-martin** [Caphyon/clang-power-tools#482]
It would be good to get some visual feedback that clang-format is currently running over the project. So far I thought it works not on project level, because I get no feedback after clicking.

**Comment by Enache-Ionut** [comment]
Hi,

We are happy to announce you that we added status bar support for clang-format in the new version [CPT v4.5](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools) just released. In the future we will take in consideration to improve the feedback for all the extension commands, so stay tuned for future improvements

Thank you for your feedback 😄
