### ISSUE TITLE
Clang-Format formats more than what is selected

### ISSUE THREAD

**Issue by mjendruk** [Caphyon/clang-power-tools#488]
At least since version 4.3, when I select a couple of lines in a file and hit format, Clang Format formats sometimes entire other files which have previously been opened. 

Current setup: Visual Studio 2017 (15.8.5), Clang Power Tools (4.5.0)

I would like to show you some dump or similar but I’m not sure what could be helpful.

**Comment by Enache-Ionut** [comment]
Hi,

Can you attach a sample project and few steps for reproducing this issues? It will be a great help for us.
