### ISSUE TITLE
Incorrect toolset detection blocks clang-tidy from completing

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#489]
Unable to use the current version of Clang Power Tools (4.5) as the incorrect detection of the platform VS2013 XP toolset breaks the ability for clang-tidy to complete its analysis.

All our projects use either the VS2013 or VS2013 XP toolsets.

VERBOSE: Platform toolset: v120_xp
VERBOSE: Switching to VS2015 because of v140 toolset. Reloading project...

Because of this switching, the include paths are not correct for VS2013 XP toolset, and therefore a required include in our project cannot be found

X:\******\stdafx.h(18): error: 'afx.h' file not found [clang-diagnostic-error]

This prevents clang-tidy from performing any further analysis, and resulting in this being the only error/warning being detected.

**Comment by cpp-red-lion** [comment]
Hi,

Can you attach a sample project reproducing the issue ?

**Comment by hugolm84** [comment]
This is probably linked to #450, the VS120 toolset will not be used in the current versions.

**Comment by hero101111** [comment]
Hello,

This issue should be fixed as consequence of #525, which has been released with Clang Power Tools `v4.8`.
We've retried Clang _Compile_ and _Tidy_ using your sample project and everything appears to be OK now.
