### ISSUE TITLE
tidy works not correctly on project level

### ISSUE THREAD

**Issue by s-martin** [Caphyon/clang-power-tools#495]
I discovered today that tidy does not process all source files, when applying tidy to a VS project. 

If I apply tidy to a cpp or h file, many more issues are found.

I'm not sure, if this is a regression, but I have the feeling it worked better in the past.

**Comment by s-martin** [comment]
I investigated a little more and if I run tidy on project level, I get only warnings from one cpp file. If i run tidy directly on the other cpp files, I get a lot more errors.

**Comment by Enache-Ionut** [comment]
Hi,

Could you create a simple project reproducing this issue? Please attach it here.

**Comment by s-martin** [comment]
Hi,

Currently I'm unable to reproduce the issue in a small project. Right now I'm investigating why this doesn't work.

**Comment by Enache-Ionut** [comment]
Hi, 

What is the status of this issue, it is still present?

**Comment by s-martin** [comment]
I can't reproduce it right now.

Can be closed, I would reopen it, if the issue occurs again.

**Comment by Enache-Ionut** [comment]
In this case, I will close this issue now. Thank you for your feedback.
