### ISSUE TITLE
Custom executable path for clang-tidy

### ISSUE THREAD

**Issue by bernhardmgruber** [Caphyon/clang-power-tools#503]
First, thank you for this amazing plugin!

For clang-format, we can set a custom executable file, but for clang-tidy we cannot currently. I would really like to have this feature to test my own versions of clang-tidy (I currently develop a clang-tidy check).

**Comment by cpp-red-lion** [comment]
Hi,

I want this myself :)  
We'll try to address it in the next release.  

Thanks for your suggestion.

**Comment by Enache-Ionut** [comment]
Hi,

This feature is now present in the new version of Clang Power Tools v4.7. Please upgrade the VS Extension from Visual Studio or download it from [here](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools).

Thanks for your suggestion.
