### ISSUE TITLE
Allow exporting a compilation database

### ISSUE THREAD

**Issue by bernhardmgruber** [Caphyon/clang-power-tools#504]
Hi guys!

I found myself in the need to create a compilation database to run the run-clang-tidy.py script. I wonder if it would be much work to provide it here, as the plugin probably already internally collects this information.

I found this plugin (SourceTrail), which can do it already (apart of other things): https://www.sourcetrail.com/blog/export_clang_compilation_database_from_visual_studio_solution/

Would this be of interest? To implement an export button for a compilation database of the whole solution/project?

Thank you!

**Comment by bernhardmgruber** [comment]
Are you sure #248 requests the same feature? To me it sounds like #248 wants to use an existing compilation database, whereas I would like to create a compilation database from the VS projects.

**Comment by cpp-red-lion** [comment]
I think your right.  
My mistake; that’s what happens before morning coffee :)

Reopened.

**Comment by ChrisGuzak** [comment]
A use case I have in mind is to use the compilation database (compile_commands.json) to enable use of clang-query on my .vcxproj based code. I'm new to this but I understand that this will provide the compiler options and include path needed to let the clang tools process the file.

so an option to save this database file as part of other processing would enable this.
