### ISSUE TITLE
VS2019

### ISSUE THREAD

**Issue by Astrantia** [Caphyon/clang-power-tools#505]
Will support for 2019 be added soon?

**Comment by cpp-red-lion** [comment]
Hi,

Sure thing. We didn't rush it because we thought it was a bit early (VS2019 is still in Preview).  

We'll add this soon.  
Stay tuned.

**Comment by Enache-Ionut** [comment]
Clang Power Tools v4.8.1 is now online with the Visual Studio 2019 support. Please check for updates.
