### ISSUE TITLE
PowerShellWrapper does not disable profile loading causing errors and slower startup

### ISSUE THREAD

**Issue by ChrisGuzak** [Caphyon/clang-power-tools#506]
This seems to be the same as #493 but since that is closed I've created this new issue.

When invoking PowerShell.exe my profile gets loaded and it fails to run in this enviornment. This is because PowerShell.exe is not launched with `-NoProfile` [here in PowerShellWrapper.cs](https://github.com/Caphyon/clang-power-tools/blob/master/ClangPowerTools/ClangPowerTools/Script/PowerShellWrapper.cs).

Other options should be applied here too. `-ExecutionPolicy Bypass` to avoid the script policy setting blocking (I see another issue sufferes from this) and `-Noninteractive` (not familiar with that but it looks right).

**Comment by Enache-Ionut** [comment]
Hi,

Everything you said is mentioned in the `Arguments` section of the `Process.StartInfo`. 
Is there another way to mention all of this for the `Process` class? 🤔 

Current invocation of the PowerSehll: `PowerShell.exe -ExecutionPolicy Unrestricted -NoProfile -Noninteractive ...`

**Comment by ChrisGuzak** [comment]
I did not inspect the code that constructs that argument, I see the code in RunScript does indeed compose that param so I can't explain why this fails for me. If I get a chance I'll attach a debugger and see what CreateProcessW is really getting.

**Comment by ChrisGuzak** [comment]
I debugged this and see the lpCommandLine looks suspicious, there are 2 mentions of PowerShell.exe.

```
"C:\WINDOWS\system32\WindowsPowerShell\v1.0\powershell.exe" PowerShell.exe -ExecutionPolicy Unrestricted -NoProfile -Noninteractive -command '& ''c:\users\chrisg\appdata\local\microsoft\visualstudio\15.0_d615e888\extensions\hto2yfm0.5s5\clang-build.ps1''  -proj ''F:\Source\Repos\wil\tests\Tests.vcxproj'' -file ''F:\Source\Repos\wil\tests\ComTests.cpp'' -active-config ''Debug|Win32'' -clang-flags  (''-Wall'',''-fms-compatibility-version=19.10'',''-Wmicrosoft'',''-Wno-invalid-token-paste'',''-Wno-unknown-pragmas'',''-Wno-unused-value'') -tidy-fix ''-*,google-...```

**Comment by Enache-Ionut** [comment]
Hi, 

In all this time, we made many changes to Clang Power Tools, a lot of new features and bug fixes are now available. Please check for updates. At this moment, the latest version is v7.1.

Can you tell us if this issue is still present on your machine?

**Comment by Enache-Ionut** [comment]
I will close this issue because of the lack of feedback and because we cannot reproduce it anymore.
