### ISSUE TITLE
Compile at solution/file level does not work

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#512]
When compiling the entire solution by right clicking it -> clang power tools -> compile it doesn't compile all solution projects, just a few. If i look at the commandline arguments passed to the root powershell script it passes a specific project (with the solution given in the parameters as well). It does a couple of projects and then stops. Previously this worked and only passed the solution to the powershell script, resulting in all projects being compiled. Running the powershell script without -proj parameter and with -dir specified does work. 

I have similar issues with compiling files, where it does not compile the single file anymore, but also a couple of projects. Any insights? I have a feeling this might be a local issue, but re-installing didn't help me.

**Comment by hprica** [comment]
Hello @jcageman.
Unfortunately, I cannot reproduce the bug on my side. Could you send me a sample project that has the issue?
