### ISSUE TITLE
VS2019 shows Clang Power Tools is using Deprecated APIs

### ISSUE THREAD

**Issue by japj** [Caphyon/clang-power-tools#528]
After installing v4.8.1 of the Clang Power Tools extension in VS2019 Preview3 I get the following information on startup of Visual Studio:

"This extension uses deprecated APIs and is at risk of not functioning in a future VS update"

There is more information related to this issue at https://devblogs.microsoft.com/visualstudio/improving-the-responsiveness-of-critical-scenarios-by-updating-auto-load-behavior-for-extensions/

**Comment by Enache-Ionut** [comment]
Hi, 

We fixed this issue. It will be available in the next version of Clang Power Tools.
Thank you for your feedback!
