### ISSUE TITLE
Extension resets its settings after VS close

### ISSUE THREAD

**Issue by ArchiDevil** [Caphyon/clang-power-tools#535]
This extension does not save anything I set for clang-tidy. I use .clang-tidy config file to set up my checks for the project with header filter inside.
I remove headers filter from configuration window and set up 'Use checks from .clang-tidy' option. But when I close Visual Studio it resets and I have to set it up again.
I have VS 2017 15.9.7 in case if it is needed.

**Comment by Enache-Ionut** [comment]
Hi, 

What Clang Power Tools version are you using?

**Comment by ArchiDevil** [comment]
> Hi,
> What Clang Power Tools version are you using?

Hi, what a fast reply 👍 
I use the latest one, 4.8.1 which was downloaded from VS Marketplace. It was updated two days ago automatically.

**Comment by Enache-Ionut** [comment]
I will investigate this issue and I will update this thread once the problem will be fixed.

**Comment by Enache-Ionut** [comment]
Hi

We are glad to announce you that this issue was fixed and it will be available in the next Clang Power Tools version.
