### ISSUE TITLE
Project include directories are ignored

### ISSUE THREAD

**Issue by raffaeler** [Caphyon/clang-power-tools#538]
I have a fully working project in VC++2019.
The project settings specify some "Additional Include Directories" where include files resides.

If I try to compile the project using Clang (using this extension's button), compiling fails because Clang is not instructed about those directories and the include files cannot be found.

**Comment by hero101111** [comment]
Hi,

I'm afraid we're unable to reproduce this issue, using `VS 2019 Preview 4` and `CPT 4.8.1`.
Please attach a sample project to help us investigate the issue.

Regards,
Gabriel.

**Comment by raffaeler** [comment]
It happened with P3, now with P4 works.
