### ISSUE TITLE
Add more logging to see clang command line arguments

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#54]
After installing the latest version of this great tool i still have issues, but i am so far unable to reproduce it on a smaller project. Would it be possible to add some more logging (configurable in settings) such that i can see the command line arguments being passed to clang to detect what is going wrong? I suspect still some include paths are missing in a specific case

**Comment by hero101111** [comment]
For the PS script, you can execute `$verbosePreference = "Continue"` before running the script. 
This will print the verbose logging generated by the script, including include paths.

If you're testing from the VS extension, there is currently no way of getting verbose logs.  We're working on enabling verbose logging directly from the extension.

Until then, as a workaround:
- Search for `clang-build.ps1` in %LOCALAPPDATA%
- Add `$verbosePreference = "Continue"`  to the beginning of the script (after the param() section)
- Restart Visual Studio

**Comment by jcageman** [comment]
Thanks for the hint. I am doing that now and will hopefully come back with a full repro.
