### ISSUE TITLE
Fallback-style is always "none" even set other values when using “Format On Save”

### ISSUE THREAD

**Issue by tishion** [Caphyon/clang-power-tools#541]
set fallback-style to LLVM or some other values except "none", and enable the "Format On Save", then press Ctrl+S, the clang power tool will ignores the fallback-style in setting dialog and replace it with "none" always.

I looked into the code and found:
https://github.com/Caphyon/clang-power-tools/blob/99c5479412112b18dcb7a89fb3b7cf36bed9fc45/ClangPowerTools/ClangPowerTools/Commands/CommandsController.cs#L353-L380

see the line 378: 

```C#
option.FallbackStyle` = ClangFormatFallbackStyle.none; 
```
Why do this?  I just want clang-format to fall back to the style i set in the setting dialog.

**Comment by Enache-Ionut** [comment]
Hi,

This issue was fixed and it will be available in the new version of Clang Power Tools which will be released very soon.

**Comment by tishion** [comment]
@Enache-Ionut Thanks!
