### ISSUE TITLE
Add "Additional Option" setting for clang-tidy

### ISSUE THREAD

**Issue by matbech** [Caphyon/clang-power-tools#548]
It would be useful if there would be an "Additional Option" settings for clang-tidy. The options (text input field) would then be appended to arguments passed to clan-tidy.

This would also solve the issue here: https://github.com/Caphyon/clang-power-tools/issues/285

**Comment by Enache-Ionut** [comment]
Hi, 

For #285, we will offer `-line-filter` support in a future version of Clang Power Tools. `Additional Option` would be a much easier solution, but we think it will cause more harm than good. The option will be placed in clang-tidy settings, but the code is frequently changing. The field will not be synchronized with the code, and this is a very easy situation to reach. This will cause unwanted behavior during the clang-tidy execution.
