### ISSUE TITLE
Get-Project-SDKVer returns empty version when not specified in .vcxproj

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#55]
I analyzed a case where it couldn't find includes in windows specific libraries and when $vcxproj.Project.PropertyGroup.WindowsTargetPlatformVersion is not specified in the .vcxproj you now get an empty version. It is possible to specify it default in the vcxproj template and then its not available.
[TidyRepro.zip](https://github.com/Caphyon/clang-power-tools/files/1410167/TidyRepro.zip)

I think the fix would be to know which version is the default version for a platform. I already noticed the flag $aDefaultWinSdkVersion, but apparently its empty.

**Comment by hero101111** [comment]
[Fixed issue](https://github.com/Caphyon/clang-power-tools/commit/826e69ff5060b3289dc418166a696b39392ff04b). Should work now.

**Comment by cpp-red-lion** [comment]
After a little digging through VS `*.props` files, it appears that there are two possible inherited values for `WindowsTargetPlatformVersion`

- "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Common.props"
`<WindowsTargetPlatformVersion>8.1</WindowsTargetPlatformVersion>`

- "C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Platforms\Win32\PlatformToolsets\v141_xp\Toolset.props"
`<WindowsTargetPlatformVersion>7.0</WindowsTargetPlatformVersion>`
(XP targeting)

We think the best course of action is to fallback on these values when `WindowsTargetPlatformVersion` is not found in the project.
