### ISSUE TITLE
Add a VERBOSE mode setting for VS extension

### ISSUE THREAD

**Issue by cpp-red-lion** [Caphyon/clang-power-tools#56]
PS script logging.

For the PS script, you can execute `$verbosePreference = "Continue"` before running the script.
This will print the verbose logging generated by the script, including include paths.

**Comment by Enache-Ionut** [comment]
The Verbose Mode option can be set from "Tools -> Options -> Clang Power Tools -> General -> Verbose Mode" or  "Right click on the project/file -> Clang power Tools -> Settings -> General -> Verbose Mode".
