### ISSUE TITLE
afxwin.h no longer compiles

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#579]
Use file/New Project/MFC-ATL/MFC Appliocation/Dialog based.
Compile in CLang -- now results errors below. Probably just #include <afxwin.h> is enough.

A starting workaround is to #define all __PRC macros from <rpcsal.h> to nothing. Then additional errors surface from d2d1.h. 

config:
-fms-compatibility-version=19.14
-fms-compatibility
-Wmicrosoft
-Winvalid-token-paste
-Wno-unknown-pragmas
-Wunused-variable
-Wunused-value
-Wno-missing-braces
-Wno-deprecated-declarations
-Wno-switch
-Wno-dangling-else
-Wmissing-field-initializers
-Wnonportable-include-path
-Wno-microsoft-enum-value
-Winvalid-source-encoding
-Wno-microsoft-template
-Wconversion
-Wno-sign-conversion
-Wunused-local-typedef
-Wimplicit-fallthrough
-Wunused-macros
-Wmissing-variable-declarations
-Wmissing-prototypes
  

Start Clang Compile

PROJECT: C:\Users\baloghp\Documents\Visual Studio 2017\Projects\MFCApplication1\MFCApplication1\MFCApplication1.vcxproj
1: C:\Users\baloghp\Documents\Visual Studio 2017\Projects\MFCApplication1\MFCApplication1\MFCApplication1.cpp
In file included from C:\Users\baloghp\Documents\Visual Studio 2017\Projects\MFCApplication1\MFCApplication1\MFCApplication1.cpp:5:
In file included from C:\Users\baloghp\Documents\Visual Studio 2017\Projects\MFCApplication1\MFCApplication1/stdafx.h:19:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\afxwin.h:19:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\afx.h:329:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\atltrace.h:17:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\atlconv.h:27:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\atlalloc.h:18:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um/ole2.h:37:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objbase.h:27:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\combaseapi.h:363:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6184): error: C++ requires a type specifier for all declarations
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) BYTE *buf,
                                                                   ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6184): error: C++ requires a type specifier for all declarations
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) BYTE *buf,
                                                                              ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6184): error: C++ requires a type specifier for all declarations
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) BYTE *buf,
                                            ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6184): error: expected ')'
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) BYTE *buf,
                                                                                          ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6183): message: to match this '('
        virtual HRESULT STDMETHODCALLTYPE Finish_Pull( 
                                                     ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6188): error: unknown type name '__RPC__in_xcount_full'
            /* [size_is][in] */ __RPC__in_xcount_full(cSent) BYTE *buf,
                                ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6188): error: expected ')'
            /* [size_is][in] */ __RPC__in_xcount_full(cSent) BYTE *buf,
                                                             ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6187): message: to match this '('
        virtual HRESULT STDMETHODCALLTYPE Begin_Push( 
                                                    ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6392): error: C++ requires a type specifier for all declarations
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) LONG *buf,
                                                                   ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6392): error: C++ requires a type specifier for all declarations
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) LONG *buf,
                                                                              ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6392): error: C++ requires a type specifier for all declarations
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) LONG *buf,
                                            ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6392): error: expected ')'
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) LONG *buf,
                                                                                          ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6391): message: to match this '('
        virtual HRESULT STDMETHODCALLTYPE Finish_Pull( 
                                                     ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6396): error: unknown type name '__RPC__in_xcount_full'
            /* [size_is][in] */ __RPC__in_xcount_full(cSent) LONG *buf,
                                ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6396): error: expected ')'
            /* [size_is][in] */ __RPC__in_xcount_full(cSent) LONG *buf,
                                                             ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6395): message: to match this '('
        virtual HRESULT STDMETHODCALLTYPE Begin_Push( 
                                                    ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6600): error: C++ requires a type specifier for all declarations
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) DOUBLE *buf,
                                                                   ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6600): error: C++ requires a type specifier for all declarations
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) DOUBLE *buf,
                                                                              ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6600): error: C++ requires a type specifier for all declarations
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) DOUBLE *buf,
                                            ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6600): error: expected ')'
            /* [length_is][size_is][out] */ __RPC__out_xcount_part(cRequest, *pcReturned) DOUBLE *buf,
                                                                                          ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6599): message: to match this '('
        virtual HRESULT STDMETHODCALLTYPE Finish_Pull( 
                                                     ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6604): error: unknown type name '__RPC__in_xcount_full'
            /* [size_is][in] */ __RPC__in_xcount_full(cSent) DOUBLE *buf,
                                ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6604): error: expected ')'
            /* [size_is][in] */ __RPC__in_xcount_full(cSent) DOUBLE *buf,
                                                             ^
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidlbase.h(6603): message: to match this '('
        virtual HRESULT STDMETHODCALLTYPE Begin_Push( 
                                                    ^
In file included from C:\Users\baloghp\Documents\Visual Studio 2017\Projects\MFCApplication1\MFCApplication1\MFCApplication1.cpp:5:
In file included from C:\Users\baloghp\Documents\Visual Studio 2017\Projects\MFCApplication1\MFCApplication1/stdafx.h:19:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\afxwin.h:19:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\afx.h:329:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\atltrace.h:17:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\atlconv.h:27:
In file included from C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include\atlalloc.h:18:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um/ole2.h:37:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objbase.h:28:
In file included from C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\coml2api.h:24:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um\objidl.h(14535): error: expected parameter declarator
unsigned char * __RPC_USER  ASYNC_STGMEDIUM_UserMarshal(  __RPC__in unsigned long *, __RPC__inout_xcount(0) unsigned char *, __RPC__in ASYNC_STGMEDIUM * ); 
                                                                                                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

Got errors.

Done Clang Compile

**Comment by hero101111** [comment]
Hello,

We'll look into this and update the thread as soon as progress is made.

Regards,
Gabriel.

**Comment by hero101111** [comment]
I've tested your scenario and unfortunately cannot reproduce the issue.

Are you using any specific clang flags? 
A zip file with the project at fault would really be useful here.

**Comment by pasa-** [comment]
>Are you using any specific clang flags?
>A zip file with the project at fault would really be useful here.

I’m sure the project generated by appwizard is the same.

I found the cause. I have DirectX SDK installed and in the include path:

<IncludePath>$(IncludePath);C:\Program Files (x86)\Microsoft DirectX SDK (November 2008)\Include</IncludePath>

without that the problem does not occur. The -E output shows 

# 51 "C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.17763.0\\shared\\rpcndr.h" 2 3

# 1 "C:\\Program Files (x86)\\Microsoft DirectX SDK (November 2008)\\Include\\rpcsal.h" 1 3

rpcsal is picked from this set. In the past this did not cause a problem so there must have been some relevant change in CPT.  Maybe the order of includes. in verbose I see:

VERBOSE: MSCVER: 14.16.27023

VERBOSE: WinSDK version: 10.0.17763.0

VERBOSE: Include directories:

VERBOSE:   C:\Program Files (x86)\Microsoft DirectX SDK (November 2008)\Include

VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include

VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include

VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt

VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um

VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared

VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt

VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt

VERBOSE: INVOKE: "C:\Program Files\LLVM\bin\clang++.exe" -x c++ "C:\work\fd\main\src\cad\dsk\dskcache.c" -std=c++1z 

-Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-value 

-fsyntax-only "-DDLL_NAME_=FDCADKERNEL" "-DFDCADKERNEL_EXPORTS" "-DCS2DSK_EXPORTS" "-D_WINDLL" "-D_AFXDLL" "-D_AFXEXT" 

"-DFP_EXCEPTIONS_ON=1" "-DWIN32" "-D_WINDOWS" "-DWINVER=0x0601" "-D_WIN32_WINNT=0x0601" "-DPROJ_NAME=CS2DSK" "-D_DEBUG"

"-DNDEBUG" "-DNO_GDIPLUS_SHUTDOWN" "-D_MT" "-D_DLL" "-D_DEBUG_FUNCTIONAL_MACHINERY" 

-isystem"C:\work\fd\main\src\include" -isystem"C:\Program Files (x86)\Microsoft DirectX SDK (November 2008)\Include" 

-isystem"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include" 

-isystem"C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include" 

-isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt" -isystem"C:\Program Files (x86)\Windows 

Kits\10\Include\10.0.17763.0\um" -isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared" 

-isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt" -isystem"C:\Program Files (x86)\Windows 

Kits\10\Include\10.0.17763.0\cppwinrt" -I"C:\work\fd\main\src\INCLUDE" -I"C:\work\fd\main\src" -I"C:\work\fd\main\src" 

-I"C:\work\fd\main\src\..\EX_INCLUDE" -Wno-microsoft-include -include C:\work\fd\main\src\\include\stru_forced.h

This is the wrong order, the DX sdk should appear after the win SDK.  When the msvc compiler runs, the preprocessor shows:

#line 52 "c:\\program files (x86)\\windows kits\\10\\include\\10.0.17763.0\\shared\\rpcndr.h"

 

#line 1 "c:\\program files (x86)\\windows kits\\10\\include\\10.0.17763.0\\shared\\rpcsal.h"

**Comment by hero101111** [comment]
Hello again,

I'm afraid we're stuck investigating this issue.

After installing `DirectX SDK November 2008` the project stops compiling even when using Visual Studio. We've tested previous releases of Clang Power Tools and we get the same behavior, regarding SAL RPC error messages. 

Please attach a zip file with a sample project which compiles with Visual Studio to help us investigate this.

**Comment by pasa-** [comment]
See attached projects. mfcdlg has no ref to dxsdk, mfcdlg1 compiles in VS, but not in clang, mfcdlg2 compiles in neither.   As I said earalier message the problem is with the ordering of the include files that is crucial here. CLPT had it right but recently switched the ordering dragging the sdk folder before the others.

If you can't compile either project there, then check the includes used by mfcdlg, it is not supposed to get anything from DX but might be getting it from some local setting, environment var, etc. 



[MFCDlg2.zip](https://github.com/Caphyon/clang-power-tools/files/3121360/MFCDlg2.zip)

**Comment by pasa-** [comment]
I’ve posted projects for repro a while ago and it is still marked “need more info”, could you reproduce it finally?

 

It is probably regression made during work on separating “external” includes as system for warning report purposes at the beginning of the year, and the separation leads to possibly switched order the include dirs. passed to the compiler.

**Comment by hero101111** [comment]
Hello again,

We're pleased to inform you that we've reproduced the issue with the help of your most recent sample project. We'll release a fix for it in the next release of Clang Power Tools (`v4.10.5`).
Thank you for your feedback and patience.

Regards,
Gabriel.
