### ISSUE TITLE
Need to define _AFXDLL for MFC related project

### ISSUE THREAD

**Issue by Alexolut** [Caphyon/clang-power-tools#580]
If the application uses MFC and the project configured with the following options:

* Runtime Library: Multi-threaded DLL (/MD) or Multi-threaded Debug DLL (/MDd)
* Use of MFC: Use MFC in a Shared DLL

that adds an extra define `_AFXDLL` to the build command, which is not used in clang compile mode (same as for clang-tidy). In the result this may leads to the following error message from the `<afx.h>` header:

> VC\Tools\MSVC\14.16.27023\atlmfc\include\afx.h(24): error: Building MFC application with /MD[d] (CRT dll version) requires MFC shared dll version. Please #define _AFXDLL or do not use /MD[d]

I can manually add `-D_AFXDLL` to the clang compile flags to fix the issue (build and tidy will work), but there is no need to include such option to other (non-MFC related) projects inside VS solution.

**Comment by hero101111** [comment]
Hello,

We've just pushed a fix for this; it'll be available in the next bugfix release of _ClangPowerTools_ (`v4.10.2`).
Thank you for providing feedback and helping us fix this issue.

Regards,
Gabriel.
