### ISSUE TITLE
error: 'CppCoreCheck/warnings.h' file not found

### ISSUE THREAD

**Issue by BenKey** [Caphyon/clang-power-tools#585]
I am getting the following error when using Clang-Tidy with my [TTSApp](https://svn.sullivanandkey.com/SnKOpen/cpp/TTSApp/trunk/) project.

```
Error while processing C:\src\svn\SnKOpen\cpp\TTSApp\trunk\TTSApp\TTSAppDlg.cpp.
C:\src\svn\SnKOpen\cpp\TTSApp\trunk\TTSApp\TTSAppDlg.cpp(29): error: 'CppCoreCheck/warnings.h' file not found [clang-diagnostic-error]
#include <CppCoreCheck/warnings.h>
```

The file CppCoreCheck/warnings.h is installed in the __C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\VS\includenclude__ directory. This directory is included in the include path as part of the VC_IncludePath. The value of VC_IncludePath is as follows.

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\VS\include
C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt
```

It appears that this directory is added to the include path by Microsoft.Cpp.Common.props.

**Note:** I am very pleased with this project. Some of my projects are cross platform and I am able to run clang-tidy from the command line on GNU/Linux and FreeBSD. However, some of my projects are Windows only and most of those build with Visual Studio. Until I discovered this extension, I had no easy way to run clang-tidy on these projects. The clang-power-tools extension helps with that. It has led to many improvements in the quality of my code.

**Comment by hero101111** [comment]
Hi @BenKey,

A fix for this issue will be included in the next release of Clang Power Tools (`v4.10.3`).
It's very good to hear that your codebase has been improved with the help of Clang Power Tools 👍 .

Thank you for your feedback!

Regards,
Gabriel.
