### ISSUE TITLE
Feature Request: Add .clang-tidy config file or predefined checks option.

### ISSUE THREAD

**Issue by BenKey** [Caphyon/clang-power-tools#586]
There are currently three possible values for the "Use checks from" options.

- predefined checks
- custom checks
- .clang-tidy config file

I would like to use the ".clang-tidy config file" option. However, not every project I work with has a .clang-tidy config file. If you were to add a ".clang-tidy config file or predefined checks option" that causes it to prefer the .clang-tidy config file if it can be found or use the predefined checks if it cannot be found it would be an ideal solution.

**Comment by Enache-Ionut** [comment]
Hi, 

First of all, thank you for your suggestion. This issue will be available in a feature release so stay tuned. In the meantime, the new version of Clang Power Tools, [v5.0.1](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools), is now available so check for updates.

Regards,
Ionut

**Comment by Enache-Ionut** [comment]
Hi,

We are glad to announce you that the next version of Clang Power Tools, v6.0, will contain the automatic detection for .clang-tidy file. I will let you know when the v6.0 will be released. 

Regards, 
~Ionut
