### ISSUE TITLE
Extract C++ language standard version from project files.

### ISSUE THREAD

**Issue by cpp-red-lion** [Caphyon/clang-power-tools#59]
Map MSVC  `/std:c++14 /std:c++17 /std:c++latest` compiler options to corresponding `clang++` flags: 
`-std=c++14 -std=c++17 -std=c++1z`

Note that VS property-sheet syntax for these options is: 

`<ClCompile>`
&nbsp;&nbsp; `<LanguageStandard>stdcpp14</LanguageStandard>` 
&nbsp;&nbsp; `<LanguageStandard>stdcpp17</LanguageStandard>`  
&nbsp;&nbsp; `<LanguageStandard>stdcpplatest</LanguageStandard>`
`</ClCompile>`

**Comment by cpp-red-lion** [comment]
The `/std:c++14` and `/std:c++latest` options are available beginning in **Visual C++ 2015** Update 3

The `/std:c++17` option is available beginning in **Visual C++ 2017** Update Version **15.3**

https://docs.microsoft.com/en-us/cpp/build/reference/std-specify-language-standard-version

**Comment by cpp-red-lion** [comment]
Depends on #60

**Comment by hero101111** [comment]
[Fixed](https://github.com/Caphyon/clang-power-tools/commit/5488200d4174aee7b8589fe78e2258058343b73d)
