### ISSUE TITLE
Please use the /MD switch for _AFXDLL builds

### ISSUE THREAD

**Issue by matbech** [Caphyon/clang-power-tools#593]
With the latest version 4.10.2 I get the following error now for a MFC .exe:

In file included from C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.20.27508\atlmfc\include\afx.h:71:
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\VC\Tools\MSVC\14.20.27508\atlmfc\include\afxver_.h(77): error: Please use the /MD switch for _AFXDLL builds
        #error Please use the /MD switch for _AFXDLL builds
         ^
1 error generated.
Skipping project. Reason: cannot create PCH.

**Comment by BenKey** [comment]
I am seeing this issue as well, despite the fact that the Use of MFC option is set to "Use MFC in a Shared DLL" in my project.

### clang-tidy --version:
LLVM (http://llvm.org/):
  LLVM version 8.0.0
  Optimized build.
  Default target: x86_64-pc-windows-msvc
  Host CPU: haswell

### Visual Studio Version:
Microsoft Visual Studio Professional 2017 Version 15.9.11

### Clang Power Tools Version:
4.10.2

### Project:
[AccessibleDescriptionAndHelpExample](https://svn.sullivanandkey.com/SnKOpen/cpp/AccessibleDescriptionAndHelpExample/trunk/)

**Comment by hero101111** [comment]
We've just pushed a fix for this. It will be included in the next release of Clang Power Tools.

Thank you for taking the time to give feedback. Your help is greatly appreciated.


Regards,
Gabriel.
