### ISSUE TITLE
clang-tidy restarts Visual Studio 2019

### ISSUE THREAD

**Issue by ScottHutchinson** [Caphyon/clang-power-tools#594]
Running tidy from the toolbar with this repo open causes Visual Studio 2019 to restart: https://github.com/ScottHutchinson/grade-school

**Comment by hprica** [comment]
Thank you for reporting the issue.

Unfortunately, we do not support running Clang Compile and Tidy on CMake projects at this time. We plan to do so in the near future.

**Comment by ScottHutchinson** [comment]
OK. It seems to me that you should have linked this to the open issue (or whatever) that will resolve this in the "near future". Thanks

**Comment by hprica** [comment]
Forgot to link the issue, thanks for reminding me :)
https://github.com/Caphyon/clang-power-tools/issues/605
