### ISSUE TITLE
ForcedIncludeFiles field not correctly parsed

### ISSUE THREAD

**Issue by jcageman** [Caphyon/clang-power-tools#60]
Hi,

%(ForcedIncludeFiles) in the ForcedIncludeFiles field in .vcxproj is passed to clang, while this is a field that should be ignored, instead the inherited value should be parsed. See below repro.

[TidyRepro.zip](https://github.com/Caphyon/clang-power-tools/files/1413630/TidyRepro.zip)

**Comment by cpp-red-lion** [comment]
Oops!
Thanks for that one.
I think this a more general issue.
Eg.

`<AdditionalIncludeDirectories>%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>`

`<ForcedIncludeFiles>%(ForcedIncludeFiles)</ForcedIncludeFiles>`

**Comment by cpp-red-lion** [comment]
Depends on #61

**Comment by hero101111** [comment]
This issue was [resolved](https://github.com/Caphyon/clang-power-tools/commit/8555b7bf7d11083be693fc8b0dc0e09004893de4)
