### ISSUE TITLE
Ignore individual clang-tidy checks

### ISSUE THREAD

**Issue by s7jones** [Caphyon/clang-power-tools#601]
I am using "custom checks", and I am trying to enable whole sets of the checks and then opt out of individual checks within that set.

Here is an example of a use case:

`cppcoreguidelines-*;
misc-*;
-cppcoreguidelines-avoid-magic-numbers;
-misc-non-private-member-variables-in-classes;`

Although unfortunately `cppcoreguidelines-avoid-magic-numbers` and `misc-non-private-member-variables-in-classes` are still being reported when I run clang-tidy through Power Tools.

Am I doing something wrong?
Is this feature possible (if it isn't already implemented)?

**Comment by mariru27** [comment]
Hi @s7jones,

Try to update to latest release [Clang Power Tools v2023.6.0](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools)
Do you have the same problem?

Kind regards,
Marina
