### ISSUE TITLE
Rebuild the VS project parser to properly support inherited values from property-sheets

### ISSUE THREAD

**Issue by cpp-red-lion** [Caphyon/clang-power-tools#61]
Eg.

`<AdditionalIncludeDirectories>` 
&nbsp;&nbsp; `loacal_value;%(AdditionalIncludeDirectories)`
`</AdditionalIncludeDirectories>`

`<ForcedIncludeFiles>%(ForcedIncludeFiles)</ForcedIncludeFiles>`

Basically,

`<AnyVSProp>loacal_value;%(AnyVSProp)</AnyVSProp>`

**Comment by hero101111** [comment]
[Implemented](https://github.com/Caphyon/clang-power-tools/commit/8555b7bf7d11083be693fc8b0dc0e09004893de4)

**Comment by cpp-red-lion** [comment]
This issue was fixed in version 1.5
https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools
