### ISSUE TITLE
Add ability to format line

### ISSUE THREAD

**Issue by jarruda** [Caphyon/clang-power-tools#612]
This is an essential feature when working in legacy or external codebases where you would like to have any new code written auto-formatted, but you would not like to touch any other code.  The Clang Format extension supports this via the Tools menu and the Ctrl-K, Ctrl-F hotkey.

**Comment by Enache-Ionut** [comment]
Hi,

This functionality is already implemented. All you need to do is to select the code area in the VS Editor and press the `Format` button from the toolbar. In this way, you will be able to apply clang format on a code section (single line/block of code).

We will add shortcuts in a future release for all the `Clang Power Tools` commands.
