### ISSUE TITLE
compile not just active editor file from shortcut

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#614]
The issue fixed in  #576 applies to launch from clicking on the toolbar. That appears fixed, however it still exists if the compile issued through keyboard command. 

- Assign Keyboard shortcut for the clang/compile command (Alt-C for me)
- press Alt-C on a source file in the editor 
-> compiles using selection in the solution explorer.

(obviously disable the tracking option for SE)

**Comment by Enache-Ionut** [comment]
Hi, 

I'm happy to announce you that this small issue was fixed and it will be available in the next release. 

Thank you for your feedback!
