### ISSUE TITLE
Add the possibility the generate config files from Visual Studio Plugin

### ISSUE THREAD

**Issue by ironfey** [Caphyon/clang-power-tools#620]
It would be extremely handy to have a button to generate the cpt.config, .clang-tidy etc. from within the visual studio plugin. I.e. select options including checks in visual studio, have e.g. an Export config button to export according to selection and then have configuration ready for CI and version control.

**Comment by s-martin** [comment]
This incorporates #478

**Comment by Enache-Ionut** [comment]
Hi, 

We are happy to announce the release of [Clang Power Tools version 5.1](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools). This issue was fixed so please check for updates. 

Thank you for your feedback 😃
