### ISSUE TITLE
Wrong SDK include directories with "latest installed version" setting

### ISSUE THREAD

**Issue by matbech** [Caphyon/clang-power-tools#622]
**Issue**
When the project's Windows SDK Version setting is set to "**10.0 (latest installed version)**":
``<WindowsTargetPlatformVersion>10.0</WindowsTargetPlatformVersion>``
clang-power-tools uses the following include directories:
VERBOSE: WinSDK version: 10.0
C:\Program Files (x86)\Windows Kits\10\Include\10.0\cppwinrt
etc.
However, these directories do not exist. What I'm expecting is that it uses the latest SDK version 10.0.18362.0 (see below).

When the project's Windows SDK Version setting is set to "**10.0.18362.0**" the correct include directories are used:
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt
etc.

So it seems to me that clang-power-tools is not able to find the "latest installed version" of the SDK.

Using clang-power-tools 4.10.5 with Visual Studio 2019 Preview 16.2.0 Preview 2.

**Cause**
The problem is here:
https://github.com/Caphyon/clang-power-tools/blob/master/ClangPowerTools/ClangPowerTools/psClang/msbuild-project-data.ps1#L297
If the $sdkVer is "10.0" it should look for the latest version, instead of using it as the name of the directory.

**Workaround**
C:\Program Files (x86)\Windows Kits\10\Include>mklink /J 10.0 10.0.18362.0

**Comment by hero101111** [comment]
Hello,

Thank you for taking the time to report this issue.
We are investigating it and will get back to you as soon as progress is made.

Regards,
Gabriel.

**Comment by hero101111** [comment]
Pleased to inform you that we've just pushed a fix for this issue. It will get published soon as part of a bug-fix release (`v4.10.6`).
Your thorough instructions have been truly helpful in solving this. Thank you.

Regards,
Gabriel.
