### ISSUE TITLE
Error window is stealing focus

### ISSUE THREAD

**Issue by gyzkard** [Caphyon/clang-power-tools#624]
Similar to https://github.com/Caphyon/clang-power-tools/issues/35 the error window is stealing the focus, essentially making it impossible to work in the editor while tidy is running.

The reason is
```
public void OnErrorDetected(object sender, ErrorDetectedEventArgs e) { UIUpdater.Invoke(() => {
//...
          BringToFront(); // <--
```
Error\ErrorWindowController.cs

Removing that call or a dedicated option to opt out of BringToFront would be great.

**Comment by Enache-Ionut** [comment]
Hi,

First of all, I want to thank you for your feedback. A dedicated option for this behavior is on our list. We'll update this thread when we will make progress with this improvement so stay tuned.

Regards,
Ionut

**Comment by Enache-Ionut** [comment]
Hi, 

This issue is fixed and it will be released in the next version of Clang Power Tools. 
Thank you for your feedback!

Regards,
Ionut
