### ISSUE TITLE
CPT 5 requires internet access

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#629]
Just upgraded to CPT 5, and tried to use it, but it keeps bringing up an option to "Login to use Clang Power Tools"

This is simply not possible for dev machines that are not networked! which means CPT can no longer be used.

Please do not force "Login" there needs to be a way to use in offline environments.

**Comment by hprica** [comment]
@netx123 sorry for the inconvenience. In the next release, we will create an automatic way of activating an account offline. 

For now, please write an email to **clangpowertools@caphyon.com** for the workaround steps to activate offline.

**Comment by CharonX2003** [comment]
Seriously, WTF.

You **require** internet access to use the tool.
You **require** users to (pointlessly) register an account.
And then your registration is **broken** so confirmation e-mails don't arrive so users can't actually use your tool.

What the **hell** were you thinking that this would be a good idea?

**Comment by hprica** [comment]
For offline activation, you can use our dedicated [page](https://clangpowertools.com/offline-activation.html).
