### ISSUE TITLE
No output from clang

### ISSUE THREAD

**Issue by ImanHosseini** [Caphyon/clang-power-tools#633]
I just installed clang tools, made a "hello world" project (no PCH, no nothing) and tried clang power tools for compilation/tidy and everything fails! Here is the log:
[I have working llvm, and running clang/tidy manually from cmd/powershell works fine]

--- CLANG COMPILE STARTED ---

VERBOSE: clang-build.ps1 invocation args: 
  aVcxprojToCompile = C:\Users\Iman\source\repos\Ca\Ca\Ca.vcxproj 
  aCppToCompile = C:\Users\Iman\source\repos\Ca\Ca\Ca.cpp 
  aVcxprojConfigPlatform = Debug|Win32 
  aClangCompileFlags = -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas
 -Wno-unused-value 
  Verbose = True 
  aUseParallelCompile = True 
  aVisualStudioVersion = 2019 
  aVisualStudioSku = Enterprise 
  aSolutionsPath = C:\Users\Iman\source\repos\Ca\Ca.sln 
VERBOSE: CPU logical core count: 4
VERBOSE: Scanning for solution files
VERBOSE: Caching solution file C:\Users\Iman\source\repos\Ca\Ca.sln
VERBOSE: Solution full path: C:\Users\Iman\source\repos\Ca\Ca.sln
VERBOSE: Solution data length: 1392
VERBOSE: Solution file paths:
VERBOSE:   C:\Users\Iman\source\repos\Ca\Ca.sln
VERBOSE: 
VERBOSE: Source directory: C:\Users\Iman\source\repos\Ca\
VERBOSE: Scanning for project files
VERBOSE: Retrieving project list for solution C:\Users\Iman\source\repos\Ca\Ca.sln
VERBOSE: Solution directory: C:\Users\Iman\source\repos\Ca\
VERBOSE: Intermediate solution project matches count: 1
VERBOSE: Ca\Ca.vcxproj
VERBOSE: Found 1 projects
VERBOSE: PROCESSING ALL PROJECTS
PROJECT: C:\Users\Iman\source\repos\Ca\Ca\Ca.vcxproj
VERBOSE: Deleting variables initialized by previous project:
VERBOSE: 
VERBOSE: Importing environment variables into current scope
VERBOSE: SET_VAR ALLUSERSPROFILE: C:\ProgramData
VERBOSE: SET_VAR ANDROID_HOME: C:\Android\android-sdk
VERBOSE: SET_VAR APPDATA: C:\Users\Iman\AppData\Roaming
VERBOSE: SET_VAR ChocolateyInstall: C:\ProgramData\chocolatey
VERBOSE: SET_VAR ChocolateyLastPathUpdate: Fri Jun 15 06:36:50 2018
VERBOSE: SET_VAR CommonProgramFiles: C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramW6432: C:\Program Files\Common Files
VERBOSE: SET_VAR COMPUTERNAME: DESKTOP-3LV3FIC
VERBOSE: SET_VAR ComSpec: C:\WINDOWS\system32\cmd.exe
VERBOSE: SET_VAR DriverData: C:\Windows\System32\Drivers\DriverData
VERBOSE: SET_VAR FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
VERBOSE: SET_VAR FPS_BROWSER_USER_PROFILE_STRING: Default
VERBOSE: SET_VAR GOPATH: C:\Users\Iman\go
VERBOSE: SET_VAR GOROOT: C:\Go\
VERBOSE: SET_VAR GPA_GLOBAL_INJECTION_MODE: DX12
VERBOSE: SET_VAR GPA_NEW_MONITOR: true
VERBOSE: SET_VAR GRADLE_HOME: C:\ProgramData\chocolatey\lib\gradle\tools\gradle-4.8
VERBOSE: SET_VAR HOMEDRIVE: C:
VERBOSE: SET_VAR HOMEPATH: \Users\Iman
VERBOSE: SET_VAR INTEL_SEA_FILTER: C:\Users\Iman\Documents\GPA\domain.fltr
VERBOSE: SET_VAR INTELGTDEBUGGERROOT: C:\Intel\OpenCL\debugger\
VERBOSE: SET_VAR INTELOCLPATH: C:\Intel\OpenCL\sdk\bin\x64;C:\Intel\OpenCL\sdk\bin\x86
VERBOSE: SET_VAR INTELOCLSDKROOT: C:\Intel\OpenCL\sdk\
VERBOSE: SET_VAR MSBuildLoadMicrosoftTargetsReadOnly: true
VERBOSE: SET_VAR NUMBER_OF_PROCESSORS: 4
VERBOSE: SET_VAR OneDrive: C:\Users\Iman\OneDrive
VERBOSE: SET_VAR OneDriveConsumer: C:\Users\Iman\OneDrive
VERBOSE: SET_VAR OS: Windows_NT
VERBOSE: SET_VAR Path: C:\Program 
Files\Haskell\bin;C:\Intel\OpenCL\sdk\bin\x64;C:\Intel\OpenCL\sdk\bin\x86;C:\Intel\OpenCL\sdk\bin\Pin;C:\Intel\OpenCL\s
dk\bin\GTPin;C:\Program Files (x86)\Common 
Files\Oracle\Java\javapath;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;
C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\iverilog\bin;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;
C:\Program Files\nodejs\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\Microsoft SQL 
Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\10\Windows Performance 
Toolkit\;C:\Go\bin;C:\metasploit-framework\bin\;C:\ProgramData\ComposerSetup\bin;C:\PostgreSQL\pg11\bin;C:\Program 
Files\Git\cmd;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files 
(x86)\Brackets\command;C:\Program Files\PuTTY\;C:\Program 
Files\CMake\bin;C:\llvm\bin;C:\LLVM9\bin;C:\MinGW\bin;C:\Program 
Files\dotnet\;C:\Ruby26-x64\bin;C:\Users\Iman\.cargo\bin;C:\Users\Iman\AppData\Roaming\local\bin;C:\Users\Iman\AppData\
Roaming\cabal\bin;C:\Ruby24-x64\bin;C:\Users\Iman\AppData\Roaming\OCamlPro\OCPWin\wrappers;C:\Users\Iman\AppData\Roamin
g\OCamlPro\OCPWin\4.02.1+ocp1-msvc64-20160113\bin;C:\Users\Iman\AppData\Local\Microsoft\WindowsApps;C:\modeltech64_10.5
\win64;C:\Program 
Files\Java\jdk1.8.0_121\bin;C:\Users\Iman\AppData\Local\.meteor;C:\Users\Iman\AppData\Roaming\npm;C:\chromeDriver;C:\Us
ers\Iman\Downloads\Programs\WinPython\python-3.6.5.amd64;C:\Users\Iman\Downloads\Programs\WinPython\python-3.6.5.amd64\
Scripts;C:\Users\Iman\go\bin;C:\Users\Iman\AppData\Local\GitHubDesktop\bin;C:\Program 
Files\Racket;C:\wamp64\bin\php\php7.0.10;C:\Users\Iman\Documents\nikto-2.1.5;C:\maven\apache-maven-3.2.2-bin\apache-mav
en-3.2.2\bin;C:\Users\Iman\AppData\Roaming\Composer\vendor\bin;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common
 Files\Intel\WirelessCommon\;C:\Program 
Files\Docker\Docker\resources\bin;C:\Projects\ANTLR\bin;C:\MinGW\bin;C:\Users\Iman\Desktop\Ant\apache-ant-1.9.14-bin\ap
ache-ant-1.9.14\bin;C:\Program Files\heroku\client\bin;;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps
VERBOSE: SET_VAR PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.RB;.RBW;.CPL
VERBOSE: SET_VAR PkgDefApplicationConfigFile: 
C:\Users\Iman\AppData\Local\Microsoft\VisualStudio\16.0_d3658c42\devenv.exe.config
VERBOSE: SET_VAR PROCESSOR_ARCHITECTURE: x86
VERBOSE: SET_VAR PROCESSOR_ARCHITEW6432: AMD64
VERBOSE: SET_VAR PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
VERBOSE: SET_VAR PROCESSOR_LEVEL: 6
VERBOSE: SET_VAR PROCESSOR_REVISION: 8e09
VERBOSE: SET_VAR ProgramData: C:\ProgramData
VERBOSE: SET_VAR ProgramFiles: C:\Program Files (x86)
VERBOSE: SET_VAR ProgramFiles(x86): C:\Program Files (x86)
VERBOSE: SET_VAR ProgramW6432: C:\Program Files
VERBOSE: SET_VAR PSExecutionPolicyPreference: Unrestricted
VERBOSE: SET_VAR PSModulePath: C:\Program 
Files\WindowsPowerShell\Modules;C:\Users\Iman\Documents\WindowsPowerShell\Modules;C:\Program Files 
(x86)\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
VERBOSE: SET_VAR PUBLIC: C:\Users\Public
VERBOSE: SET_VAR QUARTUS_ROOTDIR: C:\altera\12.1\quartus
VERBOSE: SET_VAR SESSIONNAME: Console
VERBOSE: SET_VAR SOPC_KIT_NIOS2: C:\altera\12.1\nios2eds
VERBOSE: SET_VAR STACK_ROOT: C:\sr
VERBOSE: SET_VAR SystemDrive: C:
VERBOSE: SET_VAR SystemRoot: C:\WINDOWS
VERBOSE: SET_VAR TEMP: C:\Users\Iman\AppData\Local\Temp
VERBOSE: SET_VAR TEST_BROWSER_DRIVER: chrome
VERBOSE: SET_VAR ThreadedWaitDialogDpiContext: -4
VERBOSE: SET_VAR TMP: C:\Users\Iman\AppData\Local\Temp
VERBOSE: SET_VAR USERDOMAIN: DESKTOP-3LV3FIC
VERBOSE: SET_VAR USERDOMAIN_ROAMINGPROFILE: DESKTOP-3LV3FIC
VERBOSE: SET_VAR USERNAME: Iman
VERBOSE: SET_VAR USERPROFILE: C:\Users\Iman
VERBOSE: SET_VAR VisualStudioDir: C:\Users\Iman\Documents\Visual Studio 2019
VERBOSE: SET_VAR VisualStudioEdition: Microsoft Visual Studio Enterprise 2019
VERBOSE: SET_VAR VisualStudioVersion: 16.0
VERBOSE: SET_VAR VS140COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VERBOSE: SET_VAR VSAPPIDDIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\
VERBOSE: SET_VAR VSAPPIDNAME: devenv.exe
VERBOSE: SET_VAR VSLANG: 1033
VERBOSE: SET_VAR VSSKUEDITION: Enterprise
VERBOSE: SET_VAR windir: C:\WINDOWS
VERBOSE: SET_VAR MSBuildProjectFullPath: C:\Users\Iman\source\repos\Ca\Ca\Ca.vcxproj
VERBOSE: SET_VAR ProjectDir: C:\Users\Iman\source\repos\Ca\Ca\
VERBOSE: SET_VAR MSBuildProjectExtension: .vcxproj
VERBOSE: SET_VAR MSBuildProjectFile: Ca.vcxproj
VERBOSE: SET_VAR MSBuildProjectName: Ca
VERBOSE: SET_VAR MSBuildProjectDirectory: C:\Users\Iman\source\repos\Ca\Ca\
VERBOSE: SET_VAR MSBuildProgramFiles32: C:\Program Files (x86)
VERBOSE: SET_VAR ProjectName: Ca
VERBOSE: SET_VAR TargetName: Ca
VERBOSE: SET_VAR UserRootDir: C:\Users\Iman\AppData\Local\Microsoft\MSBuild\v4.0
VERBOSE: SET_VAR VisualStudioVersion: 16.0
VERBOSE: SET_VAR MSBuildToolsVersion: 16.0
VERBOSE: Retrieving project list for solution C:\Users\Iman\source\repos\Ca\Ca.sln
VERBOSE: Solution directory: C:\Users\Iman\source\repos\Ca\
VERBOSE: Intermediate solution project matches count: 1
VERBOSE: Ca\Ca.vcxproj
VERBOSE: SET_VAR SolutionDir: C:\Users\Iman\source\repos\Ca\
VERBOSE: SET_VAR SolutionName: Ca
VERBOSE: 
Sanitizing C:\Users\Iman\source\repos\Ca\Ca\Ca.vcxproj
VERBOSE: SET_VAR MSBuildThisFileFullPath: C:\Users\Iman\source\repos\Ca\Ca\Ca.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: Ca.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: Ca
VERBOSE: SET_VAR MSBuildThisFileDirectory: C:\Users\Iman\source\repos\Ca\Ca\
VERBOSE: [CONTEXT] item namespace = @(ProjectConfiguration)
VERBOSE: SET_VAR CPT_PROJITEM_ProjectConfiguration: 
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: SET_VAR Configuration: Debug
VERBOSE: SET_VAR Platform: Win32
VERBOSE: SET_VAR VCProjectVersion: 16.0
VERBOSE: SET_VAR ProjectGuid: {4D19B46E-9AC4-4DDF-85E7-62835588819B}
VERBOSE: SET_VAR Keyword: Win32Proj
VERBOSE: SET_VAR RootNamespace: Ca
VERBOSE: SET_VAR WindowsTargetPlatformVersion: 10.0
VERBOSE: Could not find property sheet \Microsoft.Cpp.Default.props
VERBOSE: SET_VAR ConfigurationType: Application
VERBOSE: SET_VAR UseDebugLibraries: true
VERBOSE: SET_VAR PlatformToolset: v142
VERBOSE: SET_VAR CharacterSet: Unicode
VERBOSE: Could not find property sheet \Microsoft.Cpp.props
VERBOSE: Property sheet: C:\Users\Iman\AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props
VERBOSE: 
Sanitizing C:\Users\Iman\AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props
VERBOSE: SET_VAR MSBuildThisFileFullPath: 
C:\Users\Iman\AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props
VERBOSE: SET_VAR MSBuildThisFileExtension: .props
VERBOSE: SET_VAR MSBuildThisFile: Microsoft.Cpp.Win32.user.props
VERBOSE: SET_VAR MSBuildThisFileName: Microsoft.Cpp.Win32.user
VERBOSE: SET_VAR MSBuildThisFileDirectory: C:\Users\Iman\AppData\Local\Microsoft\MSBuild\v4.0\
VERBOSE: SET_VAR MSBuildThisFileFullPath: C:\Users\Iman\source\repos\Ca\Ca\Ca.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: Ca.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: Ca
VERBOSE: SET_VAR MSBuildThisFileDirectory: C:\Users\Iman\source\repos\Ca\Ca\
VERBOSE: SET_VAR LinkIncremental: true
VERBOSE: [CONTEXT] item namespace = @(ClCompile)
VERBOSE: [CONTEXT] propSet: PrecompiledHeader = 
VERBOSE: [CONTEXT] propSet: WarningLevel = Level3
VERBOSE: [CONTEXT] propSet: Optimization = Disabled
VERBOSE: [CONTEXT] propSet: SDLCheck = true
VERBOSE: [CONTEXT] propSet: PreprocessorDefinitions = WIN32;_DEBUG;_CONSOLE;
VERBOSE: [CONTEXT] propSet: ConformanceMode = true
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(Link)
VERBOSE: [CONTEXT] propSet: SubSystem = Console
VERBOSE: [CONTEXT] propSet: GenerateDebugInformation = true
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(ClCompile)
VERBOSE: SET_VAR CPT_PROJITEM_ClCompile: 
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: Could not find property sheet \Microsoft.Cpp.targets
VERBOSE: Platform toolset: v142
VERBOSE: [CONTEXT] item namespace = @(ClCompile)
VERBOSE: Force includes:
VERBOSE:   
VERBOSE: 
VERBOSE: Preprocessor definitions:
VERBOSE:   "-DUNICODE"
VERBOSE:   "-D_UNICODE"
VERBOSE:   "-D_MT"
VERBOSE:   "-D_DLL"
VERBOSE:   "-DWIN32"
VERBOSE:   "-D_DEBUG"
VERBOSE:   "-D_CONSOLE"
VERBOSE:   "-D_DEBUG_FUNCTIONAL_MACHINERY"
VERBOSE: 
VERBOSE: Additional include directories:
VERBOSE: 
VERBOSE: Detected (vswhere) VisualStudio installation path: C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise
VERBOSE: Visual Studio location: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
VERBOSE: Detected (vswhere) VisualStudio installation path: C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise
VERBOSE: MSCVER: 14.21.27702
VERBOSE: WinSDK version: 10.0
VERBOSE: Include directories:
VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.21.27702\include
VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.21.27702\atlmfc\include
VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\VS\include
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt
VERBOSE: 
VERBOSE: PCH not enabled for this project!
VERBOSE: Processing 1 cpps
VERBOSE: INVOKE: "\clang++.exe" -x c++ "C:\Users\Iman\source\repos\Ca\Ca\Ca.cpp" -std=c++14 -Wall 
-fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas -Wno-unused-value -m32 
-fsyntax-only "-DUNICODE" "-D_UNICODE" "-D_MT" "-D_DLL" "-DWIN32" "-D_DEBUG" "-D_CONSOLE" 
"-D_DEBUG_FUNCTIONAL_MACHINERY" -isystem"C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise\VC\Tools\MSVC\14.21.27702\include" -isystem"C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise\VC\Tools\MSVC\14.21.27702\atlmfc\include" -isystem"C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise\VC\Auxiliary\VS\include" -isystem"C:\Program Files (x86)\Windows 
Kits\10\Include\10.0.17763.0\ucrt" -isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um" 
-isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared" -isystem"C:\Program Files (x86)\Windows 
Kits\10\Include\10.0.17763.0\winrt" -isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt"
1: C:\Users\Iman\source\repos\Ca\Ca\Ca.cpp
Write-Err : Cannot bind argument to parameter 'msg' because it is an empty string.
At C:\users\iman\appdata\local\microsoft\visualstudio\16.0_d3658c42\extensions\tf4z4zsq.im5\clang-build.ps1:668 char:15
+     Write-Err ($compileResult.Output)
+               ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Err], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Write-Err
 
Got errors.
VERBOSE: Cleaning up PCH temporaries:
VERBOSE: 

--- CLANG COMPILE FINISHED ---

**Comment by hero101111** [comment]
Hello @ImanHosseini 

Please attach a sample project we can use to investigate this issue.

Regards,
Gabriel.

**Comment by ImanHosseini** [comment]
[Ca.zip](https://github.com/Caphyon/clang-power-tools/files/3381640/Ca.zip)
Here is a sample project, but there is really nothing here: This is what you get in VS when you click on "Console Project", nothing is changed, just a fresh, hello world.

**Comment by hero101111** [comment]
Thank you for the sample project.

Unfortunately, I cannot reproduce the issue. Everything works as expected on our machines (VS 2019 + LLVM 8). I've noticed that you have two LLVM bin paths added to your `%PATH%` environment variable (`C:\llvm\bin` and `C:\LLVM9\bin` respectively). I suspect this to be the source of the issue you're encontering. 

LLVM 9 is not officially supported by Clang Power Tools at this point. Please remove it from `PATH`, restart Visual Studio and try again.

**Comment by ImanHosseini** [comment]
Thanks Gabriel, 
Indeed that was the issue! Sadly, LLVM 9 does not work.

**Comment by hero101111** [comment]
You're welcome. We'll get CPT and LLVM 9 working together as soon as possible once official builds are out.

Kind regards,
Gabriel.
