### ISSUE TITLE
Registration for Free use

### ISSUE THREAD

**Issue by degski** [Caphyon/clang-power-tools#641]
I would like to ask why you would need my e-mail account, if and when I intend to use `CPT` as the free version. The only intent I can see is `evil` and as Google **used** to say, `don't be evil`! 

If I have to hand you my e-mail account, it's no longer a free plugin, I've now become the product.

Needless to say, I immediately uninstalled.

I guess, a fork [done] and a revert of a couple of commits is in order [to be done].

**Comment by cpp-red-lion** [comment]
I’m sorry you feel this way.

Hi,

We didn’t think signing up with an email to use a free product is too much of an imposition. You could definitely use a SPAM email address if you’d like; there are plenty of services like that available if you don’t trust us with your real email. 

Happy coding !

**Comment by degski** [comment]
The question is: "Why do you need [even a fake] email address"?

**Comment by cpp-red-lion** [comment]
Because it’s easier to use the same workflow and SKU both for personal (non-commercial) and commercial usage:
https://clangpowertools.com/download.html
