### ISSUE TITLE
can't login via https proxy from VS 2017

### ISSUE THREAD

**Issue by ClausKlein** [Caphyon/clang-power-tools#642]
1930 | 46.302249 | HTTP | 141 | CONNECT account.clangpowertools.com:443 HTTP/1.1 |  
1932 | 46.328533 | HTTP | 88 | HTTP/1.1 407 Proxy Authentication Required  (text/html) |

**Comment by hero101111** [comment]
Closing this issue as issue cannot be reproduced using latest Clang Power Tools.
