### ISSUE TITLE
CPT overrides classic Windows Alt Menu shortcuts

### ISSUE THREAD

**Issue by costypetrisor** [Caphyon/clang-power-tools#644]
Hi,

I use a lot in all software the classic Windows Alt  Menu shortcuts, so for instance for Visual Studio if I want to close a project quickly: `Alt+f`, 't'.
Since today, CPT blocks my ability to use any of the shortcuts from the File or Tools menu (`Alt+f`, `Alt+t`), and it opens a pop-up requiring me to create an account, and that pop-ul can't even be closed from the keyboard at all :( (tragically I have to use a mouse).

I didn't create an account to see if this is fixed if logged-in with a CPT account, because I don't want an account.

Thanks,
Costy

**Comment by hprica** [comment]
Hi Costi,

The issue will be fixed in the next release :)
