### ISSUE TITLE
Improvement: usability of settings dialog

### ISSUE THREAD

**Issue by s-martin** [Caphyon/clang-power-tools#666]
I  really like the new settings dialog, but I have a few suggestions for improvement:

- provide OK/Cancel buttons: personally I find dialogs difficult without explicit OK button, because I'm not sure, if changes have been applied
- improve selection for predefined tidy checks: as there are many checkboxes a few helpers would be nice: provide "Select All" buttons or make it possible to select multiple rows either with SHIFT/CTRL or CTRL+A and select/deselect entries with SPACE

Thanks!

**Comment by Enache-Ionut** [comment]
Hi,

We'll address this issue in a future release. Thank you for your feedback.

Meanwhile, the new version of [Clang Power Tools v5.3](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools) was just released. Please check for updates.

Regards,
~Ionut

**Comment by Enache-Ionut** [comment]
Hi, 

We are glad to announce you that the next version of Clang Power Tools will have `Enable All` tidy-checks possibility. Keep in mind that the feature can be used in combination with the `Search` filter. We also included a `Default Checks` button which will allow you to reset the checks back to the default ones.

For the multiple Clang tidy checks selection, I created a new issue. You can follow the issue status here: https://github.com/Caphyon/clang-power-tools/issues/812 

Regarding the `OK` and `Cancel` buttons we decided to not introduce them in the UI. Our goal is to create a modern user interface with Windows 10 style accents.

Regards,
~Ionut
