### ISSUE TITLE
Automatically run clang-format after clang-tidy

### ISSUE THREAD

**Issue by cpp-red-lion** [Caphyon/clang-power-tools#67]
Use clang-format config file if found, or built-in preset config.
Don't sort includes.
 Needs a new node in VS settings

**Comment by cpp-red-lion** [comment]
Depends on #68

**Comment by cpp-red-lion** [comment]
Use the `-format-style` clang-tidy.exe switch.

-format-style = Style for formatting code around applied fixes:
                          - 'none' (default) turns off formatting
                          - 'file' (literally 'file', not a placeholder) uses .clang-format file in the closest parent directory
                          - 'llvm', 'google', 'webkit', 'mozilla'

**Comment by chri7325** [comment]
If you are using the VS plugin for this, you can also set `FormatStyle: file` in your project's .clang-tidy file.  I could be wrong about this but clang-format code might be built into clang-tidy as it properly formats things for me even though I don't have clang-format on my system path.

**Comment by cpp-red-lion** [comment]
Indeed, @chri7325, when using `.clang-tidy` config file (with *FormatStyle:*) it will work auto-magically :)

But, not everybody uses a config file, so we'll also provide dedicated UI in *Settings* for configuring **clang-format** => Depends on #68

**Comment by Enache-Ionut** [comment]
This issue was fixed and it will be available in the next version.
