### ISSUE TITLE
Install LLVM

### ISSUE THREAD

**Issue by Enache-Ionut** [Caphyon/clang-power-tools#675]

**Comment by hprica** [comment]
1. Create an environment variable to store LLVM path
2. Change the variable depending on the version selected
3. Store versions in ProgramFiles or AppData
4. Create a custom tab in settings
5. Download and install selected LLVM version (have a progression bar in the UI)
6. The script first checks if the environment variable is set, if now it checks the PATH variable
7. Make the installer silent or minimal UI
8. Inform the user in the LLVM tab where the versions are stored

**Comment by Enache-Ionut** [comment]
Hi,

This issue was fixed and it is available in the new version of [Clang Power Tools v5.3](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools). Please check for updates. 

Regards,
~Ionut
