### ISSUE TITLE
Crash first time executed

### ISSUE THREAD

**Issue by jalegido** [Caphyon/clang-power-tools#681]
Each time I install clang power tools in vs2015 system informs a crash and disabled it.
In C:\Users\XXXXXX\AppData\Roaming\Microsoft\VisualStudio\14.0\ActivityLog.xml visual studio says:
  <entry>
    <record>588</record>
    <time>2019/09/18 16:49:04.698</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [RunClangPowerToolsPackage]Source: &apos;ClangPowerTools&apos; Description: Object reference not set to an instance of an object.&#x000D;&#x000A;System.NullReferenceException: Object reference not set to an instance of an object.&#x000D;&#x000A;   at ClangPowerTools.SettingsHandler.MapClangFormatOptionsToSettings(ClangFormatOptions clangFormat)&#x000D;&#x000A;   at ClangPowerTools.SettingsHandler.MapOldSettings()&#x000D;&#x000A;   at ClangPowerTools.SettingsHandler.ImportOldSettings()&#x000D;&#x000A;   at ClangPowerTools.SettingsHandler.InitializeSettings()&#x000D;&#x000A;   at ClangPowerTools.RunClangPowerToolsPackage.&lt;InitializeAsync&gt;d__13.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#x000D;&#x000A;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)&#x000D;&#x000A;   at Microsoft.VisualStudio.Services.VsTask.GetResult()</description>
    <guid>{F564F9D3-01AE-493E-883B-18DEEBDB975E}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>589</record>
    <time>2019/09/18 16:49:04.879</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [RunClangPowerToolsPackage]</description>
    <guid>{F564F9D3-01AE-493E-883B-18DEEBDB975E}</guid>
    <hr>80004003 - E_POINTER</hr>
    <errorinfo></errorinfo>
  </entry>

with an exception:
SetSite failed for package [RunClangPowerToolsPackage]Source: 
&apos;ClangPowerTools&apos; Description: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ClangPowerTools.SettingsHandler.MapClangFormatOptionsToSettings(ClangFormatOptions clangFormat)
   at ClangPowerTools.SettingsHandler.MapOldSettings()
   at ClangPowerTools.SettingsHandler.ImportOldSettings()
   at ClangPowerTools.SettingsHandler.InitializeSettings()
   at ClangPowerTools.RunClangPowerToolsPackage.&lt;InitializeAsync&gt;d__13.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Shell.AsyncPackage.&lt;&gt;c__DisplayClass16_0.&lt;&lt;Microsoft-VisualStudio-Shell-Interop-IAsyncLoadablePackageInitialize-Initialize&gt;b__1&gt;d.MoveNext()
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.VisualStudio.Services.VsTask.RethrowException(AggregateException e)
   at Microsoft.VisualStudio.Services.VsTask.InternalGetResult(Boolean ignoreUIThreadCheck)
   at Microsoft.VisualStudio.Services.VsTask.GetResult()

**Comment by Enache-Ionut** [comment]
Hi,

We'll address this issue in a future release. Thank you for your feedback.

Meanwhile, the new version of [Clang Power Tools v5.3](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools) was just released. Please check for updates.

Regards,
~Ionut

**Comment by Enache-Ionut** [comment]
Unfortunately, we can't reproduce the issue. Are you reproducing this crash in the latest version of Clang Power Tools (v5.3)? If it is still present, then can you tell us how are you trying to install our extension: via Visual Studio -> Tools -> Extensions and Updates panel or via Visual Studio marketplace?

**Comment by jalegido** [comment]
Since Clang Powers Tools v5.3 I can not use it again. All Clang Power tools options are shown disabled except "settings". But if I select menu popup: Clang Power Tools -> Settings on any cpp file; system doesn't show any dialog.

To install this tool I use "Extensions and Updates panel "

**Comment by Enache-Ionut** [comment]
We are still trying to find a solution to this issue. Can you manually delete all the user configuration files from the `%appdata%/ClangPowerTools` folder? In this way, the extension will have a fresh start-up.

If the issue is still there after the configuration files were deleted, can you please attach a sample project reproducing the issue? It will be a great help to us.

**Comment by jalegido** [comment]
I've delete all in `%appdata%/ClangPowerTools` folder and all starts to work with version 5.3

Thank you so much

**Comment by Enache-Ionut** [comment]
I'm glad to hear that everything works properly now 😃  Sorry for the inconvenience.

I want to let you know that any feedback is preciose to us, so feel free to share your thoughts about Clang Power Tools with us.

For any other issue, we are here to help.

Regards,
~Ionut
