### ISSUE TITLE
Incorrect WinSDK Detection

### ISSUE THREAD

**Issue by bjehlert** [Caphyon/clang-power-tools#685]
Windows SDK set outside the vcxproj file is not being detected correctly.

In the attached sample, the WinSDK is set to 10.0.18362.0 for x64 inside globals.xml. The vcxproj file imports that, but the verbose output still says:

```
VERBOSE: WinSDK version: 8.1
VERBOSE: Include directories:
VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include
VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\atlmfc\include
VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\VS\include
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
VERBOSE:   C:\Program Files (x86)\Windows Kits\8.1\Include\um
VERBOSE:   C:\Program Files (x86)\Windows Kits\8.1\Include\shared
VERBOSE:   C:\Program Files (x86)\Windows Kits\8.1\Include\winrt
```

This ends up setting the incorrect include paths preventing any code that relies on a newer Windows SDK from compiling.

[cpt_bug_winsdk.zip](https://github.com/Caphyon/clang-power-tools/files/3654937/cpt_bug_winsdk.zip)

**Comment by hero101111** [comment]
Hello,

Thank you for taking the time to document this issue. We've tested your project and have managed to reproduce it. It looks like you're importing the `globals.xml` property sheet too early, before the `ProjectConfigurations` property group gets defined.

Moving the property sheet import line after `ProjectConfigurations`, before the `$(VCTargetsPath)\Microsoft.Cpp.Default.props` import would fix the issue.

Let us know if this solves your problem.

Regards,
Gabriel.

**Comment by bjehlert** [comment]
While I appreciate the workaround, restructuring our prop sheet setup and changing every project file is a large task. This works correctly with MSBuild and as I understand it, this extension is trying to be compatible with MSBuild.

Referencing [MSDN](https://docs.microsoft.com/en-us/cpp/build/reference/vcxproj-file-structure?view=vs-2019#projectconfigurations-itemgroup-element), `ProjectConfigurations` is not used at build time.

To my understanding, the mapping of solution configuration/platform to project configuration/platform is done when the IDE finishes loading the projects. At that point when the build is invoked, `$(Configuration)` and `$(Platform)` properties should be defined "on the command line" so to speak and available from the very first line in the project file.

**Comment by hero101111** [comment]
The problem here was the evaluation of a condition residing in the `globals.xml` property sheet. It conditions around the `Platform` property before it being initialized, so in essence a project load issue.
We'll make sure to pre-initialize the `Configuration` and `Platform` MSBuild properties from the start, so that the `ProjectConfigurations` issue doesn't occur.

This fix will be available in the next release of Clang Power Tools.

Thanks again for your feedback and sample data.

Regards,
Gabriel.

**Comment by Enache-Ionut** [comment]
Hi,

We are happy to announce the release of [Clang Power Tools v5.3](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools). This issue was fixed so please check for updates.

Thank you for taking the time to help us to make a better product.

Regards,
~Ionut
