### ISSUE TITLE
Running a command from the toolbar broken for tidy

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#693]
#576 fixed the problem for clang compile. However the same behavior still stands for launching tidy. For me using the toolbar icon or the assigned keyboard shortcut launches tidy on some random file even if the active pane is solution explorer with a project selected. The only way to actually launch tidy is to use the context menu in solution explorer.

Also the related bug #614  was closed as fixed, while in 5.2.1 I see the problem as reported. My keyboard shortcut used in the editor launches compile on the solution-explorer active selection instead of the active file in the editor. (make sure at testing you turn off the feature that auto-selects the current file in the explorer, as then then it will seem like working)

**Comment by Enache-Ionut** [comment]
Hi, 

We'll address this issue in a future release. Thank you for your feedback. 

Meanwhile, the new version of [Clang Power Tools v5.3](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools) was just released. Please check for updates. 

Regards,
~Ionut

**Comment by pasa-** [comment]
Cool. While at it, please test CPT with llvm 9, or if that already happened update the FAQ page to reflect that. And make the Eg. ling point to 9 or 8.0.1 if staying with that.

**Comment by cpp-red-lion** [comment]
Hi,

*LLVM 9.0* is under testing as we speak.

There are some issues to be addressed both by LLVM (MSFT compat) and Visual Studio teams.

One example/blocker we found:  
https://developercommunity.visualstudio.com/content/problem/691073/-com-ptr-t-is-not-accepted-by-clang-90rc.html

Some issues will be addressed in  LLVM *9.0.1*, some in VS v16.5

**Comment by Enache-Ionut** [comment]
Hello,

I am glad to announce you that the new version of Clang Power Tools fixed this issue. Please check for updates.
Also, LLVM 10.0 is now available for installation in the Clang Power Tools - LLVM settings panel. 

Regards,
Ionut
