### ISSUE TITLE
Alt-tab from settings/flags ... locks up VS completely

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#694]
Open settings and click on ... for the Compile flags.  the dialog box appears. Hit Alt-Tab.

The result is that the top dialog gets hidden, but the settings dialog still running it in modal mode, so on any click all you get is a ding. Same in VS. The only way out is to kill VS in task manager with all the loss that brings on.
Also I noticed the settings dialog is shown as a second VS window, probably uses the wrong parent.

Another notice: in previous versions the flags appeared in the dialog nicely, one flag per one line, easy to work with. Now it shows all in a single line despite the multiline edit box...

**Comment by hprica** [comment]
Thank you for taking the time to report the issues. We are investigating and everything will be fixed in v5.4.

**Comment by hprica** [comment]
@pasa-, you can follow the dialog redesign here https://github.com/Caphyon/clang-power-tools/issues/698

**Comment by hprica** [comment]
The issue was fixed in v5.4
https://clangpowertools.com/CHANGELOG.html
