### ISSUE TITLE
Respect VS "Always show error list" option or add a custom one

### ISSUE THREAD

**Issue by Aldarrion** [Caphyon/clang-power-tools#718]
In Visual Studio it is possible to set whether one wants to see the Error List window on failed build or not. I prefer the output window (especially for C++) since it gives more info and context to the errors/warnings and in my opinion, is generally clearer to read.
Previously, if I remember correctly, Power tools did not show this window on error/warning but now it does that on both Tidy and Compile - the Error List is always shown and I cannot find an option to hide it.

It would be awesome if Power tools could either respect the option set in Visual studio or add a custom option to turn off this behavior. 
In VS 2015 the option is under Projects and Solutions -> General, "Always show Error List if build finishes with errors".
I saw a pull request with a similar theme but I don't think it solves this issue. https://github.com/Caphyon/clang-power-tools/pull/652

Currently, I am on Visual Studio 2015 but I can test 2017 and 2019 later if necessary.

**Comment by Enache-Ionut** [comment]
Hi, 

This issue was fixed and it will be available in the next version of Clang Power Tools. Thank you for your feedback. I will let you know when v5.5 will be online. 

For any other issue, we are here to help.

Regards,
~Ionut
