### ISSUE TITLE
Extract preprocessor define directives from project automatically

### ISSUE THREAD

**Issue by ben-craig** [Caphyon/clang-power-tools#72]
Currently, if you have preprocessor defines set in your project, you need to manually move those over to the "Compile Flags" field in the settings dialog.  I believe the settings dialog is also global, and not project specific, so if you have multiple projects with different preprocessor defines, you will need to frequently switch them back and forth.

**Comment by cpp-red-lion** [comment]
Hi,
Project preprocessor defines should be automatically extracted from your `*.vcxproj` or VS property-sheets.

There is no need to configure them manually.

Can you provide a simple test case, reproducing the issue ?

**Comment by ben-craig** [comment]
I'll work on a reduced test case.  I threw the plugin at an existing, code generated vcproj that I had handy, and it isn't in a state that I can make the whole thing public.

Here's a portion of my .vcxproj though (with lots of paths and defines removed).  I don't know for sure if this is an unusual snippet or perfectly normal...

`  <ItemDefinitionGroup Condition="'$(Configuration)|$(Platform)'=='win32U_release|Win32'">

    <ClCompile>

      <PreprocessorDefinitions>WIN32_LEAN_AND_MEAN</PreprocessorDefinitions>

      <AdditionalIncludeDirectories>./source;p:/perforce/ThirdPartyExports/boost/export/1.5/1.5.5f20/includes</AdditionalIncludeDirectories>
`

**Comment by cpp-red-lion** [comment]
The snippet seems OK at first glance. Should work.
It would really help if you could take some time and produce a `vcxproj` file that you can share with us, reproducing the issue.

I think there's more to it (the bug) than the snippet above...

**Comment by cpp-red-lion** [comment]
Also, using `version 1.4` (latest) of *"Clang Power Tools"* you can debug configuration issues using our new `Verbose Mode` option that you can enable from *Settings*.

**Comment by ben-craig** [comment]
[fail_import.zip](https://github.com/Caphyon/clang-power-tools/files/1427927/fail_import.zip)

Here's a reduced test case.  This was using an MSVC-14.0 (2015) project.  I got the same kinds of failures when I upgraded it to an MSVC-15.0 (2017) project.

Output from verbose mode follows...


Start Clang Compile

VERBOSE: CPU logical core count = 8
VERBOSE: Detected LLVM at C:\Program Files (x86)\LLVM\bin
VERBOSE: [INFO] Source directory: P:\perforce\sa\group\bcraig\experiments\autoprojtest\temp
VERBOSE: Scanning for .vcxproj files
VERBOSE: Found 1 projects
[ INFO ] WILL PROCESS PROJECTS: 
	autoprojtest_msvc-14.0.vcxproj
[ INFO ] 1. PROCESSING PROJECT P:\perforce\sa\group\bcraig\experiments\autoprojtest\temp\autoprojtest_msvc-14.0.vcxproj
VERBOSE: PCH not enabled for this project!
VERBOSE: Preprocessor definitions: 
VERBOSE: Platform toolset: v141
VERBOSE: Additional includes:
VERBOSE: Detected Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio 14.0
VERBOSE: WinSDK version : 8.1
VERBOSE: Include directories:
VERBOSE: P:\perforce\sa\group\bcraig\experiments\autoprojtest\temp
VERBOSE: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include
VERBOSE: C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\atlmfc\include
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt
VERBOSE: C:\Program Files (x86)\Windows Kits\8.1\Include\um
VERBOSE: C:\Program Files (x86)\Windows Kits\8.1\Include\shared
VERBOSE: C:\Program Files (x86)\Windows Kits\8.1\Include\winrt
VERBOSE: 
VERBOSE: 
VERBOSE: Force includes: 
VERBOSE: Processing 1 cpps
1: P:\perforce\sa\group\bcraig\experiments\autoprojtest\temp\source\main.cpp
P:\perforce\sa\group\bcraig\experiments\autoprojtest\temp\source\main.cpp:2:10: fatal error: 'foo.h' file not found
#include <foo.h>
         ^~~~~~~
1 error generated.


Got errors.

Done Clang Compile

**Comment by cpp-red-lion** [comment]
Thanks for the attached project.
I immediately spotted the issue causing your problems: you have **custom names** for your project configurations, eg. `win32U_debug`, `win64U_debug`, etc.

We currently assume they are called: "Debug", "Release" .... oops!

Will fix this issue as soon as possible.
Thank you for bringing it to our attention.

**Comment by cpp-red-lion** [comment]
The same bug also affects your submitted issue: #74

**Comment by hero101111** [comment]
This functionality was just implemented [here](https://github.com/Caphyon/clang-power-tools/commit/8555b7bf7d11083be693fc8b0dc0e09004893de4)

**Comment by cpp-red-lion** [comment]
This issue was fixed in version 1.5
https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools

Thank you for your feedback!
