### ISSUE TITLE
Extract include paths from project automatically

### ISSUE THREAD

**Issue by ben-craig** [Caphyon/clang-power-tools#73]
The settings dialog has a field for Include Directories, but this appears to be global to all projects and solutions.  It also has isn't automatically populated by the project's include directories.

**Comment by cpp-red-lion** [comment]
Hi,
Project `Include Directories` should be **automatically** extracted from your *.vcxproj or VS property-sheets.
There is no need to configure them manually.
The *global setting* you are referring to is there for historical reasons and will be removed in the next version, to avoid any further confusion.

Can you provide a simple test case, reproducing the issue ?

**Comment by cpp-red-lion** [comment]
Also, starting with `version 1.4` (latest), you can debug configuration issues using our new `Verbose Mode` option that you can enable from *"Clang Power Tools" Settings*.

That will print in the `Output` pane all the project config details driving the `clang` compile script.
Eg. 
> VERBOSE: Include directories:
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\shared
VERBOSE: C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\winrt

> VERBOSE: Preprocessor definitions: -DWIN32 -D_WINDOWS -D_DEBUG -DUNICODE -D_UNICODE

**Comment by cpp-red-lion** [comment]
This is related/affected by the same bug causing issue: #72

**Comment by hero101111** [comment]
[Fixed](https://github.com/Caphyon/clang-power-tools/commit/8555b7bf7d11083be693fc8b0dc0e09004893de4)

**Comment by cpp-red-lion** [comment]
This issue was fixed in version 1.5
https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools

Thank you for your feedback!
