### ISSUE TITLE
Visual Studio loses focus in source codebox when saving

### ISSUE THREAD

**Issue by WolfgangVogl** [Caphyon/clang-power-tools#737]
Sine 2020-01-21 I've got the new Clang Power Tools version 5.5.1.
I use the function "Format on save" and it seems that starting with the update, with every "Save" the focus of my cursor/text input is suddenly in the "Output" Window with the "Show output from: Clang Power Tools" Option selected. In the box itself the Message
"--- CLANG FORMAT FINISHED ---" is shown - and the cursor is there!

This hinders me very much in my work.
![clang-power-tools_problem](https://user-images.githubusercontent.com/6816234/72962969-2b6b0e80-3db6-11ea-890a-5e6e33f3dd74.gif)

**Comment by hprica** [comment]
@WolfgangVogl thank you for taking the time to report this issue. 

The bug was fixed in today's point release 5.5.2, which is now live. If you have any other issues and feedback let us know, we greatly appreciate it.
