### ISSUE TITLE
Long freezes in a big file with many highlights.

### ISSUE THREAD

**Issue by jovibor** [Caphyon/clang-power-tools#745]
Latest VS (16.4.4), latest CPT.
In a .cpp file with ~4000 lines of code, the whole interface of VS becomes almost unresponsive. 
It freezes for 5-6 seconds on any operation, then works for one-two seconds.
The only thing that helps is to close that big file - interface immediately unfreezes.

My guess is (although i might be wrong), it's because of too many highlights in the editor.

Can we have the option to switch highlights from CPT off? The error list itself would suffice, in my case at least.

![image](https://user-images.githubusercontent.com/5625787/74200507-dc2c4580-4cb2-11ea-8dd4-f59f1983de32.png)

**Comment by Enache-Ionut** [comment]
Hi,

Thank you for taking the time to report this issue. 

We are already aware of this situation and we are actively working to improve the performance of the Clang Power Tools squiggle feature. A fix for this issue will be released very soon.

If you encounter any other inconvenience with Clang Power Tools or if you have any suggestions or feature requests for us, we are here to help 😃 

Regards,
Ionut

**Comment by Enache-Ionut** [comment]
Hello @jovibor, 

We are glad to announce you that the new version of Clang Power Tools 5.6 has fixed this issue. It brings a big performance improvement and also offers the possibility to disable squiggles very easily from our settings panel. We are sorry for the inconvenience, we encountered multiple unexpected challenges and issues on the road. 

Please check for updates. 

Regards,
Ionut
