### ISSUE TITLE
Settings from Directory.Build.props are ignored

### ISSUE THREAD

**Issue by vbaderks** [Caphyon/clang-power-tools#75]
I use normally the file Directory.Build.props to configure global settings for my C++ projects. MSBuild will pick this file up by walking up the directory tree. The clang-power-tools are unable to detect this file and thus assume that my projects are targeting WinSDK 8.1 and cannot file the OS include files (my projects are using the win10 sdk headers)

**Comment by cpp-red-lion** [comment]
Thank you for your feedback.

Currently we have no support for this.
I don't know how this works exactly under VS. Can you please point me to some Microsoft documentation about this feature ?

**Comment by cpp-red-lion** [comment]
Is this what you're referring to ?

https://docs.microsoft.com/en-us/visualstudio/msbuild/customize-your-build

**Comment by vbaderks** [comment]
yes that is the mechanism. Directory.Build.props is just a file that is found by Msbuild when it walks the directory structure upwards.

I have moved the common properties to this file and removed them from my .vcxproj files. Msbuild properties can be redefined, but I want my central defined properties most of the time not to be redefined. For example <WindowsTargetPlatformVersion> should be the same for all projects in a certain tree.

**Comment by hero101111** [comment]
This functionality was just implemented [here](https://github.com/Caphyon/clang-power-tools/commit/8555b7bf7d11083be693fc8b0dc0e09004893de4)

**Comment by cpp-red-lion** [comment]
This feature was implemented in version 1.5
https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools

Thank you for your feedback!
