### ISSUE TITLE
<CharacterSet>Unicode</CharacterSet> is not used

### ISSUE THREAD

**Issue by vbaderks** [Caphyon/clang-power-tools#76]
Unless I also define UNICODE;UNICODE the clang-power-tools will try to compile my projects for ANSI, which doesn't work

**Comment by cpp-red-lion** [comment]
Hi,
Currently the `<CharacterSet>Unicode</CharacterSet>` property is extracted only from `*vcxproj` directly. If you configured it via a VS property-sheet, it won't be picked-up.

A major improvement in this area is coming out this week ( #61 ).
Right now is in testing on a branch; will merge it soon to master and release a new version of the VS extension.

**Comment by hero101111** [comment]
The functionality described by @cpp-red-lion was just [implemented](https://github.com/Caphyon/clang-power-tools/commit/8555b7bf7d11083be693fc8b0dc0e09004893de4)

**Comment by cpp-red-lion** [comment]
This issue was fixed in version 1.5
https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools

Thank you for your feedback!
