### ISSUE TITLE
LLVM 10 support

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#760]
I'm aware that we just got support for the most recent release 9.0.1 and that 10 is not even released...  however rc3 is already out and final release expected in short time.

My problem is that we already started using concepts as released int MSVC.  And some already made it in the central headers.  What means that clang compile chokes on everything, rendering it not usable till catches up. The language page suggests it is happening in clang 10.

Please make it a priority to support from CPT as it gets released.

**Comment by cpp-red-lion** [comment]
Hi,

Definitely. Clang 10 is top priority.    
As soon as it's stable (tagged), we'll make sure it works with CPT out of the box.

**Comment by hprica** [comment]
Hello @pasa-, we are happy to announce that starting with version 5.7 we offer support for LLVM 10
