### ISSUE TITLE
Clang Power Tools 5.6.0 causing errors when opening NuGet window.

### ISSUE THREAD

**Issue by MikeDiack** [Caphyon/clang-power-tools#762]
This issue has newly started happening since I upgraded from Clang Power Tools 5.5.3 to 5.6.0.
I can reproduce it with 100% accuracy on VS 2015 Update 3 fully patched, VS 2017 Update 9.20 fully patched, on Windows 8.1 x64 fully patched (not yet tried with VS 2019).
It occurs if the solution does use NuGet packages or if it doesn't - as soon as the NuGet window opens:

To repro:
1) Load a solution into VS 2015 (or 2017). Any solution will do - even a Hello World one.
2) Right click on the solution for the "Manage NuGet Packages for Solution" context menu option.
3) As soon as you do, the Nuget Window opens, and you get a flurry of message boxes.

Title: Error
Text: The parameter is incorrect. (Exception from HRESULT: 0x80070057 (E_INVALIDARG))

![image](https://user-images.githubusercontent.com/24409268/76090799-1cca6680-5fb4-11ea-813a-a04138b39bc8.png)

This issue is 100% reproducible for me. If I disable Clang Power Tools, restart VS and retry, the problem doesn't occur. If I re-enable Clang Power Tools and retry the problem does occur.

**Comment by hprica** [comment]
Hello Mike,

Thank you for taking the time to report the bug.  We have resolved your issue in the point(5.6.1) release we just published.

If you have any other problems or feature suggestions let us know.

Have a great weekend!
