### ISSUE TITLE
Project macros not being resolved

### ISSUE THREAD

**Issue by trstolze** [Caphyon/clang-power-tools#778]
On our CI server, CPT is not resolving project macros properly, e.g:
* %(AdditionalIncludeDirectories)
* %(AdditionalLibraryDirectories)
* etc..

With the latest release of CPT, the issue first appears as a `[clang-diagnostic-error]` error complaining about not being able to find header files. 

Originally I was trying to run this in a CI environment using the `clang-build.ps1` script (although the issue persists when using the VS GUI). I dug into the problem enough to know where in the script the issue occurs:

File: `msbuild-expression-eval.ps1`
Function: `function Evaluate-MSBuildExpression([string] $expression, [switch] $isCondition)`
```
    try
    {
        if ( ($expression.IndexOf('::') -ge 0) -or $isCondition)
        {
            try
            {
                $resInvokeResult = Invoke-Expression $expression

                if ($resInvokeResult -is [array])
                {
                    $res = $resInvokeResult -join ';'
                }
                else
                {
                    $res = $resInvokeResult
                }
            }
            catch
            {
                Write-Verbose $_.Exception.Message
                $res = $ExecutionContext.InvokeCommand.ExpandString($expression)
            }
        }
        else
        {
            $res = $ExecutionContext.InvokeCommand.ExpandString($expression)
        }
    }
    catch
    {
        Write-Verbose $_.Exception.Message
    }
```

The calls to `ExpandString` is failing because the macros, like those listed above, are not defined anywhere. This results in the rest of the `<AdditionalIncludeDirectories>` in the project setting from being effectively ignored (because part of the string failed to be expanded), hence the original symptom I described. 

I have been primarily using Clang Tidy but I have no reason to believe that this issue is limited to Tidy.

I have been successfully using CPT, including Clang Tidy on our code-base on several machines with no issue. I was trying to deploy the Clang Tidy checks to our CI server and this is where I have the issue. The CI server has the same build tools installed (VS 2015), same code base, same everything. The one interesting difference is that on the CI server, the user account running the CPT automation has a dollar sign in the username (i.e. $trstolze). But there is clearly something unique about our CI server because the problem only shows up there.

**Comment by hero101111** [comment]
Hello,

Unfortunately I've been unable to reproduce this issue, even when the current user name starts with the dollar sign. In order to gain an understanding of what's going on, we need some additional. A verbose log or a minimal project would help us greatly.

Thanks in advance,
--Gabriel.

**Comment by hero101111** [comment]
Hi @trstolze

Have you managed to get the verbose log or sample project needed in order to investigate this issue?

**Comment by trstolze** [comment]
Hi @hero101111 ,

I don't think the project file would be helpful since the issue seems to be localized to the CI server I am trying to perform Clang Tidy on. I can run the same script on my machine with no issues.

Attached is a sanitized log file I've generated when running the Clang Tidy script on the server. You can see hints of what I've described above where the `ExpandString` failing possibly because the property sheets cannot be found. Note that as part of the sanitation process I removed the environment variables.

If you need more information or would like me to perform some experiments let me know. I realize this is probably difficult for you to work out without being able to test on the machine where the problem exists.

Log file:
[tidy.log](https://github.com/Caphyon/clang-power-tools/files/4628690/tidy.log)

**Comment by pasa-** [comment]
I just noticed that I have the same issue (probably) on my notebook.

The properties in my project that are not simple does not resolve.

    <PROJ_UPPER Condition="'$(PROJ_UPPER)'==''">$(ProjectOrigName.Replace(' ','_').ToUpper())</PROJ_UPPER>

also, if simplified to just 
    <PROJ_UPPER Condition="'$(PROJ_UPPER)'==''">$(ProjectOrigName.ToUpper())</PROJ_UPPER>

throws an exception and gets resolved to an empty string -- leading to incorrect defines  and such.   It does work on my main PC.  It used to work on this one too, maybe a year ago, when I last used CPT on it.   

The only notable difference I see is the OS, Win10 professional on the main, Win7 enterprise on this notebook.

**Comment by hero101111** [comment]
Hello,

Clang Power Tools 7.5.0, which has just been released, addresses this issue and should provide an error-free build pipeline now.

Regards,
Gabriel.
