### ISSUE TITLE
Quoted command line defines lose quotes in clang tidy

### ISSUE THREAD

**Issue by ben-craig** [Caphyon/clang-power-tools#79]
When run through clang power tools "Compile (syntax only)" and "Tidy Code", quotes on command line preprocessor defines get lost.  This usually ends with a quoted string turning into "use of undeclared identifier" errors.  Project with the problem attached.
[bad_quote.zip](https://github.com/Caphyon/clang-power-tools/files/1434370/bad_quote.zip)

**Comment by hero101111** [comment]
Hi, Ben

I've been able to reproduce this problem. [Fixed it](https://github.com/Caphyon/clang-power-tools/commit/bdd86b85fdb164ff8af054622ce4908200e4e0eb)

Please note that this fix is currently live only for the github repository. 
The latest Visual Studio extension (1.5.0) does not contain the fix. It will be included in the next release.

Until then, as a workaround, you can manually replace `clang-build.ps1` in the VS extension directory with the latest from github. 

To locate  the extension directory search for `clang-build.ps1` in `%LOCALAPPDATA%`

**Comment by cpp-red-lion** [comment]
Thanks for all the good feedback and test cases, @ben-craig !

**Comment by ben-craig** [comment]
Glad to help.  Thanks for the tool, the CppCon talk, and the rapid turnaround on the fixes.

With this issue fixed, I'm sufficiently unblocked to need to deal with more interesting problems, mostly of my own doing.

**Comment by cpp-red-lion** [comment]
Happy to share and help.

Let us know if you encounter any other problems going further.
Also, if you have suggestions for improvement/features.

Victor
