### ISSUE TITLE
consider custom properties in property files

### ISSUE THREAD

**Issue by reinsch82** [Caphyon/clang-power-tools#80]
When you define a property like that:
`    <BuildUtilitiesDirectory Condition="Exists('../../../../BuildUtilities')">../../../../BuildUtilities</BuildUtilitiesDirectory>
`

it can be reused in other places like that:
` <ClCompile>
      <AdditionalIncludeDirectories>$(SrcDirectory);$(BuildUtilitiesDirectory)/Cpp/include;$(BuildUtilitiesDirectory)/Cpp/boost;$(BuildUtilitiesDirectory)/Cpp/opencv;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>`

Currently those properties are not evaluated. 

It would be nice to have that.

thx for this extension, it's really helpful to get better code quality

**Comment by cpp-red-lion** [comment]
Thanks for your suggestion.
Currently we don't have any support for this.
There is another related issue #33 that we're looking at.
It's definitely on our roadmap.

**Comment by jcageman** [comment]
Note that most of these kind of issues would be solved if you would use the visual studio extension api to parse the vxproj's. It will automatically deduce custom properties. To see how to do that you can easily use the solution at https://www.sourcetrail.com/blog/export_clang_compilation_database_from_visual_studio_solution/

**Comment by hero101111** [comment]
Hi Mariusz,

We're happy to inform you that we've just released version 2.0 of [Clang Power Tools](https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools).
It fixes the project xml data [limitations](https://github.com/Caphyon/clang-power-tools/blob/master/CHANGELOG.md) that were at the core of this issue.

Projects with user-defined macros (properties) should now integrate successfully with Clang Power Tools.

The Visual Studio Extension should now update automatically to v2.0. 
If you've disabled automatic updates you'll have to update the extension manually.


Thank you for feedback and patience.

Regards,
Gabriel.
