### ISSUE TITLE
Clang-tidy issue on VS CMake

### ISSUE THREAD

**Issue by Yuhanun** [Caphyon/clang-power-tools#802]
I'm using a C++ project (CMAKE) in visual studio with submodules. The following occurs when I hit clang-tidy:

```

--- CLANG TIDY STARTED ---

Cannot find given project(s)

--- CLANG TIDY FINISHED ---
```

How do I resolve this?

**Comment by Enache-Ionut** [comment]
Hi,

Can you tell us a few information about your environment as:

- What version of Clang Power Tools are you running?
- What version of Visual Studio 2019 are you using?
- The issue occurred after an update or is the first time are you using Clang Power Tools?
- Can you attach a project which has this issue?

**Comment by Yuhanun** [comment]
I'll do this tomorrow. Haven't been on windows today.

**Comment by nokinger** [comment]
Hi, 

i had exact the same. Also there is no entries available in Context Menu for Power Tools.

Installed latest Version (today) of Power Tools: 5.9.2
My Visul Studio Version is: 16.5.5 (Enterprise)
Is my First time using the power tools

How To reproduce it: just create a small cmake project and open it with Visual Studio.

**Comment by Enache-Ionut** [comment]
Hi @nokinger, 

The context menu commands are not yet available for CMake projects. 
CMake support is a Beta feature. It's a huge step forward for us, but like any other big change, we encountered many difficulties until now. 

We work continuously to improve our CMake compatibility and to build a better product. We highly appreciate your feedback and your patience.

Regards,
Ionut
