### ISSUE TITLE
Error output steals keyboard focus

### ISSUE THREAD

**Issue by magnesj** [Caphyon/clang-power-tools#810]
We have a project where some source code is using clang-format and some source code is not. We use the format-on-save feature, and this works great for the clang-format parts of the project. When we touch a file in non-clang-formatted code, an error message is displayed:

    --- ERROR ---
    Format config file not found.
    Create the config file and place it in the solution folder or select one of the predefined format styles from Clang Power Tools settings -> Format -> Style.

This operation steals keyboard focus, and moves keyboard focus into the Output window. This behaviour is very annoying for our workflow.

**Comment by Enache-Ionut** [comment]
Hi,

Thank you for taking the time to report this issue.

We are aware of the loss of focus regarding the additional information from Output Window. We will address this issue in the next version of Clang Power Tools, which will be released soon.

Regards,
~Ionut

**Comment by Enache-Ionut** [comment]
Hi,

This issue is now fixed and it will be available on the next version of Clang Power Tools, v6.0. 
Thank you for your feedback.

Regards,
~Ionut
