### ISSUE TITLE
clang-format-11

### ISSUE THREAD

**Issue by janwilmans** [Caphyon/clang-power-tools#813]
We see an off problem that, running clang-format-11 on a files on the commandline has slightly different behavior, from running the same version of clang-format-11 (full path specified) in visual studio from the clang-power-tools format-on-save option.  I will try to gather a reproduction scenario.

**Comment by cpp-red-lion** [comment]
HI Jan,

A simple repro test project would help narrow down the investigation.

**Comment by janwilmans** [comment]
Sorry, I was too hasty reporting this, it was a user error, the right version of clang-format was not set in the custom binary setting in clang-format settings. closed.
