### ISSUE TITLE
Provide better defaults for "Checks" dialog

### ISSUE THREAD

**Issue by ben-craig** [Caphyon/clang-power-tools#82]
After installing the clang-power-tools extension, all the checks start off disabled.  This probably isn't what people want.  Consider setting most of them to enabled by default.  The main ones I can see leaving off by default would be the clang-analyzer-optin category.

Alternatively, make it easier to switch large chunks from false to true.

**Comment by cpp-red-lion** [comment]
We were just about to to that in the next release :)
We were thinking of enabling by default all `modernize` and `readability` checks.

**Comment by cpp-red-lion** [comment]
BTW, did you know that you can also specify **wildcard** filters for clang-tidy checks ?

Eg.
`-*,modernize-*,readability-*`  <== that means "enable just the modernize and readability" checks
(that's `clang-tidy` standard syntax/CLI)

**Comment by cpp-red-lion** [comment]
[](url)
<img width="527" alt="tidy wildcard checks" src="https://user-images.githubusercontent.com/32536589/32336093-079482be-bff7-11e7-97d1-05718930a5cf.PNG">

**Comment by cpp-red-lion** [comment]
This issue was [fixed](https://github.com/Caphyon/clang-power-tools/commit/683d912a22953d74a54dfb84f092f01768f2e34e)
