### ISSUE TITLE
The Tidy command fails if the solution file contains environment variable references.

### ISSUE THREAD

**Issue by BenKey** [Caphyon/clang-power-tools#825]
It is possible to use environment variable references in solution files as part of the path to a project file. For example, a MyCoolLibrarySource environment variable may be set to the location for the source code of My Cool Library. This project may then be included in a SLN file that depends on My Cool Library as follows.

    Project("{F7B8AA50-FE58-49C0-B063-BD7FE7AF5BCA}") = "MyCoolLibrary", "%MyCoolLibrarySource%\src\MyCoolLibrary.vcxproj", "{712C652D-DDFE-414B-8147-4ED7DB4A4187}"
    EndProject

If you use the [Clang Power Tools\Tidy] menu item when a solution that uses this technique is loaded in Visual Studio 2019, the following error will occur.

    VERBOSE: %MyCoolLibrarySource%\src\MyCoolLibrary.vcxproj
    Cannot find given project(s)

**Comment by hero101111** [comment]
Hi @BenKey 

We're happy to let you know that we've addressed this issue. SLN project loading using environment variables  will be available in the next release of Clang Power Tools. Thank you for helping us fix this limitation.
