### ISSUE TITLE
Directory.Build.Props is ignored

### ISSUE THREAD

**Issue by vikhik** [Caphyon/clang-power-tools#830]
According to the changelog, this was fixed in 2018.

However, in [my project](https://bitbucket.org/VikramSaran/playphys/src/develop/) it is not finding the directory props sheet or using it at all (the project is quite small, so should be usable as a sample).

I have attached the verbose output: [verbose.log](https://github.com/Caphyon/clang-power-tools/files/4728242/verbose.log)

**Comment by vikhik** [comment]
I did end up getting my solution to build with clang using the msbuild/clang integration in VS.
So mostly just leaving this up to help you folks out! It would also be nice to use the rest of your tooling while my main build is MSVC.

**Comment by hprica** [comment]
Hello @vikhik ,

A new version **(6.0.1)** containing the fix for your bug was just released. Let us know if the issue persists.
