### ISSUE TITLE
[Bug] Focus stealing to the Error List window.

### ISSUE THREAD

**Issue by jovibor** [Caphyon/clang-power-tools#835]
I think it's related to #810.

When running `Tidy` command through the `Clang Power Tools` menu on a folder in solution explorer, the focus is constantly getting stolen while command is running.

VS 16.6.1

**Comment by Enache-Ionut** [comment]
Hello @jovibor, 

Thank you for your feedback! We reproduced and fixed this issue. It will be available in the next version of Clang Power Tools, v6.1. I will let you know when the new version will be available.

Regards,
~Ionut

**Comment by Enache-Ionut** [comment]
Hello @jovibor, 

Clang Power Tools v6.1 is now online. Please check for updates.
