### ISSUE TITLE
Invalid fallback style

### ISSUE THREAD

**Issue by janwilmans** [Caphyon/clang-power-tools#837]
Occurs with 6.0.1 if you select 'file' as fallback style

![image](https://user-images.githubusercontent.com/5933444/83975677-49fd1c80-a8f5-11ea-81f5-e70bae607a06.png)

**Comment by janwilmans** [comment]
thanks for your super fast response, I will test it once 6.1 is released

**Comment by Enache-Ionut** [comment]
Hello @janwilmans, 

Clang Power Tools v6.1 is now online. Please check for updates.
