### ISSUE TITLE
Property sheet parsing still doesn't work right

### ISSUE THREAD

**Issue by leadfoot59** [Caphyon/clang-power-tools#85]
Using 1.5.0
When using the Clang Power Tools->Compile option it still doesn't find all the preprocessor defines and include file paths that are in our various property sheets. I have a stripped down version of our solution that demonstrates the issue but I would rather not post it on a public forum. Is there an email I can send it to?

**Comment by cpp-red-lion** [comment]
If you do not wish to attach your project here, you can send it to:
`victor` dot `ciura` @ `caphyon` dot `com`

**Comment by cpp-red-lion** [comment]
I still haven't received any project from you (by email, or here) reproducing the problem.
I'm going to close this issue soon, if we don't get more details.
My suspicion is that you're affected by the same issue as #81

**Comment by leadfoot59** [comment]
I sent a project 4 days ago. I just tried sending it again directly to victor dot ciura @ caphyon dot com

**Comment by cpp-red-lion** [comment]
My apologies. It got lost in my business inbox; found it just now.
Thanks for sending it.

My suspicion is confirmed: you're affected by the same issue as: #81 

This is a more difficult one to fix, but I assure you we're going to fix it soon.
We'll let you know when it's fixed.

**Comment by hero101111** [comment]
Hi @leadfoot59 ,

We're happy to inform you that we've just released version 2.0 of [Clang Power Tools](https://marketplace.visualstudio.com/items?itemName=vs-publisher-690586.ClangPowerTools).
It fixes the project xml data [limitations](https://github.com/Caphyon/clang-power-tools/blob/master/CHANGELOG.md) that were at the core of this issue.

Your projects should now integrate successfully with Clang Power Tools.

The Visual Studio Extension should now update automatically to v2.0. 
If you've disabled automatic updates you'll have to update the extension manually.


Thank you for feedback and patience.

Regards,
Gabriel.
