### ISSUE TITLE
Add Microsoft style to Clang Format

### ISSUE THREAD

**Issue by sonulohani** [Caphyon/clang-power-tools#856]
Hi,

Currently under Format tab inside Style option there is no Microsoft style. In https://releases.llvm.org/9.0.0/tools/clang/docs/ClangFormatStyleOptions.html the **microsoft** style also comes under standard style which is missing in this tool. Just want you to know that this is the only style with 3 space indentations.

**Comment by hprica** [comment]
Hello @sonulohani,

Thank you for your suggestion. We will add the **Microsoft** style in the coming version **6.1** which will release early next week.

**Comment by mydeveloperday** [comment]
Could you also consider adding support for C# formatting which clang-format
supports?

**Comment by sonulohani** [comment]
You can raise seperate enhancement ticket for C#.

**Comment by hprica** [comment]
Hello,

I have created a new issue about C# format support https://github.com/Caphyon/clang-power-tools/issues/858 
If you have any other suggestions or feedback let me know.

**Comment by hprica** [comment]
@sonulohani a Clang Power Tools 6.1 was just released and it includes support for Microsoft style.

**Comment by hprica** [comment]
@mydeveloperday Clang Power Tools 6.1 was just released and it includes support to format C# files. 

Make sure you add .cs to the Format Tab > File Extensions field to run format or just reset your settings from the Team Tab, to use the default values which now includes .cs.
