### ISSUE TITLE
Add support for specifying clang-format command

### ISSUE THREAD

**Issue by PazerOP** [Caphyon/clang-power-tools#867]
I'm aware of the ability to specify a custom executable for clang-format, but I would appreciate it if that was changed to a command instead. Specifically, it is *much* easier to get clang-format-11 on linux (and by extension, wsl) than it is on Windows (it's also much more convenient to keep it updated via apt).

It would be great if we could specify something in settings like
```
Custom command: C:\Windows\Sysnative\wsl.exe -e clang-format-11
```

Right now if I try to do that I get this, which seems to indicate that it's trying to run the whole command as the executable, rather than parsing the string and pulling the arguments out of it:
![image](https://user-images.githubusercontent.com/6569500/86844219-95255f00-c05c-11ea-9440-dccd130cbe9e.png)

Setting the executable to just `C:\Windows\Sysnative\wsl.exe` gives a different error message caused by it not writing anything to stdout/stderr (obviously), so the path to wsl.exe is correct.

**Comment by hprica** [comment]
Hello @PazerOP,

Thank you for your suggestion. We'll try to implement this feature in a future release. If you have any other suggestions, please let us know.
