### ISSUE TITLE
Errors when running Ctidy 

### ISSUE THREAD

**Issue by sabas869** [Caphyon/clang-power-tools#879]
--- CLANG TIDY STARTED ---

PROJECT: C:\Users\DanielLiezrowice-ESL\source\repos\sensor\sensor.vcxproj
1: C:\Users\DanielLiezrowice-ESL\source\repos\sensor\sensor.cpp
The command line is too long.
Write-Err : Cannot bind argument to parameter 'msg' because it is an empty string.
At C:\users\danielliezrowice-esl\appdata\local\microsoft\visualstudio\16.0_6d58c1ac\extensions\pmeqvz03.n0i\clang-build
.ps1:695 char:15
+     Write-Err ($compileResult.Output)
+               ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Write-Err], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorEmptyStringNotAllowed,Write-Err
 
Got errors.

--- CLANG TIDY FINISHED ---

**Comment by hprica** [comment]
@sabas869 thank you for the sample. We'll let you know when we have more info.

https://github.com/sabas869/demo-project-for-Clang-Power-Tools

**Comment by hero101111** [comment]
Hello @sabas869,

Unfortunately we cannot reproduce this issue on our end.
Please attach a verbose log (enable from _Clang Power Tools Settings > Verbose mode_). 
The verbose log will help us to further investigate the issue.

Regards,
Gabriel.

**Comment by sabas869** [comment]
Hi

Here it is.




Daniel Liezrowice
+972 54 6496673
https://www.linkedin.com/in/liezrowice/

[logo1]<http://www.eswlab.com/>

**Comment by hero101111** [comment]
We've reproduced this issue and will include a fix in the next Clang Power Tools release.
Meanwhile, a workaround for you would be to reduce the number of Tidy checks used.

Thanks for helping us investigate this issue.
