### ISSUE TITLE
With version 6.4, by .clang-tidy is ignored

### ISSUE THREAD

**Issue by Philippe91** [Caphyon/clang-power-tools#889]
With version 6.4, by .clang-tidy is ignored (cf. attachment)
Instead, some checks that I have not chosen, are executed, and the ones from .clang-tidy are ignored.
 eg. I get:

Warning (...) [clang-analyzer-optin.cplusplus.VirtualCall]
Warning (...) [clang-analyzer-core.UndefinedBinaryOperatorResult]

[clang-tidy.zip](https://github.com/Caphyon/clang-power-tools/files/5440506/clang-tidy.zip)

**Comment by hero101111** [comment]
Please check the configuration UI, on Tidy > Use checks from. Is the 'TidyFile` option checked?

**Comment by Philippe91** [comment]
Yes, I verified this. Same problem if I select a single check with "CustomChecks".

**Comment by hero101111** [comment]
Thank you for the info. We're looking into it and will let you know as soon as a fix is ready.

**Comment by Philippe91** [comment]
I have looked on git for an older version of clang-build.ps1, and there is no problem with the version
SHA-1: e96746324616c31faf79a039af9dc24c4a7f8f0d
(I guess from 6.3)

**Comment by Enache-Ionut** [comment]
Hi, 

Thank you for your feedback. 
This issue is now fixed and it is available in the new version of Clang Power Tools, v6.4.1.
Please check for updates.

Regards,
Ionut
