### ISSUE TITLE
Add ability to select a custom LLVM directory path.

### ISSUE THREAD

**Issue by ghost-420** [Caphyon/clang-power-tools#892]
I install LLVM through Scoop: https://github.com/ScoopInstaller/Main/blob/master/bucket/llvm.json
Which installs into: `C:\Users\example\scoop\apps\llvm\11.0.0` and vice versa for older versions.
Visual Studio 2019 has no issues using LLVM installed using Scoop by default (no configuration required), including the `clang-cl.exe` provided by Scoop.

> LLVM provided by Chocolatey does not require this, as it installs into `C:\Program Files\LLVM`.

**Comment by Enache-Ionut** [comment]
Hello,

We'll investigate this issue as soon as possible.
Thank you for the helpful feedback.

**Comment by Enache-Ionut** [comment]
This issue has been solved and it will be present in the next version of Clang Power Tools, v6.5, which will be released this week.

For any other issues or feature suggestions regarding Clang Power Tools do not hesitate to open another issue. 😄 
Thank you for your feedback!

Regards,
Ionut
