### ISSUE TITLE
Use the active project configuration

### ISSUE THREAD

**Issue by Farwaykorse** [Caphyon/clang-power-tools#90]
I expected Clang-Tidy to use the 'active' Solution in VS and the Project configuration that goes with it.

But the current implementation always uses the configuration mentioned first in the "ItemGroup" "ProjectConfigurations" within each projects' vcxproj-file.

I ran into this while trying to set-up at least one configuration with explicit paths to external libraries. To circumvent #80 and #81, after the global include setting was removed.
As an work-around I've added a Project Configuration called "ClangTidy" to each project, that I modify to get the required behaviour.

Clang Power Tools v1.5.1
VS Community v15.4.2

**Comment by cpp-red-lion** [comment]
Hi,
This a very good suggestion.
We just implemented it and we're testing it right now...
It will be available in our next release, due by the end of this week.
