### ISSUE TITLE
ClangPowerTools crashes Visual Studio when using the "compile" or "tidy" options with a CMake project

### ISSUE THREAD

**Issue by tjwrona1992** [Caphyon/clang-power-tools#909]
This may need to be broken out into two separate issues if the two crashes end up being due to different bugs.

I am trying to use ClangPowerTools on one of my CMake projects in Visual Studio: https://github.com/tnt-coders/cpp-dsp

_Note: This project can be compiled within Visual Studio simply by opening the main "CMakeLists.txt" file in Visual Studio and building within the IDE. As long as you have the Conan Package manager installed and the latest version of Visual Studio 2019 Preview it should automatically install its dependencies and just work with no extra steps._

The "clang-format" feature of ClangPowerTools seems to work great! And I was even able to get it to format on save which is a real time saver, but if I try to use either the "compile" or "tidy" commands it crashes the entire IDE with no error message.

**Comment by Enache-Ionut** [comment]
Hello @tjwrona1992,

We have encountered multiple issues with our BETA CMake support. You can find a small explication about how Clang Power Tools works on CMake projects [here](https://github.com/Caphyon/clang-power-tools/issues/764#issuecomment-733814474). 

Multiple users saw some improvements by following these [steps](https://github.com/Caphyon/clang-power-tools/issues/764#issuecomment-737175480).

I'll investigate this issue further, and I'll update this thread when a solution is found.

Thank you for your feedback. 
For any other problems, do not hesitate to open a new issue any time you need.

Regards,
Ionut
