### ISSUE TITLE
Clang Power Tools 7 crashing in VS 2019, 2017, 2015, but Clang Power Tools 6.50 is fine.

### ISSUE THREAD

**Issue by MikeDiack** [Caphyon/clang-power-tools#923]
With VS 2019 Update 9 Preview 3, VS 2017 Update 9.1 and VS 2015 Update 3 (fully patched), running on Windows 8.1 x64 Pro fully patched:

Running Clang Tidy with Clang Power Tools 7 fails (in all 3 IDEs) (see output below)
Reverting to Clang Power Tools 6.50 (in all 3 IDEs) is fine (no PowerShell script crash)

--- CLANG TIDY STARTED ---

At 
C:\Users\mdiack\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\dhfxt1r0.f2r\psClang\msbuild-project-load.ps1:33 
char:1
+ class ProjectConfigurationNotFound: System.Exception
+ ~~~~~
The 'class' keyword is not supported in this version of the language.
    + CategoryInfo          : ParserError: (:) [], ParseException
    + FullyQualifiedErrorId : ReservedKeywordNotAllowed
Update-ParametersFromConfigFile : The term 'Update-ParametersFromConfigFile' is not recognized as the name of a 
cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At C:\Users\mdiack\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\dhfxt1r0.f2r\clang-build.ps1:1294 char:1
+ Update-ParametersFromConfigFile
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Update-ParametersFromConfigFile:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
Unable to find type [ProjectConfigurationNotFound]. Make sure that the assembly that contains this type is loaded.
At C:\Users\mdiack\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\dhfxt1r0.f2r\clang-build.ps1:943 char:5
+     LoadProject($vcxprojPath)
+     ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (ProjectConfigurationNotFound:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
The variable '$VisualStudioVersion' cannot be retrieved because it has not been set.
At C:\Users\mdiack\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\dhfxt1r0.f2r\clang-build.ps1:989 char:9
+     if ($VisualStudioVersion -ne $desiredVisualStudioVerNumber)
+         ~~~~~~~~~~~~~~~~~~~~
    + FullyQualifiedErrorId : VariableIsUndefined
 
Get-Project-ItemList : The term 'Get-Project-ItemList' is not recognized as the name of a cmdlet, function, script 

    + CategoryInfo          : InvalidOperation: (VisualStudioVersion:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined
Get-Project-ItemList : The term 'Get-Project-ItemList' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At 
C:\Users\mdiack\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\dhfxt1r0.f2r\psClang\msbuild-project-data.ps1:95 
char:30
+     $projectCompileItems = @(Get-Project-ItemList "ClCompile")

--- CLANG TIDY FINISHED ---

**Comment by MikeDiack** [comment]
If it helps, it looks like my Powershell version that is trying to run the script is Version 4.0 but Clang Power Tools 6.5.0 works fine, 7.0.0 doesn't (in all 3 IDEs).

**Comment by MikeDiack** [comment]
Quick update on this, having looked at the fact that my system couldn't parse the generated PowerShell script -  I've discovered the "solution" is to upgrade to PowerShell 5.1 on my Windows 8.1 system - when I do both 6.5.0 and 7.0.0 work!

But did the changes to the powershell code in Clang Power Tools 7 really require users to upgrade their Power Shell version?
Not only that this means the system requirement of PowerShell 3 now looks to be wrong. Please check/confirm?

**Comment by hero101111** [comment]
Hello @MikeDiack 

We apologize for the inconvenience. We've recently made some changes to the code that we suspect are at fault. We are currently working of fixing it with an imminent bugfix-release. Thank you for understanding

**Comment by MikeDiack** [comment]
Thanks. Mike

**Comment by MikeDiack** [comment]
Looks like a fix is in progress by virtue of the commit just made. Thanks.

**Comment by MikeDiack** [comment]
I imagine this is fixed, but I can't easily revert the update of PowerShell I made on Windows 8.1 to work around the bug, in order to check that Power Tools still runs with PowerShell 3.

**Comment by hero101111** [comment]
Closing this issue as it was fixed. Thank you for your feedback.
