### ISSUE TITLE
Error: Cannot specify -o when generating multiple output files

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#925]
VS2019 16.8.5
CPT 7.01

I have found that for some projects, both Tidy and Compile fail with the following error message:

--- CLANG COMPILE STARTED ---

PROJECT: F:\REDACTED\redacted.vcxproj [Release|x64]
clang++: error: cannot specify -o when generating multiple output files
Errors encountered during PCH creation

--- CLANG COMPILE FINISHED ---

I have not yet been able to identify anything special with these projects that might be triggering this issue.

**Comment by hero101111** [comment]
Hello @netx123 

A verbose log here would be very helpful. You can activate it from the Clang Power Tools setttings pane. Please attach it to this thread.

Also, can you make a stripped-down version of the project that we can work with in order to investigate this? That would be very helpful.

**Comment by netx123** [comment]
The issue occurs when using the latest [LLVM (12.0.0) snapshot](https://prereleases.llvm.org/win-snapshots/LLVM-12.0.0-6923b0a7-win32.exe).

If i switch CPT back to use LLVM 11.0.0 the issue goes away.

**Comment by netx123** [comment]
I do not yet have a stripped down project, but I have been able to create a verbose log for you:

--- CLANG TIDY STARTED ---

VERBOSE: Loaded assembly C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Build.Utilities.Core.dll
VERBOSE: clang-build.ps1 invocation args: 
  aVcxprojToCompile = F:\XXX - Source\REDACTED - 1.0.0.0\redacted\redacted.vcxproj 
  aVcxprojConfigPlatform = Release|Win32 
  aClangCompileFlags = -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas
 -Wno-unused-value 
  Verbose = True 
  aTidyFlags = C:\Users\Redacted\AppData\Local\Temp\.clang-tidy 
  aTidyHeaderFilter = .* 
  aVisualStudioVersion = 2019 
  aVisualStudioSku = Enterprise 
  aSolutionsPath = F:\XXX - Source\REDACTED - 1.0.0.0\redacted.sln 
VERBOSE: CPU logical core count: 12
VERBOSE: LLVM location: C:\Program Files (x86)\LLVM\bin
VERBOSE: Scanning for solution files
VERBOSE: Caching solution file F:\XXX - Source\REDACTED - 1.0.0.0\redacted.sln
VERBOSE: Solution full path: F:\XXX - Source\REDACTED - 1.0.0.0\redacted.sln
VERBOSE: Solution data length: 2819
VERBOSE: Solution file paths:
VERBOSE:   F:\XXX - Source\REDACTED - 1.0.0.0\redacted.sln
VERBOSE: 
VERBOSE: Source directory: F:\XXX - Source\REDACTED - 1.0.0.0\
VERBOSE: Scanning for project files
VERBOSE: Retrieving project list for solution F:\XXX - Source\REDACTED - 1.0.0.0\redacted.sln
VERBOSE: Solution directory: F:\XXX - Source\REDACTED - 1.0.0.0\
VERBOSE: Intermediate solution project matches count: 2
VERBOSE: redacted\redacted.vcxproj
VERBOSE: REDACTED Documentation\REDACTED Documentation.shfbproj
VERBOSE: Resolved project paths for solution F:\XXX - Source\REDACTED - 1.0.0.0\redacted.sln:
VERBOSE:   F:\XXX - Source\REDACTED - 1.0.0.0\redacted\redacted.vcxproj
VERBOSE: 
VERBOSE: Found 1 projects
VERBOSE: PROCESSING ALL PROJECTS
VERBOSE: Deleting variables initialized by previous project:
VERBOSE: 
VERBOSE: Importing environment variables into current scope
VERBOSE: SET_VAR ADVISOR_2020_DIR: C:\Program Files (x86)\IntelSWTools\Advisor 2020\
VERBOSE: SET_VAR ADVISOR_2021_DIR: C:\Program Files (x86)\Intel\oneAPI\advisor\2021.1.1
VERBOSE: SET_VAR ALLUSERSPROFILE: C:\ProgramData
VERBOSE: SET_VAR APPDATA: C:\Users\Redacted\AppData\Roaming
VERBOSE: SET_VAR CommonProgramFiles: C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramFiles(x86): C:\Program Files (x86)\Common Files
VERBOSE: SET_VAR CommonProgramW6432: C:\Program Files\Common Files
VERBOSE: SET_VAR COMPUTERNAME: DESKTOP-0000000
VERBOSE: SET_VAR ComSpec: C:\WINDOWS\system32\cmd.exe
VERBOSE: SET_VAR DriverData: C:\Windows\System32\Drivers\DriverData
VERBOSE: SET_VAR FPS_BROWSER_APP_PROFILE_STRING: Internet Explorer
VERBOSE: SET_VAR FPS_BROWSER_USER_PROFILE_STRING: Default
VERBOSE: SET_VAR HOMEDRIVE: C:
VERBOSE: SET_VAR HOMEPATH: \Users\Redacted
VERBOSE: SET_VAR LOCALAPPDATA: C:\Users\Redacted\AppData\Local
VERBOSE: SET_VAR LOGONSERVER: \\DESKTOP-0000000
VERBOSE: SET_VAR MSBuildLoadMicrosoftTargetsReadOnly: true
VERBOSE: SET_VAR MSMPI_BENCHMARKS: C:\Program Files\Microsoft MPI\Benchmarks\
VERBOSE: SET_VAR MSMPI_BIN: C:\Program Files\Microsoft MPI\Bin\
VERBOSE: SET_VAR MSMPI_INC: C:\Program Files (x86)\Microsoft SDKs\MPI\Include\
VERBOSE: SET_VAR MSMPI_LIB32: C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x86\
VERBOSE: SET_VAR MSMPI_LIB64: C:\Program Files (x86)\Microsoft SDKs\MPI\Lib\x64\
VERBOSE: SET_VAR NUMBER_OF_PROCESSORS: 12
VERBOSE: SET_VAR ONEAPI_ROOT: C:\Program Files (x86)\Intel\oneAPI\
VERBOSE: SET_VAR OneDrive: C:\Users\Redacted\OneDrive
VERBOSE: SET_VAR OS: Windows_NT
VERBOSE: SET_VAR Path: C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\Microsoft 
MPI\Bin\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows
\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft 
SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL 
Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft
 SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;C:\Program 
Files\Microsoft SQL Server\140\Tools\Binn\;C:\Program Files\Microsoft SQL Server\140\DTS\Binn\;C:\Program Files 
(x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files 
(x86)\Gpg4win\..\GnuPG\bin;C:\Program Files (x86)\swigwin-4.0.2\;C:\Program Files 
(x86)\Java\jdk1.8.0_271\bin\;C:\Users\Redacted\AppData\Local\Android\Sdk\platform-tools\;C:\android-ndk-r22\;C:\Program 
Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program 
Files\Microsoft SQL 
Server\150\DTS\Binn\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0
\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Azure Data Studio\bin;C:\Program Files 
(x86)\dotnet\;C:\Users\Redacted\AppData\Local\Microsoft\WindowsApps;C:\Users\Redacted\.dotnet\tools;C:\Users\Redacted\AppData
\Roaming\ClangPowerTools\LLVM\LLVM11.0.0\bin;C:\Program Files (x86)\LLVM\bin
VERBOSE: SET_VAR PATHEXT: .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
VERBOSE: SET_VAR PkgDefApplicationConfigFile: 
C:\Users\Redacted\AppData\Local\Microsoft\VisualStudio\16.0_d664648c\devenv.exe.config
VERBOSE: SET_VAR PROCESSOR_ARCHITECTURE: x86
VERBOSE: SET_VAR PROCESSOR_ARCHITEW6432: AMD64
VERBOSE: SET_VAR PROCESSOR_IDENTIFIER: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
VERBOSE: SET_VAR PROCESSOR_LEVEL: 6
VERBOSE: SET_VAR PROCESSOR_REVISION: 9e0a
VERBOSE: SET_VAR ProgramData: C:\ProgramData
VERBOSE: SET_VAR ProgramFiles: C:\Program Files (x86)
VERBOSE: SET_VAR ProgramFiles(x86): C:\Program Files (x86)
VERBOSE: SET_VAR ProgramW6432: C:\Program Files
VERBOSE: SET_VAR PSExecutionPolicyPreference: Unrestricted
VERBOSE: SET_VAR PSModulePath: C:\Program 
Files\WindowsPowerShell\Modules;C:\Users\Redacted\Documents\WindowsPowerShell\Modules;C:\Program Files 
(x86)\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files (x86)\Microsoft SQL
 Server\140\Tools\PowerShell\Modules\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\PowerShell\Modules\
VERBOSE: SET_VAR PUBLIC: C:\Users\Public
VERBOSE: SET_VAR ServiceHubLogSessionKey: 0107D229
VERBOSE: SET_VAR SESSIONNAME: Console
VERBOSE: SET_VAR SHFBROOT: C:\Program Files (x86)\EWSoftware\Sandcastle Help File Builder\
VERBOSE: SET_VAR SystemDrive: C:
VERBOSE: SET_VAR SystemRoot: C:\WINDOWS
VERBOSE: SET_VAR TEMP: C:\Users\Redacted\AppData\Local\Temp
VERBOSE: SET_VAR ThreadedWaitDialogDpiContext: -4
VERBOSE: SET_VAR TMP: C:\Users\Redacted\AppData\Local\Temp
VERBOSE: SET_VAR USERDOMAIN: DESKTOP-0000000
VERBOSE: SET_VAR USERDOMAIN_ROAMINGPROFILE: DESKTOP-0000000
VERBOSE: SET_VAR USERNAME: Redacted
VERBOSE: SET_VAR USERPROFILE: C:\Users\Redacted
VERBOSE: SET_VAR VisualStudioDir: C:\Users\Redacted\Documents\Visual Studio 2019
VERBOSE: SET_VAR VisualStudioEdition: Microsoft Visual Studio Enterprise 2019
VERBOSE: SET_VAR VisualStudioVersion: 16.0
VERBOSE: SET_VAR VS110COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\Tools\
VERBOSE: SET_VAR VS120COMNTOOLS: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
VERBOSE: SET_VAR VS2019INSTALLDIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
VERBOSE: SET_VAR VSAPPIDDIR: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\
VERBOSE: SET_VAR VSAPPIDNAME: devenv.exe
VERBOSE: SET_VAR VSLANG: 1033
VERBOSE: SET_VAR VSLS_SESSION_KEEPALIVE_INTERVAL: 20
VERBOSE: SET_VAR VSSKUEDITION: Enterprise
VERBOSE: SET_VAR VTUNE_PROFILER_2020_DIR: C:\Program Files (x86)\IntelSWTools\VTune Profiler 2020\
VERBOSE: SET_VAR VTUNE_PROFILER_2021_DIR: C:\Program Files (x86)\Intel\oneAPI\vtune\2021.1.1
VERBOSE: SET_VAR windir: C:\WINDOWS
VERBOSE: SET_VAR ZES_ENABLE_SYSMAN: 1
VERBOSE: SET_VAR MSBuildProjectFullPath: F:\XXX - Source\REDACTED - 1.0.0.0\redacted\redacted.vcxproj
VERBOSE: SET_VAR ProjectDir: F:\XXX - Source\REDACTED - 1.0.0.0\redacted\
VERBOSE: SET_VAR MSBuildProjectExtension: .vcxproj
VERBOSE: SET_VAR MSBuildProjectFile: redacted.vcxproj
VERBOSE: SET_VAR MSBuildProjectName: redacted
VERBOSE: SET_VAR MSBuildProjectDirectory: F:\XXX - Source\REDACTED - 1.0.0.0\redacted\
VERBOSE: SET_VAR MSBuildProgramFiles32: C:\Program Files (x86)
VERBOSE: SET_VAR ProjectName: redacted
VERBOSE: SET_VAR TargetName: redacted
VERBOSE: SET_VAR UserRootDir: C:\Users\Redacted\AppData\Local\Microsoft\MSBuild\v4.0
VERBOSE: SET_VAR VisualStudioVersion: 16.0
VERBOSE: SET_VAR MSBuildToolsVersion: 16.0
VERBOSE: Retrieving project list for solution F:\XXX - Source\REDACTED - 1.0.0.0\redacted.sln
VERBOSE: Solution directory: F:\XXX - Source\REDACTED - 1.0.0.0\
VERBOSE: Intermediate solution project matches count: 2
VERBOSE: redacted\redacted.vcxproj
VERBOSE: REDACTED Documentation\REDACTED Documentation.shfbproj
VERBOSE: Resolved project paths for solution F:\XXX - Source\REDACTED - 1.0.0.0\redacted.sln:
VERBOSE:   F:\XXX - Source\REDACTED - 1.0.0.0\redacted\redacted.vcxproj
VERBOSE: 
VERBOSE: SET_VAR SolutionDir: F:\XXX - Source\REDACTED - 1.0.0.0\
VERBOSE: SET_VAR SolutionName: redacted
VERBOSE: SET_VAR Configuration: Release
VERBOSE: SET_VAR Platform: Win32
VERBOSE: 
Sanitizing F:\XXX - Source\REDACTED - 1.0.0.0\redacted\redacted.vcxproj
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\XXX - Source\REDACTED - 1.0.0.0\redacted\redacted.vcxproj
VERBOSE: SET_VAR MSBuildThisFileExtension: .vcxproj
VERBOSE: SET_VAR MSBuildThisFile: redacted.vcxproj
VERBOSE: SET_VAR MSBuildThisFileName: redacted
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\XXX - Source\REDACTED - 1.0.0.0\redacted\
VERBOSE: [CONTEXT] item namespace = @(ProjectConfiguration)
VERBOSE: SET_VAR CPT_PROJITEM_ProjectConfiguration: 
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: SET_VAR Configuration: Release
VERBOSE: SET_VAR Platform: Win32
VERBOSE: SET_VAR ProjectName: REDACTED
VERBOSE: SET_VAR ProjectGuid: {26EC71A4-A298-4784-96D1-D1075FF6044F}
VERBOSE: SET_VAR RootNamespace: listview2
VERBOSE: SET_VAR Keyword: MFCProj
VERBOSE: SET_VAR WindowsTargetPlatformVersion: 10.0
VERBOSE: Could not find property sheet \Microsoft.Cpp.Default.props
VERBOSE: SET_VAR ConfigurationType: Application
VERBOSE: SET_VAR UseOfMfc: Dynamic
VERBOSE: SET_VAR CharacterSet: Unicode
VERBOSE: SET_VAR WholeProgramOptimization: false
VERBOSE: SET_VAR PlatformToolset: v142
VERBOSE: Could not find property sheet \Microsoft.Cpp.props
VERBOSE: Property sheet: C:\Users\Redacted\AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props
VERBOSE: 
Sanitizing C:\Users\Redacted\AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props
VERBOSE: SET_VAR MSBuildThisFileFullPath: 
C:\Users\Redacted\AppData\Local\Microsoft\MSBuild\v4.0\Microsoft.Cpp.Win32.user.props
VERBOSE: SET_VAR MSBuildThisFileExtension: .props
VERBOSE: SET_VAR MSBuildThisFile: Microsoft.Cpp.Win32.user.props
VERBOSE: SET_VAR MSBuildThisFileName: Microsoft.Cpp.Win32.user
VERBOSE: SET_VAR MSBuildThisFileDirectory: C:\Users\Redacted\AppData\Local\Microsoft\MSBuild\v4.0\
VERBOSE: SET_VAR _ProjectFileVersion: 10.0.40219.1
VERBOSE: SET_VAR OutDir: F:\XXX - Source\REDACTED - 1.0.0.0\Release\
VERBOSE: SET_VAR IntDir: Release\
VERBOSE: SET_VAR LinkIncremental: false
VERBOSE: SET_VAR CodeAnalysisRuleSet: Custom.ruleset
VERBOSE: SET_VAR CodeAnalysisRules: 
VERBOSE: SET_VAR CodeAnalysisRuleAssemblies: 
VERBOSE: SET_VAR IncludePath: F:\XXX - Source\REDACTED - 1.0.0.0\redacted\includes;F:\XXX - Source\REDACTED - 
1.0.0.0\redacted\fmr;
VERBOSE: [CONTEXT] item namespace = @(Midl)
VERBOSE: [CONTEXT] propSet: PreprocessorDefinitions = NDEBUG;
VERBOSE: [CONTEXT] propSet: MkTypLibCompatible = false
VERBOSE: [CONTEXT] propSet: ValidateAllParameters = true
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(ClCompile)
VERBOSE: [CONTEXT] propSet: Optimization = Full
VERBOSE: [CONTEXT] propSet: IntrinsicFunctions = true
VERBOSE: [CONTEXT] propSet: AdditionalIncludeDirectories = 
VERBOSE: [CONTEXT] propSet: PreprocessorDefinitions = 
_MSC_PLATFORM_TOOLSET=;WIN32;_WINDOWS;NDEBUG
;_CRT_SECURE_NO_WARNINGS;HAVE_FCNTL_H;OPJ_STATIC;_MSC_PLATFORM_TOOLSET_v142;
VERBOSE: [CONTEXT] propSet: MinimalRebuild = false
VERBOSE: [CONTEXT] propSet: RuntimeLibrary = MultiThreadedDLL
VERBOSE: [CONTEXT] propSet: StructMemberAlignment = Default
VERBOSE: [CONTEXT] propSet: FunctionLevelLinking = true
VERBOSE: [CONTEXT] propSet: PrecompiledHeader = Use
VERBOSE: [CONTEXT] propSet: WarningLevel = Level3
VERBOSE: [CONTEXT] propSet: DebugInformationFormat = ProgramDatabase
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(ResourceCompile)
VERBOSE: [CONTEXT] propSet: PreprocessorDefinitions = NDEBUG;
VERBOSE: [CONTEXT] propSet: Culture = 0x0409
VERBOSE: [CONTEXT] propSet: AdditionalIncludeDirectories = Release\;
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(Link)
VERBOSE: [CONTEXT] propSet: AdditionalDependencies = version.lib;
VERBOSE: [CONTEXT] propSet: IgnoreAllDefaultLibraries = false
VERBOSE: [CONTEXT] propSet: IgnoreSpecificDefaultLibraries = libcmt.lib; 
VERBOSE: [CONTEXT] propSet: GenerateDebugInformation = false
VERBOSE: [CONTEXT] propSet: SubSystem = Windows
VERBOSE: [CONTEXT] propSet: OptimizeReferences = true
VERBOSE: [CONTEXT] propSet: EnableCOMDATFolding = true
VERBOSE: [CONTEXT] propSet: TargetMachine = MachineX86
VERBOSE: [CONTEXT] propSet: AdditionalOptions = /PDBALTPATH:%_PDB% /FORCE:MULTIPLE 
VERBOSE: [CONTEXT] propSet: Profile = false
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(PostBuildEvent)
VERBOSE: [CONTEXT] propSet: Command = xcopy /y "F:\XXX - Source\REDACTED - 1.0.0.0\redacted\884.dat" ""
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(Manifest)
VERBOSE: [CONTEXT] propSet: AdditionalManifestFiles = REDACTED.manifest.xml
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(ClCompile)
VERBOSE: SET_VAR CPT_PROJITEM_ClCompile: 
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(ClInclude)
VERBOSE: SET_VAR CPT_PROJITEM_ClInclude: 
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(None)
VERBOSE: SET_VAR CPT_PROJITEM_None: 
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(ResourceCompile)
VERBOSE: SET_VAR CPT_PROJITEM_ResourceCompile: 
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: [CONTEXT] item namespace = @(Image)
VERBOSE: SET_VAR CPT_PROJITEM_Image: 
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: Could not find property sheet \Microsoft.Cpp.targets
VERBOSE: Property sheet: F:\XXX - Source\REDACTED - 
1.0.0.0\packages\Microsoft.Gsl.0.0.1.0\build\native\Microsoft.Gsl.targets
VERBOSE: 
Sanitizing F:\XXX - Source\REDACTED - 1.0.0.0\packages\Microsoft.Gsl.0.0.1.0\build\native\Microsoft.Gsl.targets
VERBOSE: SET_VAR MSBuildThisFileFullPath: F:\XXX - Source\REDACTED - 
1.0.0.0\packages\Microsoft.Gsl.0.0.1.0\build\native\Microsoft.Gsl.targets
VERBOSE: SET_VAR MSBuildThisFileExtension: .targets
VERBOSE: SET_VAR MSBuildThisFile: Microsoft.Gsl.targets
VERBOSE: SET_VAR MSBuildThisFileName: Microsoft.Gsl
VERBOSE: SET_VAR MSBuildThisFileDirectory: F:\XXX - Source\REDACTED - 
1.0.0.0\packages\Microsoft.Gsl.0.0.1.0\build\native\
VERBOSE: [CONTEXT] item namespace = @(ClCompile)
VERBOSE: [CONTEXT] propSet: AdditionalIncludeDirectories = F:\XXX - Source\REDACTED - 
1.0.0.0\packages\Microsoft.Gsl.0.0.1.0\build\native\include;
VERBOSE: [CONTEXT] item namespace = @()
VERBOSE: SET_VAR ErrorText: This project references NuGet package(s) that are missing on this computer. Use NuGet 
Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing
 file is {0}.
PROJECT: F:\XXX - Source\REDACTED - 1.0.0.0\redacted\redacted.vcxproj [Release|Win32]
VERBOSE: Platform toolset: v142
VERBOSE: [CONTEXT] item namespace = @(ClCompile)
VERBOSE: Force includes:
VERBOSE:   
VERBOSE: 
VERBOSE: Preprocessor definitions:
VERBOSE:   "-DUNICODE"
VERBOSE:   "-D_UNICODE"
VERBOSE:   "-D_MT"
VERBOSE:   "-D_DLL"
VERBOSE:   "-D_AFXDLL"
VERBOSE:   "-D_MSC_PLATFORM_TOOLSET="
VERBOSE:   "-DWIN32"
VERBOSE:   "-D_WINDOWS"
VERBOSE:   "-DNDEBUG"
VERBOSE:   "-D_CRT_SECURE_NO_WARNINGS"
VERBOSE:   "-DHAVE_FCNTL_H"
VERBOSE:   "-DOPJ_STATIC"
VERBOSE:   "-D_MSC_PLATFORM_TOOLSET_v142"
VERBOSE:   "-D_DEBUG_FUNCTIONAL_MACHINERY"
VERBOSE: 
VERBOSE: Additional include directories:
VERBOSE:   F:\XXX - Source\REDACTED - 1.0.0.0\packages\Microsoft.Gsl.0.0.1.0\build\native\include
VERBOSE: 
VERBOSE: Detected (vswhere) VisualStudio installation path: C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise
VERBOSE: Visual Studio location: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
VERBOSE: Detected (vswhere) VisualStudio installation path: C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise
VERBOSE: MSCVER: 14.28.29333
VERBOSE: WinSDK version: 10.0
VERBOSE: Include directories:
VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include
VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\atlmfc\include
VERBOSE:   C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\VS\include
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\ucrt
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\winrt
VERBOSE:   C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt
VERBOSE:   F:\XXX - Source\REDACTED - 1.0.0.0\redacted\includes
VERBOSE:   F:\XXX - Source\REDACTED - 1.0.0.0\redacted\fmr
VERBOSE: 
VERBOSE: PCH cpp name: F:\XXX - Source\REDACTED - 1.0.0.0\redacted\stdafx.cpp
VERBOSE: PCH header name: stdafx.h
VERBOSE: PCH directory: F:\XXX - Source\REDACTED - 1.0.0.0\redacted\
VERBOSE: Processing 38 cpps
VERBOSE: Generating PCH...
VERBOSE: INVOKE: C:\Program Files (x86)\LLVM\bin\clang++.exe "F:\XXX - Source\REDACTED - 
1.0.0.0\redacted\stdafx.h.hpp" -emit-pch -o "F:\XXX - Source\REDACTED - 1.0.0.0\redacted.clang.pch" -x c++ 
-std=c++14 -Wall -fms-compatibility-version=19.10 -Wmicrosoft -Wno-invalid-token-paste -Wno-unknown-pragmas 
-Wno-unused-value -m32 -Wno-unused-command-line-argument "-DUNICODE" "-D_UNICODE" "-D_MT" "-D_DLL" "-D_AFXDLL" 
"-D_MSC_PLATFORM_TOOLSET=" "-DWIN32" "-D_WINDOWS" "-DNDEBUG" "-D_CRT_SECURE_NO_WARNINGS" "-DHAVE_FCNTL_H" "-DOPJ_STATIC" 
"-D_MSC_PLATFORM_TOOLSET_v142" "-D_DEBUG_FUNCTIONAL_MACHINERY" -isystem"F:\XXX - Source\REDACTED - 
1.0.0.0\redacted" -isystem"C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include" -isystem"C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\atlmfc\include" -isystem"C:\Program Files (x86)\Microsoft Visual 
Studio\2019\Enterprise\VC\Auxiliary\VS\include" -isystem"C:\Program Files (x86)\Windows 
Kits\10\Include\10.0.18362.0\ucrt" -isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um" 
-isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\shared" -isystem"C:\Program Files (x86)\Windows 
Kits\10\Include\10.0.18362.0\winrt" -isystem"C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\cppwinrt" 
-isystem"F:\XXX - Source\REDACTED - 1.0.0.0\redacted\includes" -isystem"F:\XXX - Source\REDACTED - 
1.0.0.0\redacted\fmr" -I"F:\XXX - Source\REDACTED - 1.0.0.0\packages\Microsoft.Gsl.0.0.1.0\build\native\include"
clang++: error: cannot specify -o when generating multiple output files
VERBOSE: Cleaning up PCH temporaries:
VERBOSE:   F:\XXX - Source\REDACTED - 1.0.0.0\redacted\stdafx.h.hpp
VERBOSE:   F:\XXX - Source\REDACTED - 1.0.0.0\redacted.clang.pch
VERBOSE: 
Errors encountered during PCH creation

--- CLANG TIDY FINISHED ---

**Comment by hero101111** [comment]
Hello again @netx123 ,

Can you please retest this scenario now that the public release of LLVM 12.0 is available?

Thank you.

**Comment by netx123** [comment]
Hi @hero101111 , I've tried again using the public release of LLVM 12.0 and I receive exactly the same error as before.
Interestingly I also tried adding the 12.0.0 version through CPT->Settings->LLVM->Add Existing LLVM , however browsing to the folder "C:\Program Files\LLVM\bin" did not display any error messages, however it failed to insert LLVM 12.0.0 into the list of available LLVMs as I would have expected.

**Comment by hero101111** [comment]
Hello @netx123 ,

This issue has been addressed in the latest Clang Power Tools release (v7.4.0).  It brings support for LLVM 12.
Thank you for bringing it to our attention, your feedback has been very helpful.

Regards,
Gabriel.
