### ISSUE TITLE
Clang Power Tools/Tidy/Checks is missing a few checks vs llvm 5.0.0 release

### ISSUE THREAD

**Issue by loofbon** [Caphyon/clang-power-tools#93]
First off, thanks for this amazing toolset, it is great to be able to do this stuff directly in VS.

I noticed this since some these checks are active by default, so they get applied even if you set all the checks to "False". I'm trying to roll out these fixes in small doses, so it's a little hard to control as much as I'd like.

bugprone-integer-division
cppcoreguidelines-owning-memory
hicpp-braces-around-statements
hicpp-deprecated-headers
hicpp-exception-baseclass
hicpp-move-const-arg
hicpp-no-array-decay
hicpp-no-malloc
hicpp-signed-bitwise
hicpp-static-assert
hicpp-use-auto
hicpp-use-emplace
hicpp-use-nullptr
hicpp-vararg
readability-static-accessed-through-instance

Some seem spelled differently:
performance-implicit-conversion-in-loop != performance-implicit-cast-in-loop
readability-implicit-bool-conversion != readability-implicit-bool-cast

**Comment by loofbon** [comment]
I didn't check which of the hicpp ones are just aliases -- don't know whether you want to include them all just so the list is 1-1 with clang-tidy, or exclude them as duplicates

**Comment by cpp-red-lion** [comment]
We'll look into it.
Thanks for bringing it to our attention.

**Comment by cpp-red-lion** [comment]
Note that, when using **Custom Checks** the standard `clang-tidy` behavior is to run default enabled checks along the ones you specify.
To ensure that tidy runs **only** your specified checks, you need to **explicitly** disable the default ones.
Eg.

If you want just `modernize-use-nullptr` you have to write:
`-*,modernize-use-nullptr`

(see screenshot above)

**Comment by loofbon** [comment]
Sorry, should have been clear I was using the Checks page; good to know I can use the Custom Checks as a workaround.
