### ISSUE TITLE
Path separator for include files is using '/' in Error pane

### ISSUE THREAD

**Issue by netx123** [Caphyon/clang-power-tools#931]
I've observed that when output from CPT is inserted into the Errors pane, the full File path uses the '/' path separator for include files '.h'  but the '\\' for source files such as '.cpp'

This causes issues when filtering files in this pane as the same include file can end up being listed twice, once with a '\\' , and again with a '/'.

As all file paths that are output from VS into the error pane use '\\' can the output of CPT also be corrected to use the '\\' for consistency?

**Comment by hero101111** [comment]
Hello @netx123 

I'm afraid I do not fully understand this behavior. Can you attach a screenshot?

**Comment by netx123** [comment]
@hero101111 Please see the attached screenshots:
The first shows 2 warnings generated by VS Code Analysis, and 2 warnings generated by CPT, these warnings are for two distinct files one being a .cpp and one .h
![image](https://user-images.githubusercontent.com/8387938/108063988-f205e080-7053-11eb-97ce-4f6b7a5b745f.png)

The second screenhot shows the issue circled in red in the File filter, the file filter should only show two distinct files for filtering, but because CPT (for headers) is using '/' in the path separator, the filter shows the same header file twice.
![image](https://user-images.githubusercontent.com/8387938/108064029-021dc000-7054-11eb-9679-9054a5eeaa82.png)
For consistency and to fix the above issue it would be good if all paths in the File filter used the '\' separator.

**Comment by Enache-Ionut** [comment]
Hi @netx123,

Thank you for bringing this to our attention.
We solved this issue and it will be present in the next release of Clang Power Tools, v7.2, which will happen later this afternoon.

Regards,
Ionut
