### ISSUE TITLE
Clang-Format won't run on inl files

### ISSUE THREAD

**Issue by DominikGrabiec** [Caphyon/clang-power-tools#932]
I use `inl` files for custom inline code, to separate it out from the header and into its own file. Right now I when I'm editing an inl file I cannot click on any of the clang-format or clang-tidy buttons, where as I can on a h or hpp file.

One suggestion would be to add an option to specify what files we can run these tools on so the button will be enabled for them.

**Comment by Enache-Ionut** [comment]
Hi @DominikGrabiec,

Thank you for your feedback. We'll address this problem in the next version of Clang Power Tools. 
For any other inconvenience or feature suggestion, feel free to open a new issue anytime you need. 

Regards, 
Ionut

**Comment by Enache-Ionut** [comment]
Hi @DominikGrabiec,

Now you can run clang-format on .inl files. 
We solved this issue and it will be present in the next release of Clang Power Tools, v7.2, which will happen later this afternoon. 

The user cannot specify on what files he can run CPT, at least not yet. We took into account your suggestion, but we need to think about that more rigorously. 

Regards, 
Ionut
