### ISSUE TITLE
Squared brackets in solution/project path fails to find directory

### ISSUE THREAD

**Issue by webez** [Caphyon/clang-power-tools#934]
Hi.

If the solution/project has square brackets in its path, the powershell scripts can't find/join paths properly

**Comment by hero101111** [comment]
Hello @webez,

We can confirm this is an issue indeed. After looking into it, we can tell it's a more serious issue than first meets the eyes. A fix for this is not trivial and will need some time for thorough testing. Until we will release a fix please consider placing the project in a path that does not contain squared brackets. 

Thank you for your understanding.
Regards,
Gabriel.

**Comment by webez** [comment]
I have made a hackish fix to be able to use the tools adding -LiteralPath wherever possible and replacing [] with `[`] inside Canonize-Path.

**Comment by hero101111** [comment]
Pleased to inform you that Clang Power Tools 7.2.1, just released, has fixed this issue.

Thank you for providing us with the feedback required.
