### ISSUE TITLE
ArgumentException in VisualStudio 

### ISSUE THREAD

**Issue by xonfug** [Caphyon/clang-power-tools#936]
![image](https://user-images.githubusercontent.com/9591898/109120483-e85c3700-773d-11eb-8e45-ace357ec5531.png)

This error often appears in Visual Studio (16.7.3). Here is the corresponding log entry
  <entry>
    <record>1342</record>
    <time>2021/02/25 07:42:56.816</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.ArgumentException: Value does not fall within the expected range.&#x000D;&#x000A;   at EnvDTE80.DTE2.get_ActiveDocument()&#x000D;&#x000A;   at ClangPowerTools.Squiggle.SquiggleErrorTagger.CreateSquiggles()&#x000D;&#x000A;   at ClangPowerTools.Squiggle.SquiggleErrorTagger.&lt;GetTags&gt;d__15.MoveNext()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.&lt;GetTagsForBuffer&gt;d__47.MoveNext()&#x000D;&#x000A;--- End of stack trace from previous location where exception was thrown ---&#x000D;&#x000A;   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)</description>
  </entry>

**Comment by hero101111** [comment]
Hello @xonfug,

Thank you for bringing this issue to our attention. We are looking into it and will update this issue thread as soon as we have an update for you.

Regards,
Gabriel.

**Comment by Enache-Ionut** [comment]
Hi @xonfug,

This issue might be possible to be related to #896. At this moment, we encounter some difficulties with the squiggle module. 
As a temporary workaround, you can disable this module by going to Settings -> Compiler tab -> Show squiggles -> Off.

Please let me know if this workaround is working for you.

**Comment by Enache-Ionut** [comment]
I will close this issue because of the lack of information.
