### ISSUE TITLE
Generate-Pch leaves copied  Pch as read only and can't be recreated

### ISSUE THREAD

**Issue by webez** [Caphyon/clang-power-tools#937]
Hi,

I can't reproduce the conditions in which this has began to happen but suddenly the generated PCH has its  permissions to write only after being generated. I have modified Copy-Item in Generate-Pch with -Force to avoid this problem but the cause is still unknown

**Comment by hero101111** [comment]
Hello @webez,

Can you provide more information on this issue? We've unable to reproduce it. Consider enabling "Verbose mode" and check the detailed log.

**Comment by webez** [comment]
Hi,
I am sorry for the lack of information related with this problem. I myself was unabale to reproduce it consistently and the "Verbose mode" does not give any hint about it (I have used it a lot to find the other problem with great results).
That's why as a precaution I have added -Force to Copy-Item

**Comment by bjehlert** [comment]
I've hit this problem as well on 7.2.0 and believe I have a repro.

Perforce keeps files as read-only until they are checked out for modification so the majority of code files are in a read-only state. When it copies a read-only stdafx.h to stdafx.h.hpp, the new file is also read-only.

In my case, the PCH has errors so it failed to compile and ended with:

```
4 errors generated.
Skipping project. Reason: cannot create PCH.
```

The read-only stdafx.h.hpp was not deleted. Next time I run tidy, it shows:

```Copy-Item : Access to the path 'C:\stuff\stdafx.h.hpp' is denied.```

**Comment by webez** [comment]
That could be, because I am also using Perforce

**Comment by hero101111** [comment]
@bjehlert Thank you for the additional information, it was very helpful. We are currently working on a fix for the issue.

**Comment by hero101111** [comment]
Pleased to inform you that Clang Power Tools 7.2.1, just released, has fixed this issue.

Thank you for providing us with the feedback required.
