### ISSUE TITLE
Start-Process in Generate-Pch can't resolve path with squared brackets

### ISSUE THREAD

**Issue by webez** [Caphyon/clang-power-tools#947]
Hi.

Thanks for the latest update, but I think the paths with special characters problem is still not fully fixed.

When launching Start-Process inside Generate-Pch it fails because it can't properly resolve the path used with Push-Location

**Comment by hero101111** [comment]
Hi @webez ,

Sorry to hear that the issue addressed by #945 still persists.
Could there be other special characters in the path besides square brackets?
Please provide a disk location path we can use for further testing.


Regards,
Gabriel.

**Comment by webez** [comment]
Hi,

The path only contains square brackets. The solution path has this format
C:\xxx\[xx00]\PRJ_00\xxx\Code\Apps

I fixed it as I did it last time, replacing brackets and using WorkingDirectory, which is missing in the update

  $kClangWorkingDir = "$(Get-SourceDirectory)" -replace '\[', '`[' -replace ']', '`]'
  [System.Diagnostics.Process] $processInfo = Start-Process -FilePath $kClangCompiler `
                                                            -ArgumentList $compilationFlags `
                                                            -WorkingDirectory $kClangWorkingDir `
                                                            -NoNewWindow `
                                                            -Wait `
                                                            -PassThru

**Comment by hero101111** [comment]
Closing this issue, as of Clang Power Tools 7.3.2 this issue should be fixed. Thanks for the feedback!
