### ISSUE TITLE
Clang after MSVC and Tidy on save not working 

### ISSUE THREAD

**Issue by webez** [Caphyon/clang-power-tools#948]
Hi.
I think in the previous version I tried Clang after MSVC and it worked properly but with current version,Clang after MSVC and Tidy on save are not working for me. None of those two are triggered.

I have tried modifying the file, compiling the file, Ctrl+F7, compiling the project, etc. but nothing works

Clang format on save works properly

**Comment by Enache-Ionut** [comment]
Hello, 

Thank you for your feedback. The issues you mentioned above are now fixed and Clang Power Tools v7.3.1 was just released. Please check for updates. 

Happy coding!
