### ISSUE TITLE
Test-Path fails with squared brackets

### ISSUE THREAD

**Issue by webez** [Caphyon/clang-power-tools#951]
Hi again!

I have found that some Property Sheets were not loading inside SanitizeProjectNode and found that the problem is that Test-Path also needs -LiteralPath.
Thanks for your great work and your patience in this neverding fixes!

**Comment by hero101111** [comment]
Hi @webez 

Thanks for the feedback, a fix for the square bracket bug will be available soon.

Regards,
Gabriel

**Comment by hero101111** [comment]
Closing this issue, as of Clang Power Tools 7.3.2 this issue should be fixed. Thanks for the feedback!
