### ISSUE TITLE
SanitizeProjectNode does not check Condition attribute in property nodes

### ISSUE THREAD

**Issue by webez** [Caphyon/clang-power-tools#952]
Hi!

I was having a problem with a .cpp file that was being compiled even if it was excluded from the build in the current configuration/platform.

My project has a configuration like this:

``<ClCompile Include="Filecpp">``
``<ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Debug|x32'">true</ExcludedFromBuild>``
``<ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">true</ExcludedFromBuild>``
`` <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Release|x32'">false</ExcludedFromBuild>``
``<ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Release|x64'">false</ExcludedFromBuild>``
``</ClCompile>``

And checking the SanitizeProjectNode  in the parse ItemGroup section I have seen that right now, because Conditions are not checked, the last property is the one that ends in the properties.

After checking conditions it works as it should.

Thanks for your work!

**Comment by hero101111** [comment]
Hi @webez,

I am unable to fully understand this issue and what exactly are we to fix. Please elaborate further and provide a sample project that we can test with.

We really appreciate the feedback.

Regards,
Gabriel.

**Comment by webez** [comment]
Wow, sorry, the project code was last when pasting it.

    <ClCompile Include="File.cpp">
      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">true</ExcludedFromBuild>
      <ExcludedFromBuild Condition="'$(Configuration)|$(Platform)'=='Final|x64'">false</ExcludedFromBuild>
   </ClCompile>

If  you compile that file with that project configuration in Debug x64 (which should not include the file), because Conditions are not checked where I told in the previous post, the last ExcludedFromBuild condition is used instead of the one that satisfies the condition (which will compile the file).

**Comment by hero101111** [comment]
Closing this issue, as of Clang Power Tools 7.3.2 this issue should be fixed. Thanks for the feedback!
