### ISSUE TITLE
C source files being treated as C++

### ISSUE THREAD

**Issue by Kelly12612** [Caphyon/clang-power-tools#953]
In clang-build.ps1, in the function Get-ProjectFileLanguageFlag, there is a check against the project file setting CompileAs. 
In my C (or mixed C and C++) projects, this property value on the property page is "Default", when Get-ProjectFileSetting is called, it is returning the empty string.
Since the empty string is not equal to $kCProjectCompile, this is setting $isCpp to true, which is incorrect.
I added the empty string test in the version below and this worked as expected, clang++ was run with the "-x c" flag instead of "-x cpp".  There are probably better ways to fix this, but since I had a workaround, I wanted to share it.

```
  try
  {
    # If the property value is empty, just use the $isCpp value determined above.
    if ((Get-ProjectFileSetting -fileFullName $fileFullName -propertyName "CompileAs") -ne "") {
      $isCpp = (Get-ProjectFileSetting -fileFullName $fileFullName -propertyName "CompileAs") -ine $kCProjectCompile
    }
  }
  catch {}

```

**Comment by hero101111** [comment]
Hi @Kelly1261,

Thank you for providing us with this scenario and fix. We'll integrate it into the next Clang Power Tools release.

Regards,
Gabriel.

**Comment by hero101111** [comment]
Closing this issue, as of Clang Power Tools 7.3.2 this issue should be fixed. Thanks for the feedback!
