### ISSUE TITLE
Extension causes unexpected behavor and corrputs Cmake generated solution/projects files. 

### ISSUE THREAD

**Issue by strngtn** [Caphyon/clang-power-tools#958]
https://gitlab.kitware.com/cmake/cmake/-/issues/22210

**Comment by bredej** [comment]
I typically generate a VS solution from CMake with Debug and Release configurations.  I can open the solution in VS and I can build Debug and Release.  The second I open a source file (using Solution Explorer) a File Modification Detected dialog appears telling me the solution has been modified.  If I select Reload the Release configuration is gone.

**Comment by bredej** [comment]
That's great news.
Thank you!
