### ISSUE TITLE
$(MSBuildThisFileDirectory) not properly evaluated

### ISSUE THREAD

**Issue by tpzworks** [Caphyon/clang-power-tools#959]
MSBuildThisFileDirectory should be evaluated for each props file separately. The problem is, that our props file are located in different folder than the project file, consequently clang power tools do not properly forward "AdditionalIncludeDirectories".

**Comment by hero101111** [comment]
Hello @tpzworks

We have reproduced the issue and a fix has been pushed to our Github code.  A bugfix Clang Power Tools release will soon be made available.
Thank you for reporting this issue.

Regards,
Gabriel

**Comment by hero101111** [comment]
Hi again,

Clang Power Tools 7.4 has just been released and it includes the fix for this issue.

Kind regards,
Gabriel.
