### ISSUE TITLE
[question] generate compile_commands.json over the command line

### ISSUE THREAD

**Issue by FrancescElies** [Caphyon/clang-power-tools#960]
At the moment I am exporting `compile_commands.json` for a solution via `Export Compilation Database` button in visual studio.

Is there a way to do this over the command line?

**Comment by hero101111** [comment]
Hello @FrancescElies ,

Naturally, all functionality of Clang Power Tools is accessible via [clang-build.ps1](https://github.com/Caphyon/clang-power-tools/blob/master/ClangPowerTools/ClangPowerTools/clang-build.ps1), our automation script. 

You can invoke it using Poweshell, e.g. `.\clang-build.ps1 -proj "c:\myproject\sample.vcxproj" -export-jsondb`

This will export the compilation database file in the current working directory.

Regards,
Gabriel

**Comment by FrancescElies** [comment]
@hero101111 

Thanks for your message, just gave it a shot but I got

![image](https://user-images.githubusercontent.com/6558089/122390579-702ab300-cf72-11eb-986e-dedd2e7af30e.png)

Am I doing something wrong?

**Comment by hero101111** [comment]
That message is displayed because of multiple clang-build.ps1 invocations in the same command-line session. We can take care of that but it is benign here. Also we should not display the 'Exported JSON Compilation Db to...' message when no projects are found, we will have to fix that.

However, the question to be addressed is why there are no projects discovered by CPT. Make sure that the current working directory contains Visual Studio solutions and projects and you do not pass a filter using the `-proj` parameter that would filter out all projects. What are your invocation command line args?

**Comment by FrancescElies** [comment]
Alright I executed the previous command in a non developer prompt, now that error is gone.

Using powershell developer prompt with working dir `C:\s\clang-power-tools\ClangPowerTools\ClangPowerTools`
`.\clang-build.ps1 "C:\s\eklang\src\eklang.sln" -export-jsondb`

Now I get 
![image](https://user-images.githubusercontent.com/6558089/122509581-520d9300-d004-11eb-90cb-96e44c66ee23.png)

Json is empty, but the same works fine for the same solution if I export things from visual studio.

**Comment by hero101111** [comment]
Hi @FrancescElies 

Please take note that you should give a project as argument to the script, not the solution file.
Retry and let us know if then it works correctly.

Regards,
Gabriel

**Comment by FrancescElies** [comment]
With `.\clang-build.ps1 -proj "c:\myproject\sample.vcxproj" -export-jsondb` I get the previous `kJsonCompilationDbPath` error again.

Since this is not an open project where I could share the vcxproj with youI think I am just fine to export things with a click in visual studio, so feel fre to close this bug if you like.

**Comment by hero101111** [comment]
Also, I failed to notice in your previous example that you have your working directory pointing to the CPT location, that is not how it's intended to be used. You should have the CWD pointing to the root directory of your projects/solutions.

**Comment by FrancescElies** [comment]
I will Give it another try on Monday. Thanks for your help

**Comment by FrancescElies** [comment]
So finally got to have a look into this again.

Executing the following with CWD a visual studio solution works.
`C:\s\clang-power-tools\ClangPowerTools\ClangPowerTools\clang-build.ps1 -export-jsondb`

At the begining I still get
![image](https://user-images.githubusercontent.com/6558089/124079220-2a2d1f00-da49-11eb-9ad5-d2e34bde055c.png)

But the script continues and endsup exporting `compile_commands.json`, shall we close this issue? I am already happy with this outcome.

**Comment by hero101111** [comment]
Hi @FrancescElies 

Good to hear that you got it working. I am now closing this issue.
Thanks for reaching out to us and we hope you continue enjoying using Clang Power Tools.

Regards,
Gabriel.
