### ISSUE TITLE
clang output not showing in error list

### ISSUE THREAD

**Issue by avineshmohan** [Caphyon/clang-power-tools#962]

**Comment by hprica** [comment]
Hello @avineshmohan, did you check the settings? 

If the options below are enabled and you still have the issue, could you provide a small test project or a scenario where the error list is not shown?

![image](https://user-images.githubusercontent.com/28626088/124438566-03d8ed80-dd81-11eb-8849-738a0fd34a84.png)

**Comment by mariru27** [comment]
I will close this issue as we need more information to reproduce the problem
