### ISSUE TITLE
Incorrect warning about a pointer to bool ("readability-non-const-parameter")

### ISSUE THREAD

**Issue by vbazarov** [Caphyon/clang-power-tools#972]
Clang-Tidy will recommends making 'ptr_to_bool' a pointer to const, which is WRONG because I access the object through a reference to non-const with the intention to change its value in the body of the function.

	void foo(bool *ptr_to_bool)
	{
		bool &ref_to_bool = *ptr_to_bool;

		if (rand() > 1000)
		{
			ref_to_bool = true;
		}
		else
		{
			assert(!"Less or equal");
		}
	}

Yes, I know that I don't check the pointer for null-ness, as I ought to.  That is not the point.

**Comment by hero101111** [comment]
Hi @vbazarov 

Please consider taking this inquiry up with the clang-tidy[ LLVM team](https://llvm.org/docs/HowToSubmitABug.html). 
Clang Power Tools uses clang-tidy _as-it-is_ and we cannot offer any fixes regarding its implementation.

Thank you for taking the time to contact us.

Regards,
Gabriel.
