### ISSUE TITLE
Fails to load in VS

### ISSUE THREAD

**Issue by pasa-** [Caphyon/clang-power-tools#981]
Lately on my old Win7 laptop CTP fails to load in VS2019. VS reports it and these entries are in the activitlog:

  <entry>
    <record>1545</record>
    <time>2021/08/17 09:49:45.548</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [RunClangPowerToolsPackage]Source: &apos;mscorlib&apos; Description: An error occurred while sending the request.&#x000D;&#x000A;</description>
    <guid>{F564F9D3-01AE-493E-883B-18DEEBDB975E}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>
  <entry>
    <record>1546</record>
    <time>2021/08/17 09:49:45.558</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [RunClangPowerToolsPackage]</description>
    <guid>{F564F9D3-01AE-493E-883B-18DEEBDB975E}</guid>
    <hr>80131500</hr>
    <errorinfo></errorinfo>
  </entry>

Already tried: 
- installing latest  .NET framework
- uninstall and reinstall the extension
- delete ComponentModelCache under VS local appdata

**Comment by hprica** [comment]
Hello @pasa- ,

Did you update to the latest version of VS2019? 

This problem often affects extensions or certain VS functionality, after an update or on a new installation.

**Possible fix**
1. - Uninstall the extension
2. - Delete ComponentModelCache under VS local appdata
3. - Repair Visual Studio
4. - Reinstall the extension

Let me know if it works.

**Comment by mariru27** [comment]
Hi @pasa-,

Do you have the same problem on the latest [Clang Power Tools v2023.6.0](https://marketplace.visualstudio.com/items?itemName=caphyon.ClangPowerTools)

Kind regards,
Marina

**Comment by mariru27** [comment]
I will close this issue as we need more information

**Comment by pasa-** [comment]
I decommissioned the referred W7 laptop almost a year ago.  Didn't see anything similar on my other installations.
